// Sheet: IN_build
export const data = {
  "A1":  /* unknown */ "Bezeichnung",
  "B1":  /* unknown */ "Gruppe ",
  "C1":  /* unknown */ "Subgruppe",
  "D1":  /* unknown */ "Variable",
  "E1":  /* unknown */ "Fragentext ",
  "F1":  /* unknown */ "Hilfstext",
  "G1":  /* unknown */ "Antworttyp",
  "H1":  /* unknown */ "Filter ",
  "I1":  /* unknown */ "Einheit ",
  "J1":  /* unknown */ "Datentyp",
  "K1":  /* unknown */ "Pflichtfeld ",
  "L1":  /* unknown */ "Nachkommastellen",
  "M1":  /* unknown */ "min Wert",
  "N1":  /* unknown */ "max Wert",
  "O1":  /* unknown */ "Wert intern",
  "P1":  /* unknown */ "Wert",
  "Q1":  /* unknown */ "EXIST",
  "R1":  /* unknown */ "YEAR_eff",
  "S1":  /* unknown */ "YEAR",
  "T1":  /* unknown */ "L_ins_eff [cm]",
  "U1":  /* unknown */ "L_ins [cm]",
  "A2":  /* unknown */ "Standort",
  "B2":  /* unknown */ "build",
  "D2":  /* unknown */ "NO_build_plz",
  "E2":  /* unknown */ "Standort des Gebäudes (PLZ)",
  "G2":  /* unknown */ "Freifeld",
  "J2":  /* unknown */ "Integer",
  "K2":  /* unknown */ 1,
  "A3":  /* unknown */ "Gebäudetyp",
  "B3":  /* unknown */ "build",
  "D3":  /* unknown */ "TYP_build",
  "E3":  /* unknown */ "Das Gebäude ist ein…",
  "F3":  /* unknown */ "PopUp: Der Gebäudetyp hilft dabei, die Bauteile und ihren Wärmedurchlass besser einzuschätzen.",
  "G3":  /* unknown */ "Radio Button + Grafik",
  "J3":  /* unknown */ "String",
  "K3":  /* unknown */ 1,
  "B4":  /* unknown */ "build",
  "D4":  /* unknown */ "TYP_roof",
  "E4":  /* unknown */ "Dachform ",
  "F4":  /* unknown */ "PopUp: \nHaben Sie ein sehr flach geneigtes Dach, z.B. ein Pultdach, wählen Sie \"Flachdach\" statt \"geneigt\" aus. ",
  "G4":  /* unknown */ "Radio Button + Grafik",
  "J4":  /* unknown */ "String",
  "K4":  /* unknown */ 1,
  "B5":  /* unknown */ "build",
  "D5":  /* unknown */ "YEAR_build_bj",
  "E5":  /* unknown */ "Baujahr",
  "G5":  /* unknown */ "Dropdown",
  "J5":  /* unknown */ "Integer",
  "K5":  /* unknown */ 1,
  "B6":  /* unknown */ "build",
  "C6":  /* unknown */ "san",
  "E6":  /* unknown */ "Wurde eines der folgenden Bauteile nachträglich gedämmt / ausgetauscht? ... und ist das Modernisierungsjahr ... Dämmstärke (Freifeld Integer, cm)",
  "B7":  /* unknown */ "build",
  "C7":  /* unknown */ "san",
  "D7":  /* unknown */ "_build_wall_san",
  "E7":  /* unknown */ "Außenwand",
  "G7":  /* unknown */ "siehe Mockups",
  "K7":  /* unknown */ 0,
  "N7":  /* unknown */ 40,
  "Q7":  /* unknown */ "Nein",
  "R7":  /* formula */ "IF(S7=\"\",_xlfn.IFS(AND(RIGHT($P$5,4)<=\"1978\",$Q$7=\"Ja\"),Daten!$M$65,AND(RIGHT($P$5,4)>\"1978\",$Q$7=\"Ja\"),Daten!$M$66,$Q$7=\"Nein\",$P$5),S7)",
  "T7":  /* formula */ "IF(Q7=\"Ja\",IF(U7=\"\",_xlfn.XLOOKUP(1, (UWert_Mod[Bauteil]=E7)*(UWert_Mod[Modernisierungsjahr]=R7), UWert_Mod[d_ins]),U7),0)",
  "W7":  /* formula */ "\"\"",
  "B8":  /* unknown */ "build",
  "C8":  /* unknown */ "san",
  "D8":  /* unknown */ "_build_win_san",
  "E8":  /* unknown */ "Fenster",
  "G8":  /* unknown */ "siehe Mockups",
  "K8":  /* unknown */ 0,
  "Q8":  /* unknown */ "Nein",
  "R8":  /* formula */ "IF($Q$8=\"Ja\",_xlfn.IFS(S8<>\"\",S8,RIGHT($P$5,4)<=\"1978\",Daten!$M$66,RIGHT($P$5,4)>\"1978\",U_Werte_IWU!$D$78),$P$5)",
  "B9":  /* unknown */ "build",
  "C9":  /* unknown */ "san",
  "D9":  /* unknown */ "_build_roof_san",
  "E9":  /* unknown */ "Dach",
  "G9":  /* unknown */ "siehe Mockups",
  "K9":  /* unknown */ 0,
  "N9":  /* unknown */ 40,
  "Q9":  /* unknown */ "Nein",
  "R9":  /* formula */ "IF(S9=\"\",_xlfn.IFS(AND(RIGHT($P$5,4)<=\"1978\",$Q$9=\"Ja\"),Daten!$M$65,AND(RIGHT($P$5,4)>\"1978\",$Q$9=\"Ja\"),Daten!$M$66,$Q$9=\"Nein\",$P$5),S9)",
  "T9":  /* formula */ "IF(Q9=\"Ja\",IF(U9=\"\",_xlfn.XLOOKUP(1, (UWert_Mod[Bauteil]=E9)*(UWert_Mod[Modernisierungsjahr]=R9), UWert_Mod[d_ins]),U9),0)",
  "B10":  /* unknown */ "build",
  "C10":  /* unknown */ "san",
  "D10":  /* unknown */ "_build_botceil_san",
  "E10":  /* unknown */ "Fußboden",
  "G10":  /* unknown */ "siehe Mockups",
  "K10":  /* unknown */ 0,
  "N10":  /* unknown */ 40,
  "Q10":  /* unknown */ "Nein",
  "R10":  /* formula */ "IF(S10=\"\",_xlfn.IFS(AND(RIGHT($P$5,4)<=\"1978\",$Q$10=\"Ja\"),Daten!$M$77,AND(RIGHT($P$5,4)>\"1978\",$Q$10=\"Ja\"),Daten!$M$78,$Q$10=\"Nein\",$P$5),S10)",
  "T10":  /* formula */ "IF(Q10=\"Ja\",IF(U10=\"\",_xlfn.XLOOKUP(1, (UWert_Mod[Bauteil]=E10)*(UWert_Mod[Modernisierungsjahr]=R10), UWert_Mod[d_ins]),U10),0)",
  "B11":  /* unknown */ "build",
  "C11":  /* unknown */ "san",
  "D11":  /* unknown */ "_build_topceil_san",
  "E11":  /* unknown */ "Decke",
  "F11":  /* unknown */ "Im Haus am höchsten gelegene Decke eines beheizten Raumes.",
  "G11":  /* unknown */ "siehe Mockups",
  "K11":  /* unknown */ 0,
  "N11":  /* unknown */ 40,
  "Q11":  /* unknown */ "Nein",
  "R11":  /* formula */ "IF(S11=\"\",_xlfn.IFS(AND(RIGHT($P$5,4)<=\"1978\",$Q$11=\"Ja\"),Daten!$M$65,AND(RIGHT($P$5,4)>\"1978\",$Q$11=\"Ja\"),Daten!$M$66,$Q$11=\"Nein\",$P$5),S11)",
  "T11":  /* formula */ "IF(Q11=\"Ja\",IF(U11=\"\",_xlfn.XLOOKUP(1, (UWert_Mod[Bauteil]=E11)*(UWert_Mod[Modernisierungsjahr]=R11), UWert_Mod[d_ins]),U11),0)",
  "B12":  /* unknown */ "build",
  "D12":  /* unknown */ "EXIST_build_eff",
  "E12":  /* unknown */ "Ist Ihnen die Effizienzklasse bekannt? ",
  "F12":  /* unknown */ "PopUp: \nDie Energieeffizienzklasse des Gebäudes können Sie dem Energieausweis entnehmen.  \nHaben Sie diesen nicht zur Hand, kennen aber den Endenergiebedarf/-verbrauch ihres Gebäudes? In diesem Fall können Sie die Klasse anhand folgender Werte selbst zuordnen: ",
  "G12":  /* unknown */ "Dropdown",
  "K12":  /* unknown */ 0,
  "O12":  /* unknown */ "Nicht bekannt",
  "P12":  /* formula */ "$O$12",
  "A13":  /* unknown */ "Denkmalschutz",
  "B13":  /* unknown */ "build",
  "D13":  /* unknown */ "EXIST_build_denkmal",
  "E13":  /* unknown */ "Das Gebäude steht unter Denkmalschutz",
  "G13":  /* unknown */ "toggle switch",
  "K13":  /* unknown */ 1,
  "O13":  /* unknown */ "Nein",
  "P13":  /* formula */ "$O$13",
  "A14":  /* unknown */ "Wärmeübergabe",
  "B14":  /* unknown */ "build",
  "D14":  /* unknown */ "TYP_build_rad",
  "E14":  /* unknown */ "Wie werden die Räume erwärmt?",
  "F14":  /* unknown */ "PopUp: Zusatzheizungen wie Kaminöfen, Infrarotheizungen, Elektroheizungen oder Klimaanlagen werden bei der Bewertung der Räume nicht mit einbezogen. Vorhandene Zusatzheizungen tragen aber zur Beheizung einzelner Räume bei und helfen so, die Vorlauftemperatur des zentralen Heizsystems abzusenken. Das kann beispielsweise im Badezimmer sinnvoll sein. Direktelektrische Heizungen sollten wegen ihrer begrenzten Effizienz jedoch nur gezielt und auf kleiner Fläche eingesetzt werden.",
  "G14":  /* unknown */ "Radio Button + Grafik",
  "K14":  /* unknown */ 1,
  "B15":  /* unknown */ "build",
  "D15":  /* unknown */ "TYP_distr",
  "E15":  /* unknown */ "Wie wird die Wärme verteilt?",
  "F15":  /* unknown */ "PopUp: \nEine Zweirohrheizung führt das warme Wasser über zwei getrennte Leitungen – den Vorlauf zum Heizkörper und den Rücklauf zurück zur Heizungsanlage. Bei einem Einrohrsystem dagegen durchläuft das Wasser alle Heizkörper nacheinander in einer einzigen Leitung, sodass auch geschlossene Thermostatventile den Durchfluss nicht vollständig stoppen. Erkennen lässt sich ein Einrohrsystem daran, dass das Wasser trotz geschlossener Thermostatventile weiter zum nächsten Heizkörper strömt.",
  "G15":  /* unknown */ "Radio Button",
  "H15":  /* unknown */ "not ODER(P14 = \"Nachtspeicherheizung (Stromdirektheizung)\"; P14 =  \"Andere\")",
  "K15":  /* unknown */ 1,
  "B16":  /* unknown */ "build",
  "D16":  /* unknown */ "EXIST_T_VL_set",
  "E16":  /* unknown */ "Ich weiß auf welche Vorlauftemperatur die Heizung am Auslegungspunkt eingestellt ist.",
  "F16":  /* unknown */ "Untertext:\nIst Ihnen die für den kältesten Wintertag eingestellte Heizwassertemperatur bekannt? Ansonsten wählen Sie \"Nein\".\n\nPopUp: \nDie Vorlauftemperatur ist die Temperatur des Heizwassers, das von der Zentralheizung (Wärmepumpe, Gas- oder Pelletheizung, usw.) zu den einzelnen Heizkörpern oder zur Fußbodenheizung fließt. Ist Ihnen diese Temperatur nicht bekannt, wählen Sie \"Nein\".\n\nJe kälter die Außentemperatur, desto wärmer muss das Heizwasser sein. Dieser Zusammenhang wird der Heizung durch die Heizkurve vorgegeben. Daraus ergibt sich die Heizwassertemperatur, die am kältesten Wintertag (Normaußentemperatur), der am Gebäudestandort zu erwarten ist, benötigt wird (Auslegungspunkt). \n\nIn vielen Häusern ist die Vorlauftemperatur höher eingestellt, als eigentlich nötig. Das heißt: Auch wenn Ihre Heizung derzeit mit hohen Temperaturen läuft, kann Ihr Gebäude trotzdem für eine Wärmepumpe geeignet sein.",
  "G16":  /* unknown */ "toggle switch",
  "H16":  /* unknown */ "not EXIST_T_VL_meas OR not TYP_build == \"Mehrfamilienhaus\"",
  "J16":  /* unknown */ "Boolean",
  "K16":  /* unknown */ 1,
  "O16":  /* unknown */ "Nein",
  "P16":  /* formula */ "$O$16",
  "B17":  /* unknown */ "build",
  "D17":  /* unknown */ "T_VL_nom_set ",
  "E17":  /* unknown */ "Vorlauftemperatur am Auslegungspunkt",
  "G17":  /* unknown */ "Freifeld",
  "H17":  /* unknown */ "EXIST_T_VL_set",
  "I17":  /* unknown */ "°C",
  "J17":  /* unknown */ "Integer",
  "K17":  /* unknown */ 1,
  "M17":  /* unknown */ 30,
  "N17":  /* unknown */ 90,
  "B18":  /* unknown */ "build",
  "D18":  /* unknown */ "EXIST_T_VL_meas",
  "E18":  /* unknown */ "Ich kann im Heizungsraum die Vorlauftemperatur ablesen und die Außentemperatur messen",
  "F18":  /* unknown */ "Untertext: \nLesen Sie die Vorlauftemperatur Ihrer Heizung bei kaltem Wetter ab (über mindestens zwei Tage hinweg unter 5°C) und notieren Sie dazu auch die Außentemperatur am Standort Ihres Gebäudes.\n\nPopUp: \nAnhand der beiden Temperaturwerte kann die Vorlauftemperatur am Auslegungspunkt abgeschätzt werden. Dies ist jedoch nur bei ausreichend kalten Außentemperaturen möglich.\n\nSie können die Außentemperatur falls möglich an Ihrer Heizung ablesen. Sollte Ihnen keine vor Ort gemessene Außentemperatur vorliegen, nutzen Sie die Temperaturmessungen der nächstgelegenen Wetterstation zum gleichen Zeitpunkt.\n\nIn vielen Häusern ist die Vorlauftemperatur höher eingestellt, als eigentlich nötig. Das heißt: Auch wenn Ihre Heizung derzeit mit hohen Temperaturen läuft, kann Ihr Gebäude trotzdem für eine Wärmepumpe geeignet sein.",
  "G18":  /* unknown */ "toggle switch",
  "H18":  /* unknown */ "not EXIST_T_VL_set OR not TYP_build == \"Mehrfamilienhaus\"",
  "K18":  /* unknown */ 1,
  "O18":  /* unknown */ "Nein",
  "P18":  /* formula */ "$O$18",
  "B19":  /* unknown */ "build",
  "D19":  /* unknown */ "T_VL_meas ",
  "E19":  /* unknown */ "Vorlauftemperatur",
  "G19":  /* unknown */ "Freifeld",
  "H19":  /* unknown */ "EXIST_T_VL_meas",
  "I19":  /* unknown */ "°C",
  "J19":  /* unknown */ "Integer",
  "K19":  /* unknown */ 1,
  "M19":  /* unknown */ 30,
  "N19":  /* unknown */ 90,
  "B20":  /* unknown */ "build",
  "D20":  /* unknown */ "T_amb_meas ",
  "E20":  /* unknown */ "bei einer Außentemperatur von:",
  "G20":  /* unknown */ "Freifeld",
  "H20":  /* unknown */ "EXIST_T_VL_meas",
  "I20":  /* unknown */ "°C",
  "J20":  /* unknown */ "Integer",
  "K20":  /* unknown */ 1,
  "M20":  /* unknown */ -20,
  "N20":  /* unknown */ 5,
  "B21":  /* unknown */ "build",
  "D21":  /* unknown */ "INTERN_T_VL_nom_calc",
  "H21":  /* unknown */ "EXIST_T_VL_meas",
  "I21":  /* unknown */ "°C",
  "J21":  /* unknown */ "Integer",
  "P21":  /* formula */ "P20*-1.8257+43.457+P20",
  "D22":  /* unknown */ "INTERN_EXIST_T_VL_nt",
  "H22":  /* unknown */ "EXIST_T_VL_meas",
  "J22":  /* unknown */ "Boolean",
  "P22":  /* formula */ "IF(P16=\"Ja\",P17<=55,IF(P18=\"Ja\",P19<P21,FALSE))",
} as const;
