// Sheet: PAR
export const data = {
  "A1":  /* unknown */ "Bezeichnung",
  "B1":  /* unknown */ "Parameter",
  "C1":  /* unknown */ "Einheit",
  "D1":  /* unknown */ "Beschreibung",
  "E1":  /* unknown */ "Kommentar ",
  "F1":  /* unknown */ "Bezeichnung",
  "G1":  /* unknown */ "lambda_ins_thick",
  "H1":  /* unknown */ "U_inwall",
  "I1":  /* unknown */ "T_air_norm",
  "J1":  /* unknown */ "T_air_norm_bath",
  "K1":  /* unknown */ "ang_roof_slop",
  "L1":  /* unknown */ "ang_roof_steep",
  "M1":  /* unknown */ "ang_roof_steepr",
  "N1":  /* unknown */ "U_opaque_lim",
  "O1":  /* unknown */ "U_win_lim",
  "P1":  /* unknown */ "r_worst_lim",
  "Q1":  /* unknown */ "NO_round_Qdot",
  "R1":  /* unknown */ "NO_round_Qdot_spez",
  "S1":  /* unknown */ "NO_round_rcover",
  "T1":  /* unknown */ "f_A_wall_wid",
  "U1":  /* unknown */ "f_A_wall_hei",
  "V1":  /* unknown */ "f_A_roof_wid",
  "W1":  /* unknown */ "f_A_roof_hei",
  "X1":  /* unknown */ "f_Vroom_roof",
  "Y1":  /* unknown */ "f_Awall_roof",
  "A2":  /* unknown */ "lambda_ins_thick",
  "B2":  /* unknown */ 0.04,
  "C2":  /* unknown */ "W/(mK)",
  "D2":  /* unknown */ "Annahme für lambda Wert der nachträglich aufgebrachten Dämmebene ",
  "F2":  /* unknown */ "Parameter",
  "G2":  /* unknown */ 0.04,
  "H2":  /* unknown */ 2,
  "I2":  /* unknown */ 20,
  "J2":  /* unknown */ 24,
  "K2":  /* unknown */ 25,
  "L2":  /* unknown */ 40,
  "M2":  /* unknown */ 55,
  "N2":  /* unknown */ 0.8,
  "O2":  /* unknown */ 1.7,
  "P2":  /* unknown */ 0.2,
  "Q2":  /* unknown */ 100,
  "R2":  /* unknown */ 5,
  "S2":  /* unknown */ 0.1,
  "T2":  /* unknown */ 0.5,
  "U2":  /* unknown */ 0.3,
  "V2":  /* unknown */ 0.25,
  "W2":  /* unknown */ 0.3,
  "X2":  /* unknown */ 0.7,
  "Y2":  /* unknown */ 1.1,
  "A3":  /* unknown */ "T_air_norm",
  "B3":  /* unknown */ 20,
  "C3":  /* unknown */ "°C",
  "D3":  /* unknown */ "Norm-Raumtemperatur Standardraum",
  "F3":  /* unknown */ "Einheit",
  "G3":  /* unknown */ "W/(mK)",
  "H3":  /* unknown */ "W/(m²K)",
  "I3":  /* unknown */ "°C",
  "J3":  /* unknown */ "°C",
  "K3":  /* unknown */ "°",
  "L3":  /* unknown */ "°",
  "M3":  /* unknown */ "°",
  "N3":  /* unknown */ "W/(m²K)",
  "O3":  /* unknown */ "W/(m²K)",
  "P3":  /* unknown */ "%",
  "Q3":  /* unknown */ "W",
  "R3":  /* richtext_as_string */ "W/m²",
  "S3":  /* unknown */ "%",
  "T3":  /* unknown */ "m",
  "U3":  /* unknown */ "m",
  "V3":  /* unknown */ "m",
  "A4":  /* unknown */ "T_air_norm_bath",
  "B4":  /* unknown */ 24,
  "C4":  /* unknown */ "°C",
  "D4":  /* unknown */ "Norm-Raumtemperatur Badezimmer",
  "F4":  /* unknown */ "Beschreibung",
  "G4":  /* unknown */ "Annahme für lambda Wert der nachträglich aufgebrachten Dämmebene ",
  "H4":  /* unknown */ "Pauschaler U-Wert Innenwand",
  "I4":  /* unknown */ "Norm-Raumtemperatur Standardraum",
  "J4":  /* unknown */ "Norm-Raumtemperatur Badezimmer",
  "K4":  /* unknown */ "Dachneigung geneigt",
  "L4":  /* unknown */ "Dachneigung steil",
  "M4":  /* unknown */ "Dachneigung sehr steil",
  "N4":  /* unknown */ "Grenzwert U-Wert für Austauschpotenzial opaker Bauteile",
  "O4":  /* unknown */ "Grenzwert U-Wert für Austauschpotenzial Fenster",
  "P4":  /* unknown */ "Mindestanteil eines Bauteils an der Raumheizlast, für Austauschpotenzial",
  "Q4":  /* unknown */ "Genauigkeit Ausgabe Wärmeleistung",
  "R4":  /* unknown */ "Genaugikeit ausgabe spez. Wärmeleistung",
  "S4":  /* unknown */ "Genauigkeit Ausgabe Heizkörper-Deckungsgrad ",
  "T4":  /* unknown */ "Zuschlag Wandlänge zur Berücksichtigung Außenmaße vs. erfasste Innenmaße",
  "U4":  /* unknown */ "Zuschlag Wandhöhe zur Berücksichtigung Außenmaße vs. erfasste Innenmaße",
  "V4":  /* unknown */ "Zuschlag Dachbreite zur Berücksichtigung Außenmaße vs. erfasste Innenmaße",
  "W4":  /* unknown */ "Zuschlag Dachhöhe zur Berücksichtigung Außenmaße vs. erfasste Innenmaße",
  "X4":  /* unknown */ "Abschlag Raumvolumen bei Dachräumen ",
  "Y4":  /* unknown */ "Pauschaler Vergrößerungsfaktor der Wandflächen in Dachräumen zur Berücksichtigung der Außenfläche (ggü. erfasster Innenfläche)",
  "F5":  /* unknown */ "Kommentar ",
  "F10":  /* formula */ "INDEX(PAR[T_air_norm],1)",
} as const;
