// Sheet: TXT_build
export const data = {
  "A1":  /* unknown */ "Gruppe",
  "B1":  /* unknown */ "Variable ",
  "C1":  /* unknown */ "Kommentar",
  "D1":  /* unknown */ "INPUT_TXT_rooms",
  "A2":  /* unknown */ "G1 NT-ready",
  "B2":  /* unknown */ "TXT_build_G1_not",
  "D2":  /* unknown */ "## <i class=\"bi bi-circle-fill rating-red\"></i> Derzeit noch nicht niedertemperaturfähig – Maßnahmen erforderlich  \n\nNoch nicht bereit zum effizienten und günstigen Heizen mit einer Wärmepumpe.\nIn einem gut auf eine Wärmepumpe vorbereiten Haus sollte eine <abbr title=\"Temperatur des Wassers in den Heizungsrohren, bevor das Wasser die Heizkörper erstmals durchströmt.\">Vorlauftemperatur</abbr> von 55 °C ausreichen, damit Sie sich auch an kalten Wintertagen wohlfühlen.  Ihr Haus braucht aktuell jedoch deutlich höhere Temperaturen, um warm zu bleiben.\nIn den meisten überprüften Räumen sind entweder die Heizkörper oder die Gebäudehülle noch nicht gut geeignet. Ohne Verbesserungen würde eine Wärmepumpe nicht effizient und wirtschaftlich laufen. Schon der Tausch eines Heizkörpers kann oft ausreichen, um die Vorlauftemperatur deutlich zu senken. Ein Blick in die Grafik zeigt, ob das bei Ihrem Gebäude ausreicht, um effizient mit einer Wärmepumpe zu heizen.\n\nAm Markt sind immer mehr Wärmepumpen verfügbar, die höhere Temperaturen als 55 °C bereitstellen können. Solche Geräte können auch eine Lösung darstellen, wenn es nicht gelingt, die Heizlast zu senken. Höhere Heizkreistemperaturen führen jedoch aufgrund der geringeren Effizienz zu höheren Stromkosten. Wenn Sie in Zukunft größere Modernisierungen der Gebäudehülle planen, kann in der Zwischenzeit auch eine Hybrid-Wärmepumpe eine passende Lösung für Sie sein.\n",
  "A3":  /* unknown */ "G1 NT-ready",
  "B3":  /* unknown */ "TXT_build_G1_notyet",
  "D3":  /* unknown */ "## <i class=\"bi bi-circle-fill rating-orange\"></i> Teilweise niedertemperaturfähig – Maßnahmen erforderlich  \n\n### Gute Basis – mit Potenzial \nIn einem gut auf eine Wärmepumpe vorbereiten Haus sollte eine <abbr title=\"Temperatur des Wassers in den Heizungsrohren, bevor das Wasser die Heizkörper erstmals durchströmt.\">Vorlauftemperatur</abbr> von 55 °C ausreichen, damit Sie sich auch an kalten Wintertagen wohlfühlen.\nManche der erfassten Räume lassen sich bereits mit niedrigen Vorlauftemperaturen erwärmen. Einige Räume brauchen jedoch eine höhere Vorlauftemperatur. Mit einfachen, gezielten Maßnahmen kann die Vorlauftemperatur ausreichend reduziert und das Gebäude effizient und wirtschaftlich mit einer Wärmepumpe beheizt werden. Schon der Tausch eines Heizkörpers kann oft ausreichen, um die Vorlauftemperatur deutlich zu senken. Ein Blick in die Grafik zeigt, ob das bei Ihrem Gebäude klappt.\n\nAm Markt sind immer mehr Wärmepumpen verfügbar, die höhere Temperaturen als 55 °C bereitstellen können. Solche Geräte können auch eine Lösung darstellen, wenn es nicht gelingt, die Heizlast zu senken. Höhere Heizkreistemperaturen führen jedoch aufgrund der geringeren Effizienz zu höheren Stromkosten. ",
  "A4":  /* unknown */ "G1 NT-ready",
  "B4":  /* unknown */ "TXT_build_G1_almost",
  "D4":  /* unknown */ "## <i class=\"bi bi-circle-fill rating-yellow\"></i> Fast niedertemperaturfähig – Maßnahmen empfehlenswert  \n\n### Gute Basis – mit Potenzial  \n\nIn einem gut auf eine Wärmepumpe vorbereiten Haus sollte eine <abbr title=\"Temperatur des Wassers in den Heizungsrohren, bevor das Wasser die Heizkörper erstmals durchströmt.\">Vorlauftemperatur</abbr> von 55 °C ausreichen, damit Sie sich auch an kalten Wintertagen wohlfühlen. Ihr Haus braucht aktuell jedoch deutlich höhere Temperaturen, um warm zu bleiben. \nViele der erfassten Räume lassen sich bereits mit niedrigen Vorlauftemperaturen effizient erwärmen. Ein Praxischeck im ersten Winter kann Klarheit bringen, ob in den anderen Räumen kleine gezielte Maßnahmen sinnvoll sind, damit sich das gesamte Gebäude noch effizienter und wirtschaftlicher mit einer Wärmepumpe beheizen lässt.",
  "A5":  /* unknown */ "G1 NT-ready",
  "B5":  /* unknown */ "TXT_build_G1_NTr",
  "D5":  /* unknown */ "## <i class=\"bi bi-circle-fill rating-green\"></i> Niedertemperaturfähig – gute Voraussetzungen  \n\n### Bereit für die Wärmepumpe!  \n\nAlle erfassten Räume werden auch an kalten Wintertagen bei maximal 55°C <abbr title=\"Temperatur des Wassers in den Heizungsrohren, bevor das Wasser die Heizkörper erstmals durchströmt.\">Vorlauftemperatur</abbr> angenehm warm. Ihr Haus ist damit gut vorbereitet für effizientes und wirtschaftliches Heizen mit einer Wärmepumpe – ohne zusätzliche Maßnahmen.",
  "A6":  /* unknown */ "G2 Dashboard",
  "B6":  /* unknown */ "TXT_build_G2_load_verysuit",
  "D6":  /* unknown */ "### Die Heizlast ist bereits sehr niedrig  \n\nEin besserer Wärmeschutz bringt in diesem Raum nur noch geringe Verbesserung.\n",
  "A7":  /* unknown */ "G2 Dashboard",
  "B7":  /* unknown */ "TXT_build_G2_load_1_suit",
  "D7":  /* unknown */ "### Gut geeignet, mit Potenzial  \n\nDie Heizlast ist durchschnittlich. Über die ",
  "A8":  /* unknown */ "G2 Dashboard",
  "B8":  /* unknown */ "TXT_build_G2_load_1_almostsuit",
  "D8":  /* unknown */ "### Verbesserungsbedarf, da geht noch was \n\nDie Heizlast ist überdurchschnittlich hoch. Über die ",
  "A9":  /* unknown */ "G2 Dashboard",
  "B9":  /* unknown */ "TXT_build_G2_load_1_notsuit",
  "D9":  /* unknown */ "### Sehr hohe Wärmeverluste – hoher Energieverbrauch\n\nDie Heizlast ist sehr hoch. Über die",
  "A10":  /* unknown */ "G2 Dashboard",
  "B10":  /* unknown */ "TXT_build_G2_load_2",
  "D10":  /* unknown */ "geht in diesem Raum die meiste Wärme verloren.\n",
  "A11":  /* unknown */ "G2 Dashboard",
  "B11":  /* unknown */ "TXT_build_G2_rad_notsuff",
  "D11":  /* unknown */ "### Der aktuelle Heizkörper ist zu klein \n\nSelbst ein besseres Modell (<abbr title=\"Ein Flachheizkörper modernder Bauart in der leistungsstärksten Grundkonfiguration. Mit Typ33-Heizkörpern ist bei gleichen Abmaßen die größtmögliche Heizleistung im Vergleich zu anderen Heizkörpern zu erwarten.\">Typ 33</abbr>) müsste mindestens doppelt so groß sein. Alternativ kann ein zusätzlicher Heizköper oder ein <abbr title=\"Die durch die Gebläse verstärkte Luftbewegung erhöht die Leistung des Heizkörpers, siehe Wärmepumpen-Heizkörper\"> Heizkörper mit integriertem Gebläse </abbr> installiert werden.\n",
  "A12":  /* unknown */ "G2 Dashboard",
  "B12":  /* unknown */ "TXT_build_G2_rad_suffchangeobl",
  "D12":  /* unknown */ "### Zu geringe Leistung.  \n\nAuch ein besserer Heizkörper (<abbr title=\"Ein Flachheizkörper modernder Bauart in der leistungsstärksten Grundkonfiguration. Mit Typ33-Heizkörpern ist bei gleichen Abmaßen die größtmögliche Heizleistung im Vergleich zu anderen Heizkörpern zu erwarten.\">Typ 33</abbr>) müsste etwas größer dimensioniert werden. Alternativ könnte es mit einem <abbr title=\"Die durch die Gebläse verstärkte Luftbewegung erhöht die Leistung des Heizkörpers, siehe Wärmepumpen-Heizkörper\"> Gebläseheizkörper </abbr> gleicher Größe klappen.\n",
  "A13":  /* unknown */ "G2 Dashboard",
  "B13":  /* unknown */ "TXT_build_G2_rad_suffchange",
  "D13":  /* unknown */ "### Etwas zu geringe Leistung\n\nNach Austausch mit einem leistungsstärkeren Modell gleicher Größe sollte die Leistung ausreichen. \n\n",
  "A14":  /* unknown */ "G2 Dashboard",
  "B14":  /* unknown */ "TXT_build_G2_rad_suff",
  "D14":  /* unknown */ "### Gut ausgestattet!  \n\nAusreichende Heizkörperleistung, ein Tausch ist nicht notwendig. \n\n",
  "A15":  /* unknown */ "G3 Heizkörpertausch",
  "B15":  /* unknown */ "TXT_build_G3_notsuff_1",
  "D15":  /* unknown */ "### <i class=\"bi bi-circle-fill rating-red\"></i> Viele Heizkörper sind nicht geeignet – Maßnahmen erforderlich  \n\nHier ist ein Heizkörpertausch notwendig.   \n\n\n",
  "A16":  /* unknown */ "G3 Heizkörpertausch",
  "B16":  /* unknown */ "TXT_build_G3_notsuff_2",
  "D16":  /* unknown */ "der in Ihrem Gebäude erfassten Räume benötigen aktuell eine sehr hohe  <abbr title=\"Temperatur des Wassers in den Heizungsrohren, bevor das Wasser die Heizkörper erstmals durchströmt.\">Vorlauftemperatur</abbr>  von deutlich mehr als 55 °C. Sind keine Dämmmaßnahmen geplant, sollten Sie diese Heizkörper durch größere oder leistungsstärkere Modelle ersetzen, damit eine Wärmepumpe effizient und wirtschaftlich arbeitet.\n\n<i class=\"bi bi-lightbulb-fill\"></i> Hinweis: Sie können weitere Räume eingeben, um ein genaueres Bild zu erhalten. Spätestens im Rahmen der konkreten Planung sollten alle Heizkörper und Räume im Detail bewertet werden.  \n",
  "A17":  /* unknown */ "G3 Heizkörpertausch",
  "B17":  /* unknown */ "TXT_build_G3_suffchangeobl",
  "D17":  /* unknown */ "## <i class=\"bi bi-circle-fill rating-orange\"></i> Einzelne Heizkörper sind nicht geeignet – Maßnahmen sinnvoll  \n\n### Ein Tausch verbessert die Effizienz.  \n\nEin Teil der Heizkörper benötigt relativ hohe <abbr title=\"Temperatur des Wassers in den Heizungsrohren, bevor das Wasser die Heizkörper erstmals durchströmt.\">Vorlauftemperaturen</abbr>. Sind keine Dämmmaßnahmen geplant, können Sie durch einen Austausch gegen leistungsstärkere Modelle die Voraussetzungen für eine Wärmepumpe verbessern und den Stromverbrauch senken.\n<i class=\"bi bi-lightbulb-fill\"></i> Hinweis: Prüfen Sie zusätzliche Räume oder klären Sie Details in der weiteren Planung.",
  "A18":  /* unknown */ "G3 Heizkörpertausch",
  "B18":  /* unknown */ "TXT_build_G3_suffchange",
  "D18":  /* unknown */ "## <i class=\"bi bi-circle-fill rating-yellow\"></i> Die meisten Heizkörper passen  \n\n### Ein Wärmepumpen-Praxischeck kann zeigen, ob die Heizkörperflächen in den kritischen Räumen ausreichen.   \n\nEinzelne Heizkörper in den erfassten Räumen benötigen eine etwas zu hohe <abbr title=\"Temperatur des Wassers in den Heizungsrohren, bevor das Wasser die Heizkörper erstmals durchströmt.\">Vorlauftemperatur</abbr>. Ob das in der Praxis ein Problem darstellt, hängt davon ab, wie warm Sie es in diesen Räumen haben möchten und wie intensiv sie genutzt werden. Nach der ersten Heizperiode mit Wärmepumpe haben Sie Klarheit und können über einen Austausch entscheiden.\n\n<i class=\"bi bi-lightbulb-fill\"></i> Hinweis: Wenn Sie weitere Räume hinzufügen, kann die Einschätzung noch präziser werden.",
  "A19":  /* unknown */ "G3 Heizkörpertausch",
  "B19":  /* unknown */ "TXT_build_G3_suff",
  "D19":  /* unknown */ "## <i class=\"bi bi-circle-fill rating-green\"></i> Heizkörper sind gut geeignet – keine Maßnahmen erforderlich  \n\n### Gute Voraussetzungen!  \n\nDie vorhandenen Heizkörper halten die erfassten Räume bei maximal 55°C <abbr title=\"Temperatur des Wassers in den Heizungsrohren, bevor das Wasser die Heizkörper erstmals durchströmt.\">Vorlauftemperatur</abbr> zuverlässig warm. So läuft eine Wärmepumpe effizient – ein Austausch ist nicht erforderlich.\n\n<i class=\"bi bi-lightbulb-fill\"></i> Hinweis: Wenn Sie weitere Räume hinzufügen, kann die Einschätzung noch präziser werden.",
  "A20":  /* unknown */ "G4 Gebäudehülle ",
  "B20":  /* unknown */ "TXT_build_G4_intro_notsuit",
  "D20":  /* unknown */ "## <i class=\"bi bi-house-fill rating-red\"></i> Wärmeschutzniveau gering – Maßnahmen sehr sinnvoll \n\nDas Gebäude verliert viel Wärme über die Hülle. Wenn die Heizkörper groß genug für die einzelnen Räume sind, kann eine Wärmepumpe trotzdem effizient heizen. Wenn das nicht reicht, empfiehlt sich eine energetische Verbesserung der Gebäudehülle, um den Stromverbrauch zu senken.\nMehrere Bauteile weisen einen sehr hohen Wärmedurchgang (genannt: U-Wert) auf. Eine (zusätzliche) Dämmung senkt den Energieverbrauch und die Heizlast deutlich und schafft die nötigen Voraussetzungen für den effizienten und wirtschaftlichen Wärmepumpenbetrieb. Dann genügt außerdem eine kleinere, günstigere Wärmepumpe.\nDas größte Verbesserungspotenzial",
  "A21":  /* unknown */ "G4 Gebäudehülle ",
  "B21":  /* unknown */ "TXT_build_G4_intro_notsuit_plus",
  "D21":  /* unknown */ "<i class=\"bi bi-lightbulb-fill\"></i> Hinweis: Ergänzen Sie weitere Räume, um ein vollständigeres Bild der Hüllenqualität zu erhalten – oder klären Sie die erforderliche Ertüchtigung der Bauteile in der Planungsphase.",
  "A22":  /* unknown */ "G4 Gebäudehülle ",
  "B22":  /* unknown */ "TXT_build_G4_intro_almostsuit",
  "D22":  /* unknown */ "## <i class=\"bi bi-house-fill rating-orange\"></i> Wärmeschutz ausbaufähig – Maßnahmen empfehlenswert  \n\nEinige Bauteile bieten Verbesserungspotenzial. Wenn die Heizflächen groß genug für die einzelnen Räume sind, kann eine Wärmepumpe trotzdem effizient heizen.\nDas Wärmeschutzniveau ist teilweise gut, aber die Wärmeverluste sind noch ziemlich hoch.\nGezielte Dämmmaßnahmen senken den Energieverbrauch und verbessern die Effizienz einer Wärmepumpe .\nDas größte Verbesserungspotenzial",
  "A23":  /* unknown */ "G4 Gebäudehülle ",
  "B23":  /* unknown */ "TXT_build_G4_intro_almostsuit_plus",
  "D23":  /* unknown */ "<i class=\"bi bi-lightbulb-fill\"></i> Hinweis: Für eine genauere Bewertung können weitere Räume ergänzt oder im Planungsprozess detailliert betrachtet werden.",
  "A24":  /* unknown */ "G4 Gebäudehülle ",
  "B24":  /* unknown */ "TXT_build_G4_intro_suit",
  "D24":  /* unknown */ "## <i class=\"bi bi-hpuse-fill rating-yellow\"></i> Wärmeschutz ausbaufähig – Maßnahmen vorteilhaft  \n\nEinzelne Bauteile bieten noch Potenzial.\nDas Wärmeschutzniveau ist insgesamt gut, aber zum Teil sind die Wärmeverluste hoch. \nGezielte Verbesserungen können die Effizienz einer Wärmepumpe weiter steigern und langfristig den Energieverbrauch und die Kosten senken.\nDas größte Verbesserungspotenzial ",
  "A25":  /* unknown */ "G4 Gebäudehülle ",
  "B25":  /* unknown */ "TXT_build_G4_intro_suit_plus",
  "D25":  /* unknown */ "<i class=\"bi bi-lightbulb-fill\"></i> Hinweis: Für eine genauere Bewertung können weitere Räume ergänzt oder im Planungsprozess detailliert betrachtet werden.",
  "A26":  /* unknown */ "G4 Gebäudehülle ",
  "B26":  /* unknown */ "TXT_build_G4_intro_verysuit",
  "D26":  /* unknown */ "## <i class=\"bi bi-house-fill rating-green\"></i> Gut gedämmte Gebäudehülle – keine Maßnahmen erforderlich  \n\n### Sehr gute Voraussetzungen!  \n\nDie eingegebenen Räume zeigen gut gedämmte Außenbauteile – die Wärmeverluste sind gering. Einer effizienten Beheizung mit einer Wärmepumpe steht nichts im Weg.",
  "A27":  /* unknown */ "G4 Gebäudehülle ",
  "B27":  /* unknown */ "TXT_build_G4_intro_verysuit_plus",
  "D27":  /* unknown */ "<i class=\"bi bi-lightbulb-fill\"></i> Hinweis: Zusätzliche Räume können helfen, das Bild weiter zu schärfen.",
  "A28":  /* unknown */ "G4 Gebäudehülle ",
  "B28":  /* unknown */ "TXT_buid_G4_wall_notsuit_1",
  "D28":  /* unknown */ "## Hohe Wärmeverluste über die Außenwand – Dämmung erforderlich   \n\nDie Dämmung der Außenwand ist unzureichend. Sie ist für ",
  "B29":  /* unknown */ "TXT_buid_G4_wall_notsuit_2",
  "D29":  /* unknown */ " der Wärmeverluste verantwortlich. Der hohe Wärmeverlust verschlechtert die Effizienz einer Wärmepumpe und erhöht deren Stromverbrauch. Eine zusätzliche Dämmung ist empfehlenswert und verbessert die Wärmepumpen-Eignung des gesamten Gebäudes.",
  "A30":  /* unknown */ "G4 Gebäudehülle ",
  "B30":  /* unknown */ "TXT_buid_G4_wall_almostsuit_1",
  "D30":  /* unknown */ "## Außenwand mit hohem Energieverlust – Verbesserung empfohlen  \n\nDie Dämmung der Außenwand ist unzureichend. Sie ist für ",
  "B31":  /* unknown */ "TXT_buid_G4_wall_almostsuit_2",
  "D31":  /* unknown */ " der Wärmeverluste verantwortlich. Der hohe Wärmeverlust verschlechtert die Effizienz einer Wärmepumpe und erhöht deren Stromverbrauch. Eine zusätzliche Dämmung ist empfehlenswert und verbessert die Wärmepumpen-Eignung des gesamten Gebäudes.",
  "A32":  /* unknown */ "G4 Gebäudehülle ",
  "B32":  /* unknown */ "TXT_buid_G4_wall_suit",
  "D32":  /* unknown */ "## Ausbaufähiger Wärmeschutz Außenwand – Maßnahmen vorteilhaft  \n\nDie Außenwand zeigt bereits einen moderaten Wärmeschutz. Circa ",
  "D33":  /* unknown */ " der Wärme gehen über die Außenwand verloren. Eine zusätzliche Dämmung kann die Heizlast weiter reduzieren und damit die Wärmepumpen-Eignung verbessern.",
  "A34":  /* unknown */ "G4 Gebäudehülle ",
  "B34":  /* unknown */ "TXT_buid_G4_wall_verysuit",
  "D34":  /* unknown */ "## Außenwand gut gedämmt – geringe Wärmeverluste  \n\nDie Außenwand hat einen guten energetischen Standard und sorgt für geringe Wärmeverluste. Damit bietet sie gute Voraussetzungen für den effizienten Betrieb einer Wärmepumpe. ",
  "A35":  /* unknown */ "G4 Gebäudehülle ",
  "B35":  /* unknown */ "TXT_buid_G4_win_notsuit_1",
  "D35":  /* unknown */ "## <i class=\"bi bi-circle-fill rating-red\"></i> Veraltete Fenster – Maßnahmen erforderlich  \n\n### Die Fenster verlieren sehr viel Wärme (circa ",
  "B36":  /* unknown */ "TXT_buid_G4_win_notsuit_2",
  "D36":  /* unknown */ " der Wärmeverluste).  \n\nIn vielen Räumen sind die Fenster energetisch veraltet. Der hohe Wärmeverlust verschlechtert die Effizienz einer Wärmepumpe. Ein Austausch ist empfehlenswert – am besten im Zuge einer möglichen Fassadensanierung, um Kosten zu sparen und die Fenster in die Dämmebene zu versetzen.",
  "A37":  /* unknown */ "G4 Gebäudehülle ",
  "B37":  /* unknown */ "TXT_buid_G4_win_almostsuit_1",
  "D37":  /* unknown */ "## Einige Fenster veraltet – Maßnahmen sinnvoll  \n\n### Die Fenster verlieren viel Wärme (circa ",
  "B38":  /* unknown */ "TXT_buid_G4_win_almostsuit_2",
  "D38":  /* unknown */ " der Wärmeverluste).  \nEinige Fenster sind energetisch ungünstig veraltet. Der Austausch – am besten im Zuge einer möglichen Fassadensanierung – verbessert die Wärmepumpen-Eignung und spart Energie.",
  "A39":  /* unknown */ "G4 Gebäudehülle ",
  "B39":  /* unknown */ "TXT_buid_G4_win_suit",
  "D39":  /* unknown */ "## Einzelne Fenster als Schwachstelle – Maßnahmen vorteilhaft  \n\n### Fenster verbessern – für mehr Effizienz.  \n\nEinige Fenster sind energetisch ungünstig. Der Austausch verbessert die Wärmepumpen-Eignung und spart Energie.",
  "A40":  /* unknown */ "G4 Gebäudehülle ",
  "B40":  /* unknown */ "TXT_buid_G4_win_verysuit",
  "D40":  /* unknown */ "## Fenster in gutem Zustand – kein Austausch nötig  \n\n### Alles im grünen Bereich.  \n\nDie Fenster sind ausreichend wärmedämmend – für die Nutzung einer Wärmepumpe bestehen keine Einschränkungen.",
  "A41":  /* unknown */ "G4 Gebäudehülle ",
  "B41":  /* unknown */ "TXT_buid_G4_roof_notsuit_1",
  "D41":  /* unknown */ "## Dach mit sehr hohen Wärmeverlusten – Dämmung erforderlich  \n\nDas Dach besitzt aktuell wenig Wärmeschutz und ist deshalb für circa ",
  "B42":  /* unknown */ "TXT_buid_G4_roof_notsuit_2",
  "D42":  /* unknown */ " der Wärmeverluste verantwortlich, was die <abbr title=\"Die Summe der Wärmeverluste eines Raumes über alle Bauteile bei angenommener Raum- und Außentemperatur.\">Heizlast</abbr> deutlich erhöht.  \nEine Dämmung kann hier wirksam Abhilfe schaffen – sie verbessert den Wohnkomfort und trägt zur Reduktion der Vorlauftemperatur bei.",
  "A43":  /* unknown */ "G4 Gebäudehülle ",
  "B43":  /* unknown */ "TXT_buid_G4_roof_almostsuit_1",
  "D43":  /* unknown */ "## Höhere Energieverluste Dachflächen – Verbesserung empfohlen  \n\nDer vorhandene Wärmeschutz des Dachs ist ausbaufähig (circa ",
  "B44":  /* unknown */ "TXT_buid_G4_roof_almostsuit_2",
  "D44":  /* unknown */ " der Wärmeverluste). Eine nachträgliche oder dickere Dämmung reduziert nicht nur die Heizkosten, sondern erleichtert auch den effizienten Betrieb einer Wärmepumpe.",
  "A45":  /* unknown */ "G4 Gebäudehülle ",
  "B45":  /* unknown */ "TXT_buid_G4_roof_suit",
  "D45":  /* unknown */ "## Dach mit moderatem Wärmeschutz – Optimierungspotenzial  \n\nDas Dach bietet bereits einen soliden Wärmeschutz, der jedoch weiter verbessert werden kann. Eine zusätzliche Dämmung hilft, die <abbr title=\"Die Summe der Wärmeverluste eines Raumes über alle Bauteile bei angenommener Raum- und Außentemperatur.\">Heizlast</abbr> weiter zu senken und ermöglicht niedrigere <abbr title=\"Temperatur des Wassers in den Heizungsrohren, bevor das Wasser die Heizkörper erstmals durchströmt.\">Vorlauftemperaturen</abbr>en – ein Pluspunkt für den Wärmepumpenbetrieb.",
  "A46":  /* unknown */ "G4 Gebäudehülle ",
  "B46":  /* unknown */ "TXT_buid_G4_roof_verysuit",
  "D46":  /* unknown */ "## Dach gut isoliert – sehr gute Voraussetzung  \n\nDas Dach hat einen niedrigen <abbr title=\"Ein bauphysikalischer Kennwert. Er gibt an, wie viel Wärme durch einen Quadratmeter eines Bauteils bei einer Temperaturdifferenz von einem Kelvin strömt.\">U-Wert</abbr>.  \nDamit verliert es wenig Wärme und leistet bereits einen wichtigen Beitrag zum Wärmeschutz des Gebäudes. Das ist ideal für den wirtschaftlichen und effizienten Betrieb einer Wärmepumpe.",
  "A47":  /* unknown */ "G4 Gebäudehülle ",
  "B47":  /* unknown */ "TXT_build_G4_ceil_notsuit",
  "D47":  /* unknown */ "## Oberste Geschossdecke und Fußboden mit hohen Wärmeverlusten\n\n",
  "A48":  /* unknown */ "G4 Gebäudehülle ",
  "B48":  /* unknown */ "TXT_build_G4_ceil_almostsuit",
  "D48":  /* unknown */ "## Oberste Geschossdecke und Fußboden: Wärmeschutz ausbaufähig\n\n",
  "A49":  /* unknown */ "G4 Gebäudehülle ",
  "B49":  /* unknown */ "TXT_build_G4_ceil_suit",
  "D49":  /* unknown */ "## Oberste Geschossdecke und Fußboden mit moderatem Wärmeschutz \n\n",
  "A50":  /* unknown */ "G4 Gebäudehülle ",
  "B50":  /* unknown */ "TXT_build_G4_ceil_verysuit",
  "D50":  /* unknown */ "## Geringe Wärmeverluste über oberste Geschossdecke und Fußboden\n\n",
  "A51":  /* unknown */ "G4 Gebäudehülle ",
  "B51":  /* unknown */ "TXT_buid_G4_botceil_notsuit_1",
  "D51":  /* unknown */ "### Ungedämmter Fußboden verursacht hohe Wärmeverluste (Anteil circa ",
  "A52":  /* unknown */ "G4 Gebäudehülle ",
  "B52":  /* unknown */ "TXT_buid_G4_botceil_notsuit_2",
  "D52":  /* unknown */ " ).    \n\nEine ungedämmte Kellerdecke zum nicht beheizten Keller verursacht erhebliche Verluste. Eine Dämmung von unten ist eine einfache und wirkungsvolle Maßnahme.  \nIst kein Keller vorhanden, wäre die Dämmung der Bodenplatte mit dem Neuaufbau des Fußbodens verbunden und andere Wärmeschutzmaßnahmen sind vorzuziehen. ",
  "A53":  /* unknown */ "G4 Gebäudehülle ",
  "B53":  /* unknown */ "TXT_buid_G4_botceil_almostsuit_1",
  "D53":  /* unknown */ "### Ungedämmter Fußboden verursacht spürbare Wärmeverluste (Anteil circa ",
  "A54":  /* unknown */ "G4 Gebäudehülle ",
  "B54":  /* unknown */ "TXT_buid_G4_botceil_almostsuit_2",
  "D54":  /* unknown */ " ).  \n\nEinige Räume haben einen höheren Wärmeverlust durch den Fußboden.   \nEine nachträgliche Dämmung der Kellerdecke von unten ist meist einfach umsetzbar und kann die Effizienz deutlich verbessern.  \nWenn kein Keller vorhanden ist, kann eine Dämmung sehr aufwändig sein – andere Maßnahmen haben dann Vorrang.",
  "A55":  /* unknown */ "G4 Gebäudehülle ",
  "B55":  /* unknown */ "TXT_buid_G4_botceil_suit",
  "D55":  /* unknown */ "### Fußboden mit passablem Wärmeschutz - Optimierung möglich.  \n\nGrenzt der Fußboden gegen einen unbeheizten Keller, kann die Kellerdecke einfach nachträglich gedämmt werden. ",
  "A56":  /* unknown */ "G4 Gebäudehülle ",
  "B56":  /* unknown */ "TXT_buid_G4_botceil_verysuit",
  "D56":  /* unknown */ "### Fußboden gut gedämmt – kaum Wärmeverluste nach unten.  \n\nSehr gut: In Richtung unbeheizter Keller oder Erdreich geht nur wenig Wärme verloren. ",
  "A57":  /* unknown */ "G4 Gebäudehülle ",
  "B57":  /* unknown */ "TXT_buid_G4_topceil_notsuit_1",
  "D57":  /* unknown */ "### Ungedämmte Decke zum Dachboden verursacht hohe Wärmeverluste (Anteil circa ",
  "A58":  /* unknown */ "G4 Gebäudehülle ",
  "B58":  /* unknown */ "TXT_buid_G4_topceil_notsuit_2",
  "D58":  /* unknown */ " ).  \n\nOhne Dämmung entweicht viel Wärme über die oberste Geschossdecke in den unbeheizten Dachraum.  \nEine nachträgliche Dämmung auf der Decke ist meist einfach und günstig umsetzbar und besonders effektiv.\n\n",
  "A59":  /* unknown */ "G4 Gebäudehülle ",
  "B59":  /* unknown */ "TXT_buid_G4_topceil_almostsuit_1",
  "D59":  /* unknown */ "### Ungedämmte Decke zum Dachraum bringt spürbare Wärmeverluste (Anteil circa ",
  "A60":  /* unknown */ "G4 Gebäudehülle ",
  "B60":  /* unknown */ "TXT_buid_G4_topceil_almostsuit_2",
  "D60":  /* unknown */ " ).  \n\nDie Dachräume haben einen höheren Wärmeverlust an den unbeheizten Dachraum.   \nEine nachträgliche Dämmung auf der Decke ist meist einfach und günstig umsetzbar und besonders effektiv.\n\n",
  "A61":  /* unknown */ "G4 Gebäudehülle ",
  "B61":  /* unknown */ "TXT_buid_G4_topceil_suit",
  "D61":  /* unknown */ "### Moderate Wärmeverluste zum unbeheizten Dachraum - Optimierung möglich.  \n\nSollte sich die Gelegenheit ergeben, kann etwas mehr Dämmung nachträglich kostengünstig auf der Decke aufgebracht werden. \n\n",
  "A62":  /* unknown */ "G4 Gebäudehülle ",
  "B62":  /* unknown */ "TXT_buid_G4_topceil_verysuit",
  "D62":  /* unknown */ "### Oberste Geschossdecke gut gedämmt – kaum Wärmeverluste nach oben.  \n\nSehr gut: Es entweicht kaum Wärme in den unbeheizten Dachraum – keine Maßnahme erforderlich.\n\n",
  "A63":  /* unknown */ "G4 Gebäudehülle ",
  "D63":  /* unknown */ "<i class=\"bi bi-lightbulb-fill\"></i> Hinweis: Für eine genauere Bewertung können weitere Räume ergänzt oder im Planungsprozess detailliert betrachtet werden.",
  "A64":  /* unknown */ "G4 Gebäudehülle ",
  "B64":  /* unknown */ "TXT_build_G4_wall",
  "D64":  /* unknown */ "### Der Anteil der Außenwände an der Heizlast der erfassten Räume ist relativ gering, die Sanierung anderer Bauteile geht vor.\n\n",
  "A65":  /* unknown */ "G4 Gebäudehülle ",
  "B65":  /* unknown */ "TXT_build_G4_win",
  "D65":  /* unknown */ "### Der Anteil der Fenster an der Heizlast der erfassten Räume ist relativ gering, die Sanierung anderer Bauteile geht vor.\n\n",
  "A66":  /* unknown */ "G4 Gebäudehülle ",
  "B66":  /* unknown */ "TXT_build_G4_roof",
  "D66":  /* unknown */ "### Der Anteil der Dachfläche an der Heizlast der erfassten Räume ist relativ gering, die Sanierung anderer Bauteile geht vor.\n\n",
  "A67":  /* unknown */ "G4 Gebäudehülle ",
  "B67":  /* unknown */ "TXT_build_G4_topceil",
  "D67":  /* unknown */ "### Der Anteil der obersten Geschossdecke an der Heizlast der erfassten Räume ist relativ gering, die Sanierung anderer Bauteile geht vor.\n\n",
  "A68":  /* unknown */ "G4 Gebäudehülle ",
  "B68":  /* unknown */ "TXT_build_G4_botceil",
  "D68":  /* unknown */ "### Der Anteil der des Fußbodens an der Heizlast der erfassten Räume ist relativ gering, die Sanierung anderer Bauteile geht vor.\n\n",
  "A69":  /* unknown */ "G4 Gebäudehülle ",
  "B69":  /* unknown */ "TXT_build_G4_ceil",
  "D69":  /* unknown */ "### Oberste Geschossdecke und Fußboden: geringer Anteil an den Wärmeverlusten\n\nÜber die obere Geschossdecke und den Fußboden geht in den erfassten Räumen wenig Wärme verloren. Hier geht die Sanierung anderer Bauteile vor. ",
} as const;
