// Sheet: TXT_rooms
export const data = {
  "A1":  /* unknown */ "Gruppe",
  "B1":  /* unknown */ "Variable ",
  "D1":  /* unknown */ "Kommentar",
  "E1":  /* unknown */ "INPUT_TXT_rooms",
  "A2":  /* unknown */ "R1",
  "B2":  /* unknown */ "TXT_room_R1_not",
  "E2":  /* unknown */ "## <i class=\"bi bi-circle-fill rating-red\"></i>Aktuell nicht niedertemperaturfähig:\n\n### Viel höhere Vorlauftemperatur als 55 °C führt zu geringer Effizienz.\n\nIn diesem Zustand kann der Raum nur sehr ineffizient mit einer Wärmepumpe beheizt werden – der Stromverbrauch wäre sehr hoch, dies bedeutet hohe Stromkosten für Sie. Mit einer niedrigen Vorlauftemperatur können Sie Strom und Stromkosten sparen.\n\nDenn je niedriger die benötigte Vorlauftemperatur, desto effizienter arbeitet die Wärmepumpe. Am einfachsten geht das mit einem leistungsfähigeren Heizkörper <i class=\"bi bi-1-circle-fill bs-primary\"></i>. Darüber hinaus kann auch besserer Wärmeschutz helfen <i class=\"bi bi-2-circle-fill bs-primary\"></i>. ",
  "A3":  /* unknown */ "R1",
  "B3":  /* unknown */ "TXT_room_R1_notyet",
  "E3":  /* unknown */ "## <i class=\"bi bi-circle-fill rating-orange\"></i> Noch nicht niedertemperaturfähig:\n\n### Es fehlt noch ein Stück, die Vorlauftemperatur ist höher als 55 °C.\n\nDie Wärmepumpe müsste das Heizungswasser stark erwärmen – dadurch würden Sie viel Strom verbrauchen und Ihre Stromkosten wären erhöht. Sie können Strom sparen, indem Sie die Vorlauftemperatur senken. \n\nDenn je niedriger die benötigte Vorlauftemperatur, desto effizienter arbeitet die Wärmepumpe. Am einfachsten geht das mit einem leistungsfähigeren Heizkörper <i class=\"bi bi-1-circle-fill bs-primary\"></i>. Darüber hinaus kann auch besserer Wärmeschutz helfen <i class=\"bi bi-2-circle-fill bs-primary\"></i>.",
  "A4":  /* unknown */ "R1",
  "B4":  /* unknown */ "TXT_room_R1_almost",
  "E4":  /* unknown */ "## <i class=\"bi bi-circle-fill rating-yellow\"></i> Fast niedertemperaturfähig:\n\n### Etwas höhere Vorlauftemperatur als 55 °C, fast geschafft!\n\nDieser Raum ist beinahe bereit für den effizienten Betrieb mit einer Wärmepumpe – die Vorlauftemperatur ist nur leicht erhöht. Je nachdem, wie warm Sie es haben möchten oder den Raum nutzen, können Sie diesen Raum möglicherweise schon jetzt effizient mit einer Wärmepumpe beheizen. Eine leicht reduzierte Raumtemperatur - schon ein Grad weniger - kann den Unterschied machen. Nach dem ersten Winter wissen Sie, ob der vorhandene Heizkörper Ihren Bedürfnissen genügt. Entscheiden Sie danach über den empfohlenen Heizkörpertausch. \n\nJe niedriger die benötigte Vorlauftemperatur, desto effizienter arbeitet die Wärmepumpe. Am einfachsten geht das mit einem leistungsfähigeren Heizkörper <i class=\"bi bi-1-circle-fill bs-primary\"></i>. Darüber hinaus kann auch besserer Wärmeschutz helfen <i class=\"bi bi-2-circle-fill bs-primary\"></i>. ",
  "A5":  /* unknown */ "R1",
  "B5":  /* unknown */ "TXT_room_R1_NTr",
  "E5":  /* unknown */ "## <i class=\"bi bi-circle-fill rating-green\"></i> Niedertemperaturfähig:\n\n### Gute Voraussetzungen, eine Wärmepumpe ist möglich!\n\nDiesen Raum können Sie effizient mit einer Wärmepumpe beheizen – die gewünschte Raumtemperatur wird bereits mit ausreichend geringer Vorlauftemperatur erreicht.\n\nJe niedriger die benötigte Vorlauftemperatur, desto effizienter arbeitet die Wärmepumpe. Dafür ist die Leistungsfähigkeit der Heizkörper <i class=\"bi bi-1-circle-fill bs-primary\"></i> und der Wärmeschutz <i class=\"bi bi-2-circle-fill bs-primary\"></i> entscheidend. ",
  "A6":  /* unknown */ "R2",
  "B6":  /* unknown */ "TXT_room_R2_verysuit",
  "E6":  /* unknown */ "## <i class=\"bi bi-circle-fill rating-green\"></i> Alles im grünen Bereich.\n\n### Stark gemacht!\n\nDie <abbr title=\"Die Summe der Wärmeverluste eines Raumes über alle Bauteile bei angenommener Raum- und Außentemperatur.\">Heizlast</abbr> in diesem Raum ist bereits sehr niedrig – eine Wärmepumpe kann den Raum effizient beheizen und der Energieverbrauch ist gering. Zusätzliche Maßnahmen wie Dämmung oder neue Fenster bringen nur noch geringe Verbesserungen.",
  "A7":  /* unknown */ "R2",
  "B7":  /* unknown */ "TXT_room_R2_suit_1",
  "E7":  /* unknown */ "## <i class=\"bi bi-circle-fill rating-yellow\"></i> Moderate Wärmeverluste\n\n### Gute Basis – noch optimierbar.\n\nDie <abbr title=\"Die Summe der Wärmeverluste eines Raumes über alle Bauteile bei angenommener Raum- und Außentemperatur.\">Heizlast</abbr> liegt im Mittelfeld. Eine Dämmung der",
  "A8":  /* unknown */ "R2",
  "B8":  /* unknown */ "TXT_room_R2_suit_2",
  "E8":  /* unknown */ "bietet hier das größte Potenzial, um den Energie zu sparen und den Wärmepumpenbetrieb noch effizienter zu gestalten.",
  "A9":  /* unknown */ "R2",
  "B9":  /* unknown */ "TXT_room_R2_almostsuit_1",
  "E9":  /* unknown */ "## <i class=\"bi bi-circle-fill rating-orange\"></i> Verbesserungsbedarf\n\n### Da geht noch was.\n\nDie <abbr title=\"Die Summe der Wärmeverluste eines Raumes über alle Bauteile bei angenommener Raum- und Außentemperatur.\">Heizlast</abbr> ist überdurchschnittlich.  \nVor allem über die",
  "A10":  /* unknown */ "R2",
  "B10":  /* unknown */ "TXT_room_R2_almostsuit_2",
  "E10":  /* unknown */ "geht viel Wärme verloren – eine Verbesserung des Wärmeschutzes senkt den Energieverbrauch Ihrer Heizung und steigert die Effizienz einer Wärmepumpe. Dadurch reduzieren Sie die Stromkosten für die Wärmepumpe.",
  "A11":  /* unknown */ "R2",
  "B11":  /* unknown */ "TXT_room_R2_notsuit_1",
  "E11":  /* unknown */ "## <i class=\"bi bi-circle-fill rating-red\"></i> Sehr hohe Wärmeverluste\n\n### Jetzt ist Optimierung gefragt.\n\nDie Heizlast ist sehr hoch. Wenn die Heizflächen groß genug sind, können Sie den Raum trotzdem effizient mit einer Wärmepumpe beheizen. \nDarüber hinaus empfiehlt sich eine energetische Verbesserung der Gebäudehülle – insbesondere durch Dämmung der Außenwand und",
  "A12":  /* unknown */ "R2",
  "B12":  /* unknown */ "TXT_room_R2_notsuit_2",
  "E12":  /* unknown */ ", dies reduziert den Strombedarf und senkt die sonst höheren Stromkosten. Zusätzlich verbessert es die allgemeine Effizienz und senkt den Energieverbrauch Ihrer Heizung.",
  "A13":  /* unknown */ "R3",
  "B13":  /* unknown */ "TXT_room_R3_notsuff_1",
  "E13":  /* unknown */ "## <i class=\"bi bi-circle-fill rating-red\"></i> Sehr niedrige Heizkörperleistung  \n\n### Hier reicht der Heizkörper nicht aus.    \n\nDamit eine Wärmepumpe den Raum effizient beheizen kann, wäre ein",
  "A14":  /* unknown */ "R3",
  "B14":  /* unknown */ "TXT_room_R3_notsuff_2",
  "E14":  /* unknown */ "Heizkörper oder ein zusätzlicher Heizkörper notwendig. Heizkörper der effektivsten Bauart (Typ 33) oder ein zusätzlicher Heizkörper notwendig.\nEine bessere Dämmung der Bauteile kann helfen, den Wärmebedarf zu senken. Dann muss die Heizkörperfläche nicht so viel größer werden.  \n\n<i class=\"bi bi-lightbulb-fill\"></i> Hinweis: Ein <abbr title=\"Die durch die Gebläse verstärkte Luftbewegung erhöht die Leistung des Heizkörpers, siehe Wärmepumpen-Heizkörper\"> Heizkörper mit integriertem Gebläse </abbr> könnte dabei helfen, dass der neue Heizkörper nicht so groß werden muss.  \nDiese Heizkörper-Modelle brauchen einen zusätzlichen Stromanschluss für die Gebläse. ",
  "A15":  /* unknown */ "R3",
  "B15":  /* unknown */ "TXT_room_R3_suffchangeobl_1",
  "E15":  /* unknown */ "## <i class=\"bi bi-circle-fill rating-orange\"></i> Deutlich zu geringe Leistung\n\n### Ein Tausch bringt viel.\n\nEin neuer Heizkörper mit",
  "A16":  /* unknown */ "R3",
  "B16":  /* unknown */ "TXT_room_R3_suffchangeobl_2",
  "E16":  /* unknown */ "Leistung kann die Wärmepumpe in diesem Raum deutlich effizienter machen. Dafür müsste der Heizkörper größer sein, um genug Wärme in den Raum zu bringen. \n\n<i class=\"bi bi-lightbulb-fill\"></i> Hinweis: Ein gleich großer gleicher <abbr title=\"Die durch die Gebläse verstärkte Luftbewegung erhöht die Leistung des Heizkörpers, siehe Wärmepumpen-Heizkörper\"> Heizkörper mit integriertem Gebläse </abbr> der leistungsstärksten Ausführung (Typ 33) kann vermutlich ausreichen, um die Heizlast zu decken. Für diese Heizkörper-Modelle ist ein zusätzlicher Stromanschluss für die Gebläse erforderlich.",
  "A17":  /* unknown */ "R3",
  "B17":  /* unknown */ "TXT_room_R3_suffchange_1",
  "E17":  /* unknown */ "## <i class=\"bi bi-circle-fill rating-yellow\"></i> Etwas zu geringe Leistung\n\n### Mit dem richtigen Typ klappt’s.\n\nEin Heizkörpertausch kann hier viel bewirken – ein Modell mit",
  "A18":  /* unknown */ "R3",
  "B18":  /* unknown */ "TXT_room_R3_suffchange_2",
  "E18":  /* unknown */ "mehr Leistung reicht aus.  \nVoraussichtlich genügt es, bei gleicher Größe auf einen leistungsstärkeren Typ umzusteigen.",
  "A19":  /* unknown */ "R3",
  "B19":  /* unknown */ "TXT_room_R3_suff",
  "E19":  /* unknown */ "## <i class=\"bi bi-circle-fill rating-green\"></i> Ausreichende Heizkörperleistung\n\n### Gut ausgestattet!\n\nDer Heizkörper hat genügend Fläche. Die Wärmepumpe kann den Raum mit geringer Vorlauftemperatur angenehm und effizient beheizen.",
  "A20":  /* unknown */ "room",
  "B20":  /* unknown */ "TXT_room_RW",
  "E20":  /* unknown */ "## <i class=\"bi bi-exclamation-triangle-fill-yellow\"></i> Achtung! Hohe Raumtemperatur gewählt\n\n### Die angegebene Raumtemperatur ist vergleichsweise hoch.\nTypischerweise rechnen wir mit 20 °C in Wohnräumen und 24 °C in Bädern.\n  \nHandelt es sich um ein Badezimmer? Überprüfen Sie den Raum noch einmal bei einer Raumtemperatur von 20 °C. Sollte die Heizfläche dann ausreichen, genügt es zumeist, dass an sehr kalten Tagen ein Infrarotstrahler oder ein Elektroheizkörper zusätzliche Wärme spendet.",
  "A21":  /* unknown */ "R2",
  "B21":  /* unknown */ "TXT_room_intro",
  "E21":  /* unknown */ "##Geschätzte/ermittelte Raumheizlast##\n \nDie Skala zeigt den Wärmebedarf Ihres Raums. Hohe Werte bedeuten, dass der Wärmeschutz veraltet ist und deswegen Ihre Heizung mehr Energie verbraucht. \nEine Wärmepumpe kann auch bei hoher Heizlast effizient arbeiten, wenn die Heizkörper genug Wärme abgeben können (siehe oben). Eine bessere Dämmung macht es möglich, mit kleineren Heizkörpern oder niedrigerer Vorlauftemperatur auszukommen. \nDie Effizienz steigt und der Energieverbrauch sinkt. Und eine kleinere, günstigere Wärmepumpe reicht aus. So sparen Sie bei den Stromkosten und der Wärmepumpe.",
} as const;
