import {Sheet} from "./data-grid";


export const Fragen_Prototyp_Einzelfahrzeug_data: Sheet = {
  F_R1: '',
  F_S1: '',
  F_SZ1: '',
  F_L1: '',
  F_L2: '',
  F_F1: '',

  A_R1: 150,

  "A_JN1": "Ja",
  "A_JN2": "Nein",

  A_S1: 'Selten',
  A_S2: 'Häufig',
  A_S3: 'Meistens',

  "A_SV1": "Fast nie",
  "A_SV2": "Ab und zu",
  "A_SV3": "Regelmäßig",

  "A_SP1": "Selten",
  "A_SP2": "Häufig",
  "A_SP3": "Meistens",

  "A_T1": "Nie",
  "A_T2": "Gelegentlich",
  "A_T3": "Regelmäßig",
};

export const Empfehlungslisten_data: Sheet
  = {
  "E_A1": "Wenn weder am Arbeitsplatz (bzw. im umliegenden öffentlichen Raum) noch am Wohnort der Nutzenden eine für mehrere Stunden nutzbare Lademöglichkeit besteht, ist die Beschaffung eines E-Autos nicht sinnvoll. In diesem Fall sollte ein möglichst sparsamer Verbrenner beschafft werden.\n\nDie Beschaffung von Ladeinfrastruktur ist jedoch unbedingt zu empfehlen, um in Zukunft E-Autos beschaffen zu können.",
  "E_A2": "Ein E-Auto (BEV - rein batteriebetrieben) ist bevorzugt zu beschaffen, da Reichweiten bis 150 km immer erzielbar sind, sodass das Laden über Nacht ausreicht.\n\nFür einzelne Tagesstrecken über 150 km sollte idealerweise die Bahn oder der Fernbus genutzt werden. Bei schlechter Anbindung an den öffentlichen Verkehr oder mit viel Gepäck/Transportgut kann das E-Auto auch auf längeren Tagesstrecken zum Einsatz kommen, sofern unterwegs oder am Zielort (Schnell-)Lademöglichkeiten genutzt werden können. Besteht die Möglichkeit zum Laden nicht, kann in diesen Ausnahmefällen (falls vefügbar) ein anderes Fahrzeug mit entsprechender Reichweite aus dem Fuhrpark oder sonst ein Mietwagen genutzt werden.",
  "E_A3": "Ein E-Auto (BEV - rein batteriebetrieben) ist bevorzugt zu beschaffen, da Reichweiten bis 150 km immer erzielbar sind, sodass das Laden über Nacht ausreicht.\n\nFür einzelne Tagesstrecken über 150 km sollte idealerweise die Bahn oder der Fernbus genutzt werden. Bei schlechter Anbindung an den öffentlichen Verkehr oder mit viel Gepäck/Transportgut kann das E-Auto auch auf längeren Tagesstrecken zum Einsatz kommen, sofern unterwegs oder am Zielort (Schnell-)Lademöglichkeiten genutzt werden können. Besteht die Möglichkeit zum Laden nicht, kann in diesen Ausnahmefällen ein Mietwagen genutzt werden.",
  "E_A4": "Ein E-Auto (BEV - rein batteriebetrieben) ist bevorzugt zu beschaffen, da Reichweiten bis 150 km immer erzielbar sind, sodass das Laden über Nacht ausreicht.\n\nWenn häufiger auch mal Tagesstrecken über 150 km zurückgelegt werden sollen und unterwegs oder am Zielort (Schnell-) Lademöglichkeiten genutzt werden können, kann das E-Auto auch auf diesen Strecken zum Einsatz kommen. Besteht die Möglichkeit zum Laden nicht, sollte geprüft werden, ob für die Einsatztage mit längeren Strecken regelmäßig ein anderes Fahrzeug mit entsprechender Reichweite aus dem Fuhrpark genutzt werden kann. Dieses Fahrzeug kann auch ein E-Auto mit größerer Batterie sein, da in höheren Preissegmenten reale 300 km Reichweite gängig sind. Zudem ist zu prüfen, ob die Tagesstrecken über 150 km tatsächlich zum Großteil mit dem Pkw zurückgelegt werden müssen (aufgrund schlechter Anbindung an den öffentlichen Verkehr oder viel Gepäck/Transportgut) oder ob mit Bahn oder Fernbus gereist werden kann.",
  "E_A5": "Ein E-Auto (BEV - rein batteriebetrieben) ist bevorzugt zu beschaffen, da Reichweiten bis 150 km immer erzielbar sind, sodass das Laden über Nacht ausreicht.\n\nWenn häufiger auch mal Tagesstrecken über 150 km zurückgelegt werden sollen und unterwegs oder am Zielort (Schnell-) Lademöglichkeiten genutzt werden können, kann das E-Auto auch auf diesen Strecken zum Einsatz kommen. Zudem ist zu prüfen, ob die Tagesstrecken über 150 km tatsächlich zum Großteil mit dem Pkw zurückgelegt werden müssen (aufgrund schlechter Anbindung an den öffentlichen Verkehr oder viel Gepäck/Transportgut) oder ob mit Bahn oder Fernbus gereist werden kann.\n\nIst dies nicht der Fall und besteht keine Möglichkeit zum Laden während längerer Strecken, kann die Beschaffung eines Plug-in-Hybrids (PHEV) sinnvoll sein. In diesem Fall sollte jedoch darauf geachtet werden, dass bei den kürzeren Strecken, die im Regelfall gefahren werden, ein elektrischer Fahranteil von über 70 % erzielt wird. Dazu muss ein regelmäßiges Laden gewährleistet sein. Zudem sind PHEVs eher in größeren Fahrzeugsegmenten verfügbar. Je nach Anwendungsfall kann ein kleiner, sparsamer Verbrenner auch aus Umweltsicht vorteilhaft ggü. einem PHEV sein.",
  "E_A6": "Inkonsistente Eingabe: Die Aussage zur Häufigkeit längerer Strecken passt nicht mit der angegeben Streckenlänge eines repräsentativen Tages zusammen. Bitte passen Sie die Streckenlänge so an, dass sie den Fahrten im Regelfall entspricht.",
  "E_A7": "Erlaubt die Terminplanung Fahrtunterbrechungen von mind. 20-40 min, ist ein E-Auto (BEV - rein batteriebetrieben) trotz häufiger längerer Strecken bevorzugt zu beschaffen.",
  "E_A8": "Ein E-Auto (BEV - rein batteriebetrieben) mit großer Reichweite ist ggf. geeignet. In höheren Preissegmenten sind reale 300 km Reichweite gängig. Es sollte jedoch beachtet werden, dass dem Umweltvorteil eines BEV in der Nutzung die Herstellungsemissionen einer großen Batterie gegenüberstehen. Zudem sind große Batterien vor allem in größeren Fahrzeugen verbaut. Ein kleinerer, möglichst sparsamer Verbrenner kann in diesem Anwendungsfall aus Umweltsicht (und aus Kostensicht ohnehin) also durchaus vorteilhaft sein.",
  "E_A9": "Erlaubt die Terminplanung auf langen Strecken keine bzw. nur sehr kurze Fahrtunterbrechungen unter 30 min, ist die Beschaffung eines E-Autos nicht sinnvoll. In diesem Fall sollte ein möglichst sparsamer Verbrenner beschafft werden.",
  "E_A10": "Bei vielen langen Strecken, auf denen keine Lademöglichkeit besteht, ist die Beschaffung eines E-Autos nicht sinnvoll. In diesem Fall sollte ein möglichst sparsamer Verbrenner beschafft werden.",
  "E_A11": "Bei vielen langen Strecken, auf denen keine Lademöglichkeit besteht, ist die Beschaffung eines E-Autos nicht sinnvoll. In diesem Fall sollte ein möglichst sparsamer Verbrenner beschafft werden.\n\nDas Fahrprofil mit regelmäßigen längeren Fahrtunterbrechungen eignet sich an sich allerdings für E-Autos. Der weitere Ausbau der öffentlichen Ladeinfrastruktur oder die Wahl von Alternativrouten mit verfügbaren Ladesäulen kann also (in Zukunft) eine E-Auto-Beschaffung durchaus ermöglichen.",

  "E_F1": "Bei regelmäßigen aufwändigen Transportanforderungen ist ein Van oder ein Fahrzeug der Rubrik Utilities (Hochdachkombis, Kleinbusse und Pick-ups, die als Pkw zugelassen sind) notwendig.",
  "E_F2": "Für die Leitungsebene besteht ggf. Anspruch auf ein Fahrzeug aus einem größeren Fahrzeugsegment bis zur Oberen Mittelklasse. Trotzdem sollte abgewogen werden, ob ein kleineres Fahrzeug geeignet ist und die Leitungsebene freiwillig auf diesen Anspruch verzichtet.",
  "E_F3": "Idealerweise wird bei einer Nutzung des Fahrzeugs durch max. zwei Personen ein Kleinstwagen beschafft. Sollte mehr Komfort und/oder Stauraum nötig sein, ist ein Kleinwagen zu empfehlen.",
  "E_F4": "Idealerweise wird bei einer Nutzung des Fahrzeugs durch max. zwei Personen ein Kleinstwagen beschafft. Sollte (gerade bei vielen längeren Strecken) mehr Komfort und/oder Stauraum nötig sein, ist ein Kleinwagen zu empfehlen.",
  "E_F5": "Werden nur selten mehr als zwei Sitzplätze benötigt, sollte bevorzugt ein Kleinwagen beschafft werden. Sollte mehr Komfort und/oder Stauraum nötig sein, ist ein Fahrzeug der Kompaktklasse zu empfehlen.",
  "E_F6": "Werden nur selten mehr als zwei Sitzplätze benötigt, sollte bevorzugt ein Kleinwagen beschafft werden. Sollte (gerade bei vielen längeren Strecken) mehr Komfort und/oder Stauraum nötig sein, ist ein Fahrzeug der Kompaktklasse zu empfehlen.",
  "E_F7": "Werden häufig mehr als zwei Sitzplätze benötigt, sollte bevorzugt ein Fahrzeug der Kompaktklasse beschafft werden. Sollte mehr Komfort und/oder Stauraum nötig sein, ist ein Fahrzeug der Mittelklasse zu empfehlen.",
  "E_F8": "Auch wenn meistens bis zu vier Personen in dem Auto fahren, sollte bevorzugt ein Fahrzeug der Kompaktklasse beschafft werden. Bereits in diesem Fahrzeugsegment gibt es viele Modelle mit ausreichend Platz für große Erwachsene auf der Rückbank. Sollte mehr Komfort und/oder Stauraum nötig sein, ist ein Fahrzeug der Mittelklasse zu empfehlen.",
  "E_F9": "Wenn selten alle fünf Sitzplätze benötigt werden, sollte bevorzugt ein Fahrzeug der Kompaktklasse beschafft werden. Bereits in diesem Fahrzeugsegment gibt es viele Modelle mit ausreichend Platz für große Erwachsene auf der Rückbank. Sollte mehr Komfort und/oder Stauraum nötig sein, ist ein Fahrzeug der Mittelklasse zu empfehlen.",
  "E_F10": "Werden oft alle fünf Sitzplätze benötigt, ist ein Fahrzeug der Mittelklasse zu empfehlen.",
  "E_F11": "Wenn nur selten über fünf Sitzplätze benötigt werden, kann für diese Ausnahmefälle ein Hochdachkombi (falls verfügbar) aus dem Fuhrpark verwendet oder sonst gemietet werden.\n\nIm betrachteten Beschaffungsfall sollte bei bis zu vier Personen bevorzugt ein Fahrzeug der Kompaktklasse beschafft werden. Bereits in diesem Fahrzeugsegment gibt es viele Modelle mit ausreichend Platz für große Erwachsene auf der Rückbank. Werden oft fünf Sitzplätze oder mehr Komfort/Stauraum benötigt, ist ein Fahrzeug der Mittelklasse zu empfehlen.",
  "E_F12": "Wenn nur selten über fünf Sitzplätze benötigt werden, kann für diese Ausnahmefälle ein Hochdachkombi gemietet werden.\n\nIm betrachteten Beschaffungsfall sollte bei bis zu vier Personen bevorzugt ein Fahrzeug der Kompaktklasse beschafft werden. Bereits in diesem Fahrzeugsegment gibt es viele Modelle mit ausreichend Platz für große Erwachsene auf der Rückbank. Werden oft fünf Sitzplätze oder mehr Komfort/Stauraum benötigt, ist ein Fahrzeug der Mittelklasse zu empfehlen.",
  "E_F13": "Wenn nur selten über fünf Sitzplätze benötigt werden, kann für diese Ausnahmefälle ein Hochdachkombi (falls verfügbar) aus dem Fuhrpark verwendet oder sonst gemietet werden. Bei regelmäßigen aufwändigen Transportanforderungen ist allerdings ohnehin ein Van oder ein Fahrzeug der Rubrik Utilities (Hochdachkombis, Kleinbusse und Pick-ups, die als Pkw zugelassen sind) notwendig. Bei der Wahl der Fahrzeugart ist also abzuwägen, ob der Personentransport (-> Hochdachkombi, Kleinbus) oder der Transport von Gegenständen (-> Van, Hochdachkombi, Pick-up) überwiegt.",
  "E_F14": "Wenn nur selten über fünf Sitzplätze benötigt werden, kann für diese Ausnahmefälle ein Hochdachkombi gemietet werden. Bei regelmäßigen aufwändigen Transportanforderungen ist allerdings ohnehin ein Van oder ein Fahrzeug der Rubrik Utilities (Hochdachkombis, Kleinbusse und Pick-ups, die als Pkw zugelassen sind) notwendig. Bei der Wahl der Fahrzeugart ist also abzuwägen, ob der Personentransport (-> Hochdachkombi, Kleinbus) oder der Transport von Gegenständen (-> Van, Hochdachkombi, Pick-up) überwiegt.",
  "E_F15": "Werden oft mind. sechs Sitzplätze benötigt, sollte ein Hochdachkombi beschafft werden. Diese Fahrzeugart hat unter den 7-Sitzern in der Regel das beste Preis-Leistungs-Verhältnis und fährt sparsamer als z.B. ein SUV.",
  "E_F16": "Wenn nur selten über sieben Sitzplätze benötigt werden, kann für diese Ausnahmefälle ein Kleinbus (falls verfügbar) aus dem Fuhrpark verwendet oder sonst gemietet werden.\n\nIm betrachteten Beschaffungsfall sollte bei bis zu vier Personen bevorzugt ein Fahrzeug der Kompaktklasse beschafft werden. Bereits in diesem Fahrzeugsegment gibt es viele Modelle mit ausreichend Platz für große Erwachsene auf der Rückbank. Werden oft fünf Sitzplätze oder mehr Komfort/Stauraum benötigt, ist ein Fahrzeug der Mittelklasse zu empfehlen.",
  "E_F17": "Wenn nur selten über sieben Sitzplätze benötigt werden, kann für diese Ausnahmefälle ein Kleinbus gemietet werden.\n\nIm betrachteten Beschaffungsfall sollte bei bis zu vier Personen bevorzugt ein Fahrzeug der Kompaktklasse beschafft werden. Bereits in diesem Fahrzeugsegment gibt es viele Modelle mit ausreichend Platz für große Erwachsene auf der Rückbank. Werden oft fünf Sitzplätze oder mehr Komfort/Stauraum benötigt, ist ein Fahrzeug der Mittelklasse zu empfehlen.",
  "E_F18": "Wenn nur selten über sieben Sitzplätze benötigt werden, kann für diese Ausnahmefälle ein Kleinbus (falls verfügbar) aus dem Fuhrpark verwendet oder sonst gemietet werden. Bei regelmäßigen aufwändigen Transportanforderungen ist allerdings ohnehin ein Van oder ein Fahrzeug der Rubrik Utilities (Hochdachkombis, Kleinbusse und Pick-ups, die als Pkw zugelassen sind) notwendig. Bei der Wahl der Fahrzeugart ist also abzuwägen, ob der Personentransport (-> Hochdachkombi, Kleinbus) oder der Transport von Gegenständen (-> Van, Hochdachkombi, Pick-up) überwiegt.",
  "E_F19": "Wenn nur selten über sieben Sitzplätze benötigt werden, kann für diese Ausnahmefälle ein Kleinbus gemietet werden. Bei regelmäßigen aufwändigen Transportanforderungen ist allerdings ohnehin ein Van oder ein Fahrzeug der Rubrik Utilities (Hochdachkombis, Kleinbusse und Pick-ups, die als Pkw zugelassen sind) notwendig. Bei der Wahl der Fahrzeugart ist also abzuwägen, ob der Personentransport (-> Hochdachkombi, Kleinbus) oder der Transport von Gegenständen (-> Van, Hochdachkombi, Pick-up) überwiegt.",
  "E_F20": "Werden oft mind. acht Sitzplätze benötigt, sollte ein Kleinbus beschafft werden.",
  "E_F21": "Für die Leitungsebene besteht ggf. Anspruch auf ein Fahrzeug aus einem größeren Fahrzeugsegment bis zur Oberen Mittelklasse. Trotzdem sollte abgewogen werden, ob ein kleineres Fahrzeug geeignet ist und die Leitungsebene freiwillig auf diesen Anspruch verzichtet.\n\nWenn nur gelegentlich aufwändige Transportanforderungen bestehen, die einen Van/ein Fahrzeug aus der Rubrik Utilities nötig machen, kann für diese Ausnahmefälle ein entsprechendes Fahrzeug (falls verfügbar) aus dem Fuhrpark verwendet oder sonst gemietet werden.",
  "E_F22": "Für die Leitungsebene besteht ggf. Anspruch auf ein Fahrzeug aus einem größeren Fahrzeugsegment bis zur Oberen Mittelklasse. Trotzdem sollte abgewogen werden, ob ein kleineres Fahrzeug geeignet ist und die Leitungsebene freiwillig auf diesen Anspruch verzichtet.\n\nWenn nur gelegentlich aufwändige Transportanforderungen bestehen, die einen Van/ein Fahrzeug aus der Rubrik Utilities nötig machen, kann für diese Ausnahmefälle ein entsprechendes Fahrzeug gemietet werden.",
  "E_F23": "Idealerweise wird bei einer Nutzung des Fahrzeugs durch max. zwei Personen ein Kleinstwagen beschafft. Sollte mehr Komfort und/oder Stauraum nötig sein, ist ein Kleinwagen zu empfehlen.\n\nWenn nur gelegentlich aufwändige Transportanforderungen bestehen, die einen Van/ein Fahrzeug aus der Rubrik Utilities nötig machen, kann für diese Ausnahmefälle ein entsprechendes Fahrzeug (falls verfügbar) aus dem Fuhrpark verwendet oder sonst gemietet werden.",
  "E_F24": "Idealerweise wird bei einer Nutzung des Fahrzeugs durch max. zwei Personen ein Kleinstwagen beschafft. Sollte mehr Komfort und/oder Stauraum nötig sein, ist ein Kleinwagen zu empfehlen.\n\nWenn nur gelegentlich aufwändige Transportanforderungen bestehen, die einen Van/ein Fahrzeug aus der Rubrik Utilities nötig machen, kann für diese Ausnahmefälle ein entsprechendes Fahrzeug gemietet werden.",
  "E_F25": "Idealerweise wird bei einer Nutzung des Fahrzeugs durch max. zwei Personen ein Kleinstwagen beschafft. Sollte (gerade bei vielen längeren Strecken) mehr Komfort und/oder Stauraum nötig sein, ist ein Kleinwagen zu empfehlen.\n\nWenn nur gelegentlich aufwändige Transportanforderungen bestehen, die einen Van/ein Fahrzeug aus der Rubrik Utilities nötig machen, kann für diese Ausnahmefälle ein entsprechendes Fahrzeug (falls verfügbar) aus dem Fuhrpark verwendet oder sonst gemietet werden.",
  "E_F26": "Idealerweise wird bei einer Nutzung des Fahrzeugs durch max. zwei Personen ein Kleinstwagen beschafft. Sollte (gerade bei vielen längeren Strecken) mehr Komfort und/oder Stauraum nötig sein, ist ein Kleinwagen zu empfehlen.\n\nWenn nur gelegentlich aufwändige Transportanforderungen bestehen, die einen Van/ein Fahrzeug aus der Rubrik Utilities nötig machen, kann für diese Ausnahmefälle ein entsprechendes Fahrzeug gemietet werden.",
  "E_F27": "Werden nur selten mehr als zwei Sitzplätze benötigt, sollte bevorzugt ein Kleinwagen beschafft werden. Sollte mehr Komfort und/oder Stauraum nötig sein, ist ein Fahrzeug der Kompaktklasse zu empfehlen.\n\nWenn nur gelegentlich aufwändige Transportanforderungen bestehen, die einen Van/ein Fahrzeug aus der Rubrik Utilities nötig machen, kann für diese Ausnahmefälle ein entsprechendes Fahrzeug (falls verfügbar) aus dem Fuhrpark verwendet oder sonst gemietet werden.",
  "E_F28": "Werden nur selten mehr als zwei Sitzplätze benötigt, sollte bevorzugt ein Kleinwagen beschafft werden. Sollte mehr Komfort und/oder Stauraum nötig sein, ist ein Fahrzeug der Kompaktklasse zu empfehlen.\n\nWenn nur gelegentlich aufwändige Transportanforderungen bestehen, die einen Van/ein Fahrzeug aus der Rubrik Utilities nötig machen, kann für diese Ausnahmefälle ein entsprechendes Fahrzeug gemietet werden.",
  "E_F29": "Werden nur selten mehr als zwei Sitzplätze benötigt, sollte bevorzugt ein Kleinwagen beschafft werden. Sollte (gerade bei vielen längeren Strecken) mehr Komfort und/oder Stauraum nötig sein, ist ein Fahrzeug der Kompaktklasse zu empfehlen.\n\nWenn nur gelegentlich aufwändige Transportanforderungen bestehen, die einen Van/ein Fahrzeug aus der Rubrik Utilities nötig machen, kann für diese Ausnahmefälle ein entsprechendes Fahrzeug (falls verfügbar) aus dem Fuhrpark verwendet oder sonst gemietet werden.",
  "E_F30": "Werden nur selten mehr als zwei Sitzplätze benötigt, sollte bevorzugt ein Kleinwagen beschafft werden. Sollte (gerade bei vielen längeren Strecken) mehr Komfort und/oder Stauraum nötig sein, ist ein Fahrzeug der Kompaktklasse zu empfehlen.\n\nWenn nur gelegentlich aufwändige Transportanforderungen bestehen, die einen Van/ein Fahrzeug aus der Rubrik Utilities nötig machen, kann für diese Ausnahmefälle ein entsprechendes Fahrzeug gemietet werden.",
  "E_F31": "Werden häufig mehr als zwei Sitzplätze benötigt, sollte bevorzugt ein Fahrzeug der Kompaktklasse beschafft werden. Sollte mehr Komfort und/oder Stauraum nötig sein, ist ein Fahrzeug der Mittelklasse zu empfehlen.\n\nWenn nur gelegentlich aufwändige Transportanforderungen bestehen, die einen Van/ein Fahrzeug aus der Rubrik Utilities nötig machen, kann für diese Ausnahmefälle ein entsprechendes Fahrzeug (falls verfügbar) aus dem Fuhrpark verwendet oder sonst gemietet werden.",
  "E_F32": "Werden häufig mehr als zwei Sitzplätze benötigt, sollte bevorzugt ein Fahrzeug der Kompaktklasse beschafft werden. Sollte mehr Komfort und/oder Stauraum nötig sein, ist ein Fahrzeug der Mittelklasse zu empfehlen.\n\nWenn nur gelegentlich aufwändige Transportanforderungen bestehen, die einen Van/ein Fahrzeug aus der Rubrik Utilities nötig machen, kann für diese Ausnahmefälle ein entsprechendes Fahrzeug gemietet werden.",
  "E_F33": "Auch wenn meistens bis zu vier Personen in dem Auto fahren, sollte bevorzugt ein Fahrzeug der Kompaktklasse beschafft werden. Bereits in diesem Fahrzeugsegment gibt es viele Modelle mit ausreichend Platz für große Erwachsene auf der Rückbank. Sollte mehr Komfort und/oder Stauraum nötig sein, ist ein Fahrzeug der Mittelklasse zu empfehlen.\n\nWenn nur gelegentlich aufwändige Transportanforderungen bestehen, die einen Van/ein Fahrzeug aus der Rubrik Utilities nötig machen, kann für diese Ausnahmefälle ein entsprechendes Fahrzeug (falls verfügbar) aus dem Fuhrpark verwendet oder sonst gemietet werden.",
  "E_F34": "Auch wenn meistens bis zu vier Personen in dem Auto fahren, sollte bevorzugt ein Fahrzeug der Kompaktklasse beschafft werden. Bereits in diesem Fahrzeugsegment gibt es viele Modelle mit ausreichend Platz für große Erwachsene auf der Rückbank. Sollte mehr Komfort und/oder Stauraum nötig sein, ist ein Fahrzeug der Mittelklasse zu empfehlen.\n\nWenn nur gelegentlich aufwändige Transportanforderungen bestehen, die einen Van/ein Fahrzeug aus der Rubrik Utilities nötig machen, kann für diese Ausnahmefälle ein entsprechendes Fahrzeug gemietet werden.",
  "E_F35": "Wenn selten alle fünf Sitzplätze benötigt werden, sollte bevorzugt ein Fahrzeug der Kompaktklasse beschafft werden. Bereits in diesem Fahrzeugsegment gibt es viele Modelle mit ausreichend Platz für große Erwachsene auf der Rückbank. Sollte mehr Komfort und/oder Stauraum nötig sein, ist ein Fahrzeug der Mittelklasse zu empfehlen.\n\nWenn nur gelegentlich aufwändige Transportanforderungen bestehen, die einen Van/ein Fahrzeug aus der Rubrik Utilities nötig machen, kann für diese Ausnahmefälle ein entsprechendes Fahrzeug (falls verfügbar) aus dem Fuhrpark verwendet oder sonst gemietet werden.",
  "E_F36": "Wenn selten alle fünf Sitzplätze benötigt werden, sollte bevorzugt ein Fahrzeug der Kompaktklasse beschafft werden. Bereits in diesem Fahrzeugsegment gibt es viele Modelle mit ausreichend Platz für große Erwachsene auf der Rückbank. Sollte mehr Komfort und/oder Stauraum nötig sein, ist ein Fahrzeug der Mittelklasse zu empfehlen.\n\nWenn nur gelegentlich aufwändige Transportanforderungen bestehen, die einen Van/ein Fahrzeug aus der Rubrik Utilities nötig machen, kann für diese Ausnahmefälle ein entsprechendes Fahrzeug gemietet werden.",
  "E_F37": "Werden oft alle fünf Sitzplätze benötigt, ist ein Fahrzeug der Mittelklasse zu empfehlen.\n\nWenn nur gelegentlich aufwändige Transportanforderungen bestehen, die einen Van/ein Fahrzeug aus der Rubrik Utilities nötig machen, kann für diese Ausnahmefälle ein entsprechendes Fahrzeug (falls verfügbar) aus dem Fuhrpark verwendet oder sonst gemietet werden.",
  "E_F38": "Werden oft alle fünf Sitzplätze benötigt, ist ein Fahrzeug der Mittelklasse zu empfehlen.\n\nWenn nur gelegentlich aufwändige Transportanforderungen bestehen, die einen Van/ein Fahrzeug aus der Rubrik Utilities nötig machen, kann für diese Ausnahmefälle ein entsprechendes Fahrzeug gemietet werden.",
  "E_F39": "Wenn nur selten über fünf Sitzplätze benötigt werden/aufwändige Transportanforderungen bestehen, kann für diese Ausnahmefälle ein Hochdachkombi bzw. Van (falls verfügbar) aus dem Fuhrpark verwendet oder sonst gemietet werden.\n\nIm betrachteten Beschaffungsfall sollte bei bis zu vier Personen bevorzugt ein Fahrzeug der Kompaktklasse beschafft werden. Bereits in diesem Fahrzeugsegment gibt es viele Modelle mit ausreichend Platz für große Erwachsene auf der Rückbank. Werden oft fünf Sitzplätze oder mehr Komfort/Stauraum benötigt, ist ein Fahrzeug der Mittelklasse zu empfehlen.",
  "E_F40": "Wenn nur selten über fünf Sitzplätze benötigt werden/aufwändige Transportanforderungen bestehen, kann für diese Ausnahmefälle ein Hochdachkombi bzw. Van gemietet werden.\n\nIm betrachteten Beschaffungsfall sollte bei bis zu vier Personen bevorzugt ein Fahrzeug der Kompaktklasse beschafft werden. Bereits in diesem Fahrzeugsegment gibt es viele Modelle mit ausreichend Platz für große Erwachsene auf der Rückbank. Werden oft fünf Sitzplätze oder mehr Komfort/Stauraum benötigt, ist ein Fahrzeug der Mittelklasse zu empfehlen.",
  "E_F41": "Wenn nur selten über sieben Sitzplätze benötigt werden/aufwändige Transportanforderungen bestehen, kann für diese Ausnahmefälle ein Kleinbus bzw. Van (falls verfügbar) aus dem Fuhrpark verwendet oder sonst gemietet werden.\n\nIm betrachteten Beschaffungsfall sollte bei bis zu vier Personen bevorzugt ein Fahrzeug der Kompaktklasse beschafft werden. Bereits in diesem Fahrzeugsegment gibt es viele Modelle mit ausreichend Platz für große Erwachsene auf der Rückbank. Werden oft fünf Sitzplätze oder mehr Komfort/Stauraum benötigt, ist ein Fahrzeug der Mittelklasse zu empfehlen.",
  "E_F42": "Wenn nur selten über sieben Sitzplätze benötigt werden/aufwändige Transportanforderungen bestehen, kann für diese Ausnahmefälle ein Kleinbus bzw. Van gemietet werden.\n\nIm betrachteten Beschaffungsfall sollte bei bis zu vier Personen bevorzugt ein Fahrzeug der Kompaktklasse beschafft werden. Bereits in diesem Fahrzeugsegment gibt es viele Modelle mit ausreichend Platz für große Erwachsene auf der Rückbank. Werden oft fünf Sitzplätze oder mehr Komfort/Stauraum benötigt, ist ein Fahrzeug der Mittelklasse zu empfehlen.",
};


export const Hinweislisten_für_Flotte: Sheet = {
  'H_F1': 'verkleinern',
  'H_F2': 'vergrößern',
//	Hinweis Fuhrparkgröße
  'H_F3': 'Bitte überlegen Sie mithilfe der nächsten Frage, ob der Fuhrpark verkleinert statt vergrößert werden kann. Damit würden Sie einen entscheidenden Beitrag zur umweltverträglichen Beschaffung leisten.',
  'H_F4': 'Bitte überlegen Sie mithilfe der nächsten Frage, ob der Fuhrpark verkleinert werden kann. Damit würden Sie einen entscheidenden Beitrag zur umweltverträglichen Beschaffung leisten.',
  'H_F5': 'Mit der Verkleinerung des Fuhrparks leisten Sie einen entscheidenden Beitrag zur umweltverträglichen Beschaffung. Bitte überlegen Sie mithilfe der nächsten Frage, ob der Fuhrpark noch weiter verkleinert werden kann.',
//	Hinweis Verzicht auf Pkw-Beschaffung
  'H_V1': 'Mit dem Verzicht auf zu beschaffende Pkw leisten Sie einen entscheidenden Beitrag zur umweltverträglichen Beschaffung.',
  'H_V2': 'Sie haben den Fuhrpark bereits vor der Nutzung des Tools verkleinert. Damit leisten Sie einen entscheidenden Beitrag zur umweltverträglichen Beschaffung.',
  'H_V3': 'Bei der nächsten Beschaffung sollten Sie bereits in der Bedarfsermittlung prüfen, ob der Fuhrpark verkleinert werden kann.',
  'H_V4': 'Mit dem Verzicht auf zu beschaffende Pkw leisten Sie einen entscheidenden Beitrag zur umweltverträglichen Beschaffung. Insgesamt besteht jedoch nach wie vor eine Vergrößerung im Vergleich zum vorhandenen Fuhrpark. Bei der nächsten Beschaffung sollten Sie bereits in der Bedarfsermittlung prüfen, ob der Fuhrpark verkleinert werden kann.',
  'H_V5': 'Mit dem Verzicht auf zu beschaffende Pkw leisten Sie einen entscheidenden Beitrag zur umweltverträglichen Beschaffung. Insgesamt besteht jedoch nach wie vor keine Verkleinerung im Vergleich zum vorhandenen Fuhrpark. Bei der nächsten Beschaffung sollten Sie bereits in der Bedarfsermittlung prüfen, ob der Fuhrpark verkleinert werden kann.',

};
