// Sheet: clc_build
// Generated on: 2025-05-10T13:08:38.977Z

export const data: Record<string, any> = {
  "A1":  /* unknown */ "Bezeichnung",
  "B1":  /* unknown */ "Gruppe",
  "C1":  /* unknown */ "Variable ",
  "D1":  /* unknown */ "Einheit",
  "E1":  /* unknown */ "Kommentar",
  "F1":  /* unknown */ "Zellenbezug Gebäude",
  "G1":  /* unknown */ "Werte Raum",
  "H1":  /* unknown */ "Werte Raum",
  "I1":  /* unknown */ "Werte Raum",
  "J1":  /* unknown */ "Werte Raum",
  "K1":  /* unknown */ "Werte Raum",
  "L1":  /* unknown */ "Werte Raum",
  "A2":  /* unknown */ "Raumindex",
  "C2":  /* unknown */ "ID_R#",
  "G2":  /* unknown */ 1,
  "H2":  /* unknown */ 2,
  "I2":  /* unknown */ 3,
  "J2":  /* unknown */ 4,
  "K2":  /* unknown */ 5,
  "L2":  /* unknown */ 6,
  "A3":  /* unknown */ "Heizlast Transmission ",
  "A4":  /* unknown */ "Heizlast Lüftung ",
  "A5":  /* unknown */ "Heizlast_total",
  "C5":  /* unknown */ "Qdot_room",
  "D5":  /* unknown */ "W",
  "G5":  /* formula */ "ROUND(clc_load!M72/INDEX(PAR[NO_round_Qdot],1),0)*INDEX(PAR[NO_round_Qdot],1)",
  "H5":  /* formula */ "ROUND(clc_load!N72/INDEX(PAR[NO_round_Qdot_spez],1),0)*INDEX(PAR[NO_round_Qdot_spez],1)",
  "I5":  /* formula */ "ROUND(clc_load!O72/INDEX(PAR[NO_round_Qdot],1),0)*INDEX(PAR[NO_round_Qdot],1)",
  "J5":  /* formula */ "ROUND(clc_load!T72/INDEX(PAR[NO_r_nt1],1),0)*INDEX(PAR[NO_r_nt1],1)",
  "K5":  /* formula */ "ROUND(clc_load!U72/INDEX(PAR[NO_r_nt2],1),0)*INDEX(PAR[NO_r_nt2],1)",
  "L5":  /* formula */ "ROUND(clc_load!V72/INDEX(PAR[NO_r_nt3],1),0)*INDEX(PAR[NO_r_nt3],1)",
  "A6":  /* unknown */ "Heizlast_spezifisch ",
  "C6":  /* unknown */ "qdot_room",
  "D6":  /* unknown */ "W/m²",
  "G6":  /* formula */ "ROUND(clc_load!M73/INDEX(PAR[NO_round_Qdot_spez],1),0)*INDEX(PAR[NO_round_Qdot_spez],1)",
  "H6":  /* formula */ "ROUND(clc_load!N73/INDEX(PAR[NO_round_rcover],1),0)*INDEX(PAR[NO_round_rcover],1)",
  "I6":  /* formula */ "ROUND(clc_load!O73/INDEX(PAR[NO_round_Qdot_spez],1),0)*INDEX(PAR[NO_round_Qdot_spez],1)",
  "J6":  /* formula */ "ROUND(clc_load!T73/INDEX(PAR[NO_r_nt2],1),0)*INDEX(PAR[NO_r_nt2],1)",
  "K6":  /* formula */ "ROUND(clc_load!U73/INDEX(PAR[NO_r_nt3],1),0)*INDEX(PAR[NO_r_nt3],1)",
  "L6":  /* formula */ "ROUND(clc_load!V73/INDEX(PAR[Spalte13],1),0)*INDEX(PAR[Spalte13],1)",
  "A7":  /* unknown */ "Heizlast mit Abschlag",
  "C7":  /* unknown */ "Qdot_room_cor",
  "D7":  /* unknown */ "W",
  "G7":  /* formula */ "ROUND(clc_load!M74/INDEX(PAR[NO_round_Qdot],1),0)*INDEX(PAR[NO_round_Qdot],1)",
  "H7":  /* formula */ "ROUND(clc_load!N74/INDEX(PAR[NO_round_Qdot_spez],1),0)*INDEX(PAR[NO_round_Qdot_spez],1)",
  "I7":  /* formula */ "ROUND(clc_load!O74/INDEX(PAR[NO_round_Qdot],1),0)*INDEX(PAR[NO_round_Qdot],1)",
  "J7":  /* formula */ "ROUND(clc_load!T74/INDEX(PAR[NO_r_nt1],1),0)*INDEX(PAR[NO_r_nt1],1)",
  "K7":  /* formula */ "ROUND(clc_load!U74/INDEX(PAR[NO_r_nt2],1),0)*INDEX(PAR[NO_r_nt2],1)",
  "L7":  /* formula */ "ROUND(clc_load!V74/INDEX(PAR[NO_r_nt3],1),0)*INDEX(PAR[NO_r_nt3],1)",
  "A8":  /* unknown */ "Heizlast_spez mit Abschlag",
  "C8":  /* unknown */ "qdot_room_cor",
  "D8":  /* unknown */ "W/m²",
  "G8":  /* formula */ "ROUND(clc_load!M75/INDEX(PAR[NO_round_Qdot_spez],1),0)*INDEX(PAR[NO_round_Qdot_spez],1)",
  "H8":  /* formula */ "ROUND(clc_load!N75/INDEX(PAR[NO_round_rcover],1),0)*INDEX(PAR[NO_round_rcover],1)",
  "I8":  /* formula */ "ROUND(clc_load!O75/INDEX(PAR[NO_round_Qdot_spez],1),0)*INDEX(PAR[NO_round_Qdot_spez],1)",
  "J8":  /* formula */ "ROUND(clc_load!T75/INDEX(PAR[NO_r_nt2],1),0)*INDEX(PAR[NO_r_nt2],1)",
  "K8":  /* formula */ "ROUND(clc_load!U75/INDEX(PAR[NO_r_nt3],1),0)*INDEX(PAR[NO_r_nt3],1)",
  "L8":  /* formula */ "ROUND(clc_load!V75/INDEX(PAR[Spalte13],1),0)*INDEX(PAR[Spalte13],1)",
  "A10":  /* unknown */ "Bauteilbewertung",
  "A11":  /* unknown */ "U-Wert ",
  "B11":  /* unknown */ "wall",
  "D11":  /* unknown */ "W/m²K",
  "G11":  /* formula */ "clc_load!M16",
  "H11":  /* formula */ "clc_load!N16",
  "I11":  /* formula */ "clc_load!O16",
  "J11":  /* formula */ "clc_load!T16",
  "K11":  /* formula */ "clc_load!U16",
  "L11":  /* formula */ "clc_load!V16",
  "A12":  /* unknown */ "Heizlast Transmission",
  "B12":  /* unknown */ "wall",
  "D12":  /* unknown */ "W",
  "G12":  /* formula */ "clc_load!M17",
  "H12":  /* formula */ "clc_load!N17",
  "I12":  /* formula */ "clc_load!O17",
  "J12":  /* formula */ "clc_load!T17",
  "K12":  /* formula */ "clc_load!U17",
  "L12":  /* formula */ "clc_load!V17",
  "A13":  /* unknown */ "Anteil Raumheizlast",
  "B13":  /* unknown */ "wall",
  "D13":  /* unknown */ "%",
  "G13":  /* formula */ "clc_load!M18",
  "H13":  /* formula */ "clc_load!N18",
  "I13":  /* formula */ "clc_load!O18",
  "J13":  /* formula */ "clc_load!T18",
  "K13":  /* formula */ "clc_load!U18",
  "L13":  /* formula */ "clc_load!V18",
  "A14":  /* unknown */ "Potenzial Austausch",
  "B14":  /* unknown */ "wall",
  "D14":  /* unknown */ "-",
  "G14":  /* formula */ "AND(G$11>=INDEX(PAR[U_opaque_lim],1),G$13>=INDEX(PAR[r_worst_lim],1))",
  "H14":  /* formula */ "AND(H$11>=INDEX(PAR[U_win_lim],1),H$13>=INDEX(PAR[NO_round_Qdot],1))",
  "I14":  /* formula */ "AND(I$11>=INDEX(PAR[U_opaque_lim],1),I$13>=INDEX(PAR[r_worst_lim],1))",
  "J14":  /* formula */ "AND(J$11>=INDEX(PAR[NO_round_Qdot],1),J$13>=INDEX(PAR[NO_round_rcover],1))",
  "K14":  /* formula */ "AND(K$11>=INDEX(PAR[NO_round_Qdot_spez],1),K$13>=INDEX(PAR[NO_r_nt1],1))",
  "L14":  /* formula */ "AND(L$11>=INDEX(PAR[NO_round_rcover],1),L$13>=INDEX(PAR[NO_r_nt2],1))",
  "A15":  /* unknown */ "U-Wert ",
  "B15":  /* unknown */ "win",
  "D15":  /* unknown */ "W/m²K",
  "G15":  /* formula */ "MAX(clc_load!M45,clc_load!M51,clc_load!M57)",
  "H15":  /* formula */ "MAX(clc_load!N45,clc_load!N51,clc_load!N57)",
  "I15":  /* formula */ "MAX(clc_load!O45,clc_load!O51,clc_load!O57)",
  "J15":  /* formula */ "MAX(clc_load!T45,clc_load!T51,clc_load!T57)",
  "K15":  /* formula */ "MAX(clc_load!U45,clc_load!U51,clc_load!U57)",
  "L15":  /* formula */ "MAX(clc_load!V45,clc_load!V51,clc_load!V57)",
  "A16":  /* unknown */ "Heizlast Transmission",
  "B16":  /* unknown */ "win",
  "D16":  /* unknown */ "W",
  "G16":  /* formula */ "(clc_load!M46+clc_load!M52+clc_load!M58)",
  "H16":  /* formula */ "(clc_load!N46+clc_load!N52+clc_load!N58)",
  "I16":  /* formula */ "(clc_load!O46+clc_load!O52+clc_load!O58)",
  "J16":  /* formula */ "(clc_load!T46+clc_load!T52+clc_load!T58)",
  "K16":  /* formula */ "(clc_load!U46+clc_load!U52+clc_load!U58)",
  "L16":  /* formula */ "(clc_load!V46+clc_load!V52+clc_load!V58)",
  "A17":  /* unknown */ "Anteil Raumheizlast",
  "B17":  /* unknown */ "win",
  "D17":  /* unknown */ "%",
  "G17":  /* formula */ "clc_load!M47+clc_load!M53+clc_load!M59",
  "H17":  /* formula */ "clc_load!N47+clc_load!N53+clc_load!N59",
  "I17":  /* formula */ "clc_load!O47+clc_load!O53+clc_load!O59",
  "J17":  /* formula */ "clc_load!T47+clc_load!T53+clc_load!T59",
  "K17":  /* formula */ "clc_load!U47+clc_load!U53+clc_load!U59",
  "L17":  /* formula */ "clc_load!V47+clc_load!V53+clc_load!V59",
  "A18":  /* unknown */ "Potenzial Austausch",
  "B18":  /* unknown */ "win",
  "D18":  /* unknown */ "-",
  "G18":  /* formula */ "AND(G$15>=INDEX(PAR[U_win_lim],1),G$17>=INDEX(PAR[r_worst_lim],1))",
  "H18":  /* formula */ "AND(H$15>=INDEX(PAR[r_worst_lim],1),H$17>=INDEX(PAR[NO_round_Qdot],1))",
  "I18":  /* formula */ "AND(I$15>=INDEX(PAR[U_win_lim],1),I$17>=INDEX(PAR[r_worst_lim],1))",
  "J18":  /* formula */ "AND(J$15>=INDEX(PAR[NO_round_Qdot_spez],1),J$17>=INDEX(PAR[NO_round_rcover],1))",
  "K18":  /* formula */ "AND(K$15>=INDEX(PAR[NO_round_rcover],1),K$17>=INDEX(PAR[NO_r_nt1],1))",
  "L18":  /* formula */ "AND(L$15>=INDEX(PAR[NO_r_nt1],1),L$17>=INDEX(PAR[NO_r_nt2],1))",
  "A19":  /* unknown */ "U-Wert ",
  "B19":  /* unknown */ "roof",
  "D19":  /* unknown */ "W/m²K",
  "G19":  /* formula */ "clc_load!M28",
  "H19":  /* formula */ "clc_load!N28",
  "I19":  /* formula */ "clc_load!O28",
  "J19":  /* formula */ "clc_load!T28",
  "K19":  /* formula */ "clc_load!U28",
  "L19":  /* formula */ "clc_load!V28",
  "A20":  /* unknown */ "Heizlast Transmission",
  "B20":  /* unknown */ "roof",
  "D20":  /* unknown */ "W",
  "G20":  /* formula */ "clc_load!M29",
  "H20":  /* formula */ "clc_load!N29",
  "I20":  /* formula */ "clc_load!O29",
  "J20":  /* formula */ "clc_load!T29",
  "K20":  /* formula */ "clc_load!U29",
  "L20":  /* formula */ "clc_load!V29",
  "A21":  /* unknown */ "Anteil Raumheizlast",
  "B21":  /* unknown */ "roof",
  "D21":  /* unknown */ "%",
  "G21":  /* formula */ "clc_load!M30",
  "H21":  /* formula */ "clc_load!N30",
  "I21":  /* formula */ "clc_load!O30",
  "J21":  /* formula */ "clc_load!T30",
  "K21":  /* formula */ "clc_load!U30",
  "L21":  /* formula */ "clc_load!V30",
  "A22":  /* unknown */ "Potenzial Austausch",
  "B22":  /* unknown */ "roof",
  "D22":  /* unknown */ "-",
  "G22":  /* formula */ "AND(G$19>=INDEX(PAR[U_opaque_lim],1),G$21>=INDEX(PAR[r_worst_lim],1))",
  "H22":  /* formula */ "AND(H$19>=INDEX(PAR[U_win_lim],1),H$21>=INDEX(PAR[NO_round_Qdot],1))",
  "I22":  /* formula */ "AND(I$19>=INDEX(PAR[U_opaque_lim],1),I$21>=INDEX(PAR[r_worst_lim],1))",
  "J22":  /* formula */ "AND(J$19>=INDEX(PAR[NO_round_Qdot],1),J$21>=INDEX(PAR[NO_round_rcover],1))",
  "K22":  /* formula */ "AND(K$19>=INDEX(PAR[NO_round_Qdot_spez],1),K$21>=INDEX(PAR[NO_r_nt1],1))",
  "L22":  /* formula */ "AND(L$19>=INDEX(PAR[NO_round_rcover],1),L$21>=INDEX(PAR[NO_r_nt2],1))",
  "A23":  /* unknown */ "U-Wert ",
  "B23":  /* unknown */ "botceil",
  "D23":  /* unknown */ "W/m²K",
  "G23":  /* formula */ "clc_load!M39",
  "H23":  /* formula */ "clc_load!N38",
  "I23":  /* formula */ "clc_load!O38",
  "J23":  /* formula */ "clc_load!T38",
  "K23":  /* formula */ "clc_load!U38",
  "L23":  /* formula */ "clc_load!V38",
  "A24":  /* unknown */ "Heizlast Transmission",
  "B24":  /* unknown */ "botceil",
  "D24":  /* unknown */ "W",
  "G24":  /* formula */ "clc_load!M40",
  "H24":  /* formula */ "clc_load!N40",
  "I24":  /* formula */ "clc_load!O40",
  "J24":  /* formula */ "clc_load!T40",
  "K24":  /* formula */ "clc_load!U40",
  "L24":  /* formula */ "clc_load!V40",
  "A25":  /* unknown */ "Anteil Raumheizlast",
  "B25":  /* unknown */ "botceil",
  "D25":  /* unknown */ "%",
  "G25":  /* formula */ "clc_load!M41",
  "H25":  /* formula */ "clc_load!N41",
  "I25":  /* formula */ "clc_load!O41",
  "J25":  /* formula */ "clc_load!T41",
  "K25":  /* formula */ "clc_load!U41",
  "L25":  /* formula */ "clc_load!V41",
  "A26":  /* unknown */ "Potenzial Austausch",
  "B26":  /* unknown */ "botceil",
  "D26":  /* unknown */ "-",
  "G26":  /* formula */ "AND(G$23>=INDEX(PAR[U_opaque_lim],1),G$25>=INDEX(PAR[r_worst_lim],1))",
  "H26":  /* formula */ "AND(H$23>=INDEX(PAR[U_win_lim],1),H$25>=INDEX(PAR[NO_round_Qdot],1))",
  "I26":  /* formula */ "AND(I$23>=INDEX(PAR[U_opaque_lim],1),I$25>=INDEX(PAR[r_worst_lim],1))",
  "J26":  /* formula */ "AND(J$23>=INDEX(PAR[NO_round_Qdot],1),J$25>=INDEX(PAR[NO_round_rcover],1))",
  "K26":  /* formula */ "AND(K$23>=INDEX(PAR[NO_round_Qdot_spez],1),K$25>=INDEX(PAR[NO_r_nt1],1))",
  "L26":  /* formula */ "AND(L$23>=INDEX(PAR[NO_round_rcover],1),L$25>=INDEX(PAR[NO_r_nt2],1))",
  "A27":  /* unknown */ "U-Wert ",
  "B27":  /* unknown */ "topceil",
  "D27":  /* unknown */ "W/m²K",
  "G27":  /* formula */ "clc_load!M34",
  "H27":  /* formula */ "clc_load!N34",
  "I27":  /* formula */ "clc_load!O34",
  "J27":  /* formula */ "clc_load!T34",
  "K27":  /* formula */ "clc_load!U34",
  "L27":  /* formula */ "clc_load!V34",
  "A28":  /* unknown */ "Heizlast Transmission",
  "B28":  /* unknown */ "topceil",
  "D28":  /* unknown */ "W",
  "G28":  /* formula */ "clc_load!M35",
  "H28":  /* formula */ "clc_load!N35",
  "I28":  /* formula */ "clc_load!O35",
  "J28":  /* formula */ "clc_load!T35",
  "K28":  /* formula */ "clc_load!U35",
  "L28":  /* formula */ "clc_load!V35",
  "A29":  /* unknown */ "Anteil Raumheizlast",
  "B29":  /* unknown */ "topceil",
  "D29":  /* unknown */ "%",
  "G29":  /* formula */ "clc_load!M36",
  "H29":  /* formula */ "clc_load!N36",
  "I29":  /* formula */ "clc_load!O36",
  "J29":  /* formula */ "clc_load!T36",
  "K29":  /* formula */ "clc_load!U36",
  "L29":  /* formula */ "clc_load!V36",
  "A30":  /* unknown */ "Potenzial Austausch",
  "B30":  /* unknown */ "topceil",
  "D30":  /* unknown */ "-",
  "G30":  /* formula */ "AND(G$27>=INDEX(PAR[U_opaque_lim],1),G$29>=INDEX(PAR[r_worst_lim],1))",
  "H30":  /* formula */ "AND(H$27>=INDEX(PAR[U_win_lim],1),H$29>=INDEX(PAR[NO_round_Qdot],1))",
  "I30":  /* formula */ "AND(I$27>=INDEX(PAR[U_opaque_lim],1),I$29>=INDEX(PAR[r_worst_lim],1))",
  "J30":  /* formula */ "AND(J$27>=INDEX(PAR[NO_round_Qdot],1),J$29>=INDEX(PAR[NO_round_rcover],1))",
  "K30":  /* formula */ "AND(K$27>=INDEX(PAR[NO_round_Qdot_spez],1),K$29>=INDEX(PAR[NO_r_nt1],1))",
  "L30":  /* formula */ "AND(L$27>=INDEX(PAR[NO_round_rcover],1),L$29>=INDEX(PAR[NO_r_nt2],1))",
  "A32":  /* unknown */ "Heizkörper / NT-ready",
  "A33":  /* unknown */ "Leistung Heizkörper IST",
  "D33":  /* unknown */ "W",
  "G33":  /* formula */ "ROUND(clc_power!J211/INDEX(PAR[NO_round_Qdot],1),0)*INDEX(PAR[NO_round_Qdot],1)",
  "H33":  /* formula */ "ROUND(clc_power!K211/INDEX(PAR[NO_round_Qdot_spez],1),0)*INDEX(PAR[NO_round_Qdot_spez],1)",
  "I33":  /* formula */ "ROUND(clc_power!L211/INDEX(PAR[NO_round_Qdot],1),0)*INDEX(PAR[NO_round_Qdot],1)",
  "J33":  /* formula */ "ROUND(clc_power!M211/INDEX(PAR[NO_r_nt1],1),0)*INDEX(PAR[NO_r_nt1],1)",
  "K33":  /* formula */ "ROUND(clc_power!N211/INDEX(PAR[NO_r_nt2],1),0)*INDEX(PAR[NO_r_nt2],1)",
  "L33":  /* formula */ "ROUND(clc_power!O211/INDEX(PAR[NO_r_nt3],1),0)*INDEX(PAR[NO_r_nt3],1)",
  "A34":  /* unknown */ "Typ 33 max. Leistung Austausch-Heizkörper",
  "D34":  /* unknown */ "W",
  "G34":  /* formula */ "ROUND(clc_power!J212/INDEX(PAR[NO_round_Qdot],1),0)*INDEX(PAR[NO_round_Qdot],1)",
  "H34":  /* formula */ "ROUND(clc_power!K212/INDEX(PAR[NO_round_Qdot_spez],1),0)*INDEX(PAR[NO_round_Qdot_spez],1)",
  "I34":  /* formula */ "ROUND(clc_power!L212/INDEX(PAR[NO_round_Qdot],1),0)*INDEX(PAR[NO_round_Qdot],1)",
  "J34":  /* formula */ "ROUND(clc_power!M212/INDEX(PAR[NO_r_nt1],1),0)*INDEX(PAR[NO_r_nt1],1)",
  "K34":  /* formula */ "ROUND(clc_power!N212/INDEX(PAR[NO_r_nt2],1),0)*INDEX(PAR[NO_r_nt2],1)",
  "L34":  /* formula */ "ROUND(clc_power!O212/INDEX(PAR[NO_r_nt3],1),0)*INDEX(PAR[NO_r_nt3],1)",
  "A35":  /* unknown */ "Deckungsgrad IST",
  "D35":  /* unknown */ "%",
  "G35":  /* formula */ "ROUND(clc_power!J213/INDEX(PAR[NO_round_rcover],1),0)*INDEX(PAR[NO_round_rcover],1)",
  "H35":  /* formula */ "ROUND(clc_power!K213/INDEX(PAR[NO_r_nt1],1),0)*INDEX(PAR[NO_r_nt1],1)",
  "I35":  /* formula */ "ROUND(clc_power!L213/INDEX(PAR[NO_round_rcover],1),0)*INDEX(PAR[NO_round_rcover],1)",
  "J35":  /* formula */ "ROUND(clc_power!M213/INDEX(PAR[NO_r_nt3],1),0)*INDEX(PAR[NO_r_nt3],1)",
  "K35":  /* formula */ "ROUND(clc_power!N213/INDEX(PAR[Spalte13],1),0)*INDEX(PAR[Spalte13],1)",
  "L35":  /* formula */ "ROUND(clc_power!O213/INDEX(PAR[Spalte14],1),0)*INDEX(PAR[Spalte14],1)",
  "A36":  /* unknown */ "Typ 33 Deckungsgrad",
  "D36":  /* unknown */ "%",
  "G36":  /* formula */ "ROUND(clc_power!J214/INDEX(PAR[NO_round_rcover],1),0)*INDEX(PAR[NO_round_rcover],1)",
  "H36":  /* formula */ "ROUND(clc_power!K214/INDEX(PAR[NO_r_nt1],1),0)*INDEX(PAR[NO_r_nt1],1)",
  "I36":  /* formula */ "ROUND(clc_power!L214/INDEX(PAR[NO_round_rcover],1),0)*INDEX(PAR[NO_round_rcover],1)",
  "J36":  /* formula */ "ROUND(clc_power!M214/INDEX(PAR[NO_r_nt3],1),0)*INDEX(PAR[NO_r_nt3],1)",
  "K36":  /* formula */ "ROUND(clc_power!N214/INDEX(PAR[Spalte13],1),0)*INDEX(PAR[Spalte13],1)",
  "L36":  /* formula */ "ROUND(clc_power!O214/INDEX(PAR[Spalte14],1),0)*INDEX(PAR[Spalte14],1)",
  "A37":  /* unknown */ "NT-ready",
  "G37":  /* formula */ "G35>1",
  "H37":  /* formula */ "H35>1",
  "I37":  /* formula */ "I35>1",
  "J37":  /* formula */ "J35>1",
  "K37":  /* formula */ "K35>1",
  "L37":  /* formula */ "L35>1",
  "A38":  /* unknown */ "Typ 33 NT-ready",
  "G38":  /* formula */ "G36>1",
  "H38":  /* formula */ "H36>1",
  "I38":  /* formula */ "I36>1",
  "J38":  /* formula */ "J36>1",
  "K38":  /* formula */ "K36>1",
  "L38":  /* formula */ "L36>1",
  "A39":  /* unknown */ "Typ 33 80 % NT-ready",
  "G39":  /* formula */ "G36>INDEX(PAR[NO_r_nt2],1)",
  "H39":  /* formula */ "H36>INDEX(PAR[NO_r_nt3],1)",
  "I39":  /* formula */ "I36>INDEX(PAR[NO_r_nt2],1)",
  "J39":  /* formula */ "J36>INDEX(PAR[Spalte14],1)",
  "K39":  /* formula */ "K36>INDEX(PAR[Spalte15],1)",
  "L39":  /* formula */ "L36>INDEX(PAR[Spalte16],1)",
  "A46":  /* unknown */ "Aggregation Gebäudeebene ",
  "A47":  /* unknown */ "Azahl Räume ",
  "G47":  /* formula */ "COUNTA(G5:AA5)",
  "A48":  /* unknown */ "Bauteilbewertung ",
  "A49":  /* unknown */ "Anzahl Potenzial",
  "B49":  /* unknown */ "wall",
  "G49":  /* formula */ "COUNTIF(G14:AA14,TRUE)",
  "A50":  /* unknown */ "Anteil Potenzial ",
  "B50":  /* unknown */ "wall",
  "G50":  /* formula */ "G49/G47",
  "A63":  /* unknown */ "NT-readiness Gesamtgebäude",
  "A64":  /* unknown */ "Typ 33: alle Räume > 0,8",
  "A65":  /* unknown */ "Deckungsgrad < 0,6 für > 50 %",
};
