// Sheet: clc_flat
export const data = {
  "B2":  /* unknown */ "Heizkörper 1 in Raum 1",
  "B3":  /* unknown */ "Typ",
  "C3":  /* formula */ "IN_rooms!R49",
  "E3":  /* unknown */ "Logarithmische Übertemperatur unter Normbedingungen",
  "F3":  /* unknown */ "Logarithmische Übertemperatur unter Normbedingungen",
  "G3":  /* unknown */ "Logarithmische Übertemperatur unter Normbedingungen",
  "H3":  /* unknown */ "Logarithmische Übertemperatur unter Normbedingungen",
  "I3":  /* unknown */ "Logarithmische Übertemperatur unter Normbedingungen",
  "J3":  /* unknown */ "Logarithmische Übertemperatur unter Normbedingungen",
  "K3":  /* unknown */ "Logarithmische Übertemperatur unter Normbedingungen",
  "M3":  /* unknown */ "Logarithmische Übertemperatur unter Betriebsbedingungen",
  "N3":  /* unknown */ "Logarithmische Übertemperatur unter Betriebsbedingungen",
  "O3":  /* unknown */ "Logarithmische Übertemperatur unter Betriebsbedingungen",
  "P3":  /* unknown */ "Logarithmische Übertemperatur unter Betriebsbedingungen",
  "Q3":  /* unknown */ "Logarithmische Übertemperatur unter Betriebsbedingungen",
  "R3":  /* unknown */ "Logarithmische Übertemperatur unter Betriebsbedingungen",
  "S3":  /* unknown */ "Logarithmische Übertemperatur unter Betriebsbedingungen",
  "B4":  /* unknown */ "Subtyp",
  "C4":  /* formula */ "IN_rooms!R50",
  "B5":  /* unknown */ "Subtyp_2",
  "B6":  /* unknown */ "Höhe",
  "C6":  /* formula */ "IN_rooms!R51",
  "D6":  /* unknown */ "mm",
  "E6":  /* richtext_as_string */ "ϑV",
  "F6":  /* unknown */ "=",
  "G6":  /* unknown */ 75,
  "H6":  /* unknown */ "°C",
  "I6":  /* unknown */ "Vorlauftemp. aus Herstellerunterlagen, i.d.R. 75°C",
  "J6":  /* unknown */ "Vorlauftemp. aus Herstellerunterlagen, i.d.R. 75°C",
  "K6":  /* unknown */ "Vorlauftemp. aus Herstellerunterlagen, i.d.R. 75°C",
  "M6":  /* richtext_as_string */ "ϑV",
  "N6":  /* unknown */ "=",
  "O6":  /* unknown */ 55,
  "P6":  /* unknown */ "°C",
  "Q6":  /* unknown */ "Vorlauftemperatur des vorliegenden Systems",
  "R6":  /* unknown */ "Vorlauftemperatur des vorliegenden Systems",
  "S6":  /* unknown */ "Vorlauftemperatur des vorliegenden Systems",
  "B7":  /* unknown */ "Breite",
  "C7":  /* formula */ "IN_rooms!R52",
  "D7":  /* unknown */ "mm",
  "E7":  /* richtext_as_string */ "ϑR",
  "F7":  /* unknown */ "=",
  "G7":  /* unknown */ 65,
  "H7":  /* unknown */ "°C",
  "I7":  /* unknown */ "Rücklauftemp. aus Herstellerunterlagen, i.d.R. 65°C",
  "J7":  /* unknown */ "Rücklauftemp. aus Herstellerunterlagen, i.d.R. 65°C",
  "K7":  /* unknown */ "Rücklauftemp. aus Herstellerunterlagen, i.d.R. 65°C",
  "M7":  /* richtext_as_string */ "ϑR",
  "N7":  /* unknown */ "=",
  "O7":  /* unknown */ 45,
  "P7":  /* unknown */ "°C",
  "Q7":  /* unknown */ "Rücklauftemperatur des vorliegenden Systems",
  "R7":  /* unknown */ "Rücklauftemperatur des vorliegenden Systems",
  "S7":  /* unknown */ "Rücklauftemperatur des vorliegenden Systems",
  "B8":  /* unknown */ "Berechnungs-Raumtemperatur",
  "C8":  /* formula */ "clc_load!I10",
  "D8":  /* unknown */ "°C",
  "E8":  /* richtext_as_string */ "ϑi",
  "F8":  /* unknown */ "=",
  "G8":  /* unknown */ 20,
  "H8":  /* unknown */ "°C",
  "I8":  /* unknown */ "Norminnentemperatur, i.d.R. 20°C",
  "J8":  /* unknown */ "Norminnentemperatur, i.d.R. 20°C",
  "K8":  /* unknown */ "Norminnentemperatur, i.d.R. 20°C",
  "M8":  /* richtext_as_string */ "ϑi",
  "N8":  /* unknown */ "=",
  "O8":  /* formula */ "C8",
  "P8":  /* unknown */ "°C",
  "Q8":  /* unknown */ "Innentemperatur des Raumes, für den der HK ausgelegt werden soll",
  "R8":  /* unknown */ "Innentemperatur des Raumes, für den der HK ausgelegt werden soll",
  "S8":  /* unknown */ "Innentemperatur des Raumes, für den der HK ausgelegt werden soll",
  "B9":  /* richtext_as_string */ "θVlneu",
  "C9":  /* unknown */ 55,
  "D9":  /* unknown */ "°C",
  "B10":  /* richtext_as_string */ "θRlneu",
  "C10":  /* unknown */ 45,
  "D10":  /* unknown */ "°C",
  "E10":  /* richtext_as_string */ "∆ϑn",
  "F10":  /* unknown */ "=",
  "G10":  /* formula */ "(G6-G7)/(LN((G6-G8)/(G7-G8)))",
  "H10":  /* unknown */ "K",
  "M10":  /* richtext_as_string */ "∆ϑm",
  "N10":  /* unknown */ "=",
  "O10":  /* formula */ "(O6-O7)/(LN((O6-O8)/(O7-O8)))",
  "P10":  /* unknown */ "K",
  "B11":  /* unknown */ "Glieder",
  "C11":  /* formula */ "IN_rooms!#REF!",
  "D11":  /* unknown */ "Stk.",
  "B12":  /* unknown */ "Tiefe",
  "C12":  /* formula */ "IN_rooms!R53",
  "D12":  /* unknown */ "mm",
  "B13":  /* unknown */ "Heizkörperexponent",
  "C13":  /* formula */ "SUMIFS(tabelle1[[Heizkörperexponent n ]],tabelle1[Heizkörper_Typ],C3,tabelle1[Heizkörper_Subtyp],C4,tabelle1[Höhe H in mm],C6,tabelle1[Bautiefe T in mm],C12)",
  "D13":  /* unknown */ "[-]",
  "E13":  /* unknown */ "Betriebsbedinung in Normbedingung umrechnen",
  "F13":  /* unknown */ "Betriebsbedinung in Normbedingung umrechnen",
  "G13":  /* unknown */ "Betriebsbedinung in Normbedingung umrechnen",
  "H13":  /* unknown */ "Betriebsbedinung in Normbedingung umrechnen",
  "I13":  /* unknown */ "Betriebsbedinung in Normbedingung umrechnen",
  "J13":  /* unknown */ "Betriebsbedinung in Normbedingung umrechnen",
  "M13":  /* unknown */ "Normbedingung in Betriebsbedinung umrechnen",
  "N13":  /* unknown */ "Normbedingung in Betriebsbedinung umrechnen",
  "O13":  /* unknown */ "Normbedingung in Betriebsbedinung umrechnen",
  "P13":  /* unknown */ "Normbedingung in Betriebsbedinung umrechnen",
  "Q13":  /* unknown */ "Normbedingung in Betriebsbedinung umrechnen",
  "R13":  /* unknown */ "Normbedingung in Betriebsbedinung umrechnen",
  "S13":  /* unknown */ "Normbedingung in Betriebsbedinung umrechnen",
  "B14":  /* unknown */ "Norm-Heizleistung 75/65/20",
  "C14":  /* formula */ "SUMIFS(tabelle1[Wärmeleistung (75/65/20)  in W/m],tabelle1[Heizkörper_Typ],C3,tabelle1[Heizkörper_Subtyp],C4,tabelle1[Höhe H in mm],C6,tabelle1[Bautiefe T in mm],C12)*C7/1000",
  "D14":  /* unknown */ "W",
  "B15":  /* unknown */ "Korrekturfaktor ",
  "C15":  /* formula */ "C16/C14",
  "D15":  /* unknown */ "[-]",
  "E15":  /* richtext_as_string */ "∆ϑn",
  "F15":  /* unknown */ "=",
  "G15":  /* formula */ "G10",
  "H15":  /* unknown */ "K",
  "I15":  /* unknown */ "Logarithmische Übertemperatur unter Normbedingungen",
  "J15":  /* unknown */ "Logarithmische Übertemperatur unter Normbedingungen",
  "K15":  /* unknown */ "Logarithmische Übertemperatur unter Normbedingungen",
  "M15":  /* richtext_as_string */ "∆ϑn",
  "N15":  /* unknown */ "=",
  "O15":  /* formula */ "G10",
  "P15":  /* unknown */ "K",
  "Q15":  /* unknown */ "Logarithmische Übertemperatur unter Normbedingungen",
  "R15":  /* unknown */ "Logarithmische Übertemperatur unter Normbedingungen",
  "S15":  /* unknown */ "Logarithmische Übertemperatur unter Normbedingungen",
  "B16":  /* richtext_as_string */ "Heizleistung bei θVlneu",
  "C16":  /* formula */ "O20",
  "D16":  /* unknown */ "W",
  "E16":  /* richtext_as_string */ "∆ϑm",
  "F16":  /* unknown */ "=",
  "G16":  /* formula */ "O10",
  "H16":  /* unknown */ "K",
  "I16":  /* unknown */ "Logarithmische Übertemperatur unter Betriebsbedingungen",
  "J16":  /* unknown */ "Logarithmische Übertemperatur unter Betriebsbedingungen",
  "K16":  /* unknown */ "Logarithmische Übertemperatur unter Betriebsbedingungen",
  "M16":  /* richtext_as_string */ "∆ϑm",
  "N16":  /* unknown */ "=",
  "O16":  /* formula */ "O10",
  "P16":  /* unknown */ "K",
  "Q16":  /* unknown */ "Logarithmische Übertemperatur unter Betriebsbedingungen",
  "R16":  /* unknown */ "Logarithmische Übertemperatur unter Betriebsbedingungen",
  "S16":  /* unknown */ "Logarithmische Übertemperatur unter Betriebsbedingungen",
  "B17":  /* richtext_as_string */ "Heizleistung θVlneu, Typ 33",
  "C17":  /* formula */ "(SUMIFS(tabelle1[Wärmeleistung (75/65/20)  in W/m],tabelle1[Heizkörper_Typ],C3,tabelle1[Heizkörper_Subtyp],\"Typ_33\",tabelle1[Höhe H in mm],C6,tabelle1[Bautiefe T in mm],155)*C7/1000)*((O16/O15)^SUMIFS(tabelle1[[Heizkörperexponent n ]],tabelle1[Heizkörper_Typ],C3,tabelle1[Heizkörper_Subtyp],\"Typ_33\",tabelle1[Höhe H in mm],C6,tabelle1[Bautiefe T in mm],155))",
  "D17":  /* unknown */ "W",
  "F17":  /* unknown */ "=",
  "G17":  /* formula */ "clc_load!$I$72/clc_load!#REF!",
  "H17":  /* unknown */ "W",
  "I17":  /* unknown */ "Benötigte Leistung pro Heizkörper ( Anzahl der Heizkörper x Leistung der Heizkörper ≥ Heizlast",
  "J17":  /* unknown */ "Benötigte Leistung pro Heizkörper ( Anzahl der Heizkörper x Leistung der Heizkörper ≥ Heizlast",
  "K17":  /* unknown */ "Benötigte Leistung pro Heizkörper ( Anzahl der Heizkörper x Leistung der Heizkörper ≥ Heizlast",
  "N17":  /* unknown */ "=",
  "O17":  /* formula */ "C14",
  "P17":  /* unknown */ "W",
  "Q17":  /* unknown */ "Leistungsabgabe unter Normbedingung, aus Herstellerunterlagen zu entnehmen",
  "R17":  /* unknown */ "Leistungsabgabe unter Normbedingung, aus Herstellerunterlagen zu entnehmen",
  "S17":  /* unknown */ "Leistungsabgabe unter Normbedingung, aus Herstellerunterlagen zu entnehmen",
  "E18":  /* unknown */ "n",
  "F18":  /* unknown */ "=",
  "G18":  /* formula */ "C13",
  "I18":  /* unknown */ "Heizkörperexponent",
  "J18":  /* unknown */ "Heizkörperexponent",
  "K18":  /* unknown */ "Heizkörperexponent",
  "M18":  /* unknown */ "n",
  "N18":  /* unknown */ "=",
  "O18":  /* formula */ "C13",
  "Q18":  /* unknown */ "Heizkörperexponent, aus Herstellerunterlagen zu entnehmen",
  "R18":  /* unknown */ "Heizkörperexponent, aus Herstellerunterlagen zu entnehmen",
  "S18":  /* unknown */ "Heizkörperexponent, aus Herstellerunterlagen zu entnehmen",
  "F20":  /* unknown */ "=",
  "G20":  /* formula */ "(G17/((G16/G15)^G18))",
  "H20":  /* unknown */ "W",
  "I20":  /* unknown */ "Nötige Leistung unter Normbedingung, mit diesem Wert in die entsprechenden Herstellerunterlagen gehen",
  "J20":  /* unknown */ "Nötige Leistung unter Normbedingung, mit diesem Wert in die entsprechenden Herstellerunterlagen gehen",
  "K20":  /* unknown */ "Nötige Leistung unter Normbedingung, mit diesem Wert in die entsprechenden Herstellerunterlagen gehen",
  "N20":  /* unknown */ "=",
  "O20":  /* formula */ "$O$17*(($O$16/$O$15)^$O$18)",
  "P20":  /* unknown */ "W",
  "Q20":  /* unknown */ "Leistungsabgabe des Heizkörpers unter den Auslegungsbedingungen",
  "R20":  /* unknown */ "Leistungsabgabe des Heizkörpers unter den Auslegungsbedingungen",
  "S20":  /* unknown */ "Leistungsabgabe des Heizkörpers unter den Auslegungsbedingungen",
  "B22":  /* unknown */ "Heizkörper 2 in Raum 1",
  "B23":  /* formula */ "B3",
  "C23":  /* formula */ "IF(IN_rooms!R56=\"Flachheizkörper\",IN_rooms!R49,\"Siehe Berechnungsreiter entsprechend Heizkörpertyp\")",
  "E23":  /* unknown */ "Logarithmische Übertemperatur unter Normbedingungen",
  "F23":  /* unknown */ "Logarithmische Übertemperatur unter Normbedingungen",
  "G23":  /* unknown */ "Logarithmische Übertemperatur unter Normbedingungen",
  "H23":  /* unknown */ "Logarithmische Übertemperatur unter Normbedingungen",
  "I23":  /* unknown */ "Logarithmische Übertemperatur unter Normbedingungen",
  "J23":  /* unknown */ "Logarithmische Übertemperatur unter Normbedingungen",
  "K23":  /* unknown */ "Logarithmische Übertemperatur unter Normbedingungen",
  "M23":  /* unknown */ "Logarithmische Übertemperatur unter Betriebsbedingungen",
  "N23":  /* unknown */ "Logarithmische Übertemperatur unter Betriebsbedingungen",
  "O23":  /* unknown */ "Logarithmische Übertemperatur unter Betriebsbedingungen",
  "P23":  /* unknown */ "Logarithmische Übertemperatur unter Betriebsbedingungen",
  "Q23":  /* unknown */ "Logarithmische Übertemperatur unter Betriebsbedingungen",
  "R23":  /* unknown */ "Logarithmische Übertemperatur unter Betriebsbedingungen",
  "S23":  /* unknown */ "Logarithmische Übertemperatur unter Betriebsbedingungen",
  "B24":  /* formula */ "B4",
  "C24":  /* formula */ "IN_rooms!R57",
  "B25":  /* formula */ "B5",
  "C25":  /* formula */ "IN_rooms!#REF!",
  "B26":  /* formula */ "B6",
  "C26":  /* formula */ "IN_rooms!R58",
  "D26":  /* unknown */ "mm",
  "E26":  /* richtext_as_string */ "ϑV",
  "F26":  /* unknown */ "=",
  "G26":  /* unknown */ 70,
  "H26":  /* unknown */ "°C",
  "I26":  /* unknown */ "Vorlauftemp. aus Herstellerunterlagen, i.d.R. 75°C",
  "J26":  /* unknown */ "Vorlauftemp. aus Herstellerunterlagen, i.d.R. 75°C",
  "K26":  /* unknown */ "Vorlauftemp. aus Herstellerunterlagen, i.d.R. 75°C",
  "M26":  /* richtext_as_string */ "ϑV",
  "N26":  /* unknown */ "=",
  "O26":  /* unknown */ 55,
  "P26":  /* unknown */ "°C",
  "Q26":  /* unknown */ "Vorlauftemperatur des vorliegenden Systems",
  "R26":  /* unknown */ "Vorlauftemperatur des vorliegenden Systems",
  "S26":  /* unknown */ "Vorlauftemperatur des vorliegenden Systems",
  "B27":  /* formula */ "B7",
  "C27":  /* formula */ "IN_rooms!R59",
  "D27":  /* unknown */ "mm",
  "E27":  /* richtext_as_string */ "ϑR",
  "F27":  /* unknown */ "=",
  "G27":  /* unknown */ 55,
  "H27":  /* unknown */ "°C",
  "I27":  /* unknown */ "Rücklauftemp. aus Herstellerunterlagen, i.d.R. 65°C",
  "J27":  /* unknown */ "Rücklauftemp. aus Herstellerunterlagen, i.d.R. 65°C",
  "K27":  /* unknown */ "Rücklauftemp. aus Herstellerunterlagen, i.d.R. 65°C",
  "M27":  /* richtext_as_string */ "ϑR",
  "N27":  /* unknown */ "=",
  "O27":  /* unknown */ 45,
  "P27":  /* unknown */ "°C",
  "Q27":  /* unknown */ "Rücklauftemperatur des vorliegenden Systems",
  "R27":  /* unknown */ "Rücklauftemperatur des vorliegenden Systems",
  "S27":  /* unknown */ "Rücklauftemperatur des vorliegenden Systems",
  "B28":  /* formula */ "B12",
  "C28":  /* formula */ "IN_rooms!R60",
  "D28":  /* unknown */ "mm",
  "E28":  /* richtext_as_string */ "ϑi",
  "F28":  /* unknown */ "=",
  "G28":  /* unknown */ 20,
  "H28":  /* unknown */ "°C",
  "I28":  /* unknown */ "Norminnentemperatur, i.d.R. 20°C",
  "J28":  /* unknown */ "Norminnentemperatur, i.d.R. 20°C",
  "K28":  /* unknown */ "Norminnentemperatur, i.d.R. 20°C",
  "M28":  /* richtext_as_string */ "ϑi",
  "N28":  /* unknown */ "=",
  "O28":  /* formula */ "C32",
  "P28":  /* unknown */ "°C",
  "Q28":  /* unknown */ "Innentemperatur des Raumes, für den der HK ausgelegt werden soll",
  "R28":  /* unknown */ "Innentemperatur des Raumes, für den der HK ausgelegt werden soll",
  "S28":  /* unknown */ "Innentemperatur des Raumes, für den der HK ausgelegt werden soll",
  "B29":  /* formula */ "B11",
  "C29":  /* formula */ "IN_rooms!R61",
  "D29":  /* unknown */ "Stk.",
  "B30":  /* formula */ "B13",
  "C30":  /* formula */ "_xlfn.AGGREGATE(15,6,Data_radiator!$X$5:$X$385/((Data_radiator!$C$5:$C$385=clc_flat!$C$3)*(Data_radiator!$D$5:$D$385=clc_flat!$C$4)*(Data_radiator!$G$5:$G$385=clc_flat!$C$6)*(Data_radiator!$L$5:$L$385=clc_flat!$C$12)),1)",
  "D30":  /* unknown */ "[-]",
  "E30":  /* richtext_as_string */ "∆ϑn",
  "F30":  /* unknown */ "=",
  "G30":  /* formula */ "(G26-G27)/(LN((G26-G28)/(G27-G28)))",
  "H30":  /* unknown */ "K",
  "M30":  /* richtext_as_string */ "∆ϑm",
  "N30":  /* unknown */ "=",
  "O30":  /* formula */ "(O26-O27)/(LN((O26-O28)/(O27-O28)))",
  "P30":  /* unknown */ "K",
  "B31":  /* formula */ "B14",
  "C31":  /* formula */ "IF(C23=\"Flachheizkörper\",SUMIFS(Data_radiator!$Z$5:$Z$385,Data_radiator!$C$5:$C$385,clc_flat!C23,Data_radiator!$D$5:$D$385,clc_flat!C24,Data_radiator!$F$5:$F$385,clc_flat!C25,Data_radiator!$G$5:$G$385,clc_flat!C26,Data_radiator!$L$5:$L$385,clc_flat!C28)*C27/1000,\"Siehe Berechnungsreiter entsprechend Heizkörpertyp\")",
  "D31":  /* unknown */ "W",
  "B32":  /* formula */ "B8",
  "C32":  /* formula */ "clc_load!$I$10",
  "D32":  /* unknown */ "°C",
  "B33":  /* formula */ "B9",
  "C33":  /* unknown */ 55,
  "D33":  /* unknown */ "°C",
  "E33":  /* unknown */ "Betriebsbedinung in Normbedingung umrechnen",
  "F33":  /* unknown */ "Betriebsbedinung in Normbedingung umrechnen",
  "G33":  /* unknown */ "Betriebsbedinung in Normbedingung umrechnen",
  "H33":  /* unknown */ "Betriebsbedinung in Normbedingung umrechnen",
  "I33":  /* unknown */ "Betriebsbedinung in Normbedingung umrechnen",
  "J33":  /* unknown */ "Betriebsbedinung in Normbedingung umrechnen",
  "M33":  /* unknown */ "Normbedingung in Betriebsbedinung umrechnen",
  "N33":  /* unknown */ "Normbedingung in Betriebsbedinung umrechnen",
  "O33":  /* unknown */ "Normbedingung in Betriebsbedinung umrechnen",
  "P33":  /* unknown */ "Normbedingung in Betriebsbedinung umrechnen",
  "Q33":  /* unknown */ "Normbedingung in Betriebsbedinung umrechnen",
  "R33":  /* unknown */ "Normbedingung in Betriebsbedinung umrechnen",
  "S33":  /* unknown */ "Normbedingung in Betriebsbedinung umrechnen",
  "B34":  /* formula */ "B10",
  "C34":  /* unknown */ 45,
  "D34":  /* unknown */ "°C",
  "B35":  /* formula */ "B15",
  "C35":  /* formula */ "C36/C31",
  "D35":  /* unknown */ "[-]",
  "E35":  /* richtext_as_string */ "∆ϑn",
  "F35":  /* unknown */ "=",
  "G35":  /* formula */ "G30",
  "H35":  /* unknown */ "K",
  "I35":  /* unknown */ "Logarithmische Übertemperatur unter Normbedingungen",
  "J35":  /* unknown */ "Logarithmische Übertemperatur unter Normbedingungen",
  "K35":  /* unknown */ "Logarithmische Übertemperatur unter Normbedingungen",
  "M35":  /* richtext_as_string */ "∆ϑn",
  "N35":  /* unknown */ "=",
  "O35":  /* formula */ "G30",
  "P35":  /* unknown */ "K",
  "Q35":  /* unknown */ "Logarithmische Übertemperatur unter Normbedingungen",
  "R35":  /* unknown */ "Logarithmische Übertemperatur unter Normbedingungen",
  "S35":  /* unknown */ "Logarithmische Übertemperatur unter Normbedingungen",
  "B36":  /* formula */ "B16",
  "C36":  /* formula */ "IF(C23=\"Flachheizkörper\",O40,\"Siehe Berechnungsreiter entsprechend Heizkörpertyp\")",
  "D36":  /* unknown */ "W",
  "E36":  /* richtext_as_string */ "∆ϑm",
  "F36":  /* unknown */ "=",
  "G36":  /* formula */ "O30",
  "H36":  /* unknown */ "K",
  "I36":  /* unknown */ "Logarithmische Übertemperatur unter Betriebsbedingungen",
  "J36":  /* unknown */ "Logarithmische Übertemperatur unter Betriebsbedingungen",
  "K36":  /* unknown */ "Logarithmische Übertemperatur unter Betriebsbedingungen",
  "M36":  /* richtext_as_string */ "∆ϑm",
  "N36":  /* unknown */ "=",
  "O36":  /* formula */ "O30",
  "P36":  /* unknown */ "K",
  "Q36":  /* unknown */ "Logarithmische Übertemperatur unter Betriebsbedingungen",
  "R36":  /* unknown */ "Logarithmische Übertemperatur unter Betriebsbedingungen",
  "S36":  /* unknown */ "Logarithmische Übertemperatur unter Betriebsbedingungen",
  "F37":  /* unknown */ "=",
  "G37":  /* formula */ "clc_load!$I$72/clc_load!#REF!",
  "H37":  /* unknown */ "W",
  "I37":  /* unknown */ "Benötigte Leistung pro Heizkörper ( Anzahl der Heizkörper x Leistung der Heizkörper ≥ Heizlast",
  "J37":  /* unknown */ "Benötigte Leistung pro Heizkörper ( Anzahl der Heizkörper x Leistung der Heizkörper ≥ Heizlast",
  "K37":  /* unknown */ "Benötigte Leistung pro Heizkörper ( Anzahl der Heizkörper x Leistung der Heizkörper ≥ Heizlast",
  "N37":  /* unknown */ "=",
  "O37":  /* formula */ "C31",
  "P37":  /* unknown */ "W",
  "Q37":  /* unknown */ "Leistungsabgabe unter Normbedingung, aus Herstellerunterlagen zu entnehmen",
  "R37":  /* unknown */ "Leistungsabgabe unter Normbedingung, aus Herstellerunterlagen zu entnehmen",
  "S37":  /* unknown */ "Leistungsabgabe unter Normbedingung, aus Herstellerunterlagen zu entnehmen",
  "E38":  /* unknown */ "n",
  "F38":  /* unknown */ "=",
  "G38":  /* formula */ "C30",
  "I38":  /* unknown */ "Heizkörperexponent",
  "J38":  /* unknown */ "Heizkörperexponent",
  "K38":  /* unknown */ "Heizkörperexponent",
  "M38":  /* unknown */ "n",
  "N38":  /* unknown */ "=",
  "O38":  /* formula */ "C30",
  "Q38":  /* unknown */ "Heizkörperexponent, aus Herstellerunterlagen zu entnehmen",
  "R38":  /* unknown */ "Heizkörperexponent, aus Herstellerunterlagen zu entnehmen",
  "S38":  /* unknown */ "Heizkörperexponent, aus Herstellerunterlagen zu entnehmen",
  "F40":  /* unknown */ "=",
  "G40":  /* formula */ "(G37/((G36/G35)^G38))",
  "H40":  /* unknown */ "W",
  "I40":  /* unknown */ "Nötige Leistung unter Normbedingung, mit diesem Wert in die entsprechenden Herstellerunterlagen gehen",
  "J40":  /* unknown */ "Nötige Leistung unter Normbedingung, mit diesem Wert in die entsprechenden Herstellerunterlagen gehen",
  "K40":  /* unknown */ "Nötige Leistung unter Normbedingung, mit diesem Wert in die entsprechenden Herstellerunterlagen gehen",
  "N40":  /* unknown */ "=",
  "O40":  /* formula */ "O37*((O36/O35)^O38)",
  "P40":  /* unknown */ "W",
  "Q40":  /* unknown */ "Leistungsabgabe des Heizkörpers unter den Auslegungsbedingungen",
  "R40":  /* unknown */ "Leistungsabgabe des Heizkörpers unter den Auslegungsbedingungen",
  "S40":  /* unknown */ "Leistungsabgabe des Heizkörpers unter den Auslegungsbedingungen",
  "B43":  /* unknown */ "Heizkörper X in Raum Y",
} as const;
