// Sheet: clc_build
export const data = {
  "A1":  /* unknown */ "Bezeichnung",
  "B1":  /* unknown */ "Gruppe",
  "C1":  /* unknown */ "Variable ",
  "D1":  /* unknown */ "Einheit",
  "E1":  /* unknown */ "Kommentar",
  "F1":  /* unknown */ "Zellenbezug Gebäude",
  "G1":  /* unknown */ "Werte Raum",
  "H1":  /* unknown */ "Werte Raum",
  "I1":  /* unknown */ "Werte Raum",
  "J1":  /* unknown */ "Werte Raum",
  "K1":  /* unknown */ "Werte Raum",
  "L1":  /* unknown */ "Werte Raum",
  "A2":  /* unknown */ "Raumindex",
  "C2":  /* unknown */ "ID_R#",
  "G2":  /* unknown */ 1,
  "H2":  /* unknown */ 2,
  "I2":  /* unknown */ 3,
  "J2":  /* unknown */ 4,
  "K2":  /* unknown */ 5,
  "L2":  /* unknown */ 6,
  "A3":  /* unknown */ "Heizlast Transmission ",
  "G3":  /* formula */ "ROUND((clc_load!I72-clc_load!I12)/10,0)*10",
  "H3":  /* formula */ "ROUND((clc_load!J72-clc_load!J12)/10,0)*10",
  "I3":  /* formula */ "ROUND((clc_load!K72-clc_load!K12)/10,0)*10",
  "J3":  /* formula */ "ROUND((clc_load!L72-clc_load!L12)/10,0)*10",
  "K3":  /* formula */ "ROUND((clc_load!M72-clc_load!M12)/10,0)*10",
  "L3":  /* formula */ "ROUND((clc_load!N72-clc_load!N12)/10,0)*10",
  "A4":  /* unknown */ "Heizlast Lüftung ",
  "G4":  /* formula */ "ROUND(clc_load!I12/10,0)*10",
  "H4":  /* formula */ "ROUND(clc_load!J12/10,0)*10",
  "I4":  /* formula */ "ROUND(clc_load!K12/10,0)*10",
  "J4":  /* formula */ "ROUND(clc_load!L12/10,0)*10",
  "K4":  /* formula */ "ROUND(clc_load!M12/10,0)*10",
  "L4":  /* formula */ "ROUND(clc_load!N12/10,0)*10",
  "A5":  /* unknown */ "Heizlast_total",
  "C5":  /* unknown */ "Qdot_room",
  "D5":  /* unknown */ "W",
  "G5":  /* formula */ "ROUND(clc_load!I72/HLOOKUP(\"NO_round_Qdot\", PAR!$F$1:$AZ$5, 2, FALSE),0)*HLOOKUP(\"NO_round_Qdot\", PAR!$F$1:$AZ$5, 2, FALSE)",
  "H5":  /* formula */ "ROUND(clc_load!J72/HLOOKUP(\"NO_round_Qdot\", PAR!$F$1:$AZ$5, 2, FALSE),0)*HLOOKUP(\"NO_round_Qdot\", PAR!$F$1:$AZ$5, 2, FALSE)",
  "I5":  /* formula */ "ROUND(clc_load!K72/HLOOKUP(\"NO_round_Qdot\", PAR!$F$1:$AZ$5, 2, FALSE),0)*HLOOKUP(\"NO_round_Qdot\", PAR!$F$1:$AZ$5, 2, FALSE)",
  "J5":  /* formula */ "ROUND(clc_load!L72/HLOOKUP(\"NO_round_Qdot\", PAR!$F$1:$AZ$5, 2, FALSE),0)*HLOOKUP(\"NO_round_Qdot\", PAR!$F$1:$AZ$5, 2, FALSE)",
  "K5":  /* formula */ "ROUND(clc_load!M72/HLOOKUP(\"NO_round_Qdot\", PAR!$F$1:$AZ$5, 2, FALSE),0)*HLOOKUP(\"NO_round_Qdot\", PAR!$F$1:$AZ$5, 2, FALSE)",
  "L5":  /* formula */ "ROUND(clc_load!N72/HLOOKUP(\"NO_round_Qdot\", PAR!$F$1:$AZ$5, 2, FALSE),0)*HLOOKUP(\"NO_round_Qdot\", PAR!$F$1:$AZ$5, 2, FALSE)",
  "A6":  /* unknown */ "Heizlast_spezifisch ",
  "C6":  /* unknown */ "qdot_room",
  "D6":  /* unknown */ "W/m²",
  "G6":  /* formula */ "ROUND(clc_load!I73/HLOOKUP(\"NO_round_Qdot_spez\", PAR!$F$1:$AZ$5, 2, FALSE),0)*HLOOKUP(\"NO_round_Qdot_spez\", PAR!$F$1:$AZ$5, 2, FALSE)",
  "H6":  /* formula */ "ROUND(clc_load!J73/HLOOKUP(\"NO_round_Qdot_spez\", PAR!$F$1:$AZ$5, 2, FALSE),0)*HLOOKUP(\"NO_round_Qdot_spez\", PAR!$F$1:$AZ$5, 2, FALSE)",
  "I6":  /* formula */ "ROUND(clc_load!K73/HLOOKUP(\"NO_round_Qdot_spez\", PAR!$F$1:$AZ$5, 2, FALSE),0)*HLOOKUP(\"NO_round_Qdot_spez\", PAR!$F$1:$AZ$5, 2, FALSE)",
  "J6":  /* formula */ "ROUND(clc_load!L73/HLOOKUP(\"NO_round_Qdot_spez\", PAR!$F$1:$AZ$5, 2, FALSE),0)*HLOOKUP(\"NO_round_Qdot_spez\", PAR!$F$1:$AZ$5, 2, FALSE)",
  "K6":  /* formula */ "ROUND(clc_load!M73/HLOOKUP(\"NO_round_Qdot_spez\", PAR!$F$1:$AZ$5, 2, FALSE),0)*HLOOKUP(\"NO_round_Qdot_spez\", PAR!$F$1:$AZ$5, 2, FALSE)",
  "L6":  /* formula */ "ROUND(clc_load!N73/HLOOKUP(\"NO_round_Qdot_spez\", PAR!$F$1:$AZ$5, 2, FALSE),0)*HLOOKUP(\"NO_round_Qdot_spez\", PAR!$F$1:$AZ$5, 2, FALSE)",
  "A7":  /* unknown */ "Heizlast mit Abschlag",
  "C7":  /* unknown */ "Qdot_room_cor",
  "D7":  /* unknown */ "W",
  "G7":  /* formula */ "ROUND(clc_load!I74/HLOOKUP(\"NO_round_Qdot\", PAR!$F$1:$AZ$5, 2, FALSE),0)*HLOOKUP(\"NO_round_Qdot\", PAR!$F$1:$AZ$5, 2, FALSE)",
  "H7":  /* formula */ "ROUND(clc_load!J74/HLOOKUP(\"NO_round_Qdot\", PAR!$F$1:$AZ$5, 2, FALSE),0)*HLOOKUP(\"NO_round_Qdot\", PAR!$F$1:$AZ$5, 2, FALSE)",
  "I7":  /* formula */ "ROUND(clc_load!K74/HLOOKUP(\"NO_round_Qdot\", PAR!$F$1:$AZ$5, 2, FALSE),0)*HLOOKUP(\"NO_round_Qdot\", PAR!$F$1:$AZ$5, 2, FALSE)",
  "J7":  /* formula */ "ROUND(clc_load!L74/HLOOKUP(\"NO_round_Qdot\", PAR!$F$1:$AZ$5, 2, FALSE),0)*HLOOKUP(\"NO_round_Qdot\", PAR!$F$1:$AZ$5, 2, FALSE)",
  "K7":  /* formula */ "ROUND(clc_load!M74/HLOOKUP(\"NO_round_Qdot\", PAR!$F$1:$AZ$5, 2, FALSE),0)*HLOOKUP(\"NO_round_Qdot\", PAR!$F$1:$AZ$5, 2, FALSE)",
  "L7":  /* formula */ "ROUND(clc_load!N74/HLOOKUP(\"NO_round_Qdot\", PAR!$F$1:$AZ$5, 2, FALSE),0)*HLOOKUP(\"NO_round_Qdot\", PAR!$F$1:$AZ$5, 2, FALSE)",
  "A8":  /* unknown */ "Heizlast_spez mit Abschlag",
  "C8":  /* unknown */ "qdot_room_cor",
  "D8":  /* unknown */ "W/m²",
  "G8":  /* formula */ "ROUND(clc_load!I75/HLOOKUP(\"NO_round_Qdot_spez\", PAR!$F$1:$AZ$5, 2, FALSE),0)*HLOOKUP(\"NO_round_Qdot_spez\", PAR!$F$1:$AZ$5, 2, FALSE)",
  "H8":  /* formula */ "ROUND(clc_load!J75/HLOOKUP(\"NO_round_Qdot_spez\", PAR!$F$1:$AZ$5, 2, FALSE),0)*HLOOKUP(\"NO_round_Qdot_spez\", PAR!$F$1:$AZ$5, 2, FALSE)",
  "I8":  /* formula */ "ROUND(clc_load!K75/HLOOKUP(\"NO_round_Qdot_spez\", PAR!$F$1:$AZ$5, 2, FALSE),0)*HLOOKUP(\"NO_round_Qdot_spez\", PAR!$F$1:$AZ$5, 2, FALSE)",
  "J8":  /* formula */ "ROUND(clc_load!L75/HLOOKUP(\"NO_round_Qdot_spez\", PAR!$F$1:$AZ$5, 2, FALSE),0)*HLOOKUP(\"NO_round_Qdot_spez\", PAR!$F$1:$AZ$5, 2, FALSE)",
  "K8":  /* formula */ "ROUND(clc_load!M75/HLOOKUP(\"NO_round_Qdot_spez\", PAR!$F$1:$AZ$5, 2, FALSE),0)*HLOOKUP(\"NO_round_Qdot_spez\", PAR!$F$1:$AZ$5, 2, FALSE)",
  "L8":  /* formula */ "ROUND(clc_load!N75/HLOOKUP(\"NO_round_Qdot_spez\", PAR!$F$1:$AZ$5, 2, FALSE),0)*HLOOKUP(\"NO_round_Qdot_spez\", PAR!$F$1:$AZ$5, 2, FALSE)",
  "A9":  /* unknown */ "Name des Raums",
  "C9":  /* unknown */ "TXT_room_name",
  "G9":  /* formula */ "IN_rooms!R3",
  "H9":  /* formula */ "IN_rooms!S3",
  "I9":  /* formula */ "IN_rooms!T3",
  "J9":  /* formula */ "IN_rooms!U3",
  "K9":  /* formula */ "IN_rooms!V3",
  "L9":  /* formula */ "IN_rooms!W3",
  "A10":  /* unknown */ "Bauteilbewertung",
  "A11":  /* unknown */ "U-Wert ",
  "B11":  /* unknown */ "wall",
  "D11":  /* unknown */ "W/m²K",
  "G11":  /* formula */ "IF(clc_load!I14>0,clc_load!I16,\"\")",
  "H11":  /* formula */ "IF(clc_load!J14>0,clc_load!J16,\"\")",
  "I11":  /* formula */ "IF(clc_load!K14>0,clc_load!K16,\"\")",
  "J11":  /* formula */ "IF(clc_load!L14>0,clc_load!L16,\"\")",
  "K11":  /* formula */ "IF(clc_load!M14>0,clc_load!M16,\"\")",
  "L11":  /* formula */ "IF(clc_load!N14>0,clc_load!N16,\"\")",
  "A12":  /* unknown */ "Heizlast Transmission",
  "B12":  /* unknown */ "wall",
  "D12":  /* unknown */ "W",
  "G12":  /* formula */ "clc_load!I17",
  "H12":  /* formula */ "clc_load!J17",
  "I12":  /* formula */ "clc_load!K17",
  "J12":  /* formula */ "clc_load!L17",
  "K12":  /* formula */ "clc_load!M17",
  "L12":  /* formula */ "clc_load!N17",
  "A13":  /* unknown */ "Anteil Raumheizlast",
  "B13":  /* unknown */ "wall",
  "D13":  /* unknown */ "%",
  "G13":  /* formula */ "clc_load!I18",
  "H13":  /* formula */ "clc_load!J18",
  "I13":  /* formula */ "clc_load!K18",
  "J13":  /* formula */ "clc_load!L18",
  "K13":  /* formula */ "clc_load!M18",
  "L13":  /* formula */ "clc_load!N18",
  "A14":  /* unknown */ "Potenzial Austausch",
  "B14":  /* unknown */ "wall",
  "D14":  /* unknown */ "-",
  "G14":  /* formula */ "AND(G$11>=HLOOKUP(\"U_opaque_lim\", PAR!$F$1:$AZ$5, 2, FALSE),G$13>=HLOOKUP(\"r_worst_lim\", PAR!$F$1:$AZ$5, 2, FALSE))",
  "H14":  /* formula */ "AND(H$11>=HLOOKUP(\"U_opaque_lim\", PAR!$F$1:$AZ$5, 2, FALSE),H$13>=HLOOKUP(\"r_worst_lim\", PAR!$F$1:$AZ$5, 2, FALSE))",
  "I14":  /* formula */ "AND(I$11>=HLOOKUP(\"U_opaque_lim\", PAR!$F$1:$AZ$5, 2, FALSE),I$13>=HLOOKUP(\"r_worst_lim\", PAR!$F$1:$AZ$5, 2, FALSE))",
  "J14":  /* formula */ "AND(J$11>=HLOOKUP(\"U_opaque_lim\", PAR!$F$1:$AZ$5, 2, FALSE),J$13>=HLOOKUP(\"r_worst_lim\", PAR!$F$1:$AZ$5, 2, FALSE))",
  "K14":  /* formula */ "AND(K$11>=HLOOKUP(\"U_opaque_lim\", PAR!$F$1:$AZ$5, 2, FALSE),K$13>=HLOOKUP(\"r_worst_lim\", PAR!$F$1:$AZ$5, 2, FALSE))",
  "L14":  /* formula */ "AND(L$11>=HLOOKUP(\"U_opaque_lim\", PAR!$F$1:$AZ$5, 2, FALSE),L$13>=HLOOKUP(\"r_worst_lim\", PAR!$F$1:$AZ$5, 2, FALSE))",
  "A15":  /* unknown */ "U-Wert ",
  "B15":  /* unknown */ "innerwall",
  "D15":  /* unknown */ "W/m²K",
  "G15":  /* formula */ "IF(clc_load!I19,clc_load!I21,\"\")",
  "H15":  /* formula */ "IF(clc_load!J19,clc_load!J21,\"\")",
  "I15":  /* formula */ "IF(clc_load!K19,clc_load!K21,\"\")",
  "J15":  /* formula */ "IF(clc_load!L19,clc_load!L21,\"\")",
  "K15":  /* formula */ "IF(clc_load!M19,clc_load!M21,\"\")",
  "L15":  /* formula */ "IF(clc_load!N19,clc_load!N21,\"\")",
  "A16":  /* unknown */ "Heizlast Transmission",
  "B16":  /* unknown */ "innerwall",
  "D16":  /* unknown */ "W",
  "G16":  /* formula */ "clc_load!I22",
  "H16":  /* formula */ "clc_load!J22",
  "I16":  /* formula */ "clc_load!K22",
  "J16":  /* formula */ "clc_load!L22",
  "K16":  /* formula */ "clc_load!M22",
  "L16":  /* formula */ "clc_load!N22",
  "A17":  /* unknown */ "Anteil Raumheizlast",
  "B17":  /* unknown */ "innerwall",
  "D17":  /* unknown */ "%",
  "G17":  /* formula */ "clc_load!I23",
  "H17":  /* formula */ "clc_load!J23",
  "I17":  /* formula */ "clc_load!K23",
  "J17":  /* formula */ "clc_load!L23",
  "K17":  /* formula */ "clc_load!M23",
  "L17":  /* formula */ "clc_load!N23",
  "A18":  /* unknown */ "Potenzial Austausch",
  "B18":  /* unknown */ "innerwall",
  "D18":  /* unknown */ "-",
  "G18":  /* formula */ "AND(G$15>=HLOOKUP(\"U_opaque_lim\", PAR!$F$1:$AZ$5, 2, FALSE),G$17>=HLOOKUP(\"r_worst_lim\", PAR!$F$1:$AZ$5, 2, FALSE))",
  "H18":  /* formula */ "AND(H$15>=HLOOKUP(\"U_opaque_lim\", PAR!$F$1:$AZ$5, 2, FALSE),H$17>=HLOOKUP(\"r_worst_lim\", PAR!$F$1:$AZ$5, 2, FALSE))",
  "I18":  /* formula */ "AND(I$15>=HLOOKUP(\"U_opaque_lim\", PAR!$F$1:$AZ$5, 2, FALSE),I$17>=HLOOKUP(\"r_worst_lim\", PAR!$F$1:$AZ$5, 2, FALSE))",
  "J18":  /* formula */ "AND(J$15>=HLOOKUP(\"U_opaque_lim\", PAR!$F$1:$AZ$5, 2, FALSE),J$17>=HLOOKUP(\"r_worst_lim\", PAR!$F$1:$AZ$5, 2, FALSE))",
  "K18":  /* formula */ "AND(K$15>=HLOOKUP(\"U_opaque_lim\", PAR!$F$1:$AZ$5, 2, FALSE),K$17>=HLOOKUP(\"r_worst_lim\", PAR!$F$1:$AZ$5, 2, FALSE))",
  "L18":  /* formula */ "AND(L$15>=HLOOKUP(\"U_opaque_lim\", PAR!$F$1:$AZ$5, 2, FALSE),L$17>=HLOOKUP(\"r_worst_lim\", PAR!$F$1:$AZ$5, 2, FALSE))",
  "A19":  /* unknown */ "U-Wert ",
  "B19":  /* unknown */ "win",
  "D19":  /* unknown */ "W/m²K",
  "G19":  /* formula */ "_xlfn.LET(\n  _xlpm.cond, CHOOSE({1,2,3,4,5}, clc_load!I42, clc_load!I48, clc_load!I54, clc_load!I60, clc_load!I66),\n  _xlpm.val, CHOOSE({1,2,3,4,5}, clc_load!I45, clc_load!I51, clc_load!I57, clc_load!I63, clc_load!I69),\n  _xlpm.valid, _xlpm.cond>0,\n  _xlpm.f_val, _xlfn._xlws.FILTER(_xlpm.val, _xlpm.valid),\n  _xlpm.f_wgt, _xlfn._xlws.FILTER(_xlpm.cond, _xlpm.valid),\n  _xlpm.wgt_sum, SUM(_xlpm.f_wgt),\n  _xlpm.wgt_avg, IF(_xlpm.wgt_sum>0, SUMPRODUCT(_xlpm.f_val, _xlpm.f_wgt)/_xlpm.wgt_sum, \"\"),\n  IF(SUM(--_xlpm.valid)=0, \"\", _xlpm.wgt_avg)\n)",
  "H19":  /* formula */ "_xlfn.LET(\n  _xlpm.cond, CHOOSE({1,2,3,4,5}, clc_load!J42, clc_load!J48, clc_load!J54, clc_load!J60, clc_load!J66),\n  _xlpm.val, CHOOSE({1,2,3,4,5}, clc_load!J45, clc_load!J51, clc_load!J57, clc_load!J63, clc_load!J69),\n  _xlpm.valid, _xlpm.cond>0,\n  _xlpm.f_val, _xlfn._xlws.FILTER(_xlpm.val, _xlpm.valid),\n  _xlpm.f_wgt, _xlfn._xlws.FILTER(_xlpm.cond, _xlpm.valid),\n  _xlpm.wgt_sum, SUM(_xlpm.f_wgt),\n  _xlpm.wgt_avg, IF(_xlpm.wgt_sum>0, SUMPRODUCT(_xlpm.f_val, _xlpm.f_wgt)/_xlpm.wgt_sum, \"\"),\n  IF(SUM(--_xlpm.valid)=0, \"\", _xlpm.wgt_avg)\n)",
  "I19":  /* formula */ "_xlfn.LET(\n  _xlpm.cond, CHOOSE({1,2,3,4,5}, clc_load!K42, clc_load!K48, clc_load!K54, clc_load!K60, clc_load!K66),\n  _xlpm.val, CHOOSE({1,2,3,4,5}, clc_load!K45, clc_load!K51, clc_load!K57, clc_load!K63, clc_load!K69),\n  _xlpm.valid, _xlpm.cond>0,\n  _xlpm.f_val, _xlfn._xlws.FILTER(_xlpm.val, _xlpm.valid),\n  _xlpm.f_wgt, _xlfn._xlws.FILTER(_xlpm.cond, _xlpm.valid),\n  _xlpm.wgt_sum, SUM(_xlpm.f_wgt),\n  _xlpm.wgt_avg, IF(_xlpm.wgt_sum>0, SUMPRODUCT(_xlpm.f_val, _xlpm.f_wgt)/_xlpm.wgt_sum, \"\"),\n  IF(SUM(--_xlpm.valid)=0, \"\", _xlpm.wgt_avg)\n)",
  "J19":  /* formula */ "_xlfn.LET(\n  _xlpm.cond, CHOOSE({1,2,3,4,5}, clc_load!L42, clc_load!L48, clc_load!L54, clc_load!L60, clc_load!L66),\n  _xlpm.val, CHOOSE({1,2,3,4,5}, clc_load!L45, clc_load!L51, clc_load!L57, clc_load!L63, clc_load!L69),\n  _xlpm.valid, _xlpm.cond>0,\n  _xlpm.f_val, _xlfn._xlws.FILTER(_xlpm.val, _xlpm.valid),\n  _xlpm.f_wgt, _xlfn._xlws.FILTER(_xlpm.cond, _xlpm.valid),\n  _xlpm.wgt_sum, SUM(_xlpm.f_wgt),\n  _xlpm.wgt_avg, IF(_xlpm.wgt_sum>0, SUMPRODUCT(_xlpm.f_val, _xlpm.f_wgt)/_xlpm.wgt_sum, \"\"),\n  IF(SUM(--_xlpm.valid)=0, \"\", _xlpm.wgt_avg)\n)",
  "K19":  /* formula */ "_xlfn.LET(\n  _xlpm.cond, CHOOSE({1,2,3,4,5}, clc_load!M42, clc_load!M48, clc_load!M54, clc_load!M60, clc_load!M66),\n  _xlpm.val, CHOOSE({1,2,3,4,5}, clc_load!M45, clc_load!M51, clc_load!M57, clc_load!M63, clc_load!M69),\n  _xlpm.valid, _xlpm.cond>0,\n  _xlpm.f_val, _xlfn._xlws.FILTER(_xlpm.val, _xlpm.valid),\n  _xlpm.f_wgt, _xlfn._xlws.FILTER(_xlpm.cond, _xlpm.valid),\n  _xlpm.wgt_sum, SUM(_xlpm.f_wgt),\n  _xlpm.wgt_avg, IF(_xlpm.wgt_sum>0, SUMPRODUCT(_xlpm.f_val, _xlpm.f_wgt)/_xlpm.wgt_sum, \"\"),\n  IF(SUM(--_xlpm.valid)=0, \"\", _xlpm.wgt_avg)\n)",
  "L19":  /* formula */ "_xlfn.LET(\n  _xlpm.cond, CHOOSE({1,2,3,4,5}, clc_load!N42, clc_load!N48, clc_load!N54, clc_load!N60, clc_load!N66),\n  _xlpm.val, CHOOSE({1,2,3,4,5}, clc_load!N45, clc_load!N51, clc_load!N57, clc_load!N63, clc_load!N69),\n  _xlpm.valid, _xlpm.cond>0,\n  _xlpm.f_val, _xlfn._xlws.FILTER(_xlpm.val, _xlpm.valid),\n  _xlpm.f_wgt, _xlfn._xlws.FILTER(_xlpm.cond, _xlpm.valid),\n  _xlpm.wgt_sum, SUM(_xlpm.f_wgt),\n  _xlpm.wgt_avg, IF(_xlpm.wgt_sum>0, SUMPRODUCT(_xlpm.f_val, _xlpm.f_wgt)/_xlpm.wgt_sum, \"\"),\n  IF(SUM(--_xlpm.valid)=0, \"\", _xlpm.wgt_avg)\n)",
  "A20":  /* unknown */ "Heizlast Transmission",
  "B20":  /* unknown */ "win",
  "D20":  /* unknown */ "W",
  "G20":  /* formula */ "(clc_load!I46+clc_load!I52+clc_load!I58+clc_load!I64+clc_load!I70)",
  "H20":  /* formula */ "(clc_load!J46+clc_load!J52+clc_load!J58+clc_load!J64+clc_load!J70)",
  "I20":  /* formula */ "(clc_load!K46+clc_load!K52+clc_load!K58+clc_load!K64+clc_load!K70)",
  "J20":  /* formula */ "(clc_load!L46+clc_load!L52+clc_load!L58+clc_load!L64+clc_load!L70)",
  "K20":  /* formula */ "(clc_load!M46+clc_load!M52+clc_load!M58+clc_load!M64+clc_load!M70)",
  "L20":  /* formula */ "(clc_load!N46+clc_load!N52+clc_load!N58+clc_load!N64+clc_load!N70)",
  "A21":  /* unknown */ "Anteil Raumheizlast",
  "B21":  /* unknown */ "win",
  "D21":  /* unknown */ "%",
  "G21":  /* formula */ "clc_load!I47+clc_load!I53+clc_load!I59+clc_load!I65+clc_load!I71",
  "H21":  /* formula */ "clc_load!J47+clc_load!J53+clc_load!J59+clc_load!J65+clc_load!J71",
  "I21":  /* formula */ "clc_load!K47+clc_load!K53+clc_load!K59+clc_load!K65+clc_load!K71",
  "J21":  /* formula */ "clc_load!L47+clc_load!L53+clc_load!L59+clc_load!L65+clc_load!L71",
  "K21":  /* formula */ "clc_load!M47+clc_load!M53+clc_load!M59+clc_load!M65+clc_load!M71",
  "L21":  /* formula */ "clc_load!N47+clc_load!N53+clc_load!N59+clc_load!N65+clc_load!N71",
  "A22":  /* unknown */ "Potenzial Austausch",
  "B22":  /* unknown */ "win",
  "D22":  /* unknown */ "-",
  "G22":  /* formula */ "AND(G$19>=HLOOKUP(\"U_win_lim\", PAR!$F$1:$AZ$5, 2, FALSE),G$21>=HLOOKUP(\"r_worst_lim\", PAR!$F$1:$AZ$5, 2, FALSE))",
  "H22":  /* formula */ "AND(H$19>=HLOOKUP(\"U_win_lim\", PAR!$F$1:$AZ$5, 2, FALSE),H$21>=HLOOKUP(\"r_worst_lim\", PAR!$F$1:$AZ$5, 2, FALSE))",
  "I22":  /* formula */ "AND(I$19>=HLOOKUP(\"U_win_lim\", PAR!$F$1:$AZ$5, 2, FALSE),I$21>=HLOOKUP(\"r_worst_lim\", PAR!$F$1:$AZ$5, 2, FALSE))",
  "J22":  /* formula */ "AND(J$19>=HLOOKUP(\"U_win_lim\", PAR!$F$1:$AZ$5, 2, FALSE),J$21>=HLOOKUP(\"r_worst_lim\", PAR!$F$1:$AZ$5, 2, FALSE))",
  "K22":  /* formula */ "AND(K$19>=HLOOKUP(\"U_win_lim\", PAR!$F$1:$AZ$5, 2, FALSE),K$21>=HLOOKUP(\"r_worst_lim\", PAR!$F$1:$AZ$5, 2, FALSE))",
  "L22":  /* formula */ "AND(L$19>=HLOOKUP(\"U_win_lim\", PAR!$F$1:$AZ$5, 2, FALSE),L$21>=HLOOKUP(\"r_worst_lim\", PAR!$F$1:$AZ$5, 2, FALSE))",
  "A23":  /* unknown */ "U-Wert ",
  "B23":  /* unknown */ "roof",
  "D23":  /* unknown */ "W/m²K",
  "G23":  /* formula */ "IF(clc_load!I26>0,clc_load!I28,\"\")",
  "H23":  /* formula */ "IF(clc_load!J26>0,clc_load!J28,\"\")",
  "I23":  /* formula */ "IF(clc_load!K26>0,clc_load!K28,\"\")",
  "J23":  /* formula */ "IF(clc_load!L26>0,clc_load!L28,\"\")",
  "K23":  /* formula */ "IF(clc_load!M26>0,clc_load!M28,\"\")",
  "L23":  /* formula */ "IF(clc_load!N26>0,clc_load!N28,\"\")",
  "A24":  /* unknown */ "Heizlast Transmission",
  "B24":  /* unknown */ "roof",
  "D24":  /* unknown */ "W",
  "G24":  /* formula */ "clc_load!I29",
  "H24":  /* formula */ "clc_load!J29",
  "I24":  /* formula */ "clc_load!K29",
  "J24":  /* formula */ "clc_load!L29",
  "K24":  /* formula */ "clc_load!M29",
  "L24":  /* formula */ "clc_load!N29",
  "A25":  /* unknown */ "Anteil Raumheizlast",
  "B25":  /* unknown */ "roof",
  "D25":  /* unknown */ "%",
  "G25":  /* formula */ "clc_load!I30",
  "H25":  /* formula */ "clc_load!J30",
  "I25":  /* formula */ "clc_load!K30",
  "J25":  /* formula */ "clc_load!L30",
  "K25":  /* formula */ "clc_load!M30",
  "L25":  /* formula */ "clc_load!N30",
  "A26":  /* unknown */ "Potenzial Austausch",
  "B26":  /* unknown */ "roof",
  "D26":  /* unknown */ "-",
  "G26":  /* formula */ "AND(G$23>=HLOOKUP(\"U_opaque_lim\", PAR!$F$1:$AZ$5, 2, FALSE),G$25>=HLOOKUP(\"r_worst_lim\", PAR!$F$1:$AZ$5, 2, FALSE))",
  "H26":  /* formula */ "AND(H$23>=HLOOKUP(\"U_opaque_lim\", PAR!$F$1:$AZ$5, 2, FALSE),H$25>=HLOOKUP(\"r_worst_lim\", PAR!$F$1:$AZ$5, 2, FALSE))",
  "I26":  /* formula */ "AND(I$23>=HLOOKUP(\"U_opaque_lim\", PAR!$F$1:$AZ$5, 2, FALSE),I$25>=HLOOKUP(\"r_worst_lim\", PAR!$F$1:$AZ$5, 2, FALSE))",
  "J26":  /* formula */ "AND(J$23>=HLOOKUP(\"U_opaque_lim\", PAR!$F$1:$AZ$5, 2, FALSE),J$25>=HLOOKUP(\"r_worst_lim\", PAR!$F$1:$AZ$5, 2, FALSE))",
  "K26":  /* formula */ "AND(K$23>=HLOOKUP(\"U_opaque_lim\", PAR!$F$1:$AZ$5, 2, FALSE),K$25>=HLOOKUP(\"r_worst_lim\", PAR!$F$1:$AZ$5, 2, FALSE))",
  "L26":  /* formula */ "AND(L$23>=HLOOKUP(\"U_opaque_lim\", PAR!$F$1:$AZ$5, 2, FALSE),L$25>=HLOOKUP(\"r_worst_lim\", PAR!$F$1:$AZ$5, 2, FALSE))",
  "A27":  /* unknown */ "U-Wert ",
  "B27":  /* unknown */ "botceil",
  "D27":  /* unknown */ "W/m²K",
  "G27":  /* formula */ "IF(clc_load!I37>0,clc_load!I39,\"\")",
  "H27":  /* formula */ "IF(clc_load!J37>0,clc_load!J39,\"\")",
  "I27":  /* formula */ "IF(clc_load!K37>0,clc_load!K39,\"\")",
  "J27":  /* formula */ "IF(clc_load!L37>0,clc_load!L39,\"\")",
  "K27":  /* formula */ "IF(clc_load!M37>0,clc_load!M39,\"\")",
  "L27":  /* formula */ "IF(clc_load!N37>0,clc_load!N39,\"\")",
  "A28":  /* unknown */ "Heizlast Transmission",
  "B28":  /* unknown */ "botceil",
  "D28":  /* unknown */ "W",
  "G28":  /* formula */ "clc_load!I40",
  "H28":  /* formula */ "clc_load!J40",
  "I28":  /* formula */ "clc_load!K40",
  "J28":  /* formula */ "clc_load!L40",
  "K28":  /* formula */ "clc_load!M40",
  "L28":  /* formula */ "clc_load!N40",
  "A29":  /* unknown */ "Anteil Raumheizlast",
  "B29":  /* unknown */ "botceil",
  "G29":  /* formula */ "clc_load!I41",
  "H29":  /* formula */ "clc_load!J41",
  "I29":  /* formula */ "clc_load!K41",
  "J29":  /* formula */ "clc_load!L41",
  "K29":  /* formula */ "clc_load!M41",
  "L29":  /* formula */ "clc_load!N41",
  "A30":  /* unknown */ "Potenzial Austausch",
  "B30":  /* unknown */ "botceil",
  "D30":  /* unknown */ "-",
  "G30":  /* formula */ "AND(G$27>=HLOOKUP(\"U_opaque_lim\", PAR!$F$1:$AZ$5, 2, FALSE),G$29>=HLOOKUP(\"r_worst_lim\", PAR!$F$1:$AZ$5, 2, FALSE))",
  "H30":  /* formula */ "AND(H$27>=HLOOKUP(\"U_opaque_lim\", PAR!$F$1:$AZ$5, 2, FALSE),H$29>=HLOOKUP(\"r_worst_lim\", PAR!$F$1:$AZ$5, 2, FALSE))",
  "I30":  /* formula */ "AND(I$27>=HLOOKUP(\"U_opaque_lim\", PAR!$F$1:$AZ$5, 2, FALSE),I$29>=HLOOKUP(\"r_worst_lim\", PAR!$F$1:$AZ$5, 2, FALSE))",
  "J30":  /* formula */ "AND(J$27>=HLOOKUP(\"U_opaque_lim\", PAR!$F$1:$AZ$5, 2, FALSE),J$29>=HLOOKUP(\"r_worst_lim\", PAR!$F$1:$AZ$5, 2, FALSE))",
  "K30":  /* formula */ "AND(K$27>=HLOOKUP(\"U_opaque_lim\", PAR!$F$1:$AZ$5, 2, FALSE),K$29>=HLOOKUP(\"r_worst_lim\", PAR!$F$1:$AZ$5, 2, FALSE))",
  "L30":  /* formula */ "AND(L$27>=HLOOKUP(\"U_opaque_lim\", PAR!$F$1:$AZ$5, 2, FALSE),L$29>=HLOOKUP(\"r_worst_lim\", PAR!$F$1:$AZ$5, 2, FALSE))",
  "A31":  /* unknown */ "U-Wert ",
  "B31":  /* unknown */ "topceil",
  "D31":  /* unknown */ "W/m²K",
  "G31":  /* formula */ "IF(clc_load!I32>0,clc_load!I34,\"\")",
  "H31":  /* formula */ "IF(clc_load!J32>0,clc_load!J34,\"\")",
  "I31":  /* formula */ "IF(clc_load!K32>0,clc_load!K34,\"\")",
  "J31":  /* formula */ "IF(clc_load!L32>0,clc_load!L34,\"\")",
  "K31":  /* formula */ "IF(clc_load!M32>0,clc_load!M34,\"\")",
  "L31":  /* formula */ "IF(clc_load!N32>0,clc_load!N34,\"\")",
  "A32":  /* unknown */ "Heizlast Transmission",
  "B32":  /* unknown */ "topceil",
  "D32":  /* unknown */ "W",
  "G32":  /* formula */ "clc_load!I35",
  "H32":  /* formula */ "clc_load!J35",
  "I32":  /* formula */ "clc_load!K35",
  "J32":  /* formula */ "clc_load!L35",
  "K32":  /* formula */ "clc_load!M35",
  "L32":  /* formula */ "clc_load!N35",
  "A33":  /* unknown */ "Anteil Raumheizlast",
  "B33":  /* unknown */ "topceil",
  "D33":  /* unknown */ "%",
  "G33":  /* formula */ "clc_load!I36",
  "H33":  /* formula */ "clc_load!J36",
  "I33":  /* formula */ "clc_load!K36",
  "J33":  /* formula */ "clc_load!L36",
  "K33":  /* formula */ "clc_load!M36",
  "L33":  /* formula */ "clc_load!N36",
  "A34":  /* unknown */ "Potenzial Austausch",
  "B34":  /* unknown */ "topceil",
  "D34":  /* unknown */ "-",
  "G34":  /* formula */ "AND(G$31>=HLOOKUP(\"U_opaque_lim\", PAR!$F$1:$AZ$5, 2, FALSE),G$33>=HLOOKUP(\"r_worst_lim\", PAR!$F$1:$AZ$5, 2, FALSE))",
  "H34":  /* formula */ "AND(H$31>=HLOOKUP(\"U_opaque_lim\", PAR!$F$1:$AZ$5, 2, FALSE),H$33>=HLOOKUP(\"r_worst_lim\", PAR!$F$1:$AZ$5, 2, FALSE))",
  "I34":  /* formula */ "AND(I$31>=HLOOKUP(\"U_opaque_lim\", PAR!$F$1:$AZ$5, 2, FALSE),I$33>=HLOOKUP(\"r_worst_lim\", PAR!$F$1:$AZ$5, 2, FALSE))",
  "J34":  /* formula */ "AND(J$31>=HLOOKUP(\"U_opaque_lim\", PAR!$F$1:$AZ$5, 2, FALSE),J$33>=HLOOKUP(\"r_worst_lim\", PAR!$F$1:$AZ$5, 2, FALSE))",
  "K34":  /* formula */ "AND(K$31>=HLOOKUP(\"U_opaque_lim\", PAR!$F$1:$AZ$5, 2, FALSE),K$33>=HLOOKUP(\"r_worst_lim\", PAR!$F$1:$AZ$5, 2, FALSE))",
  "L34":  /* formula */ "AND(L$31>=HLOOKUP(\"U_opaque_lim\", PAR!$F$1:$AZ$5, 2, FALSE),L$33>=HLOOKUP(\"r_worst_lim\", PAR!$F$1:$AZ$5, 2, FALSE))",
  "A36":  /* unknown */ "Heizkörper / NT-ready",
  "A37":  /* unknown */ "Leistung Heizkörper IST 55°C",
  "D37":  /* unknown */ "W",
  "G37":  /* formula */ "ROUND(clc_power!G203/HLOOKUP(\"NO_round_Qdot\", PAR!$F$1:$AZ$5, 2, FALSE),0)*HLOOKUP(\"NO_round_Qdot\", PAR!$F$1:$AZ$5, 2, FALSE)",
  "H37":  /* formula */ "ROUND(clc_power!H203/HLOOKUP(\"NO_round_Qdot\", PAR!$F$1:$AZ$5, 2, FALSE),0)*HLOOKUP(\"NO_round_Qdot\", PAR!$F$1:$AZ$5, 2, FALSE)",
  "I37":  /* formula */ "ROUND(clc_power!I203/HLOOKUP(\"NO_round_Qdot\", PAR!$F$1:$AZ$5, 2, FALSE),0)*HLOOKUP(\"NO_round_Qdot\", PAR!$F$1:$AZ$5, 2, FALSE)",
  "J37":  /* formula */ "ROUND(clc_power!J203/HLOOKUP(\"NO_round_Qdot\", PAR!$F$1:$AZ$5, 2, FALSE),0)*HLOOKUP(\"NO_round_Qdot\", PAR!$F$1:$AZ$5, 2, FALSE)",
  "K37":  /* formula */ "ROUND(clc_power!K203/HLOOKUP(\"NO_round_Qdot\", PAR!$F$1:$AZ$5, 2, FALSE),0)*HLOOKUP(\"NO_round_Qdot\", PAR!$F$1:$AZ$5, 2, FALSE)",
  "L37":  /* formula */ "ROUND(clc_power!L203/HLOOKUP(\"NO_round_Qdot\", PAR!$F$1:$AZ$5, 2, FALSE),0)*HLOOKUP(\"NO_round_Qdot\", PAR!$F$1:$AZ$5, 2, FALSE)",
  "A38":  /* unknown */ "Typ 33 max. Leistung Austausch-Heizkörper",
  "D38":  /* unknown */ "W",
  "G38":  /* formula */ "ROUND(clc_power!G204/HLOOKUP(\"NO_round_Qdot\", PAR!$F$1:$AZ$5, 2, FALSE),0)*HLOOKUP(\"NO_round_Qdot\", PAR!$F$1:$AZ$5, 2, FALSE)",
  "H38":  /* formula */ "ROUND(clc_power!H204/HLOOKUP(\"NO_round_Qdot\", PAR!$F$1:$AZ$5, 2, FALSE),0)*HLOOKUP(\"NO_round_Qdot\", PAR!$F$1:$AZ$5, 2, FALSE)",
  "I38":  /* formula */ "ROUND(clc_power!I204/HLOOKUP(\"NO_round_Qdot\", PAR!$F$1:$AZ$5, 2, FALSE),0)*HLOOKUP(\"NO_round_Qdot\", PAR!$F$1:$AZ$5, 2, FALSE)",
  "J38":  /* formula */ "ROUND(clc_power!J204/HLOOKUP(\"NO_round_Qdot\", PAR!$F$1:$AZ$5, 2, FALSE),0)*HLOOKUP(\"NO_round_Qdot\", PAR!$F$1:$AZ$5, 2, FALSE)",
  "K38":  /* formula */ "ROUND(clc_power!K204/HLOOKUP(\"NO_round_Qdot\", PAR!$F$1:$AZ$5, 2, FALSE),0)*HLOOKUP(\"NO_round_Qdot\", PAR!$F$1:$AZ$5, 2, FALSE)",
  "L38":  /* formula */ "ROUND(clc_power!L204/HLOOKUP(\"NO_round_Qdot\", PAR!$F$1:$AZ$5, 2, FALSE),0)*HLOOKUP(\"NO_round_Qdot\", PAR!$F$1:$AZ$5, 2, FALSE)",
  "A39":  /* unknown */ "Deckungsgrad IST 55°C",
  "D39":  /* unknown */ "%",
  "G39":  /* formula */ "ROUND(clc_power!G205/HLOOKUP(\"NO_round_rcover\", PAR!$F$1:$AZ$5, 2, FALSE),0)*HLOOKUP(\"NO_round_rcover\", PAR!$F$1:$AZ$5, 2, FALSE)",
  "H39":  /* formula */ "ROUND(clc_power!H205/HLOOKUP(\"NO_round_rcover\", PAR!$F$1:$AZ$5, 2, FALSE),0)*HLOOKUP(\"NO_round_rcover\", PAR!$F$1:$AZ$5, 2, FALSE)",
  "I39":  /* formula */ "ROUND(clc_power!I205/HLOOKUP(\"NO_round_rcover\", PAR!$F$1:$AZ$5, 2, FALSE),0)*HLOOKUP(\"NO_round_rcover\", PAR!$F$1:$AZ$5, 2, FALSE)",
  "J39":  /* formula */ "ROUND(clc_power!J205/HLOOKUP(\"NO_round_rcover\", PAR!$F$1:$AZ$5, 2, FALSE),0)*HLOOKUP(\"NO_round_rcover\", PAR!$F$1:$AZ$5, 2, FALSE)",
  "K39":  /* formula */ "ROUND(clc_power!K205/HLOOKUP(\"NO_round_rcover\", PAR!$F$1:$AZ$5, 2, FALSE),0)*HLOOKUP(\"NO_round_rcover\", PAR!$F$1:$AZ$5, 2, FALSE)",
  "L39":  /* formula */ "ROUND(clc_power!L205/HLOOKUP(\"NO_round_rcover\", PAR!$F$1:$AZ$5, 2, FALSE),0)*HLOOKUP(\"NO_round_rcover\", PAR!$F$1:$AZ$5, 2, FALSE)",
  "A40":  /* unknown */ "Typ 33 Deckungsgrad",
  "D40":  /* unknown */ "%",
  "G40":  /* formula */ "ROUND(clc_power!G206/HLOOKUP(\"NO_round_rcover\", PAR!$F$1:$AZ$5, 2, FALSE),0)*HLOOKUP(\"NO_round_rcover\", PAR!$F$1:$AZ$5, 2, FALSE)",
  "H40":  /* formula */ "ROUND(clc_power!H206/HLOOKUP(\"NO_round_rcover\", PAR!$F$1:$AZ$5, 2, FALSE),0)*HLOOKUP(\"NO_round_rcover\", PAR!$F$1:$AZ$5, 2, FALSE)",
  "I40":  /* formula */ "ROUND(clc_power!I206/HLOOKUP(\"NO_round_rcover\", PAR!$F$1:$AZ$5, 2, FALSE),0)*HLOOKUP(\"NO_round_rcover\", PAR!$F$1:$AZ$5, 2, FALSE)",
  "J40":  /* formula */ "ROUND(clc_power!J206/HLOOKUP(\"NO_round_rcover\", PAR!$F$1:$AZ$5, 2, FALSE),0)*HLOOKUP(\"NO_round_rcover\", PAR!$F$1:$AZ$5, 2, FALSE)",
  "K40":  /* formula */ "ROUND(clc_power!K206/HLOOKUP(\"NO_round_rcover\", PAR!$F$1:$AZ$5, 2, FALSE),0)*HLOOKUP(\"NO_round_rcover\", PAR!$F$1:$AZ$5, 2, FALSE)",
  "L40":  /* formula */ "ROUND(clc_power!L206/HLOOKUP(\"NO_round_rcover\", PAR!$F$1:$AZ$5, 2, FALSE),0)*HLOOKUP(\"NO_round_rcover\", PAR!$F$1:$AZ$5, 2, FALSE)",
  "A41":  /* unknown */ "NT-ready",
  "G41":  /* formula */ "G39>1",
  "H41":  /* formula */ "H39>1",
  "I41":  /* formula */ "I39>1",
  "J41":  /* formula */ "J39>1",
  "K41":  /* formula */ "K39>1",
  "L41":  /* formula */ "L39>1",
  "A42":  /* unknown */ "Typ 33 NT-ready",
  "G42":  /* formula */ "G40>1",
  "H42":  /* formula */ "H40>1",
  "I42":  /* formula */ "I40>1",
  "J42":  /* formula */ "J40>1",
  "K42":  /* formula */ "K40>1",
  "L42":  /* formula */ "L40>1",
  "A43":  /* unknown */ "Typ 33 80 % NT-ready",
  "G43":  /* formula */ "G40>HLOOKUP(\"NO_r_nt2\", PAR!$F$1:$AZ$5, 2, FALSE)",
  "H43":  /* formula */ "H40>HLOOKUP(\"NO_r_nt2\", PAR!$F$1:$AZ$5, 2, FALSE)",
  "I43":  /* formula */ "I40>HLOOKUP(\"NO_r_nt2\", PAR!$F$1:$AZ$5, 2, FALSE)",
  "J43":  /* formula */ "J40>HLOOKUP(\"NO_r_nt2\", PAR!$F$1:$AZ$5, 2, FALSE)",
  "K43":  /* formula */ "K40>HLOOKUP(\"NO_r_nt2\", PAR!$F$1:$AZ$5, 2, FALSE)",
  "L43":  /* formula */ "L40>HLOOKUP(\"NO_r_nt2\", PAR!$F$1:$AZ$5, 2, FALSE)",
  "I46":  /* unknown */ "0,6 - 0,8",
  "J46":  /* unknown */ 0.7,
  "K46":  /* formula */ "J46-0.6",
  "L46":  /* formula */ "K46/0.2",
  "J47":  /* unknown */ 0.9,
  "K47":  /* formula */ "J47-0.6",
  "L47":  /* formula */ "K47/0.2",
  "A48":  /* unknown */ "Aggregation Gebäudeebene ",
  "A49":  /* unknown */ "Azahl Räume ",
  "G49":  /* formula */ "SUMPRODUCT((G9:AA9<>0)*1)",
  "A50":  /* unknown */ "Bauteilbewertung ",
  "A51":  /* unknown */ "Anzahl Potenzial",
  "B51":  /* unknown */ "wall",
  "G51":  /* formula */ "COUNTIF(G14:AA14,TRUE)",
  "A52":  /* unknown */ "Anzahl Potenzial",
  "B52":  /* unknown */ "innerwall",
  "G52":  /* formula */ "COUNTIF(G18:AA18,TRUE)",
  "A53":  /* unknown */ "Anzahl Potenzial",
  "B53":  /* unknown */ "win",
  "G53":  /* formula */ "COUNTIF(G22:AA22,TRUE)",
  "A54":  /* unknown */ "Anzahl Potenzial",
  "B54":  /* unknown */ "roof",
  "G54":  /* formula */ "COUNTIF(G26:AA26,TRUE)",
  "A55":  /* unknown */ "Anzahl Potenzial",
  "B55":  /* unknown */ "botceil",
  "G55":  /* formula */ "COUNTIF(G30:AA30,TRUE)",
  "A56":  /* unknown */ "Anzahl Potenzial",
  "B56":  /* unknown */ "topceil",
  "G56":  /* formula */ "COUNTIF(G34:AA34,TRUE)",
  "A57":  /* unknown */ "Anteil Potenzial ",
  "B57":  /* unknown */ "wall",
  "G57":  /* formula */ "G51/$G$49",
  "A58":  /* unknown */ "Anteil Potenzial ",
  "B58":  /* unknown */ "innerwall",
  "G58":  /* formula */ "G52/$G$49",
  "A59":  /* unknown */ "Anteil Potenzial ",
  "B59":  /* unknown */ "win",
  "G59":  /* formula */ "G53/$G$49",
  "A60":  /* unknown */ "Anteil Potenzial ",
  "B60":  /* unknown */ "roof",
  "G60":  /* formula */ "G54/$G$49",
  "A61":  /* unknown */ "Anteil Potenzial ",
  "B61":  /* unknown */ "botceil",
  "G61":  /* formula */ "G55/$G$49",
  "A62":  /* unknown */ "Anteil Potenzial ",
  "B62":  /* unknown */ "topceil",
  "G62":  /* formula */ "G56/$G$49",
  "A64":  /* unknown */ "NT-readiness Gesamtgebäude",
  "B64":  /* unknown */ "von",
  "C64":  /* unknown */ "bis ",
  "A65":  /* unknown */ "Anzahl Räume Deckungsgrad < 0,6",
  "C65":  /* unknown */ 0.6,
  "G65":  /* formula */ "COUNTIF($G$39:$AA$39,\"<0,6\")",
  "A66":  /* unknown */ "Anzahl Räume Deckungsgrad < 0,8",
  "C66":  /* unknown */ 0.8,
  "G66":  /* formula */ "COUNTIF($G$39:$AA$39,\"<0,8\")",
  "A67":  /* unknown */ "Anzahl Räume 0,6<Deckungsgrad<0,8",
  "B67":  /* unknown */ 0.6,
  "C67":  /* unknown */ 0.8,
  "G67":  /* formula */ "COUNTIFS(G39:AA39,\">=0,6\",G39:AA39,\"<0,8\")",
  "A68":  /* unknown */ "Anzahl Räume Deckungsgrad < 1",
  "C68":  /* unknown */ 1,
  "G68":  /* formula */ "COUNTIF($G$39:$AA$39,\"<1\")",
  "A69":  /* unknown */ "Anzahl Räume 0,8<Deckungsgrad<1,0",
  "B69":  /* unknown */ 0.8,
  "C69":  /* unknown */ 1,
  "G69":  /* formula */ "COUNTIFS(G39:AA39,\">=0,8\",G39:AA39,\"<1\")",
  "A70":  /* unknown */ "Anzahl Räume Deckungsgrad > 1",
  "B70":  /* unknown */ 1,
  "G70":  /* formula */ "COUNTIFS(G39:AA39,\">=1\")",
  "A71":  /* unknown */ "Anzahl Räume Deckungsgrad Typ 33 < 1 ",
  "C71":  /* unknown */ 1,
  "G71":  /* formula */ "COUNTIF(G40:AA40,\"<1\")",
  "A72":  /* unknown */ "Anzahl Räume Deckungsgrad Typ 33 > 1",
  "B72":  /* unknown */ 1,
  "G72":  /* formula */ "COUNTIF(G40:AA40,\">=1\")",
  "A73":  /* unknown */ "Anteil Räume Deckungsgrad < 0,6",
  "G73":  /* formula */ "G65/$G$49",
  "A74":  /* unknown */ "Anteil Räume Deckungsgrad < 0,8",
  "G74":  /* formula */ "G66/$G$49",
  "A75":  /* unknown */ "Anteil Räume 0,6<Deckungsgrad<0,8",
  "G75":  /* formula */ "G67/$G$49",
  "A76":  /* unknown */ "Anteil Räume Deckungsgrad < 1",
  "G76":  /* formula */ "G68/$G$49",
  "A77":  /* unknown */ "Anteil Räume 0,8<Deckungsgrad<1",
  "G77":  /* formula */ "G69/$G$49",
  "A78":  /* unknown */ "Anteil Räume Deckungsgrad>1",
  "G78":  /* formula */ "G70/$G$49",
  "A79":  /* unknown */ "Anteil Räume Deckungsgrad Typ 33 < 1 ",
  "G79":  /* formula */ "G71/$G$49",
  "A80":  /* unknown */ "Anteil Räume Deckungsgrad Typ 33 > 1",
  "G80":  /* formula */ "G72/$G$49",
  "A82":  /* unknown */ "Bewertung spez. Heizlast ",
  "A83":  /* unknown */ "Anteil Räume < 50 W/m²",
  "G83":  /* formula */ "COUNTIF($G$8:$AA$8,\"<50\")/$G$49",
  "A84":  /* unknown */ "Anteil Räume < 70 W/m²",
  "G84":  /* formula */ "COUNTIF($G$8:$AA$8,\"<70\")/$G$49",
  "A85":  /* unknown */ "Anteil Räume 50-70 W/m²",
  "G85":  /* formula */ "COUNTIFS($G$8:$AA$8,\">=50\",$G$8:$AA$8,\"<70\")/$G$49",
  "A86":  /* unknown */ "Anteil Räume < 90 W/m²",
  "G86":  /* formula */ "COUNTIF($G$8:$AA$8,\"<90\")/$G$49",
  "A87":  /* unknown */ "Anteil Räume 70-90 W/m²",
  "G87":  /* formula */ "COUNTIFS($G$8:$AA$8,\">=70\",$G$8:$AA$8,\"<90\")/$G$49",
  "A88":  /* unknown */ "Anteil Räume > 90 W/m²",
  "G88":  /* formula */ "COUNTIF($G$8:$AA$8,\">=90\")/$G$49",
} as const;
