// Sheet: Frontend_Räume_OLD
// Generated on: 2025-05-10T13:08:38.977Z

export const data: Record<string, any> = {
  "A1":  /* unknown */ "Bauteil (ifeu intern) ",
  "K1":  /* unknown */ "Decke",
  "L1":  /* unknown */ "Fußboden",
  "M1":  /* unknown */ "Außenwand",
  "N1":  /* unknown */ "Außenwand 1",
  "O1":  /* unknown */ "Außenwand",
  "P1":  /* unknown */ "Außenwand Art",
  "Q1":  /* unknown */ "Außenwand 2",
  "R1":  /* unknown */ "Außenwand 2",
  "S1":  /* unknown */ "Außenwand 2",
  "T1":  /* unknown */ "Außenwand Art",
  "U1":  /* unknown */ "Außenwand 3",
  "V1":  /* unknown */ "Außenwand 3",
  "W1":  /* unknown */ "Außenwand 3",
  "X1":  /* unknown */ "Außenwand Art",
  "Y1":  /* unknown */ "Außenwand 4",
  "Z1":  /* unknown */ "Außenwand 4",
  "AA1":  /* unknown */ "Außenwand 4",
  "AB1":  /* unknown */ "Außenwand Art",
  "AC1":  /* unknown */ "Dachfläche",
  "AD1":  /* unknown */ "Dachfläche",
  "AE1":  /* unknown */ "Dachfläche",
  "AF1":  /* unknown */ "Dachfläche",
  "AG1":  /* unknown */ "Dachfläche",
  "AH1":  /* unknown */ "Dachfläche",
  "AI1":  /* unknown */ "Dachfläche 2",
  "AJ1":  /* unknown */ "Dachfläche 2",
  "AK1":  /* unknown */ "Dachfläche 2",
  "AL1":  /* unknown */ "Dachfläche 3",
  "AM1":  /* unknown */ "Dachfläche 3",
  "AN1":  /* unknown */ "Dachfläche 3",
  "AO1":  /* unknown */ "Decke",
  "AP1":  /* unknown */ "Decke",
  "AQ1":  /* unknown */ "Decke",
  "AR1":  /* unknown */ "Fußboden",
  "AS1":  /* unknown */ "Fußboden",
  "AT1":  /* unknown */ "Fußboden",
  "AU1":  /* unknown */ "Fenster 1 in Außenwand",
  "AV1":  /* unknown */ "Fenster 1 in Außenwand",
  "AW1":  /* unknown */ "Fenster 1 in Außenwand",
  "AX1":  /* unknown */ "Fenster 1 in Außenwand",
  "AY1":  /* unknown */ "Fenster 2 in Außenwand",
  "AZ1":  /* unknown */ "Fenster 2 in Außenwand",
  "BA1":  /* unknown */ "Fenster 2 in Außenwand",
  "BB1":  /* unknown */ "Fenster 2 in Außenwand",
  "BC1":  /* unknown */ "Fenster 3 in Außenwand 1",
  "BD1":  /* unknown */ "Fenster 3 in Außenwand 1",
  "BE1":  /* unknown */ "Fenster 3 in Außenwand 1",
  "BF1":  /* unknown */ "Fenster 3 in Außenwand",
  "BG1":  /* unknown */ "Fenster 4 in Außenwand 1",
  "BH1":  /* unknown */ "Fenster 4 in Außenwand 1",
  "BI1":  /* unknown */ "Fenster 4 in Außenwand 1",
  "BJ1":  /* unknown */ "Fenster 1 in Außenwand 2",
  "BK1":  /* unknown */ "Fenster 1 in Außenwand 2",
  "BL1":  /* unknown */ "Fenster 1 in Außenwand 2",
  "BM1":  /* unknown */ "Fenster 2 in Außenwand 2",
  "BN1":  /* unknown */ "Fenster 2 in Außenwand 2",
  "BO1":  /* unknown */ "Fenster 2 in Außenwand 2",
  "BP1":  /* unknown */ "Fenster 3 in Außenwand 2",
  "BQ1":  /* unknown */ "Fenster 3 in Außenwand 2",
  "BR1":  /* unknown */ "Fenster 3 in Außenwand 2",
  "BS1":  /* unknown */ "Fenster 4 in Außenwand 2",
  "BT1":  /* unknown */ "Fenster 4 in Außenwand 2",
  "BU1":  /* unknown */ "Fenster 4 in Außenwand 2",
  "BV1":  /* unknown */ "Fenster 1 in Außenwand 3",
  "BW1":  /* unknown */ "Fenster 1 in Außenwand 3",
  "BX1":  /* unknown */ "Fenster 1 in Außenwand 3",
  "BY1":  /* unknown */ "Fenster 2 in Außenwand 3",
  "BZ1":  /* unknown */ "Fenster 2 in Außenwand 3",
  "CA1":  /* unknown */ "Fenster 2 in Außenwand 3",
  "CB1":  /* unknown */ "Fenster 3 in Außenwand 3",
  "CC1":  /* unknown */ "Fenster 3 in Außenwand 3",
  "CD1":  /* unknown */ "Fenster 3 in Außenwand 3",
  "CE1":  /* unknown */ "Fenster 4 in Außenwand 3",
  "CF1":  /* unknown */ "Fenster 4 in Außenwand 3",
  "CG1":  /* unknown */ "Fenster 4 in Außenwand 3",
  "CH1":  /* unknown */ "Fenster 1 in Außenwand 4",
  "CI1":  /* unknown */ "Fenster 1 in Außenwand 4",
  "CJ1":  /* unknown */ "Fenster 1 in Außenwand 4",
  "CK1":  /* unknown */ "Fenster 2 in Außenwand 4",
  "CL1":  /* unknown */ "Fenster 2 in Außenwand 4",
  "CM1":  /* unknown */ "Fenster 2 in Außenwand 4",
  "CN1":  /* unknown */ "Fenster 3 in Außenwand 4",
  "CO1":  /* unknown */ "Fenster 3 in Außenwand 4",
  "CP1":  /* unknown */ "Fenster 3 in Außenwand 4",
  "CQ1":  /* unknown */ "Fenster 4 in Außenwand 4",
  "CR1":  /* unknown */ "Fenster 4 in Außenwand 4",
  "CS1":  /* unknown */ "Fenster 4 in Außenwand 4",
  "CT1":  /* unknown */ "Fenster 1 in Dachfläche 1",
  "CU1":  /* unknown */ "Fenster 1 in Dachfläche 1",
  "CV1":  /* unknown */ "Fenster 1 in Dachfläche 1",
  "CW1":  /* unknown */ "Fenster 2 in Dachfläche 1",
  "CX1":  /* unknown */ "Fenster 2 in Dachfläche 1",
  "CY1":  /* unknown */ "Fenster 2 in Dachfläche 1",
  "CZ1":  /* unknown */ "Fenster 3 in Dachfläche 1",
  "DA1":  /* unknown */ "Fenster 3 in Dachfläche 1",
  "DB1":  /* unknown */ "Fenster 3 in Dachfläche 1",
  "DC1":  /* unknown */ "Fenster 1 in Dachfläche 2",
  "DD1":  /* unknown */ "Fenster 1 in Dachfläche 2",
  "DE1":  /* unknown */ "Fenster 1 in Dachfläche 2",
  "DF1":  /* unknown */ "Fenster 2 in Dachfläche 2",
  "DG1":  /* unknown */ "Fenster 2 in Dachfläche 2",
  "DH1":  /* unknown */ "Fenster 2 in Dachfläche 2",
  "DI1":  /* unknown */ "Fenster 3 in Dachfläche 2",
  "DJ1":  /* unknown */ "Fenster 3 in Dachfläche 2",
  "DK1":  /* unknown */ "Fenster 3 in Dachfläche 2",
  "DL1":  /* unknown */ "Fenster 1 in Dachfläche 3",
  "DM1":  /* unknown */ "Fenster 1 in Dachfläche 3",
  "DN1":  /* unknown */ "Fenster 1 in Dachfläche 3",
  "DO1":  /* unknown */ "Fenster 2 in Dachfläche 3",
  "DP1":  /* unknown */ "Fenster 2 in Dachfläche 3",
  "DQ1":  /* unknown */ "Fenster 2 in Dachfläche 3",
  "DR1":  /* unknown */ "Fenster 3 in Dachfläche 3",
  "DS1":  /* unknown */ "Fenster 3 in Dachfläche 3",
  "DT1":  /* unknown */ "Fenster 3 in Dachfläche 3",
  "DU1":  /* unknown */ "Heizkörper 1 im Raum 1",
  "DV1":  /* unknown */ "Heizkörper 1 im Raum 1",
  "DW1":  /* unknown */ "Heizkörper 1 im Raum 1",
  "DX1":  /* unknown */ "Heizkörper 1 im Raum 1",
  "DY1":  /* unknown */ "Heizkörper 1 im Raum 1",
  "DZ1":  /* unknown */ "Heizkörper 1 im Raum 1",
  "EA1":  /* unknown */ "Heizkörper 1 im Raum 1",
  "EB1":  /* unknown */ "Heizkörper 2 im Raum 1",
  "EC1":  /* unknown */ "Heizkörper 2 im Raum 1",
  "ED1":  /* unknown */ "Heizkörper 2 im Raum 1",
  "EE1":  /* unknown */ "Heizkörper 2 im Raum 1",
  "EF1":  /* unknown */ "Heizkörper 2 im Raum 1",
  "EG1":  /* unknown */ "Heizkörper 2 im Raum 1",
  "EH1":  /* unknown */ "Heizkörper 2 im Raum 1",
  "EI1":  /* unknown */ "Heizkörper 3 im Raum 1",
  "EJ1":  /* unknown */ "Heizkörper 3 im Raum 1",
  "EK1":  /* unknown */ "Heizkörper 3 im Raum 1",
  "EL1":  /* unknown */ "Heizkörper 3 im Raum 1",
  "EM1":  /* unknown */ "Heizkörper 3 im Raum 1",
  "EN1":  /* unknown */ "Heizkörper 3 im Raum 1",
  "EO1":  /* unknown */ "Heizkörper 3 im Raum 1",
  "EP1":  /* unknown */ "Heizkörper 4 im Raum 1",
  "EQ1":  /* unknown */ "Heizkörper 4 im Raum 1",
  "ER1":  /* unknown */ "Heizkörper 4 im Raum 1",
  "ES1":  /* unknown */ "Heizkörper 4 im Raum 1",
  "ET1":  /* unknown */ "Heizkörper 4 im Raum 1",
  "EU1":  /* unknown */ "Heizkörper 4 im Raum 1",
  "EV1":  /* unknown */ "Heizkörper 4 im Raum 1",
  "EW1":  /* unknown */ "Heizkörper 5 im Raum 1",
  "EX1":  /* unknown */ "Heizkörper 5 im Raum 1",
  "EY1":  /* unknown */ "Heizkörper 5 im Raum 1",
  "EZ1":  /* unknown */ "Heizkörper 5 im Raum 1",
  "FA1":  /* unknown */ "Heizkörper 5 im Raum 1",
  "FB1":  /* unknown */ "Heizkörper 5 im Raum 1",
  "FC1":  /* unknown */ "Heizkörper 5 im Raum 1",
  "A2":  /* unknown */ "Frage (ifeu intern)",
  "B2":  /* unknown */ "Raumindex",
  "C2":  /* unknown */ "Raumbezeichnung",
  "D2":  /* unknown */ "Hat der Raum eine rechteckige Grundfläche?",
  "E2":  /* unknown */ "Länge",
  "F2":  /* unknown */ "Breite",
  "G2":  /* unknown */ "Wohnfläche",
  "H2":  /* unknown */ "Raumhöhe",
  "I2":  /* unknown */ "Gewünschte Raumtemperatur",
  "J2":  /* unknown */ "Norm-Innentemperatur",
  "K2":  /* unknown */ "Grenzt an",
  "L2":  /* unknown */ "Grenzt an",
  "M2":  /* unknown */ "Länge",
  "N2":  /* unknown */ "Höhe",
  "O2":  /* unknown */ "Von Gebäude abweichende Dämmschicht? ",
  "P2":  /* unknown */ "Grenzt an",
  "Q2":  /* unknown */ "Länge",
  "R2":  /* unknown */ "Höhe",
  "S2":  /* unknown */ "Von Gebäude abweichende Dämmschicht? ",
  "T2":  /* unknown */ "Grenzt an",
  "U2":  /* unknown */ "Länge",
  "V2":  /* unknown */ "Höhe",
  "W2":  /* unknown */ "Von Gebäude abweichende Dämmschicht? ",
  "X2":  /* unknown */ "Grenzt an",
  "Y2":  /* unknown */ "Länge",
  "Z2":  /* unknown */ "Höhe",
  "AA2":  /* unknown */ "Von Gebäude abweichende Dämmschicht? ",
  "AB2":  /* unknown */ "Grenzt an",
  "AD2":  /* unknown */ "Breite ",
  "AE2":  /* unknown */ "Höhe",
  "AF2":  /* unknown */ "Von Gebäude abweichende Dämmschicht? ",
  "AI2":  /* unknown */ "Länge",
  "AJ2":  /* unknown */ "Breite",
  "AK2":  /* unknown */ "Von Gebäude abweichende Dämmschicht? ",
  "AL2":  /* unknown */ "Länge",
  "AM2":  /* unknown */ "Breite",
  "AN2":  /* unknown */ "Von Gebäude abweichende Dämmschicht? ",
  "AO2":  /* unknown */ "Länge",
  "AP2":  /* unknown */ "Breite",
  "AQ2":  /* unknown */ "Von Gebäude abweichende Dämmschicht? ",
  "AR2":  /* unknown */ "Länge",
  "AS2":  /* unknown */ "Breite",
  "AT2":  /* unknown */ "Von Gebäude abweichende Dämmschicht? ",
  "AU2":  /* unknown */ "Breite",
  "AV2":  /* unknown */ "Höhe ",
  "AW2":  /* unknown */ "Jahr, in dem die Fenster zuletzt ausgetauscht wurden",
  "AX2":  /* unknown */ "Anzahl",
  "AY2":  /* unknown */ "Breite",
  "AZ2":  /* unknown */ "Höhe ",
  "BA2":  /* unknown */ "Jahr, in dem die Fenster zuletzt ausgetauscht wurden",
  "BC2":  /* unknown */ "Breite",
  "BD2":  /* unknown */ "Höhe ",
  "BE2":  /* unknown */ "Jahr, in dem die Fenster zuletzt ausgetauscht wurden",
  "BF2":  /* unknown */ "Anzahl",
  "BG2":  /* unknown */ "Breite",
  "BH2":  /* unknown */ "Höhe ",
  "BI2":  /* unknown */ "Jahr, in dem die Fenster zuletzt ausgetauscht wurden",
  "BJ2":  /* unknown */ "Breite",
  "BK2":  /* unknown */ "Höhe ",
  "BL2":  /* unknown */ "Jahr, in dem die Fenster zuletzt ausgetauscht wurden",
  "BM2":  /* unknown */ "Breite",
  "BN2":  /* unknown */ "Höhe ",
  "BO2":  /* unknown */ "Jahr, in dem die Fenster zuletzt ausgetauscht wurden",
  "BP2":  /* unknown */ "Breite",
  "BQ2":  /* unknown */ "Höhe ",
  "BR2":  /* unknown */ "Jahr, in dem die Fenster zuletzt ausgetauscht wurden",
  "BS2":  /* unknown */ "Breite",
  "BT2":  /* unknown */ "Höhe ",
  "BU2":  /* unknown */ "Jahr, in dem die Fenster zuletzt ausgetauscht wurden",
  "BV2":  /* unknown */ "Breite",
  "BW2":  /* unknown */ "Höhe ",
  "BX2":  /* unknown */ "Jahr, in dem die Fenster zuletzt ausgetauscht wurden",
  "BY2":  /* unknown */ "Breite",
  "BZ2":  /* unknown */ "Höhe ",
  "CA2":  /* unknown */ "Jahr, in dem die Fenster zuletzt ausgetauscht wurden",
  "CB2":  /* unknown */ "Breite",
  "CC2":  /* unknown */ "Höhe ",
  "CD2":  /* unknown */ "Jahr, in dem die Fenster zuletzt ausgetauscht wurden",
  "CE2":  /* unknown */ "Breite",
  "CF2":  /* unknown */ "Höhe ",
  "CG2":  /* unknown */ "Jahr, in dem die Fenster zuletzt ausgetauscht wurden",
  "CH2":  /* unknown */ "Breite",
  "CI2":  /* unknown */ "Höhe ",
  "CJ2":  /* unknown */ "Jahr, in dem die Fenster zuletzt ausgetauscht wurden",
  "CK2":  /* unknown */ "Breite",
  "CL2":  /* unknown */ "Höhe ",
  "CM2":  /* unknown */ "Jahr, in dem die Fenster zuletzt ausgetauscht wurden",
  "CN2":  /* unknown */ "Breite",
  "CO2":  /* unknown */ "Höhe ",
  "CP2":  /* unknown */ "Jahr, in dem die Fenster zuletzt ausgetauscht wurden",
  "CQ2":  /* unknown */ "Breite",
  "CR2":  /* unknown */ "Höhe ",
  "CS2":  /* unknown */ "Jahr, in dem die Fenster zuletzt ausgetauscht wurden",
  "CT2":  /* unknown */ "Breite",
  "CU2":  /* unknown */ "Höhe ",
  "CV2":  /* unknown */ "Jahr, in dem die Fenster zuletzt ausgetauscht wurden",
  "CW2":  /* unknown */ "Breite",
  "CX2":  /* unknown */ "Höhe ",
  "CY2":  /* unknown */ "Jahr, in dem die Fenster zuletzt ausgetauscht wurden",
  "CZ2":  /* unknown */ "Breite",
  "DA2":  /* unknown */ "Höhe ",
  "DB2":  /* unknown */ "Jahr, in dem die Fenster zuletzt ausgetauscht wurden",
  "DC2":  /* unknown */ "Breite",
  "DD2":  /* unknown */ "Höhe ",
  "DE2":  /* unknown */ "Jahr, in dem die Fenster zuletzt ausgetauscht wurden",
  "DF2":  /* unknown */ "Breite",
  "DG2":  /* unknown */ "Höhe ",
  "DH2":  /* unknown */ "Jahr, in dem die Fenster zuletzt ausgetauscht wurden",
  "DI2":  /* unknown */ "Breite",
  "DJ2":  /* unknown */ "Höhe ",
  "DK2":  /* unknown */ "Jahr, in dem die Fenster zuletzt ausgetauscht wurden",
  "DL2":  /* unknown */ "Breite",
  "DM2":  /* unknown */ "Höhe ",
  "DN2":  /* unknown */ "Jahr, in dem die Fenster zuletzt ausgetauscht wurden",
  "DO2":  /* unknown */ "Breite",
  "DP2":  /* unknown */ "Höhe ",
  "DQ2":  /* unknown */ "Jahr, in dem die Fenster zuletzt ausgetauscht wurden",
  "DR2":  /* unknown */ "Breite",
  "DS2":  /* unknown */ "Höhe ",
  "DT2":  /* unknown */ "Jahr, in dem die Fenster zuletzt ausgetauscht wurden",
  "DU2":  /* unknown */ "Typ",
  "DV2":  /* unknown */ "Subtyp",
  "DW2":  /* unknown */ "Subtyp 2",
  "DX2":  /* unknown */ "Höhe",
  "DY2":  /* unknown */ "Breite",
  "DZ2":  /* unknown */ "Tiefe",
  "EA2":  /* unknown */ "Anzahl Glieder",
  "EB2":  /* unknown */ "Typ",
  "EC2":  /* unknown */ "Subtyp",
  "ED2":  /* unknown */ "Subtyp 2",
  "EE2":  /* unknown */ "Höhe",
  "EF2":  /* unknown */ "Breite",
  "EG2":  /* unknown */ "Tiefe",
  "EH2":  /* unknown */ "Anzahl Glieder",
  "EI2":  /* unknown */ "Typ",
  "EJ2":  /* unknown */ "Subtyp",
  "EK2":  /* unknown */ "Subtyp 2",
  "EL2":  /* unknown */ "Höhe",
  "EM2":  /* unknown */ "Breite",
  "EN2":  /* unknown */ "Tiefe",
  "EO2":  /* unknown */ "Anzahl Glieder",
  "EP2":  /* unknown */ "Typ",
  "EQ2":  /* unknown */ "Subtyp",
  "ER2":  /* unknown */ "Subtyp 2",
  "ES2":  /* unknown */ "Höhe",
  "ET2":  /* unknown */ "Breite",
  "EU2":  /* unknown */ "Tiefe",
  "EV2":  /* unknown */ "Anzahl Glieder",
  "EW2":  /* unknown */ "Typ",
  "EX2":  /* unknown */ "Subtyp",
  "EY2":  /* unknown */ "Subtyp 2",
  "EZ2":  /* unknown */ "Höhe",
  "FA2":  /* unknown */ "Breite",
  "FB2":  /* unknown */ "Tiefe",
  "FC2":  /* unknown */ "Anzahl Glieder",
  "A3":  /* unknown */ "Gruppe ",
  "K3":  /* unknown */ "ceiling1",
  "L3":  /* unknown */ "floor",
  "M3":  /* unknown */ "wall",
  "N3":  /* unknown */ "wall",
  "O3":  /* unknown */ "wall",
  "Q3":  /* unknown */ "wall2",
  "R3":  /* unknown */ "wall2",
  "S3":  /* unknown */ "wall2",
  "U3":  /* unknown */ "wall3",
  "V3":  /* unknown */ "wall3",
  "W3":  /* unknown */ "wall3",
  "Y3":  /* unknown */ "wall4",
  "Z3":  /* unknown */ "wall4",
  "AA3":  /* unknown */ "wall4",
  "AC3":  /* unknown */ "roof",
  "AD3":  /* unknown */ "roof",
  "AE3":  /* unknown */ "roof",
  "AF3":  /* unknown */ "roof",
  "AG3":  /* unknown */ "roof",
  "AH3":  /* unknown */ "roof",
  "AI3":  /* unknown */ "roof1",
  "AJ3":  /* unknown */ "roof1",
  "AK3":  /* unknown */ "roof1",
  "AL3":  /* unknown */ "roof1",
  "AM3":  /* unknown */ "roof1",
  "AN3":  /* unknown */ "roof1",
  "AO3":  /* unknown */ "ceiling1",
  "AP3":  /* unknown */ "ceiling1",
  "AQ3":  /* unknown */ "ceiling1",
  "AR3":  /* unknown */ "floor",
  "AS3":  /* unknown */ "floor",
  "AT3":  /* unknown */ "floor",
  "AU3":  /* unknown */ "wall",
  "AV3":  /* unknown */ "wall",
  "AW3":  /* unknown */ "wall",
  "AX3":  /* unknown */ "wall",
  "AY3":  /* unknown */ "wall",
  "AZ3":  /* unknown */ "wall",
  "BA3":  /* unknown */ "wall",
  "BB3":  /* unknown */ "wall",
  "BC3":  /* unknown */ "wall",
  "BD3":  /* unknown */ "wall",
  "BE3":  /* unknown */ "wall",
  "BF3":  /* unknown */ "wall",
  "BG3":  /* unknown */ "wall1",
  "BH3":  /* unknown */ "wall1",
  "BI3":  /* unknown */ "wall1",
  "BJ3":  /* unknown */ "wall2",
  "BK3":  /* unknown */ "wall2",
  "BL3":  /* unknown */ "wall2",
  "BM3":  /* unknown */ "wall2",
  "BN3":  /* unknown */ "wall2",
  "BO3":  /* unknown */ "wall2",
  "BP3":  /* unknown */ "wall2",
  "BQ3":  /* unknown */ "wall2",
  "BR3":  /* unknown */ "wall2",
  "BS3":  /* unknown */ "wall2",
  "BT3":  /* unknown */ "wall2",
  "BU3":  /* unknown */ "wall2",
  "BV3":  /* unknown */ "wall3",
  "BW3":  /* unknown */ "wall3",
  "BX3":  /* unknown */ "wall3",
  "BY3":  /* unknown */ "wall3",
  "BZ3":  /* unknown */ "wall3",
  "CA3":  /* unknown */ "wall3",
  "CB3":  /* unknown */ "wall3",
  "CC3":  /* unknown */ "wall3",
  "CD3":  /* unknown */ "wall3",
  "CE3":  /* unknown */ "wall3",
  "CF3":  /* unknown */ "wall3",
  "CG3":  /* unknown */ "wall3",
  "CH3":  /* unknown */ "wall4",
  "CI3":  /* unknown */ "wall4",
  "CJ3":  /* unknown */ "wall4",
  "CK3":  /* unknown */ "wall4",
  "CL3":  /* unknown */ "wall4",
  "CM3":  /* unknown */ "wall4",
  "CN3":  /* unknown */ "wall4",
  "CO3":  /* unknown */ "wall4",
  "CP3":  /* unknown */ "wall4",
  "CQ3":  /* unknown */ "wall4",
  "CR3":  /* unknown */ "wall4",
  "CS3":  /* unknown */ "wall4",
  "A4":  /* unknown */ "Subgruppe",
  "AU4":  /* unknown */ "win1",
  "AV4":  /* unknown */ "win1",
  "AW4":  /* unknown */ "win1",
  "AX4":  /* unknown */ "win1",
  "AY4":  /* unknown */ "win2",
  "AZ4":  /* unknown */ "win2",
  "BA4":  /* unknown */ "win2",
  "BB4":  /* unknown */ "win2",
  "BC4":  /* unknown */ "win3",
  "BD4":  /* unknown */ "win3",
  "BE4":  /* unknown */ "win3",
  "BF4":  /* unknown */ "win3",
  "BG4":  /* unknown */ "win4",
  "BH4":  /* unknown */ "win4",
  "BI4":  /* unknown */ "win4",
  "BJ4":  /* unknown */ "win1",
  "BK4":  /* unknown */ "win1",
  "BL4":  /* unknown */ "win1",
  "BM4":  /* unknown */ "win2",
  "BN4":  /* unknown */ "win2",
  "BO4":  /* unknown */ "win2",
  "BP4":  /* unknown */ "win3",
  "BQ4":  /* unknown */ "win3",
  "BR4":  /* unknown */ "win3",
  "BS4":  /* unknown */ "win4",
  "BT4":  /* unknown */ "win4",
  "BU4":  /* unknown */ "win4",
  "BV4":  /* unknown */ "win1",
  "BW4":  /* unknown */ "win1",
  "BX4":  /* unknown */ "win1",
  "BY4":  /* unknown */ "win2",
  "BZ4":  /* unknown */ "win2",
  "CA4":  /* unknown */ "win2",
  "CB4":  /* unknown */ "win3",
  "CC4":  /* unknown */ "win3",
  "CD4":  /* unknown */ "win3",
  "CE4":  /* unknown */ "win4",
  "CF4":  /* unknown */ "win4",
  "CG4":  /* unknown */ "win4",
  "CH4":  /* unknown */ "win1",
  "CI4":  /* unknown */ "win1",
  "CJ4":  /* unknown */ "win1",
  "CK4":  /* unknown */ "win2",
  "CL4":  /* unknown */ "win2",
  "CM4":  /* unknown */ "win2",
  "CN4":  /* unknown */ "win3",
  "CO4":  /* unknown */ "win3",
  "CP4":  /* unknown */ "win3",
  "CQ4":  /* unknown */ "win4",
  "CR4":  /* unknown */ "win4",
  "CS4":  /* unknown */ "win4",
  "A5":  /* unknown */ "Fragentext ",
  "C5":  /* unknown */ "Geben Sie den Raum einen Namen",
  "G5":  /* unknown */ "Raumfläche",
  "H5":  /* unknown */ "Raumhöhe",
  "I5":  /* unknown */ "gewünsche Raumtemperatur",
  "K5":  /* unknown */ "Decke grenzt an",
  "L5":  /* unknown */ "Fußboden grenzt an",
  "M5":  /* unknown */ "Gesamtlänge der Außenwände",
  "O5":  /* unknown */ "Modernisierungsjahr",
  "AC5":  /* unknown */ "Dachfläche vorhanden? ",
  "AD5":  /* unknown */ "Breite ",
  "AE5":  /* unknown */ "Höhe ",
  "AF5":  /* unknown */ "Modernisierungsjahr",
  "AG5":  /* unknown */ "Falls ein Kniestock vorhanden ist, geben Sie dessen Höhe an",
  "AH5":  /* unknown */ "Falls eine Dachgaube vorhanden ist, geben Sie die Länge an",
  "AU5":  /* unknown */ "Geben Sie die Abmaße des ersten Fenstertyps an, Breite",
  "AV5":  /* unknown */ "Höhe ",
  "AW5":  /* unknown */ "Abweichendes Einbaujahr ",
  "AX5":  /* unknown */ "Anzahl identischer Fenster im Raum ",
  "AY5":  /* unknown */ "Geben Sie die Abmaße des ersten Fenstertyps an, Breite",
  "AZ5":  /* unknown */ "Höhe ",
  "BA5":  /* unknown */ "Abweichendes Einbaujahr ",
  "BB5":  /* unknown */ "Anzahl identischer Fenster im Raum ",
  "BC5":  /* unknown */ "Geben Sie die Abmaße des ersten Fenstertyps an, Breite",
  "BD5":  /* unknown */ "Höhe ",
  "BE5":  /* unknown */ "Abweichendes Einbaujahr ",
  "BF5":  /* unknown */ "Anzahl identischer Fenster im Raum ",
  "A6":  /* unknown */ "Hilfstext",
  "AD6":  /* unknown */ "Bei mehreren Dachflächen bitte summieren",
  "AE6":  /* unknown */ "Bei mehreren Dachflächen bitte nicht summieren",
  "AG6":  /* unknown */ "Der Kniestock oder Drempel beschreibt im Dachbereich die Höhe der Wand zwischen Fußboden und Beginn des Dachs. ",
  "A7":  /* unknown */ "Antworttyp",
  "B7":  /* unknown */ "Intern",
  "C7":  /* unknown */ "Freitext",
  "D7":  /* unknown */ "Radio Button ",
  "E7":  /* unknown */ "Freitext Real",
  "F7":  /* unknown */ "Freitext Real",
  "G7":  /* unknown */ "Freitext",
  "H7":  /* unknown */ "Freitext ",
  "I7":  /* unknown */ "Freitext ",
  "J7":  /* unknown */ "Intern",
  "K7":  /* unknown */ "Dropdown",
  "L7":  /* unknown */ "Dropdown",
  "M7":  /* unknown */ "Freitext ",
  "N7":  /* unknown */ "Freitext",
  "O7":  /* unknown */ "Dropdown",
  "Q7":  /* unknown */ "Freitext",
  "R7":  /* unknown */ "Freitext",
  "S7":  /* unknown */ "Freitext",
  "U7":  /* unknown */ "Freitext",
  "V7":  /* unknown */ "Freitext",
  "W7":  /* unknown */ "Freitext",
  "Y7":  /* unknown */ "Freitext",
  "Z7":  /* unknown */ "Freitext",
  "AA7":  /* unknown */ "Freitext",
  "AC7":  /* unknown */ "toggle switch ",
  "AD7":  /* unknown */ "Freitext",
  "AE7":  /* unknown */ "Freitext",
  "AF7":  /* unknown */ "Dropdown",
  "AG7":  /* unknown */ "Freitext",
  "AH7":  /* unknown */ "Freitext",
  "AI7":  /* unknown */ "Freitext",
  "AJ7":  /* unknown */ "Freitext",
  "AK7":  /* unknown */ "Freitext",
  "AL7":  /* unknown */ "Freitext",
  "AM7":  /* unknown */ "Freitext",
  "AN7":  /* unknown */ "Freitext",
  "AO7":  /* unknown */ "Freitext",
  "AP7":  /* unknown */ "Freitext",
  "AQ7":  /* unknown */ "Freitext",
  "AR7":  /* unknown */ "Freitext",
  "AS7":  /* unknown */ "Freitext",
  "AT7":  /* unknown */ "Freitext",
  "AU7":  /* unknown */ "Freitext",
  "AV7":  /* unknown */ "Freitext",
  "AW7":  /* unknown */ "Dropdown",
  "AX7":  /* unknown */ "Freitext",
  "AY7":  /* unknown */ "Freitext",
  "AZ7":  /* unknown */ "Freitext",
  "BA7":  /* unknown */ "Dropdown",
  "BB7":  /* unknown */ "Freitext",
  "BC7":  /* unknown */ "Freitext",
  "BD7":  /* unknown */ "Freitext",
  "BE7":  /* unknown */ "Dropdown",
  "BF7":  /* unknown */ "Freitext",
  "A8":  /* unknown */ "Filter ",
  "E8":  /* unknown */ "B_R#_floor_rect=True",
  "F8":  /* unknown */ "B_R#_floor_rect=True",
  "AD8":  /* unknown */ "B_roof_exist",
  "AE8":  /* unknown */ "B_roof_exist",
  "AF8":  /* unknown */ "B_roof_exist",
  "AG8":  /* unknown */ "B_roof_exist",
  "AH8":  /* unknown */ "B_roof_exist",
  "AR8":  /* unknown */ "wenn TYP_R#_floor=unbeheizt/Erdreich oder TYP_R#_floor=teils-teils",
  "AS8":  /* unknown */ "wenn TYP_R#_floor=unbeheizt/Erdreich oder TYP_R#_floor=teils-teils",
  "AT8":  /* unknown */ "wenn TYP_R#_floor=Außenluft oder TYP_R#_floor=teils-teils",
  "A9":  /* unknown */ "Einheit ",
  "G9":  /* unknown */ "m²",
  "H9":  /* unknown */ "m",
  "I9":  /* unknown */ "°C",
  "M9":  /* unknown */ "m",
  "N9":  /* unknown */ "m",
  "Q9":  /* unknown */ "m",
  "R9":  /* unknown */ "m",
  "S9":  /* unknown */ "cm",
  "U9":  /* unknown */ "m",
  "V9":  /* unknown */ "m",
  "W9":  /* unknown */ "cm",
  "Y9":  /* unknown */ "m",
  "Z9":  /* unknown */ "m",
  "AA9":  /* unknown */ "cm",
  "AD9":  /* unknown */ "m",
  "AE9":  /* unknown */ "m",
  "AG9":  /* unknown */ "m",
  "AH9":  /* unknown */ "m",
  "AI9":  /* unknown */ "m",
  "AJ9":  /* unknown */ "m",
  "AK9":  /* unknown */ "cm",
  "AL9":  /* unknown */ "m",
  "AM9":  /* unknown */ "m",
  "AN9":  /* unknown */ "cm",
  "AO9":  /* unknown */ "m",
  "AP9":  /* unknown */ "m",
  "AQ9":  /* unknown */ "cm",
  "AR9":  /* unknown */ "m",
  "AS9":  /* unknown */ "m",
  "AT9":  /* unknown */ "cm",
  "AU9":  /* unknown */ "cm",
  "AV9":  /* unknown */ "cm",
  "AY9":  /* unknown */ "cm",
  "AZ9":  /* unknown */ "cm",
  "BC9":  /* unknown */ "cm",
  "BD9":  /* unknown */ "cm",
  "BH9":  /* unknown */ "cm",
  "BI9":  /* unknown */ "cm",
  "BK9":  /* unknown */ "cm",
  "BL9":  /* unknown */ "cm",
  "BN9":  /* unknown */ "cm",
  "BO9":  /* unknown */ "cm",
  "BQ9":  /* unknown */ "cm",
  "BR9":  /* unknown */ "cm",
  "BT9":  /* unknown */ "cm",
  "BU9":  /* unknown */ "cm",
  "BW9":  /* unknown */ "cm",
  "BX9":  /* unknown */ "cm",
  "BZ9":  /* unknown */ "cm",
  "CA9":  /* unknown */ "cm",
  "CC9":  /* unknown */ "cm",
  "CD9":  /* unknown */ "cm",
  "CF9":  /* unknown */ "cm",
  "CG9":  /* unknown */ "cm",
  "CI9":  /* unknown */ "cm",
  "CJ9":  /* unknown */ "cm",
  "CL9":  /* unknown */ "cm",
  "CM9":  /* unknown */ "cm",
  "CO9":  /* unknown */ "cm",
  "CP9":  /* unknown */ "cm",
  "CR9":  /* unknown */ "cm",
  "CS9":  /* unknown */ "cm",
  "CU9":  /* unknown */ "cm",
  "CV9":  /* unknown */ "cm",
  "CX9":  /* unknown */ "cm",
  "CY9":  /* unknown */ "cm",
  "DA9":  /* unknown */ "cm",
  "DB9":  /* unknown */ "cm",
  "DD9":  /* unknown */ "cm",
  "DE9":  /* unknown */ "cm",
  "DG9":  /* unknown */ "cm",
  "DH9":  /* unknown */ "cm",
  "DJ9":  /* unknown */ "cm",
  "DK9":  /* unknown */ "cm",
  "DM9":  /* unknown */ "cm",
  "DN9":  /* unknown */ "cm",
  "DP9":  /* unknown */ "cm",
  "DQ9":  /* unknown */ "cm",
  "DV9":  /* unknown */ "mm",
  "DW9":  /* unknown */ "mm",
  "DX9":  /* unknown */ "mm",
  "EB9":  /* unknown */ "mm",
  "EC9":  /* unknown */ "mm",
  "ED9":  /* unknown */ "mm",
  "EE9":  /* unknown */ "mm",
  "EI9":  /* unknown */ "mm",
  "EJ9":  /* unknown */ "mm",
  "EK9":  /* unknown */ "mm",
  "EL9":  /* unknown */ "mm",
  "EP9":  /* unknown */ "mm",
  "EQ9":  /* unknown */ "mm",
  "ER9":  /* unknown */ "mm",
  "ES9":  /* unknown */ "mm",
  "EW9":  /* unknown */ "mm",
  "EX9":  /* unknown */ "mm",
  "EY9":  /* unknown */ "mm",
  "EZ9":  /* unknown */ "mm",
  "A10":  /* unknown */ "Datentyp",
  "B10":  /* unknown */ "String",
  "C10":  /* unknown */ "String",
  "D10":  /* unknown */ "Boolean",
  "E10":  /* unknown */ "Real",
  "F10":  /* unknown */ "Real",
  "G10":  /* unknown */ "Real",
  "H10":  /* unknown */ "Real",
  "I10":  /* unknown */ "Integer",
  "J10":  /* unknown */ "Integer",
  "K10":  /* unknown */ "String",
  "L10":  /* unknown */ "String",
  "M10":  /* unknown */ "Real",
  "N10":  /* unknown */ "Real",
  "O10":  /* unknown */ "Integer",
  "Q10":  /* unknown */ "Real",
  "R10":  /* unknown */ "Real",
  "S10":  /* unknown */ "Real",
  "U10":  /* unknown */ "Real",
  "V10":  /* unknown */ "Real",
  "W10":  /* unknown */ "Real",
  "Y10":  /* unknown */ "Real",
  "Z10":  /* unknown */ "Real",
  "AA10":  /* unknown */ "Real",
  "AC10":  /* unknown */ "Boolean",
  "AD10":  /* unknown */ "Real",
  "AE10":  /* unknown */ "Real",
  "AF10":  /* unknown */ "Integer ",
  "AG10":  /* unknown */ "Real",
  "AH10":  /* unknown */ "Real",
  "AI10":  /* unknown */ "Real",
  "AJ10":  /* unknown */ "Real",
  "AK10":  /* unknown */ "Real",
  "AL10":  /* unknown */ "Real",
  "AM10":  /* unknown */ "Real",
  "AN10":  /* unknown */ "Real",
  "AO10":  /* unknown */ "Real",
  "AP10":  /* unknown */ "Real",
  "AQ10":  /* unknown */ "Real",
  "AU10":  /* unknown */ "Real",
  "AV10":  /* unknown */ "Real",
  "AW10":  /* unknown */ "Integer",
  "AX10":  /* unknown */ "Integer",
  "AY10":  /* unknown */ "Real",
  "AZ10":  /* unknown */ "Real",
  "BA10":  /* unknown */ "Integer",
  "BB10":  /* unknown */ "Integer",
  "BC10":  /* unknown */ "Real",
  "BD10":  /* unknown */ "Real",
  "BE10":  /* unknown */ "Integer",
  "BF10":  /* unknown */ "Integer",
  "A11":  /* unknown */ "Pflichtfeld ",
  "C11":  /* unknown */ 1,
  "D11":  /* unknown */ 1,
  "G11":  /* unknown */ 1,
  "H11":  /* unknown */ 1,
  "K11":  /* unknown */ 1,
  "L11":  /* unknown */ 1,
  "M11":  /* unknown */ 1,
  "AC11":  /* unknown */ 1,
  "AD11":  /* unknown */ 0,
  "AE11":  /* unknown */ 0,
  "AF11":  /* unknown */ 0,
  "AG11":  /* unknown */ 0,
  "AH11":  /* unknown */ 0,
  "AU11":  /* unknown */ 1,
  "AV11":  /* unknown */ 1,
  "AW11":  /* unknown */ 0,
  "AX11":  /* unknown */ 0,
  "AY11":  /* unknown */ 1,
  "AZ11":  /* unknown */ 1,
  "BA11":  /* unknown */ 0,
  "BB11":  /* unknown */ 0,
  "BC11":  /* unknown */ 1,
  "BD11":  /* unknown */ 1,
  "BE11":  /* unknown */ 0,
  "BF11":  /* unknown */ 0,
  "A12":  /* unknown */ "Nachkommastellen",
  "G12":  /* unknown */ 1,
  "H12":  /* unknown */ 2,
  "I12":  /* unknown */ 0,
  "M12":  /* unknown */ 1,
  "AD12":  /* unknown */ 1,
  "AE12":  /* unknown */ 1,
  "AG12":  /* unknown */ 1,
  "AH12":  /* unknown */ 1,
  "AU12":  /* unknown */ 0,
  "AV12":  /* unknown */ 0,
  "AX12":  /* unknown */ 0,
  "AY12":  /* unknown */ 0,
  "AZ12":  /* unknown */ 0,
  "BB12":  /* unknown */ 0,
  "BC12":  /* unknown */ 0,
  "BD12":  /* unknown */ 0,
  "BF12":  /* unknown */ 0,
  "A13":  /* unknown */ "Wertebereich min",
  "E13":  /* unknown */ 1,
  "F13":  /* unknown */ 1,
  "G13":  /* unknown */ 1,
  "H13":  /* unknown */ 1,
  "I13":  /* unknown */ 10,
  "M13":  /* unknown */ 1,
  "N13":  /* unknown */ 2,
  "Q13":  /* unknown */ 1,
  "R13":  /* unknown */ 2,
  "S13":  /* unknown */ 1,
  "U13":  /* unknown */ 1,
  "V13":  /* unknown */ 2,
  "W13":  /* unknown */ 1,
  "Y13":  /* unknown */ 1,
  "Z13":  /* unknown */ 2,
  "AA13":  /* unknown */ 1,
  "AD13":  /* unknown */ 1,
  "AE13":  /* unknown */ 1,
  "AG13":  /* unknown */ 0,
  "AH13":  /* unknown */ 0,
  "AI13":  /* unknown */ 1,
  "AJ13":  /* unknown */ 1,
  "AK13":  /* unknown */ 1,
  "AL13":  /* unknown */ 1,
  "AM13":  /* unknown */ 1,
  "AN13":  /* unknown */ 1,
  "AO13":  /* unknown */ 1,
  "AP13":  /* unknown */ 1,
  "AQ13":  /* unknown */ 1,
  "AR13":  /* unknown */ 1,
  "AS13":  /* unknown */ 1,
  "AT13":  /* unknown */ 1,
  "AU13":  /* unknown */ 20,
  "AV13":  /* unknown */ 20,
  "AX13":  /* unknown */ 1,
  "AY13":  /* unknown */ 20,
  "AZ13":  /* unknown */ 20,
  "BB13":  /* unknown */ 1,
  "BC13":  /* unknown */ 20,
  "BD13":  /* unknown */ 20,
  "BF13":  /* unknown */ 1,
  "A14":  /* unknown */ "Wertebereich max",
  "E14":  /* unknown */ 20,
  "F14":  /* unknown */ 20,
  "G14":  /* unknown */ 100,
  "H14":  /* unknown */ 5,
  "I14":  /* unknown */ 30,
  "M14":  /* unknown */ 20,
  "N14":  /* unknown */ 5,
  "Q14":  /* unknown */ 20,
  "R14":  /* unknown */ 5,
  "S14":  /* unknown */ 30,
  "U14":  /* unknown */ 20,
  "V14":  /* unknown */ 5,
  "W14":  /* unknown */ 30,
  "Y14":  /* unknown */ 20,
  "Z14":  /* unknown */ 5,
  "AA14":  /* unknown */ 30,
  "AD14":  /* unknown */ 10,
  "AE14":  /* unknown */ 4,
  "AG14":  /* unknown */ 3,
  "AH14":  /* unknown */ 10,
  "AI14":  /* unknown */ 10,
  "AJ14":  /* unknown */ 10,
  "AK14":  /* unknown */ 30,
  "AL14":  /* unknown */ 10,
  "AM14":  /* unknown */ 10,
  "AN14":  /* unknown */ 30,
  "AO14":  /* unknown */ 30,
  "AP14":  /* unknown */ 30,
  "AQ14":  /* unknown */ 30,
  "AR14":  /* unknown */ 20,
  "AS14":  /* unknown */ 20,
  "AT14":  /* unknown */ 30,
  "AU14":  /* unknown */ 400,
  "AV14":  /* formula */ "$H$16",
  "AX14":  /* unknown */ 10,
  "AY14":  /* unknown */ 400,
  "AZ14":  /* formula */ "$H$16",
  "BB14":  /* unknown */ 10,
  "BC14":  /* unknown */ 400,
  "BD14":  /* formula */ "$H$16",
  "BF14":  /* unknown */ 10,
  "A15":  /* unknown */ "Defaultwert",
  "H15":  /* unknown */ 2.5,
  "I15":  /* unknown */ 20,
  "K15":  /* unknown */ "unbeheizt",
  "L15":  /* unknown */ "unbeheizt",
  "N15":  /* formula */ "H16",
  "O15":  /* formula */ "Frontend_allg_OLD!F17",
  "R15":  /* formula */ "H16",
  "S15":  /* unknown */ 0,
  "V15":  /* formula */ "H16",
  "W15":  /* unknown */ 0,
  "Z15":  /* formula */ "H16",
  "AA15":  /* unknown */ 0,
  "AC15":  /* unknown */ 0,
  "AD15":  /* unknown */ 0,
  "AE15":  /* unknown */ 0,
  "AF15":  /* formula */ "Frontend_allg_OLD!F17",
  "AG15":  /* unknown */ 0,
  "AH15":  /* unknown */ 0,
  "AK15":  /* unknown */ 0,
  "AN15":  /* unknown */ 0,
  "AO15":  /* unknown */ 0,
  "AP15":  /* unknown */ 0,
  "AQ15":  /* unknown */ 0,
  "AR15":  /* unknown */ 0,
  "AS15":  /* unknown */ 0,
  "AT15":  /* unknown */ 0,
  "AW15":  /* formula */ "Frontend_allg_OLD!$F$17",
  "AX15":  /* unknown */ 1,
  "BA15":  /* formula */ "Frontend_allg_OLD!$F$17",
  "BB15":  /* unknown */ 1,
  "BE15":  /* formula */ "Frontend_allg_OLD!$F$17",
  "BF15":  /* unknown */ 1,
  "A16":  /* unknown */ "Variablenname ",
  "B16":  /* unknown */ "ID_R#",
  "C16":  /* unknown */ "TXT_R#_name",
  "D16":  /* unknown */ "B_R#_floor_rect",
  "E16":  /* unknown */ "L_R#_len",
  "F16":  /* unknown */ "L_R#_wid",
  "G16":  /* unknown */ "A_floor",
  "H16":  /* unknown */ "L_hei",
  "I16":  /* unknown */ "T_air_set",
  "J16":  /* unknown */ "T_air_norm",
  "K16":  /* unknown */ "TYP_V_above",
  "L16":  /* unknown */ "TYP_V_below",
  "M16":  /* unknown */ "L_wall_tot",
  "N16":  /* unknown */ "L_R#_wall1_hei",
  "O16":  /* unknown */ "YEAR_wall_ins",
  "Q16":  /* unknown */ "L_R#_wall2_len",
  "R16":  /* unknown */ "L_R#_wall2_hei",
  "S16":  /* unknown */ "L_R#_wall2_ins_thick",
  "U16":  /* unknown */ "L_R#_wall3_len",
  "V16":  /* unknown */ "L_R#_wall3_hei",
  "W16":  /* unknown */ "L_R#_wall3_ins_thick",
  "Y16":  /* unknown */ "L_R#_wall4_len",
  "Z16":  /* unknown */ "L_R#_wall4_hei",
  "AA16":  /* unknown */ "L_R#_wall4_ins_thick",
  "AC16":  /* unknown */ "B_roof_exist",
  "AD16":  /* unknown */ "L_roof_wid",
  "AE16":  /* unknown */ "L_roof_hei",
  "AF16":  /* unknown */ "YEAR_roof_modern",
  "AG16":  /* unknown */ "L_roof_knee_hei",
  "AH16":  /* unknown */ "L_roof_dormer_wid",
  "AI16":  /* unknown */ "L_R#_roof2_len",
  "AJ16":  /* unknown */ "L_R#_roof2_hei",
  "AK16":  /* unknown */ "L_R#_roof2_ins_thick",
  "AL16":  /* unknown */ "L_R#_roof3_len",
  "AM16":  /* unknown */ "L_R#_roof3_hei",
  "AN16":  /* unknown */ "L_R#_roof3_ins_thick",
  "AR16":  /* unknown */ "L_R#_floor_length_unheated",
  "AS16":  /* unknown */ "L_R#_floor_width_unheated",
  "AT16":  /* unknown */ "L_R#_floor_ins_thick_amb",
  "AU16":  /* formula */ "\"L_\"&AU3&\"_\"&AU4&\"_wid\"",
  "AV16":  /* formula */ "\"L_\"&AV3&\"_\"&AV4&\"_hei\"",
  "AW16":  /* formula */ "\"YEAR_\"&AW3&\"_\"&AW4",
  "AX16":  /* formula */ "\"NO_\"&AX3&\"_\"&AX4",
  "AY16":  /* formula */ "\"L_\"&AY3&\"_\"&AY4&\"_wid\"",
  "AZ16":  /* formula */ "\"L_\"&AZ3&\"_\"&AZ4&\"_hei\"",
  "BA16":  /* formula */ "\"YEAR_\"&BA3&\"_\"&BA4",
  "BB16":  /* formula */ "\"NO_\"&BB3&\"_\"&BB4",
  "BC16":  /* formula */ "\"L_\"&BC3&\"_\"&BC4&\"_wid\"",
  "BD16":  /* formula */ "\"L_\"&BD3&\"_\"&BD4&\"_hei\"",
  "BE16":  /* formula */ "\"YEAR_\"&BE3&\"_\"&BE4",
  "BF16":  /* formula */ "\"NO_\"&BF3&\"_\"&BF4",
  "BG16":  /* formula */ "\"L_R#_\"&BG3&\"_\"&BG4&\"_wid\"",
  "BH16":  /* formula */ "\"L_R#_\"&BH3&\"_\"&BH4&\"_hei\"",
  "BI16":  /* formula */ "\"NO_R#_\"&BI3&\"_\"&BI4&\"_bj\"",
  "B17":  /* unknown */ "ID_R1",
  "C17":  /* formula */ "Frontend_allg_OLD!BB17",
  "D17":  /* unknown */ "Ja",
  "G17":  /* unknown */ 11.54,
  "H17":  /* unknown */ 2.83,
  "I17":  /* unknown */ 20,
  "J17":  /* unknown */ 20,
  "K17":  /* unknown */ "unbeheizt",
  "L17":  /* unknown */ "unbeheizt",
  "M17":  /* unknown */ 3.95,
  "N17":  /* formula */ "$H$17",
  "P17":  /* unknown */ "Außenluft",
  "Q17":  /* unknown */ 2.92,
  "R17":  /* formula */ "$H$17",
  "T17":  /* unknown */ "Außenluft",
  "Z17":  /* formula */ "$H$17",
  "AC17":  /* unknown */ "Nein",
  "AO17":  /* unknown */ 3.95,
  "AP17":  /* unknown */ 2.92,
  "AQ17":  /* unknown */ 6,
  "AR17":  /* unknown */ 3.95,
  "AS17":  /* unknown */ 2.92,
  "AU17":  /* unknown */ 123,
  "AV17":  /* unknown */ 125,
  "AW17":  /* unknown */ "2003 - 2008",
  "AX17":  /* unknown */ 1,
  "BB17":  /* unknown */ 1,
  "BF17":  /* unknown */ 1,
  "BJ17":  /* unknown */ 123,
  "BK17":  /* unknown */ 125,
  "BL17":  /* unknown */ "2003 - 2008",
  "DU17":  /* unknown */ "Flachheizkörper",
  "DV17":  /* unknown */ "Senkrecht_profiliert",
  "DW17":  /* unknown */ 11,
  "DX17":  /* unknown */ 600,
  "DY17":  /* unknown */ 1100,
  "DZ17":  /* unknown */ 65,
  "B18":  /* unknown */ "ID_R2",
  "C18":  /* formula */ "Frontend_allg_OLD!BC17",
  "D18":  /* unknown */ "Ja",
  "G18":  /* unknown */ 16,
  "H18":  /* unknown */ 2.83,
  "I18":  /* unknown */ 20,
  "J18":  /* unknown */ 20,
  "K18":  /* unknown */ "unbeheizt",
  "L18":  /* unknown */ "unbeheizt",
  "M18":  /* unknown */ 3.97,
  "N18":  /* formula */ "$H$17",
  "P18":  /* unknown */ "Außenluft",
  "Q18":  /* unknown */ 4.03,
  "R18":  /* formula */ "$H$17",
  "T18":  /* unknown */ "Außenluft",
  "Z18":  /* formula */ "$H$17",
  "AC18":  /* unknown */ "Nein",
  "AO18":  /* unknown */ 4.03,
  "AP18":  /* unknown */ 3.97,
  "AQ18":  /* unknown */ 6,
  "AR18":  /* formula */ "SQRT(20.28)",
  "AS18":  /* unknown */ 4.03,
  "AT18":  /* unknown */ 3.97,
  "AU18":  /* unknown */ 147.5,
  "AV18":  /* unknown */ 125,
  "AX18":  /* unknown */ 1,
  "BB18":  /* unknown */ 1,
  "BF18":  /* unknown */ 1,
  "DU18":  /* unknown */ "Flachheizkörper",
  "DV18":  /* unknown */ "Senkrecht_profiliert",
  "DW18":  /* unknown */ 33,
  "DX18":  /* unknown */ 600,
  "DY18":  /* unknown */ 1000,
  "DZ18":  /* unknown */ 155,
  "B19":  /* unknown */ "ID_R3",
  "C19":  /* formula */ "Frontend_allg_OLD!BD17",
  "D19":  /* unknown */ "Ja",
  "G19":  /* unknown */ 10.4,
  "H19":  /* unknown */ 2.83,
  "I19":  /* unknown */ 20,
  "J19":  /* unknown */ 20,
  "K19":  /* unknown */ "unbeheizt",
  "L19":  /* unknown */ "unbeheizt",
  "M19":  /* unknown */ 2.5,
  "N19":  /* formula */ "$H$17",
  "P19":  /* unknown */ "Außenluft",
  "Z19":  /* formula */ "$H$17",
  "AC19":  /* unknown */ "Nein",
  "AO19":  /* unknown */ 2.5,
  "AP19":  /* unknown */ 4.17,
  "AQ19":  /* unknown */ 6,
  "AR19":  /* unknown */ 2.5,
  "AS19":  /* unknown */ 4.17,
  "AU19":  /* unknown */ 122.5,
  "AV19":  /* unknown */ 125,
  "AX19":  /* unknown */ 1,
  "BB19":  /* unknown */ 1,
  "BF19":  /* unknown */ 1,
  "DU19":  /* unknown */ "Flachheizkörper",
  "DV19":  /* unknown */ "Senkrecht_profiliert",
  "DW19":  /* unknown */ 11,
  "DX19":  /* unknown */ 600,
  "DY19":  /* unknown */ 1100,
  "DZ19":  /* unknown */ 65,
  "B20":  /* unknown */ "aus Frontend_allg Raumbezeichnung übernehmen",
  "C20":  /* unknown */ "aus Frontend_allg Raumbezeichnung übernehmen",
  "D20":  /* formula */ "IF($D$17=\"Nein\",\"Bitte geben Sie die Wohnfläche direkt ein\",\"\")",
  "E20":  /* unknown */ "m",
  "F20":  /* unknown */ "m",
  "G20":  /* unknown */ "m²",
  "H20":  /* unknown */ "m",
  "I20":  /* unknown */ "°C",
  "J20":  /* unknown */ "°C",
  "M20":  /* unknown */ "m",
  "N20":  /* unknown */ "m",
  "O20":  /* unknown */ "cm",
  "Q20":  /* unknown */ "m",
  "R20":  /* unknown */ "m",
  "S20":  /* unknown */ "cm",
  "U20":  /* unknown */ "m",
  "V20":  /* unknown */ "m",
  "W20":  /* unknown */ "cm",
  "Y20":  /* unknown */ "m",
  "Z20":  /* unknown */ "m",
  "AA20":  /* unknown */ "cm",
  "AD20":  /* unknown */ "m",
  "AE20":  /* unknown */ "m",
  "AF20":  /* unknown */ "cm",
  "AI20":  /* unknown */ "m",
  "AJ20":  /* unknown */ "m",
  "AK20":  /* unknown */ "cm",
  "AL20":  /* unknown */ "m",
  "AM20":  /* unknown */ "m",
  "AN20":  /* unknown */ "cm",
  "AO20":  /* unknown */ "m",
  "AP20":  /* unknown */ "m",
  "AQ20":  /* unknown */ "cm",
  "AR20":  /* unknown */ "m",
  "AS20":  /* unknown */ "m",
  "AT20":  /* unknown */ "cm",
  "AV20":  /* unknown */ "cm",
  "AZ20":  /* unknown */ "cm",
  "BA20":  /* unknown */ "cm",
  "BD20":  /* unknown */ "cm",
  "BE20":  /* unknown */ "cm",
  "BH20":  /* unknown */ "cm",
  "BI20":  /* unknown */ "cm",
  "BK20":  /* unknown */ "cm",
  "BL20":  /* unknown */ "cm",
  "BN20":  /* unknown */ "cm",
  "BO20":  /* unknown */ "cm",
  "BQ20":  /* unknown */ "cm",
  "BR20":  /* unknown */ "cm",
  "BT20":  /* unknown */ "cm",
  "BU20":  /* unknown */ "cm",
  "BW20":  /* unknown */ "cm",
  "BX20":  /* unknown */ "cm",
  "BZ20":  /* unknown */ "cm",
  "CA20":  /* unknown */ "cm",
  "CC20":  /* unknown */ "cm",
  "CD20":  /* unknown */ "cm",
  "CF20":  /* unknown */ "cm",
  "CG20":  /* unknown */ "cm",
  "CI20":  /* unknown */ "cm",
  "CJ20":  /* unknown */ "cm",
  "CL20":  /* unknown */ "cm",
  "CM20":  /* unknown */ "cm",
  "CO20":  /* unknown */ "cm",
  "CP20":  /* unknown */ "cm",
  "CR20":  /* unknown */ "cm",
  "CS20":  /* unknown */ "cm",
  "CU20":  /* unknown */ "cm",
  "CV20":  /* unknown */ "cm",
  "CX20":  /* unknown */ "cm",
  "CY20":  /* unknown */ "cm",
  "DA20":  /* unknown */ "cm",
  "DB20":  /* unknown */ "cm",
  "DD20":  /* unknown */ "cm",
  "DE20":  /* unknown */ "cm",
  "DG20":  /* unknown */ "cm",
  "DH20":  /* unknown */ "cm",
  "DJ20":  /* unknown */ "cm",
  "DK20":  /* unknown */ "cm",
  "DM20":  /* unknown */ "cm",
  "DN20":  /* unknown */ "cm",
  "DP20":  /* unknown */ "cm",
  "DQ20":  /* unknown */ "cm",
  "DV20":  /* unknown */ "mm",
  "DW20":  /* unknown */ "mm",
  "DX20":  /* unknown */ "mm",
  "EB20":  /* unknown */ "mm",
  "EC20":  /* unknown */ "mm",
  "ED20":  /* unknown */ "mm",
  "EE20":  /* unknown */ "mm",
  "EI20":  /* unknown */ "mm",
  "EJ20":  /* unknown */ "mm",
  "EK20":  /* unknown */ "mm",
  "EL20":  /* unknown */ "mm",
  "EP20":  /* unknown */ "mm",
  "EQ20":  /* unknown */ "mm",
  "ER20":  /* unknown */ "mm",
  "ES20":  /* unknown */ "mm",
  "EW20":  /* unknown */ "mm",
  "EX20":  /* unknown */ "mm",
  "EY20":  /* unknown */ "mm",
  "EZ20":  /* unknown */ "mm",
  "D21":  /* unknown */ "E3 sperren, wenn D3=\"Nein\"",
  "D22":  /* unknown */ "F3 sperren, wenn D3=\"Nein\"",
  "A26":  /* unknown */ "Löschen?",
  "C26":  /* unknown */ ">> Name kommt aus list_rooms, aber als Ausgabegröße relevant",
  "D26":  /* unknown */ ">> immer über Grundfläche gehen",
  "E26":  /* unknown */ ">> immer Fläche",
  "F26":  /* unknown */ ">> immer Fläche",
  "J26":  /* unknown */ ">> Vorschlag analog heizreport: nur Solltemperatur abfragen und Info zu Temperatur Wohnräume vs. Badezimmer in Hilfstext",
  "N26":  /* unknown */ ">> Tendenz rauslassen: Zu klären, wie es sich bspw. auf Giebelwände auswirkt, mittelt sich das raus? Wie würden wir sie sonst erfassen? (bei heizreport auch nicht differenziert). Kniestöcke fragen wir separat ab.",
  "P26":  /* unknown */ "Vorschlag: bei Außenwand immer Außenluft ansetzen? Kellerraum =! Schlechtpunkt, aber ggf. AW gegen unbeheizt? ",
  "Q26":  /* unknown */ "Löschen, da alle Wände zusammengefasst ",
  "R26":  /* unknown */ "Löschen, da alle Wände zusammengefasst ",
  "S26":  /* unknown */ "Löschen, da alle Wände zusammengefasst ",
  "T26":  /* unknown */ "Löschen, da alle Wände zusammengefasst ",
  "U26":  /* unknown */ "Löschen, da alle Wände zusammengefasst ",
  "V26":  /* unknown */ "Löschen, da alle Wände zusammengefasst ",
  "W26":  /* unknown */ "Löschen, da alle Wände zusammengefasst ",
  "X26":  /* unknown */ "Löschen, da alle Wände zusammengefasst ",
  "Y26":  /* unknown */ "Löschen, da alle Wände zusammengefasst ",
  "Z26":  /* unknown */ "Löschen, da alle Wände zusammengefasst ",
  "AA26":  /* unknown */ "Löschen, da alle Wände zusammengefasst ",
  "AB26":  /* unknown */ "Löschen, da alle Wände zusammengefasst ",
  "AI26":  /* unknown */ "Löschen, da alle Dächer zusammengefasst ",
  "AJ26":  /* unknown */ "Löschen, da alle Dächer zusammengefasst ",
  "AK26":  /* unknown */ "Löschen, da alle Dächer zusammengefasst ",
  "AL26":  /* unknown */ "Löschen, da alle Dächer zusammengefasst ",
  "AM26":  /* unknown */ "Löschen, da alle Dächer zusammengefasst ",
  "AN26":  /* unknown */ "Löschen, da alle Dächer zusammengefasst ",
  "AO26":  /* unknown */ "Löschen, da nur eine Decke",
  "AQ26":  /* unknown */ "Angabe Dämmung fehlt uns dann. Ich würde über IWU Tabula bzw. Angabe auf Gebäudeebene gehen (weicht in diesem Fall mit 12 cm von der Raumangabe ab). ",
  "BG26":  /* unknown */ "Löschen, da alle Außenwände zusammengefasst ",
  "BH26":  /* unknown */ "Löschen, da alle Außenwände zusammengefasst ",
  "BI26":  /* unknown */ "Löschen, da alle Außenwände zusammengefasst ",
  "BJ26":  /* unknown */ "Löschen, da alle Außenwände zusammengefasst ",
  "BK26":  /* unknown */ "Löschen, da alle Außenwände zusammengefasst ",
  "BL26":  /* unknown */ "Löschen, da alle Außenwände zusammengefasst ",
  "BM26":  /* unknown */ "Löschen, da alle Außenwände zusammengefasst ",
  "BN26":  /* unknown */ "Löschen, da alle Außenwände zusammengefasst ",
  "BO26":  /* unknown */ "Löschen, da alle Außenwände zusammengefasst ",
  "BP26":  /* unknown */ "Löschen, da alle Außenwände zusammengefasst ",
  "BQ26":  /* unknown */ "Löschen, da alle Außenwände zusammengefasst ",
  "BR26":  /* unknown */ "Löschen, da alle Außenwände zusammengefasst ",
  "BS26":  /* unknown */ "Löschen, da alle Außenwände zusammengefasst ",
  "BT26":  /* unknown */ "Löschen, da alle Außenwände zusammengefasst ",
  "BU26":  /* unknown */ "Löschen, da alle Außenwände zusammengefasst ",
  "BV26":  /* unknown */ "Löschen, da alle Außenwände zusammengefasst ",
  "BW26":  /* unknown */ "Löschen, da alle Außenwände zusammengefasst ",
  "BX26":  /* unknown */ "Löschen, da alle Außenwände zusammengefasst ",
  "BY26":  /* unknown */ "Löschen, da alle Außenwände zusammengefasst ",
  "BZ26":  /* unknown */ "Löschen, da alle Außenwände zusammengefasst ",
  "CA26":  /* unknown */ "Löschen, da alle Außenwände zusammengefasst ",
  "CB26":  /* unknown */ "Löschen, da alle Außenwände zusammengefasst ",
  "CC26":  /* unknown */ "Löschen, da alle Außenwände zusammengefasst ",
  "CD26":  /* unknown */ "Löschen, da alle Außenwände zusammengefasst ",
  "CE26":  /* unknown */ "Löschen, da alle Außenwände zusammengefasst ",
  "CF26":  /* unknown */ "Löschen, da alle Außenwände zusammengefasst ",
  "CG26":  /* unknown */ "Löschen, da alle Außenwände zusammengefasst ",
  "CH26":  /* unknown */ "Löschen, da alle Außenwände zusammengefasst ",
  "CI26":  /* unknown */ "Löschen, da alle Außenwände zusammengefasst ",
  "CJ26":  /* unknown */ "Löschen, da alle Außenwände zusammengefasst ",
  "CK26":  /* unknown */ "Löschen, da alle Außenwände zusammengefasst ",
  "CL26":  /* unknown */ "Löschen, da alle Außenwände zusammengefasst ",
  "CM26":  /* unknown */ "Löschen, da alle Außenwände zusammengefasst ",
  "CN26":  /* unknown */ "Löschen, da alle Außenwände zusammengefasst ",
  "CO26":  /* unknown */ "Löschen, da alle Außenwände zusammengefasst ",
  "CP26":  /* unknown */ "Löschen, da alle Außenwände zusammengefasst ",
  "CQ26":  /* unknown */ "Löschen, da alle Außenwände zusammengefasst ",
  "CR26":  /* unknown */ "Löschen, da alle Außenwände zusammengefasst ",
  "CS26":  /* unknown */ "Löschen, da alle Außenwände zusammengefasst ",
  "CZ26":  /* unknown */ "Löschen, da alle Dachflächen zusammengefasst ",
  "DA26":  /* unknown */ "Löschen, da alle Dachflächen zusammengefasst ",
  "DB26":  /* unknown */ "Löschen, da alle Dachflächen zusammengefasst ",
  "DC26":  /* unknown */ "Löschen, da alle Dachflächen zusammengefasst ",
  "DD26":  /* unknown */ "Löschen, da alle Dachflächen zusammengefasst ",
  "DE26":  /* unknown */ "Löschen, da alle Dachflächen zusammengefasst ",
  "DF26":  /* unknown */ "Löschen, da alle Dachflächen zusammengefasst ",
  "DG26":  /* unknown */ "Löschen, da alle Dachflächen zusammengefasst ",
  "DH26":  /* unknown */ "Löschen, da alle Dachflächen zusammengefasst ",
  "DI26":  /* unknown */ "Löschen, da alle Dachflächen zusammengefasst ",
  "DJ26":  /* unknown */ "Löschen, da alle Dachflächen zusammengefasst ",
  "DK26":  /* unknown */ "Löschen, da alle Dachflächen zusammengefasst ",
  "DL26":  /* unknown */ "Löschen, da alle Dachflächen zusammengefasst ",
  "DM26":  /* unknown */ "Löschen, da alle Dachflächen zusammengefasst ",
  "DN26":  /* unknown */ "Löschen, da alle Dachflächen zusammengefasst ",
  "DO26":  /* unknown */ "Löschen, da alle Dachflächen zusammengefasst ",
  "DP26":  /* unknown */ "Löschen, da alle Dachflächen zusammengefasst ",
  "DQ26":  /* unknown */ "Löschen, da alle Dachflächen zusammengefasst ",
  "DR26":  /* unknown */ "Löschen, da alle Dachflächen zusammengefasst ",
  "DS26":  /* unknown */ "Löschen, da alle Dachflächen zusammengefasst ",
  "DT26":  /* unknown */ "Löschen, da alle Dachflächen zusammengefasst ",
  "A27":  /* unknown */ "Todo",
  "N27":  /* unknown */ "Anpassen Verweis",
  "O27":  /* unknown */ "Anpassung Berechnung U-Wert: über IWU Tablua anstatt Dämmschichtdicke? Oder Dämmschichtdicke anhand Jahr Modernisierung (Tabelle unten)? Oder EnEV/GEG Vorgaben und anhand Novellen? >> Peter: es gibt Input GEMOD ",
  "P27":  /* unknown */ "Anpassen Verweis",
  "AF27":  /* unknown */ "siehe YEAR_wall_modern sowie bzgl. defaultwert: Überarbeiten Verweis auf Wert Gebäude, wenn Modernisierungsjahr für alle Bauteile getrennt abgefragt wird. ",
  "AG27":  /* unknown */ "Einbezug Berechnung in DIN12831 klären",
  "AH27":  /* unknown */ "Einbezug Berechnung in DIN12831 klären",
  "AW27":  /* unknown */ "siehe YEAR_wall_ins",
  "AX27":  /* unknown */ "Multiplikator aufnehmen",
  "BB27":  /* unknown */ "Multiplikator aufnehmen",
  "BF27":  /* unknown */ "Multiplikator aufnehmen",
  "BF28":  /* unknown */ "ggf. 4. Fenstertyp ergänzen? ",
};
