// Sheet: Frontend_allg_OLD
// Generated on: 2025-05-10T13:08:38.977Z

export const data: Record<string, any> = {
  "A1":  /* unknown */ "Bauteil (ifeu intern) ",
  "A2":  /* unknown */ "Frage (ifeu intern)",
  "C2":  /* unknown */ "Zur Person",
  "D2":  /* unknown */ "Standort",
  "E2":  /* unknown */ "Gebäudetyp",
  "F2":  /* unknown */ "Baujahr des Gebäudes",
  "AF2":  /* unknown */ "Effizienzklasse sofern bekannt",
  "AG2":  /* unknown */ "Nachträglich gedämmte Bauteile",
  "AH2":  /* unknown */ "Nachträglich gedämmte Bauteile",
  "AI2":  /* unknown */ "wenn bekannt, in welcher Dicke wurde gedämmt?",
  "AJ2":  /* unknown */ "Nachträglich gedämmte Bauteile",
  "AK2":  /* unknown */ "wenn bekannt, in welcher Dicke wurde gedämmt?",
  "AL2":  /* unknown */ "Nachträglich gedämmte Bauteile",
  "AM2":  /* unknown */ "wenn bekannt, in welcher Dicke wurde gedämmt?",
  "AN2":  /* unknown */ "Denkmalschutz",
  "AO2":  /* unknown */ "Wärmeübergabe",
  "AP2":  /* unknown */ " -Lüftung",
  "AQ2":  /* unknown */ "ich weiß, auf welchen Wert die TVL in der Heizungsregelung eingestellt ist",
  "AR2":  /* unknown */ "ich kann im Heizungsraum die Vorlauftemperatur ablesen und kann die Außentemperatur messen",
  "AS2":  /* formula */ "IF(AND($AQ$17=\"Nein\",$AR$17=\"Nein\"),\"70°C\",IF(AND($AQ$17=\"Ja\",$AR$17=\"Nein\"),\"Bitte tragen sie die Vorlauftemperatur ein\",IF(AND($AQ$17=\"Nein\",$AR$17=\"Ja\"),\"Bitte tragen sie die Vorlauftemperatur ein\",\"Bitte tragen Sie die Vorlauftemperatur ein\")))",
  "AT2":  /* formula */ "IF($AR$17=\"Ja\",\"Bitte tragen Sie die Außentemperatur zum Zeitpunkt ihrer Ablesung ein\",\"\")",
  "AU2":  /* unknown */ "Wärmeverteilung",
  "AV2":  /* unknown */ "Gibt es in Ihrem Haus / Ihrer Wohnung Räume, die nicht ausreichend warm werden?",
  "AW2":  /* unknown */ 1,
  "AX2":  /* unknown */ 2,
  "AY2":  /* unknown */ 3,
  "AZ2":  /* unknown */ 4,
  "BA2":  /* unknown */ "Gibt es in Ihrem Haus / Ihrer Wohnung Räume mit besonders vielen Außenbauteilen (Außenwände, Dachschräge, Flachdach, Räume mit Erker, oberhalb einer Durchfahrt, unter unbeheiztem Dachboden, über unbeheiztem Keller, viele Fenster)",
  "BB2":  /* unknown */ 1,
  "BC2":  /* unknown */ 2,
  "BD2":  /* unknown */ 3,
  "BE2":  /* unknown */ 4,
  "A3":  /* unknown */ "Gruppe ",
  "G3":  /* unknown */ "san",
  "H3":  /* unknown */ "san",
  "I3":  /* unknown */ "san",
  "J3":  /* unknown */ "san",
  "K3":  /* unknown */ "san",
  "L3":  /* unknown */ "san",
  "M3":  /* unknown */ "san",
  "N3":  /* unknown */ "san",
  "O3":  /* unknown */ "san",
  "P3":  /* unknown */ "san",
  "Q3":  /* unknown */ "san",
  "R3":  /* unknown */ "san",
  "S3":  /* unknown */ "san",
  "T3":  /* unknown */ "san",
  "U3":  /* unknown */ "san",
  "V3":  /* unknown */ "san",
  "W3":  /* unknown */ "san",
  "X3":  /* unknown */ "san",
  "Y3":  /* unknown */ "san",
  "Z3":  /* unknown */ "san",
  "AA3":  /* unknown */ "san",
  "AB3":  /* unknown */ "san",
  "AC3":  /* unknown */ "san",
  "AD3":  /* unknown */ "san",
  "AE3":  /* unknown */ "san",
  "A4":  /* unknown */ "Subgruppe",
  "G4":  /* unknown */ "wall",
  "H4":  /* unknown */ "wall",
  "I4":  /* unknown */ "wall",
  "J4":  /* unknown */ "wall",
  "K4":  /* unknown */ "wall",
  "L4":  /* unknown */ "win",
  "M4":  /* unknown */ "win",
  "N4":  /* unknown */ "win",
  "O4":  /* unknown */ "win",
  "P4":  /* unknown */ "win",
  "Q4":  /* unknown */ "roof",
  "R4":  /* unknown */ "roof",
  "S4":  /* unknown */ "roof",
  "T4":  /* unknown */ "roof",
  "U4":  /* unknown */ "roof",
  "V4":  /* unknown */ "botceil",
  "W4":  /* unknown */ "botceil",
  "X4":  /* unknown */ "botceil",
  "Y4":  /* unknown */ "botceil",
  "Z4":  /* unknown */ "botceil",
  "AA4":  /* unknown */ "topceil",
  "AB4":  /* unknown */ "topceil",
  "AC4":  /* unknown */ "topceil",
  "AD4":  /* unknown */ "topceil",
  "AE4":  /* unknown */ "topceil",
  "A5":  /* unknown */ "Fragentext ",
  "A6":  /* unknown */ "Hilfstext",
  "A7":  /* unknown */ "Antworttyp",
  "A8":  /* unknown */ "Filter ",
  "A9":  /* unknown */ "Einheit ",
  "A10":  /* unknown */ "Datentyp",
  "A11":  /* unknown */ "Pflichtfeld ",
  "A12":  /* unknown */ "Nachkommastellen",
  "A13":  /* unknown */ "Wertebereich min",
  "A14":  /* unknown */ "Wertebereich max",
  "A15":  /* unknown */ "Defaultwert",
  "A16":  /* unknown */ "Variablenname ",
  "G16":  /* unknown */ "EXIST_build_wall_san",
  "H16":  /* unknown */ "YEAR_build_wall_san_intern",
  "I16":  /* unknown */ "YEAR_build_wall_san",
  "J16":  /* unknown */ "L_build_wall_ins_intern",
  "K16":  /* unknown */ "L_build_wall_ins",
  "C17":  /* unknown */ "Hauseigentümer*in",
  "D17":  /* unknown */ 67435,
  "E17":  /* unknown */ "Ein- oder Zweifamilienhaus",
  "F17":  /* unknown */ "1969 - 1978",
  "AF17":  /* unknown */ "Nicht bekannt",
  "AG17":  /* unknown */ "Ja",
  "AH17":  /* unknown */ "Dämmung der obersten Geschossdecke",
  "AI17":  /* unknown */ 12,
  "AN17":  /* unknown */ "das Gebäude steht nicht unter Denkmalschutz",
  "AO17":  /* unknown */ "Heizkörper",
  "AP17":  /* unknown */ "Freie Lüftung",
  "AQ17":  /* unknown */ "Ja",
  "AS17":  /* unknown */ 75,
  "AT17":  /* unknown */ -10,
  "AU17":  /* unknown */ "Zweirohrheizung",
  "AV17":  /* unknown */ "Ja",
  "AW17":  /* unknown */ "Sonstige",
  "AX17":  /* unknown */ "Sonstige",
  "BA17":  /* unknown */ "Ja",
  "BB17":  /* unknown */ "Sonstige",
  "BC17":  /* unknown */ "Schlafzimmer",
  "BD17":  /* unknown */ "Sonstige",
  "C18":  /* unknown */ "Art der Ansprache ggf. anpassen",
  "D18":  /* unknown */ "Bitte Plz eingeben",
  "E18":  /* unknown */ "ggf. bei Plausibilisierung mit Empirie berücksichtigen (W/m²)",
  "F18":  /* unknown */ "U-Werte nach IWU",
  "AH18":  /* unknown */ "Wir müssen dieses Multiple Choice Feld in alle Einzelfälle abdecken, um die Daten verarbeiten zu können, oder? ",
  "AI18":  /* unknown */ "für Berechnung der U-Werte",
  "AK18":  /* unknown */ "für Berechnung der U-Werte",
  "AM18":  /* unknown */ "für Berechnung der U-Werte",
  "AN18":  /* formula */ "IF(AN17=Daten!E54, \"keine WDVS empfehlen\",\"WDVS können empfohlen werden\")",
  "AO18":  /* formula */ "IF(AO17=Daten!E58,\"Pauschal für WP geeignet\",IF(AO17=Daten!E60,\"Maßnahmen für den optimalen WP-Betrieb erforderlich\",IF(AO17=Daten!E61,\"Pauschal für WP geeignet\",IF(AO17=Daten!E62,\"Maßnahmen für den optimalen WP-Betrieb erforderlich\",\"\"))))",
  "AQ18":  /* unknown */ "TVL in °C",
  "AS18":  /* unknown */ "TVL in °C",
  "AT18":  /* unknown */ "AT in °C",
  "AU18":  /* formula */ "IF(AU17=\"Zweirohrheizung\",\"Bitte überprüfen Sie, ob ihr Heizsystem hydraulisch abgeglichen ist\",\"\")",
  "AV18":  /* formula */ "IF(AV17=\"Ja\",\"Bitte wählen Sie die Räume aus, die am schlechtesten warm werden\")",
  "BA18":  /* formula */ "IF(BA17=\"Ja\",\"Bitte wählen Sie die Räume mit den meisten Außenbauteilen aus\")",
  "AQ19":  /* unknown */ "Wenn ja, dann Eingabe der Vorlauftemperatur",
  "AR19":  /* unknown */ "Wenn ja, dann Eingabe der Vorlauftemperatur und Außentemperatur",
  "AT19":  /* unknown */ "max. TVL(AT)",
  "AR20":  /* unknown */ "Wenn beide nein, dann TVL pauschal 70°C",
  "AT20":  /* formula */ "AT17*-1.8257+43.457+AT17",
  "AR21":  /* unknown */ "TVL<AT*(-1,8257)+43,457+AT",
  "AT21":  /* unknown */ "ich kann im Heizungsraum die Vorlauftemperatur ablesen und kann die Außentemperatur messen",
  "E26":  /* unknown */ "Löschen?",
  "AG26":  /* unknown */ "löschen, da Abfrageart überarbeitet. Bisher gibt es hier keine Spur zum Nachfolger ",
  "E27":  /* unknown */ "Todo",
  "G27":  /* unknown */ "ggf. nach unten schieben",
  "AO69":  /* formula */ "IF(AO17=\"elektrische Nachtspeicherheizung\",\"Frage 1.5 nicht stellen\",IF(AO17=\"Luftheizung\",\"Frage nicht stellen!\",\"\"))",
};
