// Sheet: IN_build
export const data = {
  "A1":  /* unknown */ "Bezeichnung",
  "B1":  /* unknown */ "Gruppe ",
  "C1":  /* unknown */ "Subgruppe",
  "D1":  /* unknown */ "Variable",
  "E1":  /* unknown */ "Fragentext ",
  "F1":  /* unknown */ "Hilfstext",
  "G1":  /* unknown */ "Antworttyp",
  "H1":  /* unknown */ "Filter ",
  "I1":  /* unknown */ "Einheit ",
  "J1":  /* unknown */ "Datentyp",
  "K1":  /* unknown */ "Pflichtfeld ",
  "L1":  /* unknown */ "Nachkommastellen",
  "M1":  /* unknown */ "min Wert",
  "N1":  /* unknown */ "max Wert",
  "O1":  /* unknown */ "Wert intern",
  "P1":  /* unknown */ "Wert",
  "Q1":  /* unknown */ "EXIST",
  "R1":  /* unknown */ "YEAR_intern",
  "S1":  /* unknown */ "YEAR",
  "T1":  /* unknown */ "L_ins_intern [cm]",
  "U1":  /* unknown */ "L_ins [cm]",
  "A2":  /* unknown */ "Standort",
  "B2":  /* unknown */ "build",
  "D2":  /* unknown */ "NO_build_plz",
  "E2":  /* unknown */ "Standort des Gebäudes (PLZ)",
  "G2":  /* unknown */ "Freifeld",
  "J2":  /* unknown */ "Integer",
  "K2":  /* unknown */ 1,
  "P2":  /* unknown */ 69151,
  "A3":  /* unknown */ "Gebäudetyp",
  "B3":  /* unknown */ "build",
  "D3":  /* unknown */ "TYP_build",
  "E3":  /* unknown */ "Das Gebäude ist ein…",
  "G3":  /* unknown */ "Radio Button + Grafik",
  "J3":  /* unknown */ "String",
  "K3":  /* unknown */ 1,
  "P3":  /* unknown */ "Ein- oder Zweifamilienhaus",
  "A4":  /* unknown */ "Baujahr des Gebäudes",
  "B4":  /* unknown */ "build",
  "D4":  /* unknown */ "TYP_roof",
  "E4":  /* unknown */ "Dachform ",
  "G4":  /* unknown */ "Radio Button + Grafik",
  "J4":  /* unknown */ "String",
  "K4":  /* unknown */ 1,
  "P4":  /* unknown */ "steil",
  "W4":  /* unknown */ "geneigt: 25°, steil: 40°, sehr steil: 55°",
  "B5":  /* unknown */ "build",
  "D5":  /* unknown */ "YEAR_build_bj",
  "E5":  /* unknown */ "Baujahr",
  "G5":  /* unknown */ "Dropdown",
  "J5":  /* unknown */ "Integer",
  "K5":  /* unknown */ 1,
  "P5":  /* unknown */ "1979 - 1983",
  "B6":  /* unknown */ "build",
  "C6":  /* unknown */ "san",
  "E6":  /* unknown */ "Wurde eines der folgenden Bauteile nachträglich gedämmt / ausgetauscht? ... und ist das Modernisierungsjahr ... Dämmstärke (Freifeld Integer, cm)",
  "B7":  /* unknown */ "build",
  "C7":  /* unknown */ "san",
  "D7":  /* unknown */ "_build_wall_san",
  "E7":  /* unknown */ "Außenwand",
  "G7":  /* unknown */ "siehe Mockups",
  "K7":  /* unknown */ 0,
  "Q7":  /* unknown */ "Nein",
  "R7":  /* formula */ "_xlfn.IFS(AND(RIGHT($P$5,4)<=\"1978\",$Q$7=\"Ja\"),Daten!$M$65,AND(RIGHT($P$5,4)>\"1978\",$Q$7=\"Ja\"),Daten!$M$66,$Q$7=\"Nein\",$P$5)",
  "S7":  /* formula */ "$R7",
  "T7":  /* formula */ "IF(Q7=\"Ja\",_xlfn.XLOOKUP(1, (UWert_Mod[Bauteil]=E7)*(UWert_Mod[Modernisierungsjahr]=S7), UWert_Mod[d_ins]),0)",
  "U7":  /* formula */ "$T7",
  "B8":  /* unknown */ "build",
  "C8":  /* unknown */ "san",
  "D8":  /* unknown */ "_build_win_san",
  "E8":  /* unknown */ "Fenster",
  "G8":  /* unknown */ "siehe Mockups",
  "K8":  /* unknown */ 0,
  "Q8":  /* unknown */ "Nein",
  "R8":  /* formula */ "_xlfn.IFS(AND(RIGHT($P$5,4)<=\"1978\",$Q$8=\"Ja\"),Daten!$M$66,AND(RIGHT($P$5,4)>\"1978\",$Q$8=\"Ja\"),U_Werte_IWU!$D$78,$Q$8=\"Nein\",$P$5)",
  "S8":  /* formula */ "$R8",
  "B9":  /* unknown */ "build",
  "C9":  /* unknown */ "san",
  "D9":  /* unknown */ "_build_roof_san",
  "E9":  /* unknown */ "Dach",
  "G9":  /* unknown */ "siehe Mockups",
  "K9":  /* unknown */ 0,
  "Q9":  /* unknown */ "Nein",
  "R9":  /* formula */ "_xlfn.IFS(AND(RIGHT($P$5,4)<=\"1978\",$Q$9=\"Ja\"),Daten!$M$65,AND(RIGHT($P$5,4)>\"1978\",$Q$9=\"Ja\"),Daten!$M$66,$Q$9=\"Nein\",$P$5)",
  "S9":  /* formula */ "$R9",
  "T9":  /* formula */ "IF(Q9=\"Ja\",_xlfn.XLOOKUP(1, (UWert_Mod[Bauteil]=E9)*(UWert_Mod[Modernisierungsjahr]=S9), UWert_Mod[d_ins]),0)",
  "U9":  /* formula */ "$T9",
  "B10":  /* unknown */ "build",
  "C10":  /* unknown */ "san",
  "D10":  /* unknown */ "_build_botceil_san",
  "E10":  /* unknown */ "Fußboden",
  "G10":  /* unknown */ "siehe Mockups",
  "K10":  /* unknown */ 0,
  "Q10":  /* unknown */ "Nein",
  "R10":  /* formula */ "_xlfn.IFS(AND(RIGHT($P$5,4)<=\"1978\",$Q$10=\"Ja\"),Daten!$M$77,AND(RIGHT($P$5,4)>\"1978\",$Q$10=\"Ja\"),Daten!$M$78,$Q$10=\"Nein\",$P$5)",
  "S10":  /* formula */ "$R10",
  "T10":  /* formula */ "IF(Q10=\"Ja\",_xlfn.XLOOKUP(1, (UWert_Mod[Bauteil]=E10)*(UWert_Mod[Modernisierungsjahr]=S10), UWert_Mod[d_ins]),0)",
  "U10":  /* formula */ "$T10",
  "B11":  /* unknown */ "build",
  "C11":  /* unknown */ "san",
  "D11":  /* unknown */ "_build_topceil_san",
  "E11":  /* unknown */ "Decke",
  "G11":  /* unknown */ "siehe Mockups",
  "K11":  /* unknown */ 0,
  "Q11":  /* unknown */ "Nein",
  "R11":  /* formula */ "_xlfn.IFS(AND(RIGHT($P$5,4)<=\"1978\",$Q$11=\"Ja\"),Daten!$M$65,AND(RIGHT($P$5,4)>\"1978\",$Q$11=\"Ja\"),Daten!$M$66,$Q$11=\"Nein\",$P$5)",
  "S11":  /* formula */ "$R11",
  "T11":  /* formula */ "IF(Q11=\"Ja\",_xlfn.XLOOKUP(1, (UWert_Mod[Bauteil]=E11)*(UWert_Mod[Modernisierungsjahr]=S11), UWert_Mod[d_ins]),0)",
  "U11":  /* formula */ "$T11",
  "B12":  /* unknown */ "build",
  "D12":  /* unknown */ "EXIST_build_eff",
  "E12":  /* unknown */ "Ist Ihnen die Effizienzklasse bekannt? ",
  "G12":  /* unknown */ "Dropdown",
  "K12":  /* unknown */ 0,
  "O12":  /* unknown */ "Nicht bekannt",
  "P12":  /* formula */ "$O$12",
  "A13":  /* unknown */ "Denkmalschutz",
  "B13":  /* unknown */ "build",
  "D13":  /* unknown */ "EXIST_build_denkmal",
  "E13":  /* unknown */ "Das Gebäude steht unter Denkmalschutz",
  "G13":  /* unknown */ "toggle switch",
  "K13":  /* unknown */ 1,
  "O13":  /* unknown */ "Nein",
  "P13":  /* formula */ "$O$13",
  "A14":  /* unknown */ "Wärmeübergabe",
  "B14":  /* unknown */ "build",
  "D14":  /* unknown */ "TYP_build_rad",
  "E14":  /* unknown */ "Wie werden die Räume erwärmt?",
  "G14":  /* unknown */ "Radio Button + Grafik",
  "K14":  /* unknown */ 1,
  "P14":  /* unknown */ "Heizkörper",
  "B15":  /* unknown */ "build",
  "D15":  /* unknown */ "TYP_distr",
  "E15":  /* unknown */ "Wie wird die Wärme verteilt?",
  "G15":  /* unknown */ "Radio Button",
  "K15":  /* unknown */ 1,
  "P15":  /* unknown */ "Zweirohrheizung",
  "B16":  /* unknown */ "build",
  "D16":  /* unknown */ "EXIST_T_VL_set",
  "E16":  /* unknown */ "Ich weiß auf welche Vorlauftemperatur am Auslegungspunkt die Heizung eingestellt ist",
  "G16":  /* unknown */ "toggle switch",
  "J16":  /* unknown */ "Boolean",
  "K16":  /* unknown */ 1,
  "O16":  /* unknown */ "Nein",
  "P16":  /* formula */ "$O$16",
  "B17":  /* unknown */ "build",
  "D17":  /* unknown */ "T_VL_nom_set ",
  "E17":  /* unknown */ "Vorlauftemperatur am Auslegungspunkt",
  "G17":  /* unknown */ "Freifeld",
  "H17":  /* unknown */ "EXIST_T_VL_set",
  "I17":  /* unknown */ "°C",
  "J17":  /* unknown */ "Integer",
  "K17":  /* unknown */ 1,
  "M17":  /* unknown */ 30,
  "N17":  /* unknown */ 90,
  "B18":  /* unknown */ "build",
  "D18":  /* unknown */ "EXIST_T_VL_meas",
  "E18":  /* unknown */ "Ich kann im Heizungsraum die Vorlauftemperatur ablesen und die Außentemperatur messen",
  "G18":  /* unknown */ "toggle switch",
  "K18":  /* unknown */ 1,
  "O18":  /* unknown */ "Nein",
  "P18":  /* formula */ "$O$18",
  "B19":  /* unknown */ "build",
  "D19":  /* unknown */ "T_VL_meas ",
  "E19":  /* unknown */ "Bitte tragen Sie die Vorlauftemperatur ein",
  "G19":  /* unknown */ "Freifeld",
  "H19":  /* unknown */ "EXIST_T_VL_meas",
  "I19":  /* unknown */ "°C",
  "J19":  /* unknown */ "Integer",
  "K19":  /* unknown */ 1,
  "M19":  /* unknown */ 30,
  "N19":  /* unknown */ 90,
  "B20":  /* unknown */ "build",
  "D20":  /* unknown */ "T_amb_meas ",
  "E20":  /* unknown */ "Bitte tragen Sie die Außentemperatur ein",
  "G20":  /* unknown */ "Freifeld",
  "H20":  /* unknown */ "EXIST_T_VL_meas",
  "I20":  /* unknown */ "°C",
  "J20":  /* unknown */ "Integer",
  "K20":  /* unknown */ 1,
  "M20":  /* unknown */ -20,
  "N20":  /* unknown */ 40,
  "B21":  /* unknown */ "build",
  "D21":  /* unknown */ "INTERN_T_VL_nom_calc",
  "H21":  /* unknown */ "EXIST_T_VL_meas",
  "I21":  /* unknown */ "°C",
  "J21":  /* unknown */ "Integer",
  "P21":  /* formula */ "P20*-1.8257+43.457+P20",
  "D22":  /* unknown */ "INTERN_EXIST_T_VL_nt",
  "H22":  /* unknown */ "EXIST_T_VL_meas",
  "J22":  /* unknown */ "Boolean",
  "P22":  /* formula */ "IF(P16=\"Ja\",P17<=55,IF(P18=\"Ja\",P19<P21,FALSE))",
  "B25":  /* unknown */ ">>> Filterung EXIST_T_VL_set und EXIST_T_VL_meas in Frontend umsetzen >>> ",
  "B26":  /* unknown */ ">>> Filterung Räume / list_rooms in Frontend umsetzen  >>>",
} as const;
