// Sheet: IN_rooms
export const data = {
  "A1":  /* unknown */ "Anmerkung (ifeu) ",
  "B1":  /* unknown */ "Bauteil (ifeu intern) ",
  "C1":  /* unknown */ "Frage (ifeu intern)",
  "D1":  /* unknown */ "Gruppe ",
  "E1":  /* unknown */ "Subgruppe",
  "F1":  /* unknown */ "Variable",
  "G1":  /* unknown */ "Fragentext ",
  "H1":  /* unknown */ "Hilfstext",
  "I1":  /* unknown */ "Antworttyp",
  "J1":  /* unknown */ "Filter ",
  "K1":  /* unknown */ "Einheit ",
  "L1":  /* unknown */ "Datentyp",
  "M1":  /* unknown */ "Pflichtfeld ",
  "N1":  /* unknown */ "Nachkommastellen",
  "O1":  /* unknown */ "min Wert",
  "P1":  /* unknown */ "max Wert",
  "Q1":  /* unknown */ "Wert intern",
  "R1":  /* unknown */ "Wert Räume -->",
  "S1":  /* unknown */ "Wert Räume -->",
  "T1":  /* unknown */ "Wert Räume -->",
  "U1":  /* unknown */ "Wert Räume -->",
  "V1":  /* unknown */ "Wert Räume -->",
  "W1":  /* unknown */ "Wert Räume -->",
  "X1":  /* unknown */ "Wert Räume -->",
  "Y1":  /* unknown */ "Wert Räume -->",
  "Z1":  /* unknown */ "Wert Räume -->",
  "AA1":  /* unknown */ "Wert Räume -->",
  "AB1":  /* unknown */ "Wert Räume -->",
  "AC1":  /* unknown */ "Wert Räume -->",
  "AD1":  /* unknown */ "Wert Räume -->",
  "AE1":  /* unknown */ "Wert Räume -->",
  "AF1":  /* unknown */ "Wert Räume -->",
  "C2":  /* unknown */ "Raumindex",
  "F2":  /* unknown */ "ID_R#",
  "I2":  /* unknown */ "Intern",
  "L2":  /* unknown */ "String",
  "R2":  /* unknown */ 1,
  "S2":  /* unknown */ 2,
  "T2":  /* unknown */ 3,
  "U2":  /* unknown */ 4,
  "V2":  /* unknown */ 5,
  "W2":  /* unknown */ 6,
  "X2":  /* unknown */ 7,
  "Y2":  /* unknown */ 8,
  "Z2":  /* unknown */ 9,
  "AA2":  /* unknown */ 10,
  "AB2":  /* unknown */ 11,
  "AC2":  /* unknown */ 12,
  "AD2":  /* unknown */ 13,
  "AE2":  /* unknown */ 14,
  "AF2":  /* unknown */ 15,
  "A3":  /* unknown */ ">> Name kommt aus list_rooms, aber als Ausgabegröße relevant",
  "C3":  /* unknown */ "Raumbezeichnung",
  "F3":  /* unknown */ "TXT_room_name",
  "G3":  /* unknown */ "Name des Raums",
  "I3":  /* unknown */ "Ausgabe",
  "L3":  /* unknown */ "String",
  "R3":  /* unknown */ "SZ",
  "S3":  /* unknown */ "WZ",
  "T3":  /* unknown */ "Schlafzimmer",
  "U3":  /* unknown */ "Kinderzimmer",
  "V3":  /* unknown */ "Kinderzimmer",
  "W3":  /* unknown */ "Esszimmer",
  "X3":  /* formula */ "\"\"",
  "Y3":  /* formula */ "\"\"",
  "Z3":  /* formula */ "\"\"",
  "AA3":  /* formula */ "\"\"",
  "AB3":  /* formula */ "\"\"",
  "AC3":  /* formula */ "\"\"",
  "AD3":  /* formula */ "\"\"",
  "AE3":  /* formula */ "\"\"",
  "AF3":  /* formula */ "\"\"",
  "C4":  /* unknown */ "Wohnfläche",
  "F4":  /* unknown */ "A_floor",
  "G4":  /* unknown */ "Raumfläche",
  "I4":  /* unknown */ "Freitext",
  "K4":  /* unknown */ "m²",
  "L4":  /* unknown */ "Real",
  "M4":  /* unknown */ 1,
  "N4":  /* unknown */ 1,
  "O4":  /* unknown */ 1,
  "P4":  /* unknown */ 100,
  "R4":  /* unknown */ 9,
  "S4":  /* formula */ "3.2*5",
  "T4":  /* unknown */ 12,
  "U4":  /* unknown */ 10,
  "V4":  /* unknown */ 12,
  "W4":  /* unknown */ 15,
  "C5":  /* unknown */ "Raumhöhe",
  "F5":  /* unknown */ "L_hei",
  "G5":  /* unknown */ "Raumhöhe",
  "I5":  /* unknown */ "Freitext ",
  "K5":  /* unknown */ "m",
  "L5":  /* unknown */ "Real",
  "M5":  /* unknown */ 1,
  "N5":  /* unknown */ 2,
  "O5":  /* unknown */ 1,
  "P5":  /* unknown */ 5,
  "Q5":  /* unknown */ 2.5,
  "R5":  /* unknown */ 3.75,
  "S5":  /* unknown */ 3.75,
  "T5":  /* formula */ "$Q$5",
  "U5":  /* formula */ "$Q$5",
  "V5":  /* formula */ "$Q$5",
  "W5":  /* formula */ "$Q$5",
  "X5":  /* formula */ "$Q$5",
  "Y5":  /* formula */ "$Q$5",
  "Z5":  /* formula */ "$Q$5",
  "AA5":  /* formula */ "$Q$5",
  "AB5":  /* formula */ "$Q$5",
  "AC5":  /* formula */ "$Q$5",
  "AD5":  /* formula */ "$Q$5",
  "AE5":  /* formula */ "$Q$5",
  "AF5":  /* formula */ "$Q$5",
  "C6":  /* unknown */ "Gewünschte Raumtemperatur",
  "F6":  /* unknown */ "T_air_set",
  "G6":  /* unknown */ "gewünsche Raumtemperatur",
  "H6":  /* unknown */ "Es werden typischerweise 20°C in Wohnräumen und 24°C in Bädern angesetzt. Ihre Eigenen Komforttemperaturen können davon abweichen. ",
  "I6":  /* unknown */ "Freitext ",
  "K6":  /* unknown */ "°C",
  "L6":  /* unknown */ "Integer",
  "N6":  /* unknown */ 0,
  "O6":  /* unknown */ 10,
  "P6":  /* unknown */ 30,
  "Q6":  /* unknown */ 20,
  "R6":  /* formula */ "$Q$6",
  "S6":  /* formula */ "$Q$6",
  "T6":  /* unknown */ 20,
  "U6":  /* formula */ "$Q$6",
  "V6":  /* formula */ "$Q$6",
  "W6":  /* formula */ "$Q$6",
  "X6":  /* formula */ "$Q$6",
  "Y6":  /* formula */ "$Q$6",
  "Z6":  /* formula */ "$Q$6",
  "AA6":  /* formula */ "$Q$6",
  "AB6":  /* formula */ "$Q$6",
  "AC6":  /* formula */ "$Q$6",
  "AD6":  /* formula */ "$Q$6",
  "AE6":  /* formula */ "$Q$6",
  "AF6":  /* formula */ "$Q$6",
  "B7":  /* unknown */ "Decke",
  "C7":  /* unknown */ "Grenzt an",
  "D7":  /* unknown */ "topceil",
  "F7":  /* unknown */ "TYP_V_above",
  "G7":  /* unknown */ "<abbr title=\"Hiermit ist die horizontale Decke des Raumes gemeint. Befindet sich über dieser Decke ein Dachboden, wählen Sie \"unbeheizt\".\"> Decke  </abbr> grenzt an",
  "I7":  /* unknown */ "Dropdown",
  "J7":  /* unknown */ "TYP_roof =! \"Flach bzw. Flachdach\"",
  "L7":  /* unknown */ "String",
  "M7":  /* unknown */ 1,
  "Q7":  /* unknown */ "unbeheizt",
  "R7":  /* unknown */ "beheizt ",
  "S7":  /* unknown */ "beheizt ",
  "T7":  /* unknown */ "beheizt ",
  "U7":  /* unknown */ "beheizt ",
  "V7":  /* formula */ "$Q7",
  "W7":  /* formula */ "$Q7",
  "X7":  /* formula */ "$Q7",
  "Y7":  /* formula */ "$Q7",
  "Z7":  /* formula */ "$Q7",
  "AA7":  /* formula */ "$Q7",
  "AB7":  /* formula */ "$Q7",
  "AC7":  /* formula */ "$Q7",
  "AD7":  /* formula */ "$Q7",
  "AE7":  /* formula */ "$Q7",
  "AF7":  /* formula */ "$Q7",
  "B8":  /* unknown */ "Fußboden",
  "C8":  /* unknown */ "Grenzt an",
  "D8":  /* unknown */ "botceil",
  "F8":  /* unknown */ "TYP_V_below",
  "G8":  /* unknown */ "Fußboden grenzt an",
  "I8":  /* unknown */ "Dropdown",
  "L8":  /* unknown */ "String",
  "M8":  /* unknown */ 1,
  "Q8":  /* unknown */ "unbeheizt",
  "R8":  /* unknown */ "Außenluft",
  "S8":  /* unknown */ "beheizt ",
  "T8":  /* formula */ "$Q8",
  "U8":  /* unknown */ "unbeheizt",
  "V8":  /* unknown */ "beheizt ",
  "W8":  /* formula */ "$Q8",
  "X8":  /* formula */ "$Q8",
  "Y8":  /* formula */ "$Q8",
  "Z8":  /* formula */ "$Q8",
  "AA8":  /* formula */ "$Q8",
  "AB8":  /* formula */ "$Q8",
  "AC8":  /* formula */ "$Q8",
  "AD8":  /* formula */ "$Q8",
  "AE8":  /* formula */ "$Q8",
  "AF8":  /* formula */ "$Q8",
  "B9":  /* unknown */ "Außenwand",
  "C9":  /* unknown */ "Länge",
  "D9":  /* unknown */ "wall",
  "F9":  /* unknown */ "L_wall_tot",
  "G9":  /* unknown */ "Gesamtlänge der <abbr title=\"Bitte berücksichtigen Sie nur raumhohe Außenwände, die direkten Kontakt zur Außenluft haben.\"> Außenwände </abbr> ",
  "I9":  /* unknown */ "Freitext ",
  "K9":  /* unknown */ "m",
  "L9":  /* unknown */ "Real",
  "M9":  /* unknown */ 1,
  "N9":  /* unknown */ 2,
  "O9":  /* unknown */ 0,
  "P9":  /* unknown */ 20,
  "R9":  /* unknown */ 2.5,
  "S9":  /* unknown */ 3.2,
  "T9":  /* unknown */ 6,
  "U9":  /* unknown */ 4,
  "V9":  /* unknown */ 6,
  "W9":  /* unknown */ 8,
  "D10":  /* unknown */ "wall",
  "F10":  /* unknown */ "UI_YEAR_wall_ins",
  "G10":  /* unknown */ "Abweichendes Modernisierungsjahr ",
  "I10":  /* unknown */ "Dropdown",
  "L10":  /* unknown */ "Integer",
  "M10":  /* unknown */ 0,
  "N10":  /* unknown */ 0,
  "A11":  /* unknown */ "Anpassung Berechnung U-Wert: über IWU Tablua anstatt Dämmschichtdicke? Oder Dämmschichtdicke anhand Jahr Modernisierung (Tabelle unten)? Oder EnEV/GEG Vorgaben und anhand Novellen? >> Peter: es gibt Input GEMOD ",
  "B11":  /* unknown */ "Außenwand",
  "C11":  /* unknown */ "Von Gebäude abweichende Dämmschicht? ",
  "D11":  /* unknown */ "wall",
  "F11":  /* unknown */ "UI_L_wall_ins",
  "G11":  /* unknown */ "Abweichende Dämmstärke? ",
  "I11":  /* unknown */ "Freitext",
  "J11":  /* unknown */ "EXIST_build_wall_san",
  "K11":  /* unknown */ "cm",
  "L11":  /* unknown */ "Real",
  "N11":  /* unknown */ 2,
  "O11":  /* unknown */ 0,
  "P11":  /* unknown */ 50,
  "R11":  /* unknown */ 5,
  "S11":  /* unknown */ 5,
  "A12":  /* unknown */ "Vorschlag: bei Außenwand immer Außenluft ansetzen? Kellerraum =! Schlechtpunkt, aber ggf. AW gegen unbeheizt? ",
  "B12":  /* unknown */ "Außenwand Art",
  "D12":  /* unknown */ "intern",
  "F12":  /* unknown */ "INTERN_TYP_wall_grenztan_intern",
  "Q12":  /* unknown */ "Außenluft",
  "R12":  /* formula */ "$Q12",
  "S12":  /* formula */ "$Q12",
  "T12":  /* formula */ "$Q12",
  "U12":  /* formula */ "$Q12",
  "V12":  /* formula */ "$Q12",
  "W12":  /* formula */ "$Q12",
  "X12":  /* formula */ "$Q12",
  "Y12":  /* formula */ "$Q12",
  "Z12":  /* formula */ "$Q12",
  "AA12":  /* formula */ "$Q12",
  "AB12":  /* formula */ "$Q12",
  "AC12":  /* formula */ "$Q12",
  "AD12":  /* formula */ "$Q12",
  "AE12":  /* formula */ "$Q12",
  "AF12":  /* formula */ "$Q12",
  "B13":  /* unknown */ "Fenstertyp 1",
  "C13":  /* unknown */ "Breite",
  "D13":  /* unknown */ "wall",
  "E13":  /* unknown */ "win1",
  "F13":  /* formula */ "\"L_\"&D13&\"_\"&E13&\"_wid\"",
  "G13":  /* unknown */ "Geben Sie die Abmaße des Fenstertyps an, Breite",
  "I13":  /* unknown */ "Freitext",
  "K13":  /* unknown */ "m",
  "L13":  /* unknown */ "Real",
  "M13":  /* unknown */ 0,
  "N13":  /* unknown */ 0,
  "O13":  /* unknown */ 0.2,
  "P13":  /* unknown */ 4,
  "R13":  /* unknown */ 1.2,
  "S13":  /* unknown */ 1.2,
  "T13":  /* unknown */ 2,
  "U13":  /* unknown */ 1,
  "V13":  /* unknown */ 0.5,
  "W13":  /* unknown */ 2,
  "B14":  /* unknown */ "Fenstertyp 1",
  "C14":  /* unknown */ "Höhe ",
  "D14":  /* unknown */ "wall",
  "E14":  /* unknown */ "win1",
  "F14":  /* formula */ "\"L_\"&D14&\"_\"&E14&\"_hei\"",
  "G14":  /* unknown */ "Höhe ",
  "I14":  /* unknown */ "Freitext",
  "K14":  /* unknown */ "m",
  "L14":  /* unknown */ "Real",
  "M14":  /* unknown */ 0,
  "N14":  /* unknown */ 0,
  "O14":  /* unknown */ 0.2,
  "P14":  /* unknown */ 2.5,
  "R14":  /* unknown */ 2.3,
  "S14":  /* unknown */ 2.3,
  "T14":  /* unknown */ 1,
  "U14":  /* unknown */ 1,
  "V14":  /* unknown */ 1,
  "W14":  /* unknown */ 2,
  "A15":  /* unknown */ "siehe YEAR_wall_ins",
  "B15":  /* unknown */ "Fenstertyp 1",
  "C15":  /* unknown */ "Jahr, in dem die Fenster zuletzt ausgetauscht wurden",
  "D15":  /* unknown */ "wall",
  "E15":  /* unknown */ "win1",
  "F15":  /* formula */ "\"YEAR_\"&D15&\"_\"&E15",
  "G15":  /* unknown */ "Abweichendes Einbaujahr ",
  "I15":  /* unknown */ "Dropdown",
  "L15":  /* unknown */ "Integer",
  "M15":  /* unknown */ 0,
  "U15":  /* unknown */ "2003 - 2008",
  "W15":  /* unknown */ "1995 - 2002",
  "A16":  /* unknown */ "Multiplikator aufnehmen",
  "B16":  /* unknown */ "Fenstertyp 1",
  "C16":  /* unknown */ "Anzahl",
  "D16":  /* unknown */ "wall",
  "E16":  /* unknown */ "win1",
  "F16":  /* formula */ "\"NO_\"&D16&\"_\"&E16",
  "G16":  /* unknown */ "Anzahl identischer Fenster im Raum ",
  "I16":  /* unknown */ "Freitext",
  "L16":  /* unknown */ "Integer",
  "M16":  /* unknown */ 0,
  "N16":  /* unknown */ 0,
  "O16":  /* unknown */ 0,
  "P16":  /* unknown */ 10,
  "Q16":  /* unknown */ 1,
  "R16":  /* formula */ "$Q16",
  "S16":  /* unknown */ 2,
  "T16":  /* unknown */ 1,
  "U16":  /* unknown */ 2,
  "V16":  /* formula */ "$Q16",
  "W16":  /* formula */ "$Q16",
  "X16":  /* formula */ "$Q16",
  "Y16":  /* formula */ "$Q16",
  "Z16":  /* formula */ "$Q16",
  "AA16":  /* formula */ "$Q16",
  "AB16":  /* formula */ "$Q16",
  "AC16":  /* formula */ "$Q16",
  "AD16":  /* formula */ "$Q16",
  "AE16":  /* formula */ "$Q16",
  "AF16":  /* formula */ "$Q16",
  "B17":  /* unknown */ "Fenstertyp 2",
  "C17":  /* unknown */ "Breite",
  "D17":  /* unknown */ "wall",
  "E17":  /* unknown */ "win2",
  "F17":  /* formula */ "\"L_\"&D17&\"_\"&E17&\"_wid\"",
  "G17":  /* unknown */ "Geben Sie die Abmaße des Fenstertyps an, Breite",
  "I17":  /* unknown */ "Freitext",
  "K17":  /* unknown */ "m",
  "L17":  /* unknown */ "Real",
  "M17":  /* unknown */ 1,
  "N17":  /* unknown */ 0,
  "O17":  /* unknown */ 0.2,
  "P17":  /* unknown */ 4,
  "T17":  /* unknown */ 1,
  "W17":  /* unknown */ 1,
  "B18":  /* unknown */ "Fenstertyp 2",
  "C18":  /* unknown */ "Höhe ",
  "D18":  /* unknown */ "wall",
  "E18":  /* unknown */ "win2",
  "F18":  /* formula */ "\"L_\"&D18&\"_\"&E18&\"_hei\"",
  "G18":  /* unknown */ "Höhe ",
  "I18":  /* unknown */ "Freitext",
  "K18":  /* unknown */ "m",
  "L18":  /* unknown */ "Real",
  "M18":  /* unknown */ 1,
  "N18":  /* unknown */ 0,
  "O18":  /* unknown */ 0.2,
  "P18":  /* unknown */ 2.5,
  "T18":  /* unknown */ 1,
  "W18":  /* unknown */ 1,
  "B19":  /* unknown */ "Fenstertyp 2",
  "C19":  /* unknown */ "Jahr, in dem die Fenster zuletzt ausgetauscht wurden",
  "D19":  /* unknown */ "wall",
  "E19":  /* unknown */ "win2",
  "F19":  /* formula */ "\"YEAR_\"&D19&\"_\"&E19",
  "G19":  /* unknown */ "Abweichendes Einbaujahr ",
  "I19":  /* unknown */ "Dropdown",
  "L19":  /* unknown */ "Integer",
  "M19":  /* unknown */ 0,
  "W19":  /* unknown */ "1995 - 2002",
  "A20":  /* unknown */ "Multiplikator aufnehmen",
  "B20":  /* unknown */ "Fenstertyp 2",
  "D20":  /* unknown */ "wall",
  "E20":  /* unknown */ "win2",
  "F20":  /* formula */ "\"NO_\"&D20&\"_\"&E20",
  "G20":  /* unknown */ "Anzahl identischer Fenster im Raum ",
  "I20":  /* unknown */ "Freitext",
  "L20":  /* unknown */ "Integer",
  "M20":  /* unknown */ 0,
  "N20":  /* unknown */ 0,
  "O20":  /* unknown */ 0,
  "P20":  /* unknown */ 10,
  "Q20":  /* unknown */ 1,
  "R20":  /* formula */ "$Q20",
  "S20":  /* formula */ "$Q20",
  "T20":  /* formula */ "$Q20",
  "U20":  /* formula */ "$Q20",
  "V20":  /* formula */ "$Q20",
  "W20":  /* formula */ "$Q20",
  "X20":  /* formula */ "$Q20",
  "Y20":  /* formula */ "$Q20",
  "Z20":  /* formula */ "$Q20",
  "AA20":  /* formula */ "$Q20",
  "AB20":  /* formula */ "$Q20",
  "AC20":  /* formula */ "$Q20",
  "AD20":  /* formula */ "$Q20",
  "AE20":  /* formula */ "$Q20",
  "AF20":  /* formula */ "$Q20",
  "B21":  /* unknown */ "Fenstertyp 3",
  "C21":  /* unknown */ "Breite",
  "D21":  /* unknown */ "wall",
  "E21":  /* unknown */ "win3",
  "F21":  /* formula */ "\"L_\"&D21&\"_\"&E21&\"_wid\"",
  "G21":  /* unknown */ "Geben Sie die Abmaße des dritten Fenstertyps an, Breite",
  "I21":  /* unknown */ "Freitext",
  "K21":  /* unknown */ "m",
  "L21":  /* unknown */ "Real",
  "M21":  /* unknown */ 1,
  "N21":  /* unknown */ 0,
  "O21":  /* unknown */ 0.2,
  "P21":  /* unknown */ 4,
  "B22":  /* unknown */ "Fenstertyp 3",
  "C22":  /* unknown */ "Höhe ",
  "D22":  /* unknown */ "wall",
  "E22":  /* unknown */ "win3",
  "F22":  /* formula */ "\"L_\"&D22&\"_\"&E22&\"_hei\"",
  "G22":  /* unknown */ "Höhe ",
  "I22":  /* unknown */ "Freitext",
  "K22":  /* unknown */ "m",
  "L22":  /* unknown */ "Real",
  "M22":  /* unknown */ 1,
  "N22":  /* unknown */ 0,
  "O22":  /* unknown */ 0.2,
  "P22":  /* unknown */ 2.5,
  "B23":  /* unknown */ "Fenstertyp 3",
  "C23":  /* unknown */ "Jahr, in dem die Fenster zuletzt ausgetauscht wurden",
  "D23":  /* unknown */ "wall",
  "E23":  /* unknown */ "win3",
  "F23":  /* formula */ "\"YEAR_\"&D23&\"_\"&E23",
  "G23":  /* unknown */ "Abweichendes Einbaujahr ",
  "I23":  /* unknown */ "Dropdown",
  "L23":  /* unknown */ "Integer",
  "M23":  /* unknown */ 0,
  "A24":  /* unknown */ "Multiplikator aufnehmen",
  "B24":  /* unknown */ "Fenstertyp 3",
  "C24":  /* unknown */ "Anzahl",
  "D24":  /* unknown */ "wall",
  "E24":  /* unknown */ "win3",
  "F24":  /* formula */ "\"NO_\"&D24&\"_\"&E24",
  "G24":  /* unknown */ "Anzahl identischer Fenster im Raum ",
  "I24":  /* unknown */ "Freitext",
  "L24":  /* unknown */ "Integer",
  "M24":  /* unknown */ 0,
  "N24":  /* unknown */ 0,
  "O24":  /* unknown */ 0,
  "P24":  /* unknown */ 10,
  "Q24":  /* unknown */ 1,
  "R24":  /* formula */ "$Q24",
  "S24":  /* formula */ "$Q24",
  "T24":  /* formula */ "$Q24",
  "U24":  /* formula */ "$Q24",
  "V24":  /* formula */ "$Q24",
  "W24":  /* formula */ "$Q24",
  "X24":  /* formula */ "$Q24",
  "Y24":  /* formula */ "$Q24",
  "Z24":  /* formula */ "$Q24",
  "AA24":  /* formula */ "$Q24",
  "AB24":  /* formula */ "$Q24",
  "AC24":  /* formula */ "$Q24",
  "AD24":  /* formula */ "$Q24",
  "AE24":  /* formula */ "$Q24",
  "AF24":  /* formula */ "$Q24",
  "D25":  /* unknown */ "innerwall",
  "F25":  /* unknown */ "EXIST_innerwall",
  "G25":  /* unknown */ "Innenwände gegen unbeheizt vorhanden?",
  "I25":  /* unknown */ "toggle switch ",
  "L25":  /* unknown */ "Boolean",
  "M25":  /* unknown */ 1,
  "Q25":  /* unknown */ "Nein",
  "R25":  /* formula */ "$Q25",
  "S25":  /* unknown */ "Nein",
  "T25":  /* unknown */ "Ja",
  "U25":  /* formula */ "$Q25",
  "V25":  /* formula */ "$Q25",
  "W25":  /* formula */ "$Q25",
  "X25":  /* formula */ "$Q25",
  "Y25":  /* formula */ "$Q25",
  "Z25":  /* formula */ "$Q25",
  "AA25":  /* formula */ "$Q25",
  "AB25":  /* formula */ "$Q25",
  "AC25":  /* formula */ "$Q25",
  "AD25":  /* formula */ "$Q25",
  "AE25":  /* formula */ "$Q25",
  "AF25":  /* formula */ "$Q25",
  "D26":  /* unknown */ "innerwall",
  "F26":  /* unknown */ "L_innerwall_tot",
  "G26":  /* unknown */ "Gesamtlänge der Innenwände gegen unbeheizte Räume",
  "I26":  /* unknown */ "Freitext",
  "J26":  /* unknown */ "EXIST_innerwall",
  "K26":  /* unknown */ "m",
  "L26":  /* unknown */ "Real",
  "M26":  /* unknown */ 0,
  "N26":  /* unknown */ 2,
  "O26":  /* unknown */ 1,
  "P26":  /* unknown */ 20,
  "T26":  /* unknown */ 2,
  "D27":  /* unknown */ "innerwall",
  "F27":  /* unknown */ "L_innerwall_ins",
  "G27":  /* unknown */ "Dämmung vorhanden?",
  "I27":  /* unknown */ "Freitext",
  "J27":  /* unknown */ "EXIST_innerwall",
  "K27":  /* unknown */ "cm",
  "L27":  /* unknown */ "Real",
  "M27":  /* unknown */ 0,
  "N27":  /* unknown */ 0,
  "O27":  /* unknown */ 0,
  "P27":  /* unknown */ 50,
  "Q27":  /* unknown */ 0,
  "R27":  /* formula */ "$Q$27",
  "S27":  /* formula */ "$Q$27",
  "T27":  /* formula */ "$Q$27",
  "U27":  /* formula */ "$Q$27",
  "V27":  /* formula */ "$Q$27",
  "W27":  /* formula */ "$Q$27",
  "X27":  /* formula */ "$Q$27",
  "Y27":  /* formula */ "$Q$27",
  "Z27":  /* formula */ "$Q$27",
  "AA27":  /* formula */ "$Q$27",
  "AB27":  /* formula */ "$Q$27",
  "AC27":  /* formula */ "$Q$27",
  "AD27":  /* formula */ "$Q$27",
  "AE27":  /* formula */ "$Q$27",
  "AF27":  /* formula */ "$Q$27",
  "B28":  /* unknown */ "Dachfläche",
  "D28":  /* unknown */ "roof",
  "F28":  /* unknown */ "EXIST_roof",
  "G28":  /* unknown */ "Dachschräge vorhanden? ",
  "I28":  /* unknown */ "toggle switch ",
  "L28":  /* unknown */ "Boolean",
  "M28":  /* unknown */ 1,
  "R28":  /* unknown */ "Nein",
  "S28":  /* unknown */ "Nein",
  "V28":  /* unknown */ "Ja",
  "W28":  /* unknown */ "Nein",
  "B29":  /* unknown */ "Dachfläche",
  "D29":  /* unknown */ "roof",
  "F29":  /* unknown */ "NO_roof_slop",
  "G29":  /* unknown */ "Hat der Raum mehr als 1 Dachschräge?",
  "I29":  /* unknown */ "toggle switch ",
  "J29":  /* unknown */ "EXIST_roof AND TYP_roof =/ \"Flach bzw. Flachdach\"",
  "L29":  /* unknown */ "Boolean",
  "M29":  /* unknown */ 1,
  "Q29":  /* unknown */ "Nein",
  "R29":  /* formula */ "$Q$29",
  "S29":  /* unknown */ "Nein",
  "T29":  /* unknown */ "Nein",
  "U29":  /* formula */ "$Q$29",
  "V29":  /* unknown */ "Ja",
  "W29":  /* formula */ "$Q$29",
  "X29":  /* formula */ "$Q$29",
  "Y29":  /* formula */ "$Q$29",
  "Z29":  /* formula */ "$Q$29",
  "AA29":  /* formula */ "$Q$29",
  "AB29":  /* formula */ "$Q$29",
  "AC29":  /* formula */ "$Q$29",
  "AD29":  /* formula */ "$Q$29",
  "AE29":  /* formula */ "$Q$29",
  "AF29":  /* formula */ "$Q$29",
  "B30":  /* unknown */ "Dachfläche",
  "C30":  /* unknown */ "Breite ",
  "D30":  /* unknown */ "roof",
  "F30":  /* unknown */ "L_roof_wid",
  "G30":  /* unknown */ "Länge",
  "H30":  /* unknown */ "Bei mehreren Dachflächen bitte summieren",
  "I30":  /* unknown */ "Freitext",
  "J30":  /* unknown */ "EXIST_roof AND TYP_roof =/ \"Flach bzw. Flachdach\"",
  "K30":  /* unknown */ "m",
  "L30":  /* unknown */ "Real",
  "M30":  /* unknown */ 0,
  "N30":  /* unknown */ 2,
  "O30":  /* unknown */ 1,
  "P30":  /* unknown */ " ",
  "S30":  /* unknown */ 4,
  "V30":  /* unknown */ 4,
  "B31":  /* unknown */ "Dachfläche",
  "C31":  /* unknown */ "Höhe",
  "D31":  /* unknown */ "roof",
  "F31":  /* unknown */ "L_roof_hei",
  "G31":  /* unknown */ "Höhe ",
  "H31":  /* unknown */ "Bei mehreren Dachflächen bitte nicht summieren",
  "I31":  /* unknown */ "Freitext",
  "J31":  /* unknown */ "EXIST_roof AND TYP_roof =/ \"Flach bzw. Flachdach\"",
  "K31":  /* unknown */ "m",
  "L31":  /* unknown */ "Real",
  "M31":  /* unknown */ 0,
  "N31":  /* unknown */ 2,
  "O31":  /* unknown */ 1,
  "P31":  /* unknown */ 4,
  "S31":  /* unknown */ 2,
  "V31":  /* unknown */ 2.5,
  "D32":  /* unknown */ "topceil",
  "F32":  /* formula */ "\"L_\"&D32&\"_\"&E32&\"_wid\"",
  "G32":  /* unknown */ "Ist eine horizontale Decke vorhanden? Geben Sie bitte Breite an",
  "I32":  /* unknown */ "Freitext",
  "J32":  /* unknown */ "TYP_roof =/ \"Flach bzw. Flachdach\"",
  "K32":  /* unknown */ "m",
  "L32":  /* unknown */ "String",
  "M32":  /* unknown */ 1,
  "R32":  /* unknown */ 2.5,
  "S32":  /* unknown */ 3.2,
  "D33":  /* unknown */ "topceil",
  "F33":  /* formula */ "\"L_\"&D33&\"_\"&E33&\"_len\"",
  "G33":  /* unknown */ "Geben Sie die Anzahl der Giebelwände an. ",
  "I33":  /* unknown */ "Freitext",
  "J33":  /* unknown */ "TYP_roof =/ \"Flach bzw. Flachdach\"",
  "L33":  /* unknown */ "Integer",
  "M33":  /* unknown */ 1,
  "O33":  /* unknown */ 0,
  "P33":  /* unknown */ 2,
  "Q33":  /* unknown */ 1,
  "R33":  /* unknown */ 1,
  "S33":  /* unknown */ 1,
  "T33":  /* unknown */ 1,
  "U33":  /* unknown */ 1,
  "V33":  /* unknown */ 2,
  "B34":  /* unknown */ "Dachfläche",
  "D34":  /* unknown */ "roof",
  "F34":  /* unknown */ "L_roof_jamb_hei",
  "G34":  /* unknown */ "Falls eine Drempelwand bzw. Kniestock vorhanden ist, geben Sie die Höhe an",
  "I34":  /* unknown */ "Freitext",
  "J34":  /* unknown */ "EXIST_roof",
  "K34":  /* unknown */ "m",
  "L34":  /* unknown */ "Real",
  "M34":  /* unknown */ 1,
  "N34":  /* unknown */ 2,
  "V34":  /* unknown */ 0.5,
  "B35":  /* unknown */ "Dachfläche",
  "D35":  /* unknown */ "roof",
  "F35":  /* unknown */ "TYP_jamb_hei",
  "G35":  /* unknown */ "Klopfen Sie gegen die senkrechte Wand unter der Dachschräge. Klingt es hohl?",
  "I35":  /* unknown */ "toggle switch ",
  "J35":  /* unknown */ "EXIST_roof",
  "L35":  /* unknown */ "Boolean",
  "M35":  /* unknown */ 1,
  "Q35":  /* unknown */ "Ja",
  "R35":  /* unknown */ "Nein",
  "S35":  /* unknown */ "Nein",
  "T35":  /* formula */ "$Q$35",
  "U35":  /* formula */ "$Q$35",
  "V35":  /* formula */ "$Q$35",
  "W35":  /* formula */ "$Q$35",
  "X35":  /* formula */ "$Q$35",
  "Y35":  /* formula */ "$Q$35",
  "Z35":  /* formula */ "$Q$35",
  "AA35":  /* formula */ "$Q$35",
  "AB35":  /* formula */ "$Q$35",
  "AC35":  /* formula */ "$Q$35",
  "AD35":  /* formula */ "$Q$35",
  "AE35":  /* formula */ "$Q$35",
  "AF35":  /* formula */ "$Q$35",
  "B36":  /* unknown */ "Dachfläche",
  "D36":  /* unknown */ "intern",
  "F36":  /* unknown */ "EXIST_roof_knee_eff",
  "G36":  /* unknown */ "INTERN - Haben sie einen Kniestock unter der Dachschräge?",
  "I36":  /* unknown */ "toggle switch ",
  "J36":  /* unknown */ "EXIST_roof",
  "L36":  /* unknown */ "Boolean",
  "M36":  /* unknown */ 1,
  "R36":  /* formula */ "IF(R$35=\"Nein\",\"Ja\",\"Nein\")",
  "S36":  /* formula */ "IF(S$35=\"Nein\",\"Ja\",\"Nein\")",
  "T36":  /* formula */ "IF(T$35=\"Nein\",\"Ja\",\"Nein\")",
  "U36":  /* formula */ "IF(U$35=\"Nein\",\"Ja\",\"Nein\")",
  "V36":  /* formula */ "IF(V$35=\"Nein\",\"Ja\",\"Nein\")",
  "W36":  /* formula */ "IF(W$35=\"Nein\",\"Ja\",\"Nein\")",
  "X36":  /* formula */ "IF(X$35=\"Nein\",\"Ja\",\"Nein\")",
  "Y36":  /* formula */ "IF(Y$35=\"Nein\",\"Ja\",\"Nein\")",
  "Z36":  /* formula */ "IF(Z$35=\"Nein\",\"Ja\",\"Nein\")",
  "AA36":  /* formula */ "IF(AA$35=\"Nein\",\"Ja\",\"Nein\")",
  "AB36":  /* formula */ "IF(AB$35=\"Nein\",\"Ja\",\"Nein\")",
  "AC36":  /* formula */ "IF(AC$35=\"Nein\",\"Ja\",\"Nein\")",
  "AD36":  /* formula */ "IF(AD$35=\"Nein\",\"Ja\",\"Nein\")",
  "AE36":  /* formula */ "IF(AE$35=\"Nein\",\"Ja\",\"Nein\")",
  "AF36":  /* formula */ "IF(AF$35=\"Nein\",\"Ja\",\"Nein\")",
  "A37":  /* unknown */ "Einbezug Berechnung in DIN12831 klären",
  "B37":  /* unknown */ "Dachfläche",
  "C37":  /* unknown */ "Höhe",
  "D37":  /* unknown */ "intern",
  "F37":  /* unknown */ "L_roof_knee_hei_eff",
  "G37":  /* unknown */ "INTERN - Falls ein Kniestock vorhanden ist, geben Sie dessen Höhe an",
  "I37":  /* unknown */ "Freitext",
  "J37":  /* unknown */ "EXIST_roof_knee",
  "K37":  /* unknown */ "m",
  "L37":  /* unknown */ "Real",
  "M37":  /* unknown */ 0,
  "N37":  /* unknown */ 2,
  "O37":  /* unknown */ 0,
  "P37":  /* unknown */ 3,
  "R37":  /* formula */ "IF(R$35=\"Ja\",0,R$34)",
  "S37":  /* formula */ "IF(S$35=\"Ja\",0,S$34)",
  "T37":  /* formula */ "IF(T$35=\"Ja\",0,T$34)",
  "U37":  /* formula */ "IF(U$35=\"Ja\",0,U$34)",
  "V37":  /* formula */ "IF(V$35=\"Ja\",0,V$34)",
  "W37":  /* formula */ "IF(W$35=\"Ja\",0,W$34)",
  "X37":  /* formula */ "IF(X$35=\"Ja\",0,X$34)",
  "Y37":  /* formula */ "IF(Y$35=\"Ja\",0,Y$34)",
  "Z37":  /* formula */ "IF(Z$35=\"Ja\",0,Z$34)",
  "AA37":  /* formula */ "IF(AA$35=\"Ja\",0,AA$34)",
  "AB37":  /* formula */ "IF(AB$35=\"Ja\",0,AB$34)",
  "AC37":  /* formula */ "IF(AC$35=\"Ja\",0,AC$34)",
  "AD37":  /* formula */ "IF(AD$35=\"Ja\",0,AD$34)",
  "AE37":  /* formula */ "IF(AE$35=\"Ja\",0,AE$34)",
  "AF37":  /* formula */ "IF(AF$35=\"Ja\",0,AF$34)",
  "B38":  /* unknown */ "Dachfläche",
  "D38":  /* unknown */ "intern",
  "F38":  /* unknown */ "EXIST_roof_jamb_eff",
  "G38":  /* unknown */ "INTERN - Haben sie einen Drempel unter der Dachschräge?",
  "H38":  /* unknown */ "Klopfen sie gegen die senkrechte Wand unter der Dachscrhräge. Klingt es hohl, haben sie einen Drempel.",
  "I38":  /* unknown */ "toggle switch ",
  "J38":  /* unknown */ "EXIST_roof",
  "L38":  /* unknown */ "Boolean",
  "M38":  /* unknown */ 1,
  "R38":  /* formula */ "IF(R$35=\"Nein\",\"Nein\",\"Ja\")",
  "S38":  /* formula */ "IF(S$35=\"Nein\",\"Nein\",\"Ja\")",
  "T38":  /* formula */ "IF(T$35=\"Nein\",\"Nein\",\"Ja\")",
  "U38":  /* formula */ "IF(U$35=\"Nein\",\"Nein\",\"Ja\")",
  "V38":  /* formula */ "IF(V$35=\"Nein\",\"Nein\",\"Ja\")",
  "W38":  /* formula */ "IF(W$35=\"Nein\",\"Nein\",\"Ja\")",
  "X38":  /* formula */ "IF(X$35=\"Nein\",\"Nein\",\"Ja\")",
  "Y38":  /* formula */ "IF(Y$35=\"Nein\",\"Nein\",\"Ja\")",
  "Z38":  /* formula */ "IF(Z$35=\"Nein\",\"Nein\",\"Ja\")",
  "AA38":  /* formula */ "IF(AA$35=\"Nein\",\"Nein\",\"Ja\")",
  "AB38":  /* formula */ "IF(AB$35=\"Nein\",\"Nein\",\"Ja\")",
  "AC38":  /* formula */ "IF(AC$35=\"Nein\",\"Nein\",\"Ja\")",
  "AD38":  /* formula */ "IF(AD$35=\"Nein\",\"Nein\",\"Ja\")",
  "AE38":  /* formula */ "IF(AE$35=\"Nein\",\"Nein\",\"Ja\")",
  "AF38":  /* formula */ "IF(AF$35=\"Nein\",\"Nein\",\"Ja\")",
  "B39":  /* unknown */ "Dachfläche",
  "C39":  /* unknown */ "Höhe",
  "D39":  /* unknown */ "intern",
  "F39":  /* unknown */ "L_roof_jamb_hei_eff",
  "G39":  /* unknown */ "INTERN - Falls ein Drempel vorhanden ist, geben Sie dessen Höhe an",
  "H39":  /* unknown */ "Der Drempel beschreibt im Dachbereich die Höhe der leichten Trennwand zwischen Fußboden und Beginn des Dachs. ",
  "I39":  /* unknown */ "Freitext",
  "J39":  /* unknown */ "EXIST_roof_jamb",
  "K39":  /* unknown */ "m",
  "L39":  /* unknown */ "Real",
  "M39":  /* unknown */ 0,
  "N39":  /* unknown */ 2,
  "O39":  /* unknown */ 0,
  "P39":  /* unknown */ 3,
  "R39":  /* formula */ "IF(R$35=\"Nein\",0,R$34)",
  "S39":  /* formula */ "IF(S$35=\"Nein\",0,S$34)",
  "T39":  /* formula */ "IF(T$35=\"Nein\",0,T$34)",
  "U39":  /* formula */ "IF(U$35=\"Nein\",0,U$34)",
  "V39":  /* formula */ "IF(V$35=\"Nein\",0,V$34)",
  "W39":  /* formula */ "IF(W$35=\"Nein\",0,W$34)",
  "X39":  /* formula */ "IF(X$35=\"Nein\",0,X$34)",
  "Y39":  /* formula */ "IF(Y$35=\"Nein\",0,Y$34)",
  "Z39":  /* formula */ "IF(Z$35=\"Nein\",0,Z$34)",
  "AA39":  /* formula */ "IF(AA$35=\"Nein\",0,AA$34)",
  "AB39":  /* formula */ "IF(AB$35=\"Nein\",0,AB$34)",
  "AC39":  /* formula */ "IF(AC$35=\"Nein\",0,AC$34)",
  "AD39":  /* formula */ "IF(AD$35=\"Nein\",0,AD$34)",
  "AE39":  /* formula */ "IF(AE$35=\"Nein\",0,AE$34)",
  "AF39":  /* formula */ "IF(AF$35=\"Nein\",0,AF$34)",
  "B40":  /* unknown */ "Gaube",
  "D40":  /* unknown */ "roof",
  "E40":  /* unknown */ "dormer",
  "F40":  /* unknown */ "EXIST_dormer",
  "G40":  /* unknown */ "Ist eine Gaube in der Dachschräge vorhanden?",
  "I40":  /* unknown */ "toggle switch ",
  "L40":  /* unknown */ "Boolean",
  "M40":  /* unknown */ 1,
  "S40":  /* unknown */ "Nein",
  "B41":  /* unknown */ "Fenster 1 in Dachfläche 1",
  "C41":  /* unknown */ "Breite",
  "D41":  /* unknown */ "roof",
  "E41":  /* unknown */ "win1",
  "F41":  /* unknown */ "L_roof_win1_wid",
  "G41":  /* unknown */ "Geben Sie die Abmaße des Dachfenstertyps an, Breite",
  "J41":  /* unknown */ "EXIST_roof",
  "K41":  /* unknown */ "m",
  "L41":  /* unknown */ "Integer",
  "M41":  /* unknown */ 0,
  "N41":  /* unknown */ 0,
  "O41":  /* unknown */ 0.5,
  "P41":  /* unknown */ 2,
  "S41":  /* unknown */ 1,
  "B42":  /* unknown */ "Fenster 1 in Dachfläche 1",
  "C42":  /* unknown */ "Höhe ",
  "D42":  /* unknown */ "roof",
  "E42":  /* unknown */ "win1",
  "F42":  /* unknown */ "L_roof_win1_hei",
  "G42":  /* unknown */ "Höhe ",
  "J42":  /* unknown */ "EXIST_roof",
  "K42":  /* unknown */ "m",
  "L42":  /* unknown */ "Integer",
  "M42":  /* unknown */ 0,
  "N42":  /* unknown */ 0,
  "O42":  /* unknown */ 0.5,
  "P42":  /* unknown */ 2,
  "S42":  /* unknown */ 1,
  "B43":  /* unknown */ "Fenster 1 in Dachfläche 1",
  "C43":  /* unknown */ "Jahr, in dem die Fenster zuletzt ausgetauscht wurden",
  "D43":  /* unknown */ "roof",
  "E43":  /* unknown */ "win1",
  "F43":  /* unknown */ "YEAR_roof_win1",
  "G43":  /* unknown */ "Abweichendes Einbaujahr ",
  "J43":  /* unknown */ "EXIST_roof",
  "L43":  /* unknown */ "Integer",
  "M43":  /* unknown */ 0,
  "N43":  /* unknown */ 0,
  "O43":  /* unknown */ 1800,
  "P43":  /* unknown */ 2045,
  "B44":  /* unknown */ "Fenster 1 in Dachfläche 1",
  "D44":  /* unknown */ "roof",
  "E44":  /* unknown */ "win1",
  "F44":  /* unknown */ "NO_roof_win1",
  "G44":  /* unknown */ "Anzahl identischer Fenster im Raum ",
  "I44":  /* unknown */ "Freitext",
  "J44":  /* unknown */ "EXIST_roof",
  "L44":  /* unknown */ "String",
  "M44":  /* unknown */ 0,
  "O44":  /* unknown */ 0,
  "P44":  /* unknown */ 10,
  "B45":  /* unknown */ "Fenster 2 in Dachfläche 1",
  "C45":  /* unknown */ "Breite",
  "D45":  /* unknown */ "roof",
  "E45":  /* unknown */ "win2",
  "F45":  /* unknown */ "L_roof_win2_wid",
  "G45":  /* unknown */ "Geben Sie die Abmaße des Dachfenstertyps an, Breite",
  "J45":  /* unknown */ "EXIST_roof",
  "K45":  /* unknown */ "m",
  "L45":  /* unknown */ "Integer",
  "M45":  /* unknown */ 0,
  "N45":  /* unknown */ 0,
  "O45":  /* unknown */ 0.5,
  "P45":  /* unknown */ 2,
  "B46":  /* unknown */ "Fenster 2 in Dachfläche 1",
  "C46":  /* unknown */ "Höhe ",
  "D46":  /* unknown */ "roof",
  "E46":  /* unknown */ "win2",
  "F46":  /* unknown */ "L_roof_win2_hei",
  "G46":  /* unknown */ "Höhe ",
  "J46":  /* unknown */ "EXIST_roof",
  "K46":  /* unknown */ "m",
  "L46":  /* unknown */ "Integer",
  "M46":  /* unknown */ 0,
  "N46":  /* unknown */ 0,
  "O46":  /* unknown */ 0.5,
  "P46":  /* unknown */ 2,
  "B47":  /* unknown */ "Fenster 2 in Dachfläche 1",
  "C47":  /* unknown */ "Jahr, in dem die Fenster zuletzt ausgetauscht wurden",
  "D47":  /* unknown */ "roof",
  "E47":  /* unknown */ "win2",
  "F47":  /* unknown */ "YEAR_roof_win2",
  "G47":  /* unknown */ "Abweichendes Einbaujahr ",
  "J47":  /* unknown */ "EXIST_roof",
  "L47":  /* unknown */ "Integer",
  "M47":  /* unknown */ 0,
  "N47":  /* unknown */ 0,
  "O47":  /* unknown */ 1800,
  "P47":  /* unknown */ 2045,
  "B48":  /* unknown */ "Fenster 2 in Dachfläche 1",
  "D48":  /* unknown */ "roof",
  "E48":  /* unknown */ "win2",
  "F48":  /* unknown */ "NO_roof_win2",
  "G48":  /* unknown */ "Anzahl identischer Fenster im Raum ",
  "J48":  /* unknown */ "EXIST_roof",
  "L48":  /* unknown */ "String",
  "M48":  /* unknown */ 0,
  "O48":  /* unknown */ 0,
  "P48":  /* unknown */ 10,
  "Q48":  /* unknown */ 1,
  "R48":  /* formula */ "$Q48",
  "S48":  /* formula */ "$Q48",
  "T48":  /* formula */ "$Q48",
  "U48":  /* formula */ "$Q48",
  "V48":  /* formula */ "$Q48",
  "W48":  /* formula */ "$Q48",
  "X48":  /* formula */ "$Q48",
  "Y48":  /* formula */ "$Q48",
  "Z48":  /* formula */ "$Q48",
  "AA48":  /* formula */ "$Q48",
  "AB48":  /* formula */ "$Q48",
  "AC48":  /* formula */ "$Q48",
  "AD48":  /* formula */ "$Q48",
  "AE48":  /* formula */ "$Q48",
  "AF48":  /* formula */ "$Q48",
  "B49":  /* unknown */ "Heizkörper 1 im Raum 1",
  "C49":  /* unknown */ "Typ",
  "D49":  /* unknown */ "rad1",
  "F49":  /* unknown */ "TYP_1_rad1",
  "G49":  /* unknown */ "Geben Sie den Typ des Heizkörpers an",
  "I49":  /* unknown */ "Radio Button ",
  "L49":  /* unknown */ "String",
  "M49":  /* unknown */ 1,
  "R49":  /* unknown */ "Flachheizkoerper_senkrecht_profiliert",
  "S49":  /* unknown */ "Flachheizkoerper_senkrecht_profiliert",
  "T49":  /* unknown */ "Flachheizkoerper_senkrecht_profiliert",
  "U49":  /* unknown */ "Flachheizkoerper_senkrecht_profiliert",
  "V49":  /* unknown */ "Gliederheizkörper",
  "W49":  /* unknown */ "Flachheizkoerper_senkrecht_profiliert",
  "X49":  /* unknown */ "Rohrradiator",
  "Y49":  /* unknown */ "Gliederheizkörper",
  "B50":  /* unknown */ "Heizkörper 1 im Raum 1",
  "C50":  /* unknown */ "Subtyp",
  "D50":  /* unknown */ "rad1",
  "F50":  /* unknown */ "TYP_2_rad1",
  "G50":  /* unknown */ "Geben Sie den Subtyp des Heizkörpers an",
  "I50":  /* unknown */ "Radio Button ",
  "L50":  /* unknown */ "String",
  "M50":  /* unknown */ 1,
  "R50":  /* unknown */ "Typ_22",
  "S50":  /* unknown */ "Typ_22",
  "T50":  /* unknown */ "Typ_22",
  "U50":  /* unknown */ "Typ_33",
  "V50":  /* unknown */ "Stahlradiator",
  "W50":  /* unknown */ "Typ_22",
  "X50":  /* unknown */ "Stahlrohrradiator",
  "Y50":  /* unknown */ "Stahlradiator",
  "B51":  /* unknown */ "Heizkörper 1 im Raum 1",
  "C51":  /* unknown */ "Höhe",
  "D51":  /* unknown */ "rad1",
  "F51":  /* unknown */ "L_rad1_hei",
  "G51":  /* unknown */ "Geben Sie die Abmaße des Heizkörpers an, Höhe",
  "I51":  /* unknown */ "Freitext",
  "K51":  /* unknown */ "mm",
  "L51":  /* unknown */ "Integer",
  "M51":  /* unknown */ 1,
  "N51":  /* unknown */ 0,
  "O51":  /* unknown */ 200,
  "P51":  /* unknown */ 2500,
  "R51":  /* unknown */ 350,
  "S51":  /* unknown */ 350,
  "T51":  /* unknown */ 600,
  "U51":  /* unknown */ 600,
  "V51":  /* unknown */ 600,
  "W51":  /* unknown */ 350,
  "X51":  /* unknown */ 600,
  "Y51":  /* unknown */ 1000,
  "B52":  /* unknown */ "Heizkörper 1 im Raum 1",
  "C52":  /* unknown */ "Breite",
  "D52":  /* unknown */ "rad1",
  "F52":  /* unknown */ "L_rad1_wid",
  "G52":  /* unknown */ "Geben Sie die Abmaße des Heizkörpers an, Breite",
  "I52":  /* unknown */ "Freitext",
  "K52":  /* unknown */ "mm",
  "L52":  /* unknown */ "Integer",
  "M52":  /* unknown */ 1,
  "N52":  /* unknown */ 0,
  "O52":  /* unknown */ 100,
  "P52":  /* unknown */ 2500,
  "R52":  /* unknown */ 800,
  "S52":  /* unknown */ 800,
  "B53":  /* unknown */ "Heizkörper 1 im Raum 1",
  "C53":  /* unknown */ "Tiefe",
  "D53":  /* unknown */ "rad1",
  "F53":  /* unknown */ "L_rad1_thick",
  "G53":  /* unknown */ "Geben Sie die Abmaße des Heizkörpers an, Tiefe",
  "I53":  /* unknown */ "Freitext",
  "K53":  /* unknown */ "mm",
  "L53":  /* unknown */ "Integer",
  "M53":  /* unknown */ 1,
  "N53":  /* unknown */ 0,
  "O53":  /* unknown */ 40,
  "P53":  /* unknown */ 300,
  "R53":  /* unknown */ 100,
  "S53":  /* unknown */ 100,
  "T53":  /* unknown */ 100,
  "U53":  /* unknown */ 155,
  "V53":  /* unknown */ 110,
  "W53":  /* unknown */ 100,
  "X53":  /* unknown */ 225,
  "Y53":  /* unknown */ 160,
  "B54":  /* unknown */ "Heizkörper 1 im Raum 1",
  "C54":  /* unknown */ "Anzahl Glieder",
  "D54":  /* unknown */ "rad1",
  "F54":  /* unknown */ "n_rad1_col",
  "G54":  /* unknown */ "Geben Sie die Anzahl der Glieder des Heizkörpers an",
  "I54":  /* unknown */ "Freitext",
  "J54":  /* unknown */ "TYP_1_rad1=\"Gliederheizkörper\"",
  "L54":  /* unknown */ "Integer",
  "M54":  /* unknown */ 0,
  "N54":  /* unknown */ 0,
  "O54":  /* unknown */ 1,
  "P54":  /* unknown */ 20,
  "V54":  /* unknown */ 17,
  "X54":  /* unknown */ 10,
  "Y54":  /* unknown */ 6,
  "B55":  /* unknown */ "Heizkörper 1 im Raum 1",
  "C55":  /* unknown */ "Anzahl identischer HK",
  "D55":  /* unknown */ "rad1",
  "F55":  /* unknown */ "n_rad1",
  "G55":  /* unknown */ "Geben Sie die Anzahl der zu diesem Heizkörper identischen Heizkörper im Raum an",
  "I55":  /* unknown */ "Freitext",
  "L55":  /* unknown */ "Integer",
  "M55":  /* unknown */ 0,
  "N55":  /* unknown */ 0,
  "O55":  /* unknown */ 0,
  "P55":  /* unknown */ 5,
  "Q55":  /* unknown */ 1,
  "R55":  /* formula */ "$Q$55",
  "S55":  /* formula */ "$Q$55",
  "T55":  /* unknown */ 1,
  "U55":  /* formula */ "$Q$55",
  "V55":  /* formula */ "$Q$55",
  "W55":  /* formula */ "$Q$55",
  "X55":  /* formula */ "$Q$55",
  "Y55":  /* formula */ "$Q$55",
  "Z55":  /* formula */ "$Q$55",
  "AA55":  /* formula */ "$Q$55",
  "AB55":  /* formula */ "$Q$55",
  "AC55":  /* formula */ "$Q$55",
  "AD55":  /* formula */ "$Q$55",
  "AE55":  /* formula */ "$Q$55",
  "AF55":  /* formula */ "$Q$55",
  "B56":  /* unknown */ "Heizkörper 2 im Raum 1",
  "C56":  /* unknown */ "Typ",
  "D56":  /* unknown */ "rad2",
  "F56":  /* unknown */ "TYP_1_rad2",
  "G56":  /* unknown */ "Geben Sie den Typ des Heizkörpers an",
  "I56":  /* unknown */ "Radio Button ",
  "L56":  /* unknown */ "String",
  "M56":  /* unknown */ 0,
  "W56":  /* unknown */ "Rohrradiator",
  "B57":  /* unknown */ "Heizkörper 2 im Raum 1",
  "C57":  /* unknown */ "Subtyp",
  "D57":  /* unknown */ "rad2",
  "F57":  /* unknown */ "TYP_2_rad2",
  "G57":  /* unknown */ "Geben Sie den Subtyp des Heizkörpers an",
  "I57":  /* unknown */ "Radio Button ",
  "L57":  /* unknown */ "String",
  "M57":  /* unknown */ 0,
  "W57":  /* unknown */ "Handtuchradiator",
  "B58":  /* unknown */ "Heizkörper 2 im Raum 1",
  "C58":  /* unknown */ "Höhe",
  "D58":  /* unknown */ "rad2",
  "F58":  /* unknown */ "L_rad2_hei",
  "G58":  /* unknown */ "Geben Sie die Abmaße des Heizkörpers an, Höhe",
  "I58":  /* unknown */ "Freitext",
  "K58":  /* unknown */ "mm",
  "L58":  /* unknown */ "Integer",
  "M58":  /* unknown */ 0,
  "N58":  /* unknown */ 0,
  "O58":  /* unknown */ 200,
  "P58":  /* unknown */ 2500,
  "W58":  /* unknown */ 2000,
  "B59":  /* unknown */ "Heizkörper 2 im Raum 1",
  "C59":  /* unknown */ "Breite",
  "D59":  /* unknown */ "rad2",
  "F59":  /* unknown */ "L_rad2_wid",
  "G59":  /* unknown */ "Geben Sie die Abmaße des Heizkörpers an, Breite",
  "I59":  /* unknown */ "Freitext",
  "K59":  /* unknown */ "mm",
  "L59":  /* unknown */ "Integer",
  "M59":  /* unknown */ 1,
  "N59":  /* unknown */ 0,
  "O59":  /* unknown */ 100,
  "P59":  /* unknown */ 2500,
  "B60":  /* unknown */ "Heizkörper 2 im Raum 1",
  "C60":  /* unknown */ "Tiefe",
  "D60":  /* unknown */ "rad2",
  "F60":  /* unknown */ "L_rad2_thick",
  "G60":  /* unknown */ "Geben Sie die Abmaße des Heizkörpers an, Tiefe",
  "I60":  /* unknown */ "Freitext",
  "K60":  /* unknown */ "mm",
  "L60":  /* unknown */ "Integer",
  "M60":  /* unknown */ 0,
  "N60":  /* unknown */ 0,
  "O60":  /* unknown */ 40,
  "P60":  /* unknown */ 300,
  "W60":  /* unknown */ 225,
  "B61":  /* unknown */ "Heizkörper 2 im Raum 1",
  "C61":  /* unknown */ "Anzahl Glieder",
  "D61":  /* unknown */ "rad2",
  "F61":  /* unknown */ "n_rad2_col",
  "G61":  /* unknown */ "Geben Sie die Anzahl der Glieder des Heizkörpers an",
  "I61":  /* unknown */ "Freitext",
  "J61":  /* unknown */ "TYP_1_rad2=\"Gliederheizkörper\"",
  "L61":  /* unknown */ "Integer",
  "M61":  /* unknown */ 0,
  "N61":  /* unknown */ 0,
  "O61":  /* unknown */ 1,
  "P61":  /* unknown */ 20,
  "W61":  /* unknown */ 10,
  "B62":  /* unknown */ "Heizkörper 2 im Raum 1",
  "C62":  /* unknown */ "Anzahl identischer HK",
  "D62":  /* unknown */ "rad2",
  "F62":  /* unknown */ "n_rad2",
  "G62":  /* unknown */ "Geben Sie die Anzahl der zu diesem Heizkörper identischen Heizkörper im Raum an",
  "I62":  /* unknown */ "Freitext",
  "L62":  /* unknown */ "Integer",
  "M62":  /* unknown */ 0,
  "N62":  /* unknown */ 0,
  "O62":  /* unknown */ 0,
  "P62":  /* unknown */ 5,
  "Q62":  /* unknown */ 1,
  "R62":  /* formula */ "$Q$62",
  "S62":  /* formula */ "$Q$62",
  "T62":  /* formula */ "$Q$62",
  "U62":  /* formula */ "$Q$62",
  "V62":  /* formula */ "$Q$62",
  "W62":  /* formula */ "$Q$62",
  "X62":  /* formula */ "$Q$62",
  "Y62":  /* formula */ "$Q$62",
  "Z62":  /* formula */ "$Q$62",
  "AA62":  /* formula */ "$Q$62",
  "AB62":  /* formula */ "$Q$62",
  "AC62":  /* formula */ "$Q$62",
  "AD62":  /* formula */ "$Q$62",
  "AE62":  /* formula */ "$Q$62",
  "AF62":  /* formula */ "$Q$62",
  "B63":  /* unknown */ "Heizkörper 3 im Raum 1",
  "C63":  /* unknown */ "Typ",
  "D63":  /* unknown */ "rad3",
  "F63":  /* unknown */ "TYP_1_rad3",
  "G63":  /* unknown */ "Geben Sie den Typ des Heizkörpers an",
  "I63":  /* unknown */ "Radio Button ",
  "L63":  /* unknown */ "String",
  "M63":  /* unknown */ 0,
  "B64":  /* unknown */ "Heizkörper 3 im Raum 1",
  "C64":  /* unknown */ "Subtyp",
  "D64":  /* unknown */ "rad3",
  "F64":  /* unknown */ "TYP_2_rad3",
  "G64":  /* unknown */ "Geben Sie den Subtyp des Heizkörpers an",
  "I64":  /* unknown */ "Radio Button ",
  "L64":  /* unknown */ "String",
  "M64":  /* unknown */ 0,
  "B65":  /* unknown */ "Heizkörper 3 im Raum 1",
  "C65":  /* unknown */ "Höhe",
  "D65":  /* unknown */ "rad3",
  "F65":  /* unknown */ "L_rad3_hei",
  "G65":  /* unknown */ "Geben Sie die Abmaße des Heizkörpers an, Höhe",
  "I65":  /* unknown */ "Freitext",
  "K65":  /* unknown */ "mm",
  "L65":  /* unknown */ "Integer",
  "M65":  /* unknown */ 0,
  "N65":  /* unknown */ 0,
  "O65":  /* unknown */ 200,
  "P65":  /* unknown */ 2500,
  "B66":  /* unknown */ "Heizkörper 3 im Raum 1",
  "C66":  /* unknown */ "Breite",
  "D66":  /* unknown */ "rad3",
  "F66":  /* unknown */ "L_rad3_wid",
  "G66":  /* unknown */ "Geben Sie die Abmaße des Heizkörpers an, Breite",
  "I66":  /* unknown */ "Freitext",
  "K66":  /* unknown */ "mm",
  "L66":  /* unknown */ "Integer",
  "M66":  /* unknown */ 1,
  "N66":  /* unknown */ 0,
  "O66":  /* unknown */ 100,
  "P66":  /* unknown */ 2500,
  "B67":  /* unknown */ "Heizkörper 3 im Raum 1",
  "C67":  /* unknown */ "Tiefe",
  "D67":  /* unknown */ "rad3",
  "F67":  /* unknown */ "L_rad3_thick",
  "G67":  /* unknown */ "Geben Sie die Abmaße des Heizkörpers an, Tiefe",
  "I67":  /* unknown */ "Freitext",
  "K67":  /* unknown */ "mm",
  "L67":  /* unknown */ "Integer",
  "M67":  /* unknown */ 0,
  "N67":  /* unknown */ 0,
  "O67":  /* unknown */ 40,
  "P67":  /* unknown */ 300,
  "B68":  /* unknown */ "Heizkörper 3 im Raum 1",
  "C68":  /* unknown */ "Anzahl Glieder",
  "D68":  /* unknown */ "rad3",
  "F68":  /* unknown */ "n_rad3_col",
  "G68":  /* unknown */ "Geben Sie die Anzahl der Glieder des Heizkörpers an",
  "I68":  /* unknown */ "Freitext",
  "J68":  /* unknown */ "TYP_1_rad3=\"Gliederheizkörper\"",
  "L68":  /* unknown */ "Integer",
  "M68":  /* unknown */ 0,
  "N68":  /* unknown */ 0,
  "O68":  /* unknown */ 1,
  "P68":  /* unknown */ 20,
  "B69":  /* unknown */ "Heizkörper 3 im Raum 1",
  "C69":  /* unknown */ "Anzahl identischer HK",
  "D69":  /* unknown */ "rad3",
  "F69":  /* unknown */ "n_rad3",
  "G69":  /* unknown */ "Geben Sie die Anzahl der zu diesem Heizkörper identischen Heizkörper im Raum an",
  "I69":  /* unknown */ "Freitext",
  "L69":  /* unknown */ "Integer",
  "M69":  /* unknown */ 0,
  "N69":  /* unknown */ 0,
  "O69":  /* unknown */ 0,
  "P69":  /* unknown */ 5,
  "Q69":  /* unknown */ 1,
  "R69":  /* formula */ "$Q$69",
  "S69":  /* formula */ "$Q$69",
  "T69":  /* formula */ "$Q$69",
  "U69":  /* formula */ "$Q$69",
  "V69":  /* formula */ "$Q$69",
  "W69":  /* formula */ "$Q$69",
  "X69":  /* formula */ "$Q$69",
  "Y69":  /* formula */ "$Q$69",
  "Z69":  /* formula */ "$Q$69",
  "AA69":  /* formula */ "$Q$69",
  "AB69":  /* formula */ "$Q$69",
  "AC69":  /* formula */ "$Q$69",
  "AD69":  /* formula */ "$Q$69",
  "AE69":  /* formula */ "$Q$69",
  "AF69":  /* formula */ "$Q$69",
  "D72":  /* unknown */ "Effektive Werte",
  "D73":  /* unknown */ "intern",
  "F73":  /* unknown */ "YEAR_wall_ins_eff",
  "G73":  /* unknown */ "Abweichendes Modernisierungsjahr ",
  "L73":  /* unknown */ "Integer",
  "R73":  /* formula */ "IF(OR(R$10=Daten!$B$19,R$10=\"\"),IF(IN_build!$Q$7=\"Ja\",IN_build!$R$7,IN_build!$P$5),IF(OR(R$10<IN_build!$P$5,R$10=Daten!$B$20),IN_build!$P$5,R$10))",
  "S73":  /* formula */ "IF(OR(S$10=Daten!$B$19,S$10=\"\"),IF(IN_build!$Q$7=\"Ja\",IN_build!$R$7,IN_build!$P$5),IF(OR(S$10<IN_build!$P$5,S$10=Daten!$B$20),IN_build!$P$5,S$10))",
  "T73":  /* formula */ "IF(OR(T$10=Daten!$B$19,T$10=\"\"),IF(IN_build!$Q$7=\"Ja\",IN_build!$R$7,IN_build!$P$5),IF(OR(T$10<IN_build!$P$5,T$10=Daten!$B$20),IN_build!$P$5,T$10))",
  "U73":  /* formula */ "IF(OR(U$10=Daten!$B$19,U$10=\"\"),IF(IN_build!$Q$7=\"Ja\",IN_build!$R$7,IN_build!$P$5),IF(OR(U$10<IN_build!$P$5,U$10=Daten!$B$20),IN_build!$P$5,U$10))",
  "V73":  /* formula */ "IF(OR(V$10=Daten!$B$19,V$10=\"\"),IF(IN_build!$Q$7=\"Ja\",IN_build!$R$7,IN_build!$P$5),IF(OR(V$10<IN_build!$P$5,V$10=Daten!$B$20),IN_build!$P$5,V$10))",
  "W73":  /* formula */ "IF(OR(W$10=Daten!$B$19,W$10=\"\"),IF(IN_build!$Q$7=\"Ja\",IN_build!$R$7,IN_build!$P$5),IF(OR(W$10<IN_build!$P$5,W$10=Daten!$B$20),IN_build!$P$5,W$10))",
  "X73":  /* formula */ "IF(OR(X$10=Daten!$B$19,X$10=\"\"),IF(IN_build!$Q$7=\"Ja\",IN_build!$R$7,IN_build!$P$5),IF(OR(X$10<IN_build!$P$5,X$10=Daten!$B$20),IN_build!$P$5,X$10))",
  "Y73":  /* formula */ "IF(OR(Y$10=Daten!$B$19,Y$10=\"\"),IF(IN_build!$Q$7=\"Ja\",IN_build!$R$7,IN_build!$P$5),IF(OR(Y$10<IN_build!$P$5,Y$10=Daten!$B$20),IN_build!$P$5,Y$10))",
  "Z73":  /* formula */ "IF(OR(Z$10=Daten!$B$19,Z$10=\"\"),IF(IN_build!$Q$7=\"Ja\",IN_build!$R$7,IN_build!$P$5),IF(OR(Z$10<IN_build!$P$5,Z$10=Daten!$B$20),IN_build!$P$5,Z$10))",
  "AA73":  /* formula */ "IF(OR(AA$10=Daten!$B$19,AA$10=\"\"),IF(IN_build!$Q$7=\"Ja\",IN_build!$R$7,IN_build!$P$5),IF(OR(AA$10<IN_build!$P$5,AA$10=Daten!$B$20),IN_build!$P$5,AA$10))",
  "AB73":  /* formula */ "IF(OR(AB$10=Daten!$B$19,AB$10=\"\"),IF(IN_build!$Q$7=\"Ja\",IN_build!$R$7,IN_build!$P$5),IF(OR(AB$10<IN_build!$P$5,AB$10=Daten!$B$20),IN_build!$P$5,AB$10))",
  "AC73":  /* formula */ "IF(OR(AC$10=Daten!$B$19,AC$10=\"\"),IF(IN_build!$Q$7=\"Ja\",IN_build!$R$7,IN_build!$P$5),IF(OR(AC$10<IN_build!$P$5,AC$10=Daten!$B$20),IN_build!$P$5,AC$10))",
  "AD73":  /* formula */ "IF(OR(AD$10=Daten!$B$19,AD$10=\"\"),IF(IN_build!$Q$7=\"Ja\",IN_build!$R$7,IN_build!$P$5),IF(OR(AD$10<IN_build!$P$5,AD$10=Daten!$B$20),IN_build!$P$5,AD$10))",
  "AE73":  /* formula */ "IF(OR(AE$10=Daten!$B$19,AE$10=\"\"),IF(IN_build!$Q$7=\"Ja\",IN_build!$R$7,IN_build!$P$5),IF(OR(AE$10<IN_build!$P$5,AE$10=Daten!$B$20),IN_build!$P$5,AE$10))",
  "AF73":  /* formula */ "IF(OR(AF$10=Daten!$B$19,AF$10=\"\"),IF(IN_build!$Q$7=\"Ja\",IN_build!$R$7,IN_build!$P$5),IF(OR(AF$10<IN_build!$P$5,AF$10=Daten!$B$20),IN_build!$P$5,AF$10))",
  "D74":  /* unknown */ "intern",
  "F74":  /* unknown */ "L_wall_ins_intern",
  "G74":  /* unknown */ "Abweichende Dämmstärke? >> default Wert",
  "K74":  /* unknown */ "cm",
  "L74":  /* unknown */ "Real",
  "R74":  /* formula */ "IF(R73=IN_build!$P$5, 0, _xlfn.XLOOKUP(1,\n  (INDIRECT(\"UWert_Mod[Bauteil]\")=\"Außenwand\") *\n  (INDIRECT(\"UWert_Mod[Modernisierungsjahr]\")=R73),\n  INDIRECT(\"UWert_Mod[d_ins]\")\n))",
  "S74":  /* formula */ "IF(S73=IN_build!$P$5, 0, _xlfn.XLOOKUP(1,\n  (INDIRECT(\"UWert_Mod[Bauteil]\")=\"Außenwand\") *\n  (INDIRECT(\"UWert_Mod[Modernisierungsjahr]\")=S73),\n  INDIRECT(\"UWert_Mod[d_ins]\")\n))",
  "T74":  /* formula */ "IF(T73=IN_build!$P$5, 0, _xlfn.XLOOKUP(1,\n  (INDIRECT(\"UWert_Mod[Bauteil]\")=\"Außenwand\") *\n  (INDIRECT(\"UWert_Mod[Modernisierungsjahr]\")=T73),\n  INDIRECT(\"UWert_Mod[d_ins]\")\n))",
  "U74":  /* formula */ "IF(U73=IN_build!$P$5, 0, _xlfn.XLOOKUP(1,\n  (INDIRECT(\"UWert_Mod[Bauteil]\")=\"Außenwand\") *\n  (INDIRECT(\"UWert_Mod[Modernisierungsjahr]\")=U73),\n  INDIRECT(\"UWert_Mod[d_ins]\")\n))",
  "V74":  /* formula */ "IF(V73=IN_build!$P$5, 0, _xlfn.XLOOKUP(1,\n  (INDIRECT(\"UWert_Mod[Bauteil]\")=\"Außenwand\") *\n  (INDIRECT(\"UWert_Mod[Modernisierungsjahr]\")=V73),\n  INDIRECT(\"UWert_Mod[d_ins]\")\n))",
  "W74":  /* formula */ "IF(W73=IN_build!$P$5, 0, _xlfn.XLOOKUP(1,\n  (INDIRECT(\"UWert_Mod[Bauteil]\")=\"Außenwand\") *\n  (INDIRECT(\"UWert_Mod[Modernisierungsjahr]\")=W73),\n  INDIRECT(\"UWert_Mod[d_ins]\")\n))",
  "X74":  /* formula */ "IF(X73=IN_build!$P$5, 0, _xlfn.XLOOKUP(1,\n  (INDIRECT(\"UWert_Mod[Bauteil]\")=\"Außenwand\") *\n  (INDIRECT(\"UWert_Mod[Modernisierungsjahr]\")=X73),\n  INDIRECT(\"UWert_Mod[d_ins]\")\n))",
  "Y74":  /* formula */ "IF(Y73=IN_build!$P$5, 0, _xlfn.XLOOKUP(1,\n  (INDIRECT(\"UWert_Mod[Bauteil]\")=\"Außenwand\") *\n  (INDIRECT(\"UWert_Mod[Modernisierungsjahr]\")=Y73),\n  INDIRECT(\"UWert_Mod[d_ins]\")\n))",
  "Z74":  /* formula */ "IF(Z73=IN_build!$P$5, 0, _xlfn.XLOOKUP(1,\n  (INDIRECT(\"UWert_Mod[Bauteil]\")=\"Außenwand\") *\n  (INDIRECT(\"UWert_Mod[Modernisierungsjahr]\")=Z73),\n  INDIRECT(\"UWert_Mod[d_ins]\")\n))",
  "AA74":  /* formula */ "IF(AA73=IN_build!$P$5, 0, _xlfn.XLOOKUP(1,\n  (INDIRECT(\"UWert_Mod[Bauteil]\")=\"Außenwand\") *\n  (INDIRECT(\"UWert_Mod[Modernisierungsjahr]\")=AA73),\n  INDIRECT(\"UWert_Mod[d_ins]\")\n))",
  "AB74":  /* formula */ "IF(AB73=IN_build!$P$5, 0, _xlfn.XLOOKUP(1,\n  (INDIRECT(\"UWert_Mod[Bauteil]\")=\"Außenwand\") *\n  (INDIRECT(\"UWert_Mod[Modernisierungsjahr]\")=AB73),\n  INDIRECT(\"UWert_Mod[d_ins]\")\n))",
  "AC74":  /* formula */ "IF(AC73=IN_build!$P$5, 0, _xlfn.XLOOKUP(1,\n  (INDIRECT(\"UWert_Mod[Bauteil]\")=\"Außenwand\") *\n  (INDIRECT(\"UWert_Mod[Modernisierungsjahr]\")=AC73),\n  INDIRECT(\"UWert_Mod[d_ins]\")\n))",
  "AD74":  /* formula */ "IF(AD73=IN_build!$P$5, 0, _xlfn.XLOOKUP(1,\n  (INDIRECT(\"UWert_Mod[Bauteil]\")=\"Außenwand\") *\n  (INDIRECT(\"UWert_Mod[Modernisierungsjahr]\")=AD73),\n  INDIRECT(\"UWert_Mod[d_ins]\")\n))",
  "AE74":  /* formula */ "IF(AE73=IN_build!$P$5, 0, _xlfn.XLOOKUP(1,\n  (INDIRECT(\"UWert_Mod[Bauteil]\")=\"Außenwand\") *\n  (INDIRECT(\"UWert_Mod[Modernisierungsjahr]\")=AE73),\n  INDIRECT(\"UWert_Mod[d_ins]\")\n))",
  "AF74":  /* formula */ "IF(AF73=IN_build!$P$5, 0, _xlfn.XLOOKUP(1,\n  (INDIRECT(\"UWert_Mod[Bauteil]\")=\"Außenwand\") *\n  (INDIRECT(\"UWert_Mod[Modernisierungsjahr]\")=AF73),\n  INDIRECT(\"UWert_Mod[d_ins]\")\n))",
  "D75":  /* unknown */ "intern",
  "F75":  /* unknown */ "L_wall_ins_eff",
  "G75":  /* unknown */ "Abweichende Dämmstärke?  >> effektiver Wert",
  "K75":  /* unknown */ "cm",
  "L75":  /* unknown */ "Real",
  "R75":  /* formula */ "IF(R$11<=0,R$74,R$11)",
  "S75":  /* formula */ "IF(S$11<=0,S$74,S$11)",
  "T75":  /* formula */ "IF(T$11<=0,T$74,T$11)",
  "U75":  /* formula */ "IF(U$11<=0,U$74,U$11)",
  "V75":  /* formula */ "IF(V$11<=0,V$74,V$11)",
  "W75":  /* formula */ "IF(W$11<=0,W$74,W$11)",
  "X75":  /* formula */ "IF(X$11<=0,X$74,X$11)",
  "Y75":  /* formula */ "IF(Y$11<=0,Y$74,Y$11)",
  "Z75":  /* formula */ "IF(Z$11<=0,Z$74,Z$11)",
  "AA75":  /* formula */ "IF(AA$11<=0,AA$74,AA$11)",
  "AB75":  /* formula */ "IF(AB$11<=0,AB$74,AB$11)",
  "AC75":  /* formula */ "IF(AC$11<=0,AC$74,AC$11)",
  "AD75":  /* formula */ "IF(AD$11<=0,AD$74,AD$11)",
  "AE75":  /* formula */ "IF(AE$11<=0,AE$74,AE$11)",
  "AF75":  /* formula */ "IF(AF$11<=0,AF$74,AF$11)",
  "D76":  /* unknown */ "wall",
  "E76":  /* unknown */ "win1",
  "F76":  /* formula */ "\"YEAR_\"&D76&\"_\"&E76&\"_eff\"",
  "G76":  /* unknown */ "Abweichendes Einbaujahr ",
  "R76":  /* formula */ "IF(OR(R$15=Daten!$E$17,R$15=\"\"),IN_build!$R$8,IF(OR(R$15=Daten!$E$18,R$15<IN_build!$P$5),IN_build!$P$5,R$15))",
  "S76":  /* formula */ "IF(OR(S$15=Daten!$E$17,S$15=\"\"),IN_build!$R$8,IF(OR(S$15=Daten!$E$18,S$15<IN_build!$P$5),IN_build!$P$5,S$15))",
  "T76":  /* formula */ "IF(OR(T$15=Daten!$E$17,T$15=\"\"),IN_build!$R$8,IF(OR(T$15=Daten!$E$18,T$15<IN_build!$P$5),IN_build!$P$5,T$15))",
  "U76":  /* formula */ "IF(OR(U$15=Daten!$E$17,U$15=\"\"),IN_build!$R$8,IF(OR(U$15=Daten!$E$18,U$15<IN_build!$P$5),IN_build!$P$5,U$15))",
  "V76":  /* formula */ "IF(OR(V$15=Daten!$E$17,V$15=\"\"),IN_build!$R$8,IF(OR(V$15=Daten!$E$18,V$15<IN_build!$P$5),IN_build!$P$5,V$15))",
  "W76":  /* formula */ "IF(OR(W$15=Daten!$E$17,W$15=\"\"),IN_build!$R$8,IF(OR(W$15=Daten!$E$18,W$15<IN_build!$P$5),IN_build!$P$5,W$15))",
  "X76":  /* formula */ "IF(OR(X$15=Daten!$E$17,X$15=\"\"),IN_build!$R$8,IF(OR(X$15=Daten!$E$18,X$15<IN_build!$P$5),IN_build!$P$5,X$15))",
  "Y76":  /* formula */ "IF(OR(Y$15=Daten!$E$17,Y$15=\"\"),IN_build!$R$8,IF(OR(Y$15=Daten!$E$18,Y$15<IN_build!$P$5),IN_build!$P$5,Y$15))",
  "Z76":  /* formula */ "IF(OR(Z$15=Daten!$E$17,Z$15=\"\"),IN_build!$R$8,IF(OR(Z$15=Daten!$E$18,Z$15<IN_build!$P$5),IN_build!$P$5,Z$15))",
  "AA76":  /* formula */ "IF(OR(AA$15=Daten!$E$17,AA$15=\"\"),IN_build!$R$8,IF(OR(AA$15=Daten!$E$18,AA$15<IN_build!$P$5),IN_build!$P$5,AA$15))",
  "AB76":  /* formula */ "IF(OR(AB$15=Daten!$E$17,AB$15=\"\"),IN_build!$R$8,IF(OR(AB$15=Daten!$E$18,AB$15<IN_build!$P$5),IN_build!$P$5,AB$15))",
  "AC76":  /* formula */ "IF(OR(AC$15=Daten!$E$17,AC$15=\"\"),IN_build!$R$8,IF(OR(AC$15=Daten!$E$18,AC$15<IN_build!$P$5),IN_build!$P$5,AC$15))",
  "AD76":  /* formula */ "IF(OR(AD$15=Daten!$E$17,AD$15=\"\"),IN_build!$R$8,IF(OR(AD$15=Daten!$E$18,AD$15<IN_build!$P$5),IN_build!$P$5,AD$15))",
  "AE76":  /* formula */ "IF(OR(AE$15=Daten!$E$17,AE$15=\"\"),IN_build!$R$8,IF(OR(AE$15=Daten!$E$18,AE$15<IN_build!$P$5),IN_build!$P$5,AE$15))",
  "AF76":  /* formula */ "IF(OR(AF$15=Daten!$E$17,AF$15=\"\"),IN_build!$R$8,IF(OR(AF$15=Daten!$E$18,AF$15<IN_build!$P$5),IN_build!$P$5,AF$15))",
  "D77":  /* unknown */ "wall",
  "E77":  /* unknown */ "win2",
  "F77":  /* formula */ "\"YEAR_\"&D77&\"_\"&E77&\"_eff\"",
  "G77":  /* unknown */ "Abweichendes Einbaujahr ",
  "R77":  /* formula */ "IF(OR(R$19=Daten!$E$17,R$19=\"\"),IN_build!$R$8,IF(OR(R$19=Daten!$E$18,R$19<IN_build!$P$5),IN_build!$P$5,R$19))",
  "S77":  /* formula */ "IF(OR(S$19=Daten!$E$17,S$19=\"\"),IN_build!$R$8,IF(OR(S$19=Daten!$E$18,S$19<IN_build!$P$5),IN_build!$P$5,S$19))",
  "T77":  /* formula */ "IF(OR(T$19=Daten!$E$17,T$19=\"\"),IN_build!$R$8,IF(OR(T$19=Daten!$E$18,T$19<IN_build!$P$5),IN_build!$P$5,T$19))",
  "U77":  /* formula */ "IF(OR(U$19=Daten!$E$17,U$19=\"\"),IN_build!$R$8,IF(OR(U$19=Daten!$E$18,U$19<IN_build!$P$5),IN_build!$P$5,U$19))",
  "V77":  /* formula */ "IF(OR(V$19=Daten!$E$17,V$19=\"\"),IN_build!$R$8,IF(OR(V$19=Daten!$E$18,V$19<IN_build!$P$5),IN_build!$P$5,V$19))",
  "W77":  /* formula */ "IF(OR(W$19=Daten!$E$17,W$19=\"\"),IN_build!$R$8,IF(OR(W$19=Daten!$E$18,W$19<IN_build!$P$5),IN_build!$P$5,W$19))",
  "X77":  /* formula */ "IF(OR(X$19=Daten!$E$17,X$19=\"\"),IN_build!$R$8,IF(OR(X$19=Daten!$E$18,X$19<IN_build!$P$5),IN_build!$P$5,X$19))",
  "Y77":  /* formula */ "IF(OR(Y$19=Daten!$E$17,Y$19=\"\"),IN_build!$R$8,IF(OR(Y$19=Daten!$E$18,Y$19<IN_build!$P$5),IN_build!$P$5,Y$19))",
  "Z77":  /* formula */ "IF(OR(Z$19=Daten!$E$17,Z$19=\"\"),IN_build!$R$8,IF(OR(Z$19=Daten!$E$18,Z$19<IN_build!$P$5),IN_build!$P$5,Z$19))",
  "AA77":  /* formula */ "IF(OR(AA$19=Daten!$E$17,AA$19=\"\"),IN_build!$R$8,IF(OR(AA$19=Daten!$E$18,AA$19<IN_build!$P$5),IN_build!$P$5,AA$19))",
  "AB77":  /* formula */ "IF(OR(AB$19=Daten!$E$17,AB$19=\"\"),IN_build!$R$8,IF(OR(AB$19=Daten!$E$18,AB$19<IN_build!$P$5),IN_build!$P$5,AB$19))",
  "AC77":  /* formula */ "IF(OR(AC$19=Daten!$E$17,AC$19=\"\"),IN_build!$R$8,IF(OR(AC$19=Daten!$E$18,AC$19<IN_build!$P$5),IN_build!$P$5,AC$19))",
  "AD77":  /* formula */ "IF(OR(AD$19=Daten!$E$17,AD$19=\"\"),IN_build!$R$8,IF(OR(AD$19=Daten!$E$18,AD$19<IN_build!$P$5),IN_build!$P$5,AD$19))",
  "AE77":  /* formula */ "IF(OR(AE$19=Daten!$E$17,AE$19=\"\"),IN_build!$R$8,IF(OR(AE$19=Daten!$E$18,AE$19<IN_build!$P$5),IN_build!$P$5,AE$19))",
  "AF77":  /* formula */ "IF(OR(AF$19=Daten!$E$17,AF$19=\"\"),IN_build!$R$8,IF(OR(AF$19=Daten!$E$18,AF$19<IN_build!$P$5),IN_build!$P$5,AF$19))",
  "D78":  /* unknown */ "wall",
  "E78":  /* unknown */ "win3",
  "F78":  /* formula */ "\"YEAR_\"&D78&\"_\"&E78&\"_eff\"",
  "G78":  /* unknown */ "Abweichendes Einbaujahr ",
  "R78":  /* formula */ "IF(OR(R$23=Daten!$E$17,R$23=\"\"),IN_build!$R$8,IF(OR(R$23=Daten!$E$18,R$23<IN_build!$P$5),IN_build!$P$5,R$23))",
  "S78":  /* formula */ "IF(OR(S$23=Daten!$E$17,S$23=\"\"),IN_build!$R$8,IF(OR(S$23=Daten!$E$18,S$23<IN_build!$P$5),IN_build!$P$5,S$23))",
  "T78":  /* formula */ "IF(OR(T$23=Daten!$E$17,T$23=\"\"),IN_build!$R$8,IF(OR(T$23=Daten!$E$18,T$23<IN_build!$P$5),IN_build!$P$5,T$23))",
  "U78":  /* formula */ "IF(OR(U$23=Daten!$E$17,U$23=\"\"),IN_build!$R$8,IF(OR(U$23=Daten!$E$18,U$23<IN_build!$P$5),IN_build!$P$5,U$23))",
  "V78":  /* formula */ "IF(OR(V$23=Daten!$E$17,V$23=\"\"),IN_build!$R$8,IF(OR(V$23=Daten!$E$18,V$23<IN_build!$P$5),IN_build!$P$5,V$23))",
  "W78":  /* formula */ "IF(OR(W$23=Daten!$E$17,W$23=\"\"),IN_build!$R$8,IF(OR(W$23=Daten!$E$18,W$23<IN_build!$P$5),IN_build!$P$5,W$23))",
  "X78":  /* formula */ "IF(OR(X$23=Daten!$E$17,X$23=\"\"),IN_build!$R$8,IF(OR(X$23=Daten!$E$18,X$23<IN_build!$P$5),IN_build!$P$5,X$23))",
  "Y78":  /* formula */ "IF(OR(Y$23=Daten!$E$17,Y$23=\"\"),IN_build!$R$8,IF(OR(Y$23=Daten!$E$18,Y$23<IN_build!$P$5),IN_build!$P$5,Y$23))",
  "Z78":  /* formula */ "IF(OR(Z$23=Daten!$E$17,Z$23=\"\"),IN_build!$R$8,IF(OR(Z$23=Daten!$E$18,Z$23<IN_build!$P$5),IN_build!$P$5,Z$23))",
  "AA78":  /* formula */ "IF(OR(AA$23=Daten!$E$17,AA$23=\"\"),IN_build!$R$8,IF(OR(AA$23=Daten!$E$18,AA$23<IN_build!$P$5),IN_build!$P$5,AA$23))",
  "AB78":  /* formula */ "IF(OR(AB$23=Daten!$E$17,AB$23=\"\"),IN_build!$R$8,IF(OR(AB$23=Daten!$E$18,AB$23<IN_build!$P$5),IN_build!$P$5,AB$23))",
  "AC78":  /* formula */ "IF(OR(AC$23=Daten!$E$17,AC$23=\"\"),IN_build!$R$8,IF(OR(AC$23=Daten!$E$18,AC$23<IN_build!$P$5),IN_build!$P$5,AC$23))",
  "AD78":  /* formula */ "IF(OR(AD$23=Daten!$E$17,AD$23=\"\"),IN_build!$R$8,IF(OR(AD$23=Daten!$E$18,AD$23<IN_build!$P$5),IN_build!$P$5,AD$23))",
  "AE78":  /* formula */ "IF(OR(AE$23=Daten!$E$17,AE$23=\"\"),IN_build!$R$8,IF(OR(AE$23=Daten!$E$18,AE$23<IN_build!$P$5),IN_build!$P$5,AE$23))",
  "AF78":  /* formula */ "IF(OR(AF$23=Daten!$E$17,AF$23=\"\"),IN_build!$R$8,IF(OR(AF$23=Daten!$E$18,AF$23<IN_build!$P$5),IN_build!$P$5,AF$23))",
  "D79":  /* unknown */ "roof",
  "E79":  /* unknown */ "win1",
  "F79":  /* unknown */ "YEAR_roof_win1_eff",
  "G79":  /* unknown */ "Abweichendes Einbaujahr ",
  "R79":  /* formula */ "IF(OR(R$43=Daten!$E$17,R$43=\"\"),IF(IN_build!$R$8>=IN_build!$R$9,IN_build!$R$8,IN_build!$R$9),IF(OR(R$43=Daten!$E$18,R$43<IN_build!$P$5),IN_build!$P$5,R$43))",
  "S79":  /* formula */ "IF(OR(S$43=Daten!$E$17,S$43=\"\"),IN_build!$R$8,IF(OR(S$43=Daten!$E$18,S$43<IN_build!$P$5),IN_build!$P$5,S$43))",
  "T79":  /* formula */ "IF(OR(T$43=Daten!$E$17,T$43=\"\"),IN_build!$R$8,IF(OR(T$43=Daten!$E$18,T$43<IN_build!$P$5),IN_build!$P$5,T$43))",
  "U79":  /* formula */ "IF(OR(U$43=Daten!$E$17,U$43=\"\"),IN_build!$R$8,IF(OR(U$43=Daten!$E$18,U$43<IN_build!$P$5),IN_build!$P$5,U$43))",
  "V79":  /* formula */ "IF(OR(V$43=Daten!$E$17,V$43=\"\"),IN_build!$R$8,IF(OR(V$43=Daten!$E$18,V$43<IN_build!$P$5),IN_build!$P$5,V$43))",
  "W79":  /* formula */ "IF(OR(W$43=Daten!$E$17,W$43=\"\"),IN_build!$R$8,IF(OR(W$43=Daten!$E$18,W$43<IN_build!$P$5),IN_build!$P$5,W$43))",
  "X79":  /* formula */ "IF(OR(X$43=Daten!$E$17,X$43=\"\"),IN_build!$R$8,IF(OR(X$43=Daten!$E$18,X$43<IN_build!$P$5),IN_build!$P$5,X$43))",
  "Y79":  /* formula */ "IF(OR(Y$43=Daten!$E$17,Y$43=\"\"),IN_build!$R$8,IF(OR(Y$43=Daten!$E$18,Y$43<IN_build!$P$5),IN_build!$P$5,Y$43))",
  "Z79":  /* formula */ "IF(OR(Z$43=Daten!$E$17,Z$43=\"\"),IN_build!$R$8,IF(OR(Z$43=Daten!$E$18,Z$43<IN_build!$P$5),IN_build!$P$5,Z$43))",
  "AA79":  /* formula */ "IF(OR(AA$43=Daten!$E$17,AA$43=\"\"),IN_build!$R$8,IF(OR(AA$43=Daten!$E$18,AA$43<IN_build!$P$5),IN_build!$P$5,AA$43))",
  "AB79":  /* formula */ "IF(OR(AB$43=Daten!$E$17,AB$43=\"\"),IN_build!$R$8,IF(OR(AB$43=Daten!$E$18,AB$43<IN_build!$P$5),IN_build!$P$5,AB$43))",
  "AC79":  /* formula */ "IF(OR(AC$43=Daten!$E$17,AC$43=\"\"),IN_build!$R$8,IF(OR(AC$43=Daten!$E$18,AC$43<IN_build!$P$5),IN_build!$P$5,AC$43))",
  "AD79":  /* formula */ "IF(OR(AD$43=Daten!$E$17,AD$43=\"\"),IN_build!$R$8,IF(OR(AD$43=Daten!$E$18,AD$43<IN_build!$P$5),IN_build!$P$5,AD$43))",
  "AE79":  /* formula */ "IF(OR(AE$43=Daten!$E$17,AE$43=\"\"),IN_build!$R$8,IF(OR(AE$43=Daten!$E$18,AE$43<IN_build!$P$5),IN_build!$P$5,AE$43))",
  "AF79":  /* formula */ "IF(OR(AF$43=Daten!$E$17,AF$43=\"\"),IN_build!$R$8,IF(OR(AF$43=Daten!$E$18,AF$43<IN_build!$P$5),IN_build!$P$5,AF$43))",
  "D80":  /* unknown */ "roof",
  "E80":  /* unknown */ "win2",
  "F80":  /* unknown */ "YEAR_roof_win1_eff",
  "G80":  /* unknown */ "Abweichendes Einbaujahr ",
  "R80":  /* formula */ "IF(OR(R$47=Daten!$E$17,R$47=\"\"),IF(IN_build!$R$8>=IN_build!$R$9,IN_build!$R$8,IN_build!$R$9),IF(OR(R$47=Daten!$E$18,R$47<IN_build!$P$5),IN_build!$P$5,R$47))",
  "S80":  /* formula */ "IF(OR(S$47=Daten!$E$17,S$47=\"\"),IF(IN_build!$R$8>=IN_build!$R$9,IN_build!$R$8,IN_build!$R$9),IF(OR(S$47=Daten!$E$18,S$47<IN_build!$P$5),IN_build!$P$5,S$47))",
  "T80":  /* formula */ "IF(OR(T$47=Daten!$E$17,T$47=\"\"),IF(IN_build!$R$8>=IN_build!$R$9,IN_build!$R$8,IN_build!$R$9),IF(OR(T$47=Daten!$E$18,T$47<IN_build!$P$5),IN_build!$P$5,T$47))",
  "U80":  /* formula */ "IF(OR(U$47=Daten!$E$17,U$47=\"\"),IF(IN_build!$R$8>=IN_build!$R$9,IN_build!$R$8,IN_build!$R$9),IF(OR(U$47=Daten!$E$18,U$47<IN_build!$P$5),IN_build!$P$5,U$47))",
  "V80":  /* formula */ "IF(OR(V$47=Daten!$E$17,V$47=\"\"),IF(IN_build!$R$8>=IN_build!$R$9,IN_build!$R$8,IN_build!$R$9),IF(OR(V$47=Daten!$E$18,V$47<IN_build!$P$5),IN_build!$P$5,V$47))",
  "W80":  /* formula */ "IF(OR(W$47=Daten!$E$17,W$47=\"\"),IF(IN_build!$R$8>=IN_build!$R$9,IN_build!$R$8,IN_build!$R$9),IF(OR(W$47=Daten!$E$18,W$47<IN_build!$P$5),IN_build!$P$5,W$47))",
  "X80":  /* formula */ "IF(OR(X$47=Daten!$E$17,X$47=\"\"),IF(IN_build!$R$8>=IN_build!$R$9,IN_build!$R$8,IN_build!$R$9),IF(OR(X$47=Daten!$E$18,X$47<IN_build!$P$5),IN_build!$P$5,X$47))",
  "Y80":  /* formula */ "IF(OR(Y$47=Daten!$E$17,Y$47=\"\"),IF(IN_build!$R$8>=IN_build!$R$9,IN_build!$R$8,IN_build!$R$9),IF(OR(Y$47=Daten!$E$18,Y$47<IN_build!$P$5),IN_build!$P$5,Y$47))",
  "Z80":  /* formula */ "IF(OR(Z$47=Daten!$E$17,Z$47=\"\"),IF(IN_build!$R$8>=IN_build!$R$9,IN_build!$R$8,IN_build!$R$9),IF(OR(Z$47=Daten!$E$18,Z$47<IN_build!$P$5),IN_build!$P$5,Z$47))",
  "AA80":  /* formula */ "IF(OR(AA$47=Daten!$E$17,AA$47=\"\"),IF(IN_build!$R$8>=IN_build!$R$9,IN_build!$R$8,IN_build!$R$9),IF(OR(AA$47=Daten!$E$18,AA$47<IN_build!$P$5),IN_build!$P$5,AA$47))",
  "AB80":  /* formula */ "IF(OR(AB$47=Daten!$E$17,AB$47=\"\"),IF(IN_build!$R$8>=IN_build!$R$9,IN_build!$R$8,IN_build!$R$9),IF(OR(AB$47=Daten!$E$18,AB$47<IN_build!$P$5),IN_build!$P$5,AB$47))",
  "AC80":  /* formula */ "IF(OR(AC$47=Daten!$E$17,AC$47=\"\"),IF(IN_build!$R$8>=IN_build!$R$9,IN_build!$R$8,IN_build!$R$9),IF(OR(AC$47=Daten!$E$18,AC$47<IN_build!$P$5),IN_build!$P$5,AC$47))",
  "AD80":  /* formula */ "IF(OR(AD$47=Daten!$E$17,AD$47=\"\"),IF(IN_build!$R$8>=IN_build!$R$9,IN_build!$R$8,IN_build!$R$9),IF(OR(AD$47=Daten!$E$18,AD$47<IN_build!$P$5),IN_build!$P$5,AD$47))",
  "AE80":  /* formula */ "IF(OR(AE$47=Daten!$E$17,AE$47=\"\"),IF(IN_build!$R$8>=IN_build!$R$9,IN_build!$R$8,IN_build!$R$9),IF(OR(AE$47=Daten!$E$18,AE$47<IN_build!$P$5),IN_build!$P$5,AE$47))",
  "AF80":  /* formula */ "IF(OR(AF$47=Daten!$E$17,AF$47=\"\"),IF(IN_build!$R$8>=IN_build!$R$9,IN_build!$R$8,IN_build!$R$9),IF(OR(AF$47=Daten!$E$18,AF$47<IN_build!$P$5),IN_build!$P$5,AF$47))",
} as const;
