// Sheet: OUT_rooms
export const data = {
  "A1":  /* unknown */ "Bezeichnung",
  "B1":  /* unknown */ "Gruppe",
  "C1":  /* unknown */ "Subgruppe",
  "D1":  /* unknown */ "Variable ",
  "E1":  /* unknown */ "Einheit",
  "F1":  /* unknown */ "Kommentar",
  "G1":  /* unknown */ "Position Mockup",
  "H1":  /* unknown */ "Werte Raum",
  "I1":  /* unknown */ "Werte Raum",
  "J1":  /* unknown */ "Werte Raum",
  "K1":  /* unknown */ "Werte Raum",
  "L1":  /* unknown */ "Werte Raum",
  "M1":  /* unknown */ "Werte Raum",
  "A2":  /* unknown */ "Raumindex",
  "D2":  /* unknown */ "ID_R#",
  "H2":  /* unknown */ 1,
  "I2":  /* unknown */ 2,
  "J2":  /* unknown */ 3,
  "K2":  /* unknown */ 4,
  "L2":  /* unknown */ 5,
  "M2":  /* unknown */ 6,
  "N2":  /* unknown */ 7,
  "O2":  /* unknown */ 8,
  "P2":  /* unknown */ 9,
  "Q2":  /* unknown */ 10,
  "R2":  /* unknown */ 11,
  "S2":  /* unknown */ 12,
  "T2":  /* unknown */ 13,
  "U2":  /* unknown */ 14,
  "V2":  /* unknown */ 15,
  "A3":  /* unknown */ "Ausgabe zur Wärmepumpeneignung",
  "B3":  /* unknown */ "room",
  "D3":  /* unknown */ "TXT_room_R1",
  "G3":  /* unknown */ "R1",
  "H3":  /* formula */ "_xlfn.IFS(\n1<=clc_build!G$39,TXT_rooms!$E$5,\n AND(1>clc_build!G$39,clc_build!G$39>=0.8),TXT_rooms!$E$4,\n  OR(AND(0.8>clc_build!G$39,clc_build!G$39>=0.6),clc_build!G$38>clc_build!G$7),TXT_rooms!$E$3,\n   AND(clc_build!G$39<0.6,clc_build!G$38<clc_build!G$7),TXT_rooms!$E$2\n)",
  "I3":  /* formula */ "_xlfn.IFS(\n1<=clc_build!H$39,TXT_rooms!$E$5,\nAND(1>clc_build!H$39,clc_build!H$39>=0.8),TXT_rooms!$E$4,\nOR(AND(0.8>clc_build!H$39,clc_build!H$39>=0.6),clc_build!H$38>clc_build!H$5),TXT_rooms!$E$3,\nAND(clc_build!H$39<0.6,clc_build!H$38<clc_build!H$5),TXT_rooms!$E$2\n)",
  "J3":  /* formula */ "_xlfn.IFS(\n1<=clc_build!I$39,TXT_rooms!$E$5,\nAND(1>clc_build!I$39,clc_build!I$39>=0.8),TXT_rooms!$E$4,\nOR(AND(0.8>clc_build!I$39,clc_build!I$39>=0.6),clc_build!I$38>clc_build!I$5),TXT_rooms!$E$3,\nAND(clc_build!I$39<0.6,clc_build!I$38<clc_build!I$5),TXT_rooms!$E$2\n)",
  "K3":  /* formula */ "_xlfn.IFS(\n1<=clc_build!J$39,TXT_rooms!$E$5,\nAND(1>clc_build!J$39,clc_build!J$39>=0.8),TXT_rooms!$E$4,\nOR(AND(0.8>clc_build!J$39,clc_build!J$39>=0.6),clc_build!J$38>clc_build!J$5),TXT_rooms!$E$3,\nAND(clc_build!J$39<0.6,clc_build!J$38<clc_build!J$5),TXT_rooms!$E$2\n)",
  "L3":  /* formula */ "_xlfn.IFS(\n1<=clc_build!K$39,TXT_rooms!$E$5,\nAND(1>clc_build!K$39,clc_build!K$39>=0.8),TXT_rooms!$E$4,\nOR(AND(0.8>clc_build!K$39,clc_build!K$39>=0.6),clc_build!K$38>clc_build!K$5),TXT_rooms!$E$3,\nAND(clc_build!K$39<0.6,clc_build!K$38<clc_build!K$5),TXT_rooms!$E$2\n)",
  "M3":  /* formula */ "_xlfn.IFS(\n1<=clc_build!L$39,TXT_rooms!$E$5,\nAND(1>clc_build!L$39,clc_build!L$39>=0.8),TXT_rooms!$E$4,\nOR(AND(0.8>clc_build!L$39,clc_build!L$39>=0.6),clc_build!L$38>clc_build!L$5),TXT_rooms!$E$3,\nAND(clc_build!L$39<0.6,clc_build!L$38<clc_build!L$5),TXT_rooms!$E$2\n)",
  "N3":  /* formula */ "_xlfn.IFS(\n1<=clc_build!M$39,TXT_rooms!$E$5,\nAND(1>clc_build!M$39,clc_build!M$39>=0.8),TXT_rooms!$E$4,\nOR(AND(0.8>clc_build!M$39,clc_build!M$39>=0.6),clc_build!M$38>clc_build!M$5),TXT_rooms!$E$3,\nAND(clc_build!M$39<0.6,clc_build!M$38<clc_build!M$5),TXT_rooms!$E$2\n)",
  "O3":  /* formula */ "_xlfn.IFS(\n1<=clc_build!N$39,TXT_rooms!$E$5,\nAND(1>clc_build!N$39,clc_build!N$39>=0.8),TXT_rooms!$E$4,\nOR(AND(0.8>clc_build!N$39,clc_build!N$39>=0.6),clc_build!N$38>clc_build!N$5),TXT_rooms!$E$3,\nAND(clc_build!N$39<0.6,clc_build!N$38<clc_build!N$5),TXT_rooms!$E$2\n)",
  "P3":  /* formula */ "_xlfn.IFS(\n1<=clc_build!O$39,TXT_rooms!$E$5,\nAND(1>clc_build!O$39,clc_build!O$39>=0.8),TXT_rooms!$E$4,\nOR(AND(0.8>clc_build!O$39,clc_build!O$39>=0.6),clc_build!O$38>clc_build!O$5),TXT_rooms!$E$3,\nAND(clc_build!O$39<0.6,clc_build!O$38<clc_build!O$5),TXT_rooms!$E$2\n)",
  "Q3":  /* formula */ "_xlfn.IFS(\n1<=clc_build!P$39,TXT_rooms!$E$5,\nAND(1>clc_build!P$39,clc_build!P$39>=0.8),TXT_rooms!$E$4,\nOR(AND(0.8>clc_build!P$39,clc_build!P$39>=0.6),clc_build!P$38>clc_build!P$5),TXT_rooms!$E$3,\nAND(clc_build!P$39<0.6,clc_build!P$38<clc_build!P$5),TXT_rooms!$E$2\n)",
  "R3":  /* formula */ "_xlfn.IFS(\n1<=clc_build!Q$39,TXT_rooms!$E$5,\nAND(1>clc_build!Q$39,clc_build!Q$39>=0.8),TXT_rooms!$E$4,\nOR(AND(0.8>clc_build!Q$39,clc_build!Q$39>=0.6),clc_build!Q$38>clc_build!Q$5),TXT_rooms!$E$3,\nAND(clc_build!Q$39<0.6,clc_build!Q$38<clc_build!Q$5),TXT_rooms!$E$2\n)",
  "S3":  /* formula */ "_xlfn.IFS(\n1<=clc_build!R$39,TXT_rooms!$E$5,\nAND(1>clc_build!R$39,clc_build!R$39>=0.8),TXT_rooms!$E$4,\nOR(AND(0.8>clc_build!R$39,clc_build!R$39>=0.6),clc_build!R$38>clc_build!R$5),TXT_rooms!$E$3,\nAND(clc_build!R$39<0.6,clc_build!R$38<clc_build!R$5),TXT_rooms!$E$2\n)",
  "T3":  /* formula */ "_xlfn.IFS(\n1<=clc_build!S$39,TXT_rooms!$E$5,\nAND(1>clc_build!S$39,clc_build!S$39>=0.8),TXT_rooms!$E$4,\nOR(AND(0.8>clc_build!S$39,clc_build!S$39>=0.6),clc_build!S$38>clc_build!S$5),TXT_rooms!$E$3,\nAND(clc_build!S$39<0.6,clc_build!S$38<clc_build!S$5),TXT_rooms!$E$2\n)",
  "U3":  /* formula */ "_xlfn.IFS(\n1<=clc_build!T$39,TXT_rooms!$E$5,\nAND(1>clc_build!T$39,clc_build!T$39>=0.8),TXT_rooms!$E$4,\nOR(AND(0.8>clc_build!T$39,clc_build!T$39>=0.6),clc_build!T$38>clc_build!T$5),TXT_rooms!$E$3,\nAND(clc_build!T$39<0.6,clc_build!T$38<clc_build!T$5),TXT_rooms!$E$2\n)",
  "V3":  /* formula */ "_xlfn.IFS(\n1<=clc_build!U$39,TXT_rooms!$E$5,\nAND(1>clc_build!U$39,clc_build!U$39>=0.8),TXT_rooms!$E$4,\nOR(AND(0.8>clc_build!U$39,clc_build!U$39>=0.6),clc_build!U$38>clc_build!U$5),TXT_rooms!$E$3,\nAND(clc_build!U$39<0.6,clc_build!U$38<clc_build!U$5),TXT_rooms!$E$2\n)",
  "A4":  /* unknown */ "Lückentext Bauteilbewertung Raumebene 1",
  "B4":  /* unknown */ "room",
  "D4":  /* unknown */ "TXT_room_R2_fill_1",
  "G4":  /* unknown */ "R2",
  "H4":  /* formula */ "_xlfn.LET(_xlpm.max_HT_share,MAX(clc_build!G$13,clc_build!G$17,clc_build!G$21,clc_build!G$25,clc_build!G$29,clc_build!G$33),\n_xlfn.IFS(clc_load!I$18=_xlpm.max_HT_share,\" Außenwand \",\nclc_load!I$23=_xlpm.max_HT_share,\" Innenwand \",\nclc_load!I$30=_xlpm.max_HT_share,\" Dachfläche \",\nclc_load!I$36=_xlpm.max_HT_share,\" Decke \",\nclc_load!I$41=_xlpm.max_HT_share,\" Fußbodenfläche \",\nclc_build!G$21,\" Fenster \"\n))",
  "I4":  /* formula */ "_xlfn.LET(_xlpm.max_HT_share,MAX(clc_build!H$13,clc_build!H$17,clc_build!H$21,clc_build!H$25,clc_build!H$29,clc_build!H$33),\n_xlfn.IFS(clc_load!J$18=_xlpm.max_HT_share,\" Außenwand \",\nclc_load!J$23=_xlpm.max_HT_share,\" Innenwand \",\nclc_load!J$30=_xlpm.max_HT_share,\" Dachfläche \",\nclc_load!J$36=_xlpm.max_HT_share,\" Decke \",\nclc_load!J$41=_xlpm.max_HT_share,\" Fußbodenfläche \",\nclc_build!H$21,\" Fenster \"\n))",
  "J4":  /* formula */ "_xlfn.LET(_xlpm.max_HT_share,MAX(clc_build!I$13,clc_build!I$17,clc_build!I$21,clc_build!I$25,clc_build!I$29,clc_build!I$33),\n_xlfn.IFS(clc_load!K$18=_xlpm.max_HT_share,\" Außenwand \",\nclc_load!K$23=_xlpm.max_HT_share,\" Innenwand \",\nclc_load!K$30=_xlpm.max_HT_share,\" Dachfläche \",\nclc_load!K$36=_xlpm.max_HT_share,\" Decke \",\nclc_load!K$41=_xlpm.max_HT_share,\" Fußbodenfläche \",\nclc_build!I$21,\" Fenster \"\n))",
  "K4":  /* formula */ "_xlfn.LET(_xlpm.max_HT_share,MAX(clc_build!J$13,clc_build!J$17,clc_build!J$21,clc_build!J$25,clc_build!J$29,clc_build!J$33),\n_xlfn.IFS(clc_load!L$18=_xlpm.max_HT_share,\" Außenwand \",\nclc_load!L$23=_xlpm.max_HT_share,\" Innenwand \",\nclc_load!L$30=_xlpm.max_HT_share,\" Dachfläche \",\nclc_load!L$36=_xlpm.max_HT_share,\" Decke \",\nclc_load!L$41=_xlpm.max_HT_share,\" Fußbodenfläche \",\nclc_build!J$21,\" Fenster \"\n))",
  "L4":  /* formula */ "_xlfn.LET(_xlpm.max_HT_share,MAX(clc_build!K$13,clc_build!K$17,clc_build!K$21,clc_build!K$25,clc_build!K$29,clc_build!K$33),\n_xlfn.IFS(clc_load!M$18=_xlpm.max_HT_share,\" Außenwand \",\nclc_load!M$23=_xlpm.max_HT_share,\" Innenwand \",\nclc_load!M$30=_xlpm.max_HT_share,\" Dachfläche \",\nclc_load!M$36=_xlpm.max_HT_share,\" Decke \",\nclc_load!M$41=_xlpm.max_HT_share,\" Fußbodenfläche \",\nclc_build!K$21,\" Fenster \"\n))",
  "M4":  /* formula */ "_xlfn.LET(_xlpm.max_HT_share,MAX(clc_build!L$13,clc_build!L$17,clc_build!L$21,clc_build!L$25,clc_build!L$29,clc_build!L$33),\n_xlfn.IFS(clc_load!N$18=_xlpm.max_HT_share,\" Außenwand \",\nclc_load!N$23=_xlpm.max_HT_share,\" Innenwand \",\nclc_load!N$30=_xlpm.max_HT_share,\" Dachfläche \",\nclc_load!N$36=_xlpm.max_HT_share,\" Decke \",\nclc_load!N$41=_xlpm.max_HT_share,\" Fußbodenfläche \",\nclc_build!L$21,\" Fenster \"\n))",
  "N4":  /* formula */ "_xlfn.LET(_xlpm.max_HT_share,MAX(clc_build!M$13,clc_build!M$17,clc_build!M$21,clc_build!M$25,clc_build!M$29,clc_build!M$33),\n_xlfn.IFS(clc_load!O$18=_xlpm.max_HT_share,\" Außenwand \",\nclc_load!O$23=_xlpm.max_HT_share,\" Innenwand \",\nclc_load!O$30=_xlpm.max_HT_share,\" Dachfläche \",\nclc_load!O$36=_xlpm.max_HT_share,\" Decke \",\nclc_load!O$41=_xlpm.max_HT_share,\" Fußbodenfläche \",\nclc_build!M$21,\" Fenster \"\n))",
  "O4":  /* formula */ "_xlfn.LET(_xlpm.max_HT_share,MAX(clc_build!N$13,clc_build!N$17,clc_build!N$21,clc_build!N$25,clc_build!N$29,clc_build!N$33),\n_xlfn.IFS(clc_load!P$18=_xlpm.max_HT_share,\" Außenwand \",\nclc_load!P$23=_xlpm.max_HT_share,\" Innenwand \",\nclc_load!P$30=_xlpm.max_HT_share,\" Dachfläche \",\nclc_load!P$36=_xlpm.max_HT_share,\" Decke \",\nclc_load!P$41=_xlpm.max_HT_share,\" Fußbodenfläche \",\nclc_build!N$21,\" Fenster \"\n))",
  "P4":  /* formula */ "_xlfn.LET(_xlpm.max_HT_share,MAX(clc_build!O$13,clc_build!O$17,clc_build!O$21,clc_build!O$25,clc_build!O$29,clc_build!O$33),\n_xlfn.IFS(clc_load!Q$18=_xlpm.max_HT_share,\" Außenwand \",\nclc_load!Q$23=_xlpm.max_HT_share,\" Innenwand \",\nclc_load!Q$30=_xlpm.max_HT_share,\" Dachfläche \",\nclc_load!Q$36=_xlpm.max_HT_share,\" Decke \",\nclc_load!Q$41=_xlpm.max_HT_share,\" Fußbodenfläche \",\nclc_build!O$21,\" Fenster \"\n))",
  "Q4":  /* formula */ "_xlfn.LET(_xlpm.max_HT_share,MAX(clc_build!P$13,clc_build!P$17,clc_build!P$21,clc_build!P$25,clc_build!P$29,clc_build!P$33),\n_xlfn.IFS(clc_load!R$18=_xlpm.max_HT_share,\" Außenwand \",\nclc_load!R$23=_xlpm.max_HT_share,\" Innenwand \",\nclc_load!R$30=_xlpm.max_HT_share,\" Dachfläche \",\nclc_load!R$36=_xlpm.max_HT_share,\" Decke \",\nclc_load!R$41=_xlpm.max_HT_share,\" Fußbodenfläche \",\nclc_build!P$21,\" Fenster \"\n))",
  "R4":  /* formula */ "_xlfn.LET(_xlpm.max_HT_share,MAX(clc_build!Q$13,clc_build!Q$17,clc_build!Q$21,clc_build!Q$25,clc_build!Q$29,clc_build!Q$33),\n_xlfn.IFS(clc_load!S$18=_xlpm.max_HT_share,\" Außenwand \",\nclc_load!S$23=_xlpm.max_HT_share,\" Innenwand \",\nclc_load!S$30=_xlpm.max_HT_share,\" Dachfläche \",\nclc_load!S$36=_xlpm.max_HT_share,\" Decke \",\nclc_load!S$41=_xlpm.max_HT_share,\" Fußbodenfläche \",\nclc_build!Q$21,\" Fenster \"\n))",
  "S4":  /* formula */ "_xlfn.LET(_xlpm.max_HT_share,MAX(clc_build!R$13,clc_build!R$17,clc_build!R$21,clc_build!R$25,clc_build!R$29,clc_build!R$33),\n_xlfn.IFS(clc_load!T$18=_xlpm.max_HT_share,\" Außenwand \",\nclc_load!T$23=_xlpm.max_HT_share,\" Innenwand \",\nclc_load!T$30=_xlpm.max_HT_share,\" Dachfläche \",\nclc_load!T$36=_xlpm.max_HT_share,\" Decke \",\nclc_load!T$41=_xlpm.max_HT_share,\" Fußbodenfläche \",\nclc_build!R$21,\" Fenster \"\n))",
  "T4":  /* formula */ "_xlfn.LET(_xlpm.max_HT_share,MAX(clc_build!S$13,clc_build!S$17,clc_build!S$21,clc_build!S$25,clc_build!S$29,clc_build!S$33),\n_xlfn.IFS(clc_load!U$18=_xlpm.max_HT_share,\" Außenwand \",\nclc_load!U$23=_xlpm.max_HT_share,\" Innenwand \",\nclc_load!U$30=_xlpm.max_HT_share,\" Dachfläche \",\nclc_load!U$36=_xlpm.max_HT_share,\" Decke \",\nclc_load!U$41=_xlpm.max_HT_share,\" Fußbodenfläche \",\nclc_build!S$21,\" Fenster \"\n))",
  "U4":  /* formula */ "_xlfn.LET(_xlpm.max_HT_share,MAX(clc_build!T$13,clc_build!T$17,clc_build!T$21,clc_build!T$25,clc_build!T$29,clc_build!T$33),\n_xlfn.IFS(clc_load!V$18=_xlpm.max_HT_share,\" Außenwand \",\nclc_load!V$23=_xlpm.max_HT_share,\" Innenwand \",\nclc_load!V$30=_xlpm.max_HT_share,\" Dachfläche \",\nclc_load!V$36=_xlpm.max_HT_share,\" Decke \",\nclc_load!V$41=_xlpm.max_HT_share,\" Fußbodenfläche \",\nclc_build!T$21,\" Fenster \"\n))",
  "V4":  /* formula */ "_xlfn.LET(_xlpm.max_HT_share,MAX(clc_build!U$13,clc_build!U$17,clc_build!U$21,clc_build!U$25,clc_build!U$29,clc_build!U$33),\n_xlfn.IFS(clc_load!W$18=_xlpm.max_HT_share,\" Außenwand \",\nclc_load!W$23=_xlpm.max_HT_share,\" Innenwand \",\nclc_load!W$30=_xlpm.max_HT_share,\" Dachfläche \",\nclc_load!W$36=_xlpm.max_HT_share,\" Decke \",\nclc_load!W$41=_xlpm.max_HT_share,\" Fußbodenfläche \",\nclc_build!U$21,\" Fenster \"\n))",
  "A5":  /* unknown */ "Lückentext Bauteilbewertung Raumebene 2",
  "B5":  /* unknown */ "room",
  "D5":  /* unknown */ "TXT_room_R2_fill_2",
  "G5":  /* unknown */ "R2",
  "H5":  /* formula */ "_xlfn.LET(\n_xlpm.second_HT_share,LARGE((clc_build!G$13,clc_build!G$17,clc_build!G$21,clc_build!G$25,clc_build!G$29,clc_build!G$33),2),\n_xlfn.IFS(clc_load!I$18=_xlpm.second_HT_share,\" Außenwand \",\nclc_load!I$23=_xlpm.second_HT_share,\" Innenwand \",\nclc_load!I$30=_xlpm.second_HT_share,\" Dachfläche \",\nclc_load!I$36=_xlpm.second_HT_share,\" Decke \",\nclc_load!I$41=_xlpm.second_HT_share,\" Fußbodenfläche \",\nclc_build!G$21=_xlpm.second_HT_share,\" Fenster \"))",
  "I5":  /* formula */ "_xlfn.LET(\n_xlpm.second_HT_share,LARGE((clc_build!H$13,clc_build!H$17,clc_build!H$21,clc_build!H$25,clc_build!H$29,clc_build!H$33),2),\n_xlfn.IFS(clc_load!J$18=_xlpm.second_HT_share,\" Außenwand \",\nclc_load!J$23=_xlpm.second_HT_share,\" Innenwand \",\nclc_load!J$30=_xlpm.second_HT_share,\" Dachfläche \",\nclc_load!J$36=_xlpm.second_HT_share,\" Decke \",\nclc_load!J$41=_xlpm.second_HT_share,\" Fußbodenfläche \",\nclc_build!H$21=_xlpm.second_HT_share,\" Fenster \"))",
  "J5":  /* formula */ "_xlfn.LET(\n_xlpm.second_HT_share,LARGE((clc_build!I$13,clc_build!I$17,clc_build!I$21,clc_build!I$25,clc_build!I$29,clc_build!I$33),2),\n_xlfn.IFS(clc_load!K$18=_xlpm.second_HT_share,\" Außenwand \",\nclc_load!K$23=_xlpm.second_HT_share,\" Innenwand \",\nclc_load!K$30=_xlpm.second_HT_share,\" Dachfläche \",\nclc_load!K$36=_xlpm.second_HT_share,\" Decke \",\nclc_load!K$41=_xlpm.second_HT_share,\" Fußbodenfläche \",\nclc_build!I$21=_xlpm.second_HT_share,\" Fenster \"))",
  "K5":  /* formula */ "_xlfn.LET(\n_xlpm.second_HT_share,LARGE((clc_build!J$13,clc_build!J$17,clc_build!J$21,clc_build!J$25,clc_build!J$29,clc_build!J$33),2),\n_xlfn.IFS(clc_load!L$18=_xlpm.second_HT_share,\" Außenwand \",\nclc_load!L$23=_xlpm.second_HT_share,\" Innenwand \",\nclc_load!L$30=_xlpm.second_HT_share,\" Dachfläche \",\nclc_load!L$36=_xlpm.second_HT_share,\" Decke \",\nclc_load!L$41=_xlpm.second_HT_share,\" Fußbodenfläche \",\nclc_build!J$21=_xlpm.second_HT_share,\" Fenster \"))",
  "L5":  /* formula */ "_xlfn.LET(\n_xlpm.second_HT_share,LARGE((clc_build!K$13,clc_build!K$17,clc_build!K$21,clc_build!K$25,clc_build!K$29,clc_build!K$33),2),\n_xlfn.IFS(clc_load!M$18=_xlpm.second_HT_share,\" Außenwand \",\nclc_load!M$23=_xlpm.second_HT_share,\" Innenwand \",\nclc_load!M$30=_xlpm.second_HT_share,\" Dachfläche \",\nclc_load!M$36=_xlpm.second_HT_share,\" Decke \",\nclc_load!M$41=_xlpm.second_HT_share,\" Fußbodenfläche \",\nclc_build!K$21=_xlpm.second_HT_share,\" Fenster \"))",
  "M5":  /* formula */ "_xlfn.LET(\n_xlpm.second_HT_share,LARGE((clc_build!L$13,clc_build!L$17,clc_build!L$21,clc_build!L$25,clc_build!L$29,clc_build!L$33),2),\n_xlfn.IFS(clc_load!N$18=_xlpm.second_HT_share,\" Außenwand \",\nclc_load!N$23=_xlpm.second_HT_share,\" Innenwand \",\nclc_load!N$30=_xlpm.second_HT_share,\" Dachfläche \",\nclc_load!N$36=_xlpm.second_HT_share,\" Decke \",\nclc_load!N$41=_xlpm.second_HT_share,\" Fußbodenfläche \",\nclc_build!L$21=_xlpm.second_HT_share,\" Fenster \"))",
  "N5":  /* formula */ "_xlfn.LET(\n_xlpm.second_HT_share,LARGE((clc_build!M$13,clc_build!M$17,clc_build!M$21,clc_build!M$25,clc_build!M$29,clc_build!M$33),2),\n_xlfn.IFS(clc_load!O$18=_xlpm.second_HT_share,\" Außenwand \",\nclc_load!O$23=_xlpm.second_HT_share,\" Innenwand \",\nclc_load!O$30=_xlpm.second_HT_share,\" Dachfläche \",\nclc_load!O$36=_xlpm.second_HT_share,\" Decke \",\nclc_load!O$41=_xlpm.second_HT_share,\" Fußbodenfläche \",\nclc_build!M$21=_xlpm.second_HT_share,\" Fenster \"))",
  "O5":  /* formula */ "_xlfn.LET(\n_xlpm.second_HT_share,LARGE((clc_build!N$13,clc_build!N$17,clc_build!N$21,clc_build!N$25,clc_build!N$29,clc_build!N$33),2),\n_xlfn.IFS(clc_load!P$18=_xlpm.second_HT_share,\" Außenwand \",\nclc_load!P$23=_xlpm.second_HT_share,\" Innenwand \",\nclc_load!P$30=_xlpm.second_HT_share,\" Dachfläche \",\nclc_load!P$36=_xlpm.second_HT_share,\" Decke \",\nclc_load!P$41=_xlpm.second_HT_share,\" Fußbodenfläche \",\nclc_build!N$21=_xlpm.second_HT_share,\" Fenster \"))",
  "P5":  /* formula */ "_xlfn.LET(\n_xlpm.second_HT_share,LARGE((clc_build!O$13,clc_build!O$17,clc_build!O$21,clc_build!O$25,clc_build!O$29,clc_build!O$33),2),\n_xlfn.IFS(clc_load!Q$18=_xlpm.second_HT_share,\" Außenwand \",\nclc_load!Q$23=_xlpm.second_HT_share,\" Innenwand \",\nclc_load!Q$30=_xlpm.second_HT_share,\" Dachfläche \",\nclc_load!Q$36=_xlpm.second_HT_share,\" Decke \",\nclc_load!Q$41=_xlpm.second_HT_share,\" Fußbodenfläche \",\nclc_build!O$21=_xlpm.second_HT_share,\" Fenster \"))",
  "Q5":  /* formula */ "_xlfn.LET(\n_xlpm.second_HT_share,LARGE((clc_build!P$13,clc_build!P$17,clc_build!P$21,clc_build!P$25,clc_build!P$29,clc_build!P$33),2),\n_xlfn.IFS(clc_load!R$18=_xlpm.second_HT_share,\" Außenwand \",\nclc_load!R$23=_xlpm.second_HT_share,\" Innenwand \",\nclc_load!R$30=_xlpm.second_HT_share,\" Dachfläche \",\nclc_load!R$36=_xlpm.second_HT_share,\" Decke \",\nclc_load!R$41=_xlpm.second_HT_share,\" Fußbodenfläche \",\nclc_build!P$21=_xlpm.second_HT_share,\" Fenster \"))",
  "R5":  /* formula */ "_xlfn.LET(\n_xlpm.second_HT_share,LARGE((clc_build!Q$13,clc_build!Q$17,clc_build!Q$21,clc_build!Q$25,clc_build!Q$29,clc_build!Q$33),2),\n_xlfn.IFS(clc_load!S$18=_xlpm.second_HT_share,\" Außenwand \",\nclc_load!S$23=_xlpm.second_HT_share,\" Innenwand \",\nclc_load!S$30=_xlpm.second_HT_share,\" Dachfläche \",\nclc_load!S$36=_xlpm.second_HT_share,\" Decke \",\nclc_load!S$41=_xlpm.second_HT_share,\" Fußbodenfläche \",\nclc_build!Q$21=_xlpm.second_HT_share,\" Fenster \"))",
  "S5":  /* formula */ "_xlfn.LET(\n_xlpm.second_HT_share,LARGE((clc_build!R$13,clc_build!R$17,clc_build!R$21,clc_build!R$25,clc_build!R$29,clc_build!R$33),2),\n_xlfn.IFS(clc_load!T$18=_xlpm.second_HT_share,\" Außenwand \",\nclc_load!T$23=_xlpm.second_HT_share,\" Innenwand \",\nclc_load!T$30=_xlpm.second_HT_share,\" Dachfläche \",\nclc_load!T$36=_xlpm.second_HT_share,\" Decke \",\nclc_load!T$41=_xlpm.second_HT_share,\" Fußbodenfläche \",\nclc_build!R$21=_xlpm.second_HT_share,\" Fenster \"))",
  "T5":  /* formula */ "_xlfn.LET(\n_xlpm.second_HT_share,LARGE((clc_build!S$13,clc_build!S$17,clc_build!S$21,clc_build!S$25,clc_build!S$29,clc_build!S$33),2),\n_xlfn.IFS(clc_load!U$18=_xlpm.second_HT_share,\" Außenwand \",\nclc_load!U$23=_xlpm.second_HT_share,\" Innenwand \",\nclc_load!U$30=_xlpm.second_HT_share,\" Dachfläche \",\nclc_load!U$36=_xlpm.second_HT_share,\" Decke \",\nclc_load!U$41=_xlpm.second_HT_share,\" Fußbodenfläche \",\nclc_build!S$21=_xlpm.second_HT_share,\" Fenster \"))",
  "U5":  /* formula */ "_xlfn.LET(\n_xlpm.second_HT_share,LARGE((clc_build!T$13,clc_build!T$17,clc_build!T$21,clc_build!T$25,clc_build!T$29,clc_build!T$33),2),\n_xlfn.IFS(clc_load!V$18=_xlpm.second_HT_share,\" Außenwand \",\nclc_load!V$23=_xlpm.second_HT_share,\" Innenwand \",\nclc_load!V$30=_xlpm.second_HT_share,\" Dachfläche \",\nclc_load!V$36=_xlpm.second_HT_share,\" Decke \",\nclc_load!V$41=_xlpm.second_HT_share,\" Fußbodenfläche \",\nclc_build!T$21=_xlpm.second_HT_share,\" Fenster \"))",
  "V5":  /* formula */ "_xlfn.LET(\n_xlpm.second_HT_share,LARGE((clc_build!U$13,clc_build!U$17,clc_build!U$21,clc_build!U$25,clc_build!U$29,clc_build!U$33),2),\n_xlfn.IFS(clc_load!W$18=_xlpm.second_HT_share,\" Außenwand \",\nclc_load!W$23=_xlpm.second_HT_share,\" Innenwand \",\nclc_load!W$30=_xlpm.second_HT_share,\" Dachfläche \",\nclc_load!W$36=_xlpm.second_HT_share,\" Decke \",\nclc_load!W$41=_xlpm.second_HT_share,\" Fußbodenfläche \",\nclc_build!U$21=_xlpm.second_HT_share,\" Fenster \"))",
  "A6":  /* unknown */ "Ausgabe Bauteilbewertung Raumebene",
  "B6":  /* unknown */ "room",
  "D6":  /* unknown */ "TXT_room_R2_Qdot",
  "G6":  /* unknown */ "R2",
  "H6":  /* formula */ "_xlfn.IFS(\nclc_build!G$8<50,TXT_rooms!$E$6,\nAND(clc_build!G$8>=50,clc_build!G$8<70),TXT_rooms!$E$7&OUT_rooms!H$4&TXT_rooms!$E$8,\nAND(clc_build!G$8>=70,clc_build!G$8<90),TXT_rooms!$E$9&OUT_rooms!H$4&TXT_rooms!$E$10,\nclc_build!G$8>=90,TXT_rooms!$E$11&OUT_rooms!H$4&\"und die\"&H$5&TXT_rooms!$E$12\n)",
  "I6":  /* formula */ "_xlfn.IFS(\nclc_build!H$8<50,TXT_rooms!$E$6,\nAND(clc_build!H$8>=50,clc_build!H$8<70),TXT_rooms!$E$7&OUT_rooms!I$4&TXT_rooms!$E$8,\nAND(clc_build!H$8>=70,clc_build!H$8<90),TXT_rooms!$E$9&OUT_rooms!I$4&TXT_rooms!$E$10,\nclc_build!H$8>=90,TXT_rooms!$E$11&OUT_rooms!I$4&\"und die\"&I$5&TXT_rooms!$E$12\n)",
  "J6":  /* formula */ "_xlfn.IFS(\nclc_build!I$8<50,TXT_rooms!$E$6,\nAND(clc_build!I$8>=50,clc_build!I$8<70),TXT_rooms!$E$7&OUT_rooms!J$4&TXT_rooms!$E$8,\nAND(clc_build!I$8>=70,clc_build!I$8<90),TXT_rooms!$E$9&OUT_rooms!J$4&TXT_rooms!$E$10,\nclc_build!I$8>=90,TXT_rooms!$E$11&OUT_rooms!J$4&\"und die\"&J$5&TXT_rooms!$E$12\n)",
  "K6":  /* formula */ "_xlfn.IFS(\nclc_build!J$8<50,TXT_rooms!$E$6,\nAND(clc_build!J$8>=50,clc_build!J$8<70),TXT_rooms!$E$7&OUT_rooms!K$4&TXT_rooms!$E$8,\nAND(clc_build!J$8>=70,clc_build!J$8<90),TXT_rooms!$E$9&OUT_rooms!K$4&TXT_rooms!$E$10,\nclc_build!J$8>=90,TXT_rooms!$E$11&OUT_rooms!K$4&\"und die\"&K$5&TXT_rooms!$E$12\n)",
  "L6":  /* formula */ "_xlfn.IFS(\nclc_build!K$8<50,TXT_rooms!$E$6,\nAND(clc_build!K$8>=50,clc_build!K$8<70),TXT_rooms!$E$7&OUT_rooms!L$4&TXT_rooms!$E$8,\nAND(clc_build!K$8>=70,clc_build!K$8<90),TXT_rooms!$E$9&OUT_rooms!L$4&TXT_rooms!$E$10,\nclc_build!K$8>=90,TXT_rooms!$E$11&OUT_rooms!L$4&\"und die\"&L$5&TXT_rooms!$E$12\n)",
  "M6":  /* formula */ "_xlfn.IFS(\nclc_build!L$8<50,TXT_rooms!$E$6,\nAND(clc_build!L$8>=50,clc_build!L$8<70),TXT_rooms!$E$7&OUT_rooms!M$4&TXT_rooms!$E$8,\nAND(clc_build!L$8>=70,clc_build!L$8<90),TXT_rooms!$E$9&OUT_rooms!M$4&TXT_rooms!$E$10,\nclc_build!L$8>=90,TXT_rooms!$E$11&OUT_rooms!M$4&\"und die\"&M$5&TXT_rooms!$E$12\n)",
  "N6":  /* formula */ "_xlfn.IFS(\nclc_build!M$8<50,TXT_rooms!$E$6,\nAND(clc_build!M$8>=50,clc_build!M$8<70),TXT_rooms!$E$7&OUT_rooms!N$4&TXT_rooms!$E$8,\nAND(clc_build!M$8>=70,clc_build!M$8<90),TXT_rooms!$E$9&OUT_rooms!N$4&TXT_rooms!$E$10,\nclc_build!M$8>=90,TXT_rooms!$E$11&OUT_rooms!N$4&\"und die\"&N$5&TXT_rooms!$E$12\n)",
  "O6":  /* formula */ "_xlfn.IFS(\nclc_build!N$8<50,TXT_rooms!$E$6,\nAND(clc_build!N$8>=50,clc_build!N$8<70),TXT_rooms!$E$7&OUT_rooms!O$4&TXT_rooms!$E$8,\nAND(clc_build!N$8>=70,clc_build!N$8<90),TXT_rooms!$E$9&OUT_rooms!O$4&TXT_rooms!$E$10,\nclc_build!N$8>=90,TXT_rooms!$E$11&OUT_rooms!O$4&\"und die\"&O$5&TXT_rooms!$E$12\n)",
  "P6":  /* formula */ "_xlfn.IFS(\nclc_build!O$8<50,TXT_rooms!$E$6,\nAND(clc_build!O$8>=50,clc_build!O$8<70),TXT_rooms!$E$7&OUT_rooms!P$4&TXT_rooms!$E$8,\nAND(clc_build!O$8>=70,clc_build!O$8<90),TXT_rooms!$E$9&OUT_rooms!P$4&TXT_rooms!$E$10,\nclc_build!O$8>=90,TXT_rooms!$E$11&OUT_rooms!P$4&\"und die\"&P$5&TXT_rooms!$E$12\n)",
  "Q6":  /* formula */ "_xlfn.IFS(\nclc_build!P$8<50,TXT_rooms!$E$6,\nAND(clc_build!P$8>=50,clc_build!P$8<70),TXT_rooms!$E$7&OUT_rooms!Q$4&TXT_rooms!$E$8,\nAND(clc_build!P$8>=70,clc_build!P$8<90),TXT_rooms!$E$9&OUT_rooms!Q$4&TXT_rooms!$E$10,\nclc_build!P$8>=90,TXT_rooms!$E$11&OUT_rooms!Q$4&\"und die\"&Q$5&TXT_rooms!$E$12\n)",
  "R6":  /* formula */ "_xlfn.IFS(\nclc_build!Q$8<50,TXT_rooms!$E$6,\nAND(clc_build!Q$8>=50,clc_build!Q$8<70),TXT_rooms!$E$7&OUT_rooms!R$4&TXT_rooms!$E$8,\nAND(clc_build!Q$8>=70,clc_build!Q$8<90),TXT_rooms!$E$9&OUT_rooms!R$4&TXT_rooms!$E$10,\nclc_build!Q$8>=90,TXT_rooms!$E$11&OUT_rooms!R$4&\"und die\"&R$5&TXT_rooms!$E$12\n)",
  "S6":  /* formula */ "_xlfn.IFS(\nclc_build!R$8<50,TXT_rooms!$E$6,\nAND(clc_build!R$8>=50,clc_build!R$8<70),TXT_rooms!$E$7&OUT_rooms!S$4&TXT_rooms!$E$8,\nAND(clc_build!R$8>=70,clc_build!R$8<90),TXT_rooms!$E$9&OUT_rooms!S$4&TXT_rooms!$E$10,\nclc_build!R$8>=90,TXT_rooms!$E$11&OUT_rooms!S$4&\"und die\"&S$5&TXT_rooms!$E$12\n)",
  "T6":  /* formula */ "_xlfn.IFS(\nclc_build!S$8<50,TXT_rooms!$E$6,\nAND(clc_build!S$8>=50,clc_build!S$8<70),TXT_rooms!$E$7&OUT_rooms!T$4&TXT_rooms!$E$8,\nAND(clc_build!S$8>=70,clc_build!S$8<90),TXT_rooms!$E$9&OUT_rooms!T$4&TXT_rooms!$E$10,\nclc_build!S$8>=90,TXT_rooms!$E$11&OUT_rooms!T$4&\"und die\"&T$5&TXT_rooms!$E$12\n)",
  "U6":  /* formula */ "_xlfn.IFS(\nclc_build!T$8<50,TXT_rooms!$E$6,\nAND(clc_build!T$8>=50,clc_build!T$8<70),TXT_rooms!$E$7&OUT_rooms!U$4&TXT_rooms!$E$8,\nAND(clc_build!T$8>=70,clc_build!T$8<90),TXT_rooms!$E$9&OUT_rooms!U$4&TXT_rooms!$E$10,\nclc_build!T$8>=90,TXT_rooms!$E$11&OUT_rooms!U$4&\"und die\"&U$5&TXT_rooms!$E$12\n)",
  "V6":  /* formula */ "_xlfn.IFS(\nclc_build!U$8<50,TXT_rooms!$E$6,\nAND(clc_build!U$8>=50,clc_build!U$8<70),TXT_rooms!$E$7&OUT_rooms!V$4&TXT_rooms!$E$8,\nAND(clc_build!U$8>=70,clc_build!U$8<90),TXT_rooms!$E$9&OUT_rooms!V$4&TXT_rooms!$E$10,\nclc_build!U$8>=90,TXT_rooms!$E$11&OUT_rooms!V$4&\"und die\"&V$5&TXT_rooms!$E$12\n)",
  "A7":  /* unknown */ "Lückentext Bewertung Heizkörpertausch Raumebene 1",
  "B7":  /* unknown */ "room",
  "D7":  /* unknown */ "TXT_room_R3_fill_1",
  "G7":  /* unknown */ "R3",
  "H7":  /* formula */ " _xlfn.IFS(\n    clc_build!G$39>0.5,\n\" größerer \",\n    AND(clc_build!G$39 >0.45,clc_build!G$39<=0.5),\n\" mindestens doppelt so großer \",\n    AND(clc_build!G$39 >0.34,clc_build!G$39<=0.45),\n\" dreimal so großer \",\n   clc_build!G$39<=0.34,\n\" sehr viel größerer \"\n)",
  "I7":  /* formula */ " _xlfn.IFS(\n    clc_build!H$39>0.5,\n\" größerer \",\n    AND(clc_build!H$39 >0.45,clc_build!H$39<=0.5),\n\" mindestens doppelt so großer \",\n    AND(clc_build!H$39 >0.34,clc_build!H$39<=0.45),\n\" dreimal so großer \",\n   clc_build!H$39<=0.34,\n\" sehr viel größerer \"\n)",
  "J7":  /* formula */ " _xlfn.IFS(\n    clc_build!I$39>0.5,\n\" größerer \",\n    AND(clc_build!I$39 >0.45,clc_build!I$39<=0.5),\n\" mindestens doppelt so großer \",\n    AND(clc_build!I$39 >0.34,clc_build!I$39<=0.45),\n\" dreimal so großer \",\n   clc_build!I$39<=0.34,\n\" sehr viel größerer \"\n)",
  "K7":  /* formula */ " _xlfn.IFS(\n    clc_build!J$39>0.5,\n\" größerer \",\n    AND(clc_build!J$39 >0.45,clc_build!J$39<=0.5),\n\" mindestens doppelt so großer \",\n    AND(clc_build!J$39 >0.34,clc_build!J$39<=0.45),\n\" dreimal so großer \",\n   clc_build!J$39<=0.34,\n\" sehr viel größerer \"\n)",
  "L7":  /* formula */ " _xlfn.IFS(\n    clc_build!K$39>0.5,\n\" größerer \",\n    AND(clc_build!K$39 >0.45,clc_build!K$39<=0.5),\n\" mindestens doppelt so großer \",\n    AND(clc_build!K$39 >0.34,clc_build!K$39<=0.45),\n\" dreimal so großer \",\n   clc_build!K$39<=0.34,\n\" sehr viel größerer \"\n)",
  "M7":  /* formula */ " _xlfn.IFS(\n    clc_build!L$39>0.5,\n\" größerer \",\n    AND(clc_build!L$39 >0.45,clc_build!L$39<=0.5),\n\" mindestens doppelt so großer \",\n    AND(clc_build!L$39 >0.34,clc_build!L$39<=0.45),\n\" dreimal so großer \",\n   clc_build!L$39<=0.34,\n\" sehr viel größerer \"\n)",
  "N7":  /* formula */ " _xlfn.IFS(\n    clc_build!M$39>0.5,\n\" größerer \",\n    AND(clc_build!M$39 >0.45,clc_build!M$39<=0.5),\n\" mindestens doppelt so großer \",\n    AND(clc_build!M$39 >0.34,clc_build!M$39<=0.45),\n\" dreimal so großer \",\n   clc_build!M$39<=0.34,\n\" sehr viel größerer \"\n)",
  "O7":  /* formula */ " _xlfn.IFS(\n    clc_build!N$39>0.5,\n\" größerer \",\n    AND(clc_build!N$39 >0.45,clc_build!N$39<=0.5),\n\" mindestens doppelt so großer \",\n    AND(clc_build!N$39 >0.34,clc_build!N$39<=0.45),\n\" dreimal so großer \",\n   clc_build!N$39<=0.34,\n\" sehr viel größerer \"\n)",
  "P7":  /* formula */ " _xlfn.IFS(\n    clc_build!O$39>0.5,\n\" größerer \",\n    AND(clc_build!O$39 >0.45,clc_build!O$39<=0.5),\n\" mindestens doppelt so großer \",\n    AND(clc_build!O$39 >0.34,clc_build!O$39<=0.45),\n\" dreimal so großer \",\n   clc_build!O$39<=0.34,\n\" sehr viel größerer \"\n)",
  "Q7":  /* formula */ " _xlfn.IFS(\n    clc_build!P$39>0.5,\n\" größerer \",\n    AND(clc_build!P$39 >0.45,clc_build!P$39<=0.5),\n\" mindestens doppelt so großer \",\n    AND(clc_build!P$39 >0.34,clc_build!P$39<=0.45),\n\" dreimal so großer \",\n   clc_build!P$39<=0.34,\n\" sehr viel größerer \"\n)",
  "R7":  /* formula */ " _xlfn.IFS(\n    clc_build!Q$39>0.5,\n\" größerer \",\n    AND(clc_build!Q$39 >0.45,clc_build!Q$39<=0.5),\n\" mindestens doppelt so großer \",\n    AND(clc_build!Q$39 >0.34,clc_build!Q$39<=0.45),\n\" dreimal so großer \",\n   clc_build!Q$39<=0.34,\n\" sehr viel größerer \"\n)",
  "S7":  /* formula */ " _xlfn.IFS(\n    clc_build!R$39>0.5,\n\" größerer \",\n    AND(clc_build!R$39 >0.45,clc_build!R$39<=0.5),\n\" mindestens doppelt so großer \",\n    AND(clc_build!R$39 >0.34,clc_build!R$39<=0.45),\n\" dreimal so großer \",\n   clc_build!R$39<=0.34,\n\" sehr viel größerer \"\n)",
  "T7":  /* formula */ " _xlfn.IFS(\n    clc_build!S$39>0.5,\n\" größerer \",\n    AND(clc_build!S$39 >0.45,clc_build!S$39<=0.5),\n\" mindestens doppelt so großer \",\n    AND(clc_build!S$39 >0.34,clc_build!S$39<=0.45),\n\" dreimal so großer \",\n   clc_build!S$39<=0.34,\n\" sehr viel größerer \"\n)",
  "U7":  /* formula */ " _xlfn.IFS(\n    clc_build!T$39>0.5,\n\" größerer \",\n    AND(clc_build!T$39 >0.45,clc_build!T$39<=0.5),\n\" mindestens doppelt so großer \",\n    AND(clc_build!T$39 >0.34,clc_build!T$39<=0.45),\n\" dreimal so großer \",\n   clc_build!T$39<=0.34,\n\" sehr viel größerer \"\n)",
  "V7":  /* formula */ " _xlfn.IFS(\n    clc_build!U$39>0.5,\n\" größerer \",\n    AND(clc_build!U$39 >0.45,clc_build!U$39<=0.5),\n\" mindestens doppelt so großer \",\n    AND(clc_build!U$39 >0.34,clc_build!U$39<=0.45),\n\" dreimal so großer \",\n   clc_build!U$39<=0.34,\n\" sehr viel größerer \"\n)",
  "A8":  /* unknown */ "Lückentext Bewertung Heizkörpertausch Raumebene 2",
  "B8":  /* unknown */ "room",
  "D8":  /* unknown */ "TXT_room_R3_fill_2",
  "G8":  /* unknown */ "R3",
  "H8":  /* formula */ " _xlfn.IFS(\n    clc_build!G$39>0.85,\n\" spürbar mehr \",\n    AND(clc_build!G$39 >0.77,clc_build!G$39<=0.85),\n\" 30 Prozent mehr\",\n    AND(clc_build!G$39 > 0.65, clc_build!G$39 <= 0.77),\n\" 50 Prozent mehr \",\n    AND(clc_build!G$39 > 0.5, clc_build!G$39 <= 0.65),\n\" doppelt so viel \",\nclc_build!G$39 <= 0.5,\n\" deutlich mehr \"\n)",
  "I8":  /* formula */ " _xlfn.IFS(\n    clc_build!H$39>0.85,\n\" spürbar mehr \",\n    AND(clc_build!H$39 >0.77,clc_build!H$39<=0.85),\n\" 30 Prozent mehr\",\n    AND(clc_build!H$39 > 0.65, clc_build!H$39 <= 0.77),\n\" 50 Prozent mehr \",\n    AND(clc_build!H$39 > 0.5, clc_build!H$39 <= 0.65),\n\" doppelt so viel \",\nclc_build!H$39 <= 0.5,\n\" deutlich mehr \"\n)",
  "J8":  /* formula */ " _xlfn.IFS(\n    clc_build!I$39>0.85,\n\" spürbar mehr \",\n    AND(clc_build!I$39 >0.77,clc_build!I$39<=0.85),\n\" 30 Prozent mehr\",\n    AND(clc_build!I$39 > 0.65, clc_build!I$39 <= 0.77),\n\" 50 Prozent mehr \",\n    AND(clc_build!I$39 > 0.5, clc_build!I$39 <= 0.65),\n\" doppelt so viel \",\nclc_build!I$39 <= 0.5,\n\" deutlich mehr \"\n)",
  "K8":  /* formula */ " _xlfn.IFS(\n    clc_build!J$39>0.85,\n\" spürbar mehr \",\n    AND(clc_build!J$39 >0.77,clc_build!J$39<=0.85),\n\" 30 Prozent mehr\",\n    AND(clc_build!J$39 > 0.65, clc_build!J$39 <= 0.77),\n\" 50 Prozent mehr \",\n    AND(clc_build!J$39 > 0.5, clc_build!J$39 <= 0.65),\n\" doppelt so viel \",\nclc_build!J$39 <= 0.5,\n\" deutlich mehr \"\n)",
  "L8":  /* formula */ " _xlfn.IFS(\n    clc_build!K$39>0.85,\n\" spürbar mehr \",\n    AND(clc_build!K$39 >0.77,clc_build!K$39<=0.85),\n\" 30 Prozent mehr\",\n    AND(clc_build!K$39 > 0.65, clc_build!K$39 <= 0.77),\n\" 50 Prozent mehr \",\n    AND(clc_build!K$39 > 0.5, clc_build!K$39 <= 0.65),\n\" doppelt so viel \",\nclc_build!K$39 <= 0.5,\n\" deutlich mehr \"\n)",
  "M8":  /* formula */ " _xlfn.IFS(\n    clc_build!L$39>0.85,\n\" spürbar mehr \",\n    AND(clc_build!L$39 >0.77,clc_build!L$39<=0.85),\n\" 30 Prozent mehr\",\n    AND(clc_build!L$39 > 0.65, clc_build!L$39 <= 0.77),\n\" 50 Prozent mehr \",\n    AND(clc_build!L$39 > 0.5, clc_build!L$39 <= 0.65),\n\" doppelt so viel \",\nclc_build!L$39 <= 0.5,\n\" deutlich mehr \"\n)",
  "N8":  /* formula */ " _xlfn.IFS(\n    clc_build!M$39>0.85,\n\" spürbar mehr \",\n    AND(clc_build!M$39 >0.77,clc_build!M$39<=0.85),\n\" 30 Prozent mehr\",\n    AND(clc_build!M$39 > 0.65, clc_build!M$39 <= 0.77),\n\" 50 Prozent mehr \",\n    AND(clc_build!M$39 > 0.5, clc_build!M$39 <= 0.65),\n\" doppelt so viel \",\nclc_build!M$39 <= 0.5,\n\" deutlich mehr \"\n)",
  "O8":  /* formula */ " _xlfn.IFS(\n    clc_build!N$39>0.85,\n\" spürbar mehr \",\n    AND(clc_build!N$39 >0.77,clc_build!N$39<=0.85),\n\" 30 Prozent mehr\",\n    AND(clc_build!N$39 > 0.65, clc_build!N$39 <= 0.77),\n\" 50 Prozent mehr \",\n    AND(clc_build!N$39 > 0.5, clc_build!N$39 <= 0.65),\n\" doppelt so viel \",\nclc_build!N$39 <= 0.5,\n\" deutlich mehr \"\n)",
  "P8":  /* formula */ " _xlfn.IFS(\n    clc_build!O$39>0.85,\n\" spürbar mehr \",\n    AND(clc_build!O$39 >0.77,clc_build!O$39<=0.85),\n\" 30 Prozent mehr\",\n    AND(clc_build!O$39 > 0.65, clc_build!O$39 <= 0.77),\n\" 50 Prozent mehr \",\n    AND(clc_build!O$39 > 0.5, clc_build!O$39 <= 0.65),\n\" doppelt so viel \",\nclc_build!O$39 <= 0.5,\n\" deutlich mehr \"\n)",
  "Q8":  /* formula */ " _xlfn.IFS(\n    clc_build!P$39>0.85,\n\" spürbar mehr \",\n    AND(clc_build!P$39 >0.77,clc_build!P$39<=0.85),\n\" 30 Prozent mehr\",\n    AND(clc_build!P$39 > 0.65, clc_build!P$39 <= 0.77),\n\" 50 Prozent mehr \",\n    AND(clc_build!P$39 > 0.5, clc_build!P$39 <= 0.65),\n\" doppelt so viel \",\nclc_build!P$39 <= 0.5,\n\" deutlich mehr \"\n)",
  "R8":  /* formula */ " _xlfn.IFS(\n    clc_build!Q$39>0.85,\n\" spürbar mehr \",\n    AND(clc_build!Q$39 >0.77,clc_build!Q$39<=0.85),\n\" 30 Prozent mehr\",\n    AND(clc_build!Q$39 > 0.65, clc_build!Q$39 <= 0.77),\n\" 50 Prozent mehr \",\n    AND(clc_build!Q$39 > 0.5, clc_build!Q$39 <= 0.65),\n\" doppelt so viel \",\nclc_build!Q$39 <= 0.5,\n\" deutlich mehr \"\n)",
  "S8":  /* formula */ " _xlfn.IFS(\n    clc_build!R$39>0.85,\n\" spürbar mehr \",\n    AND(clc_build!R$39 >0.77,clc_build!R$39<=0.85),\n\" 30 Prozent mehr\",\n    AND(clc_build!R$39 > 0.65, clc_build!R$39 <= 0.77),\n\" 50 Prozent mehr \",\n    AND(clc_build!R$39 > 0.5, clc_build!R$39 <= 0.65),\n\" doppelt so viel \",\nclc_build!R$39 <= 0.5,\n\" deutlich mehr \"\n)",
  "T8":  /* formula */ " _xlfn.IFS(\n    clc_build!S$39>0.85,\n\" spürbar mehr \",\n    AND(clc_build!S$39 >0.77,clc_build!S$39<=0.85),\n\" 30 Prozent mehr\",\n    AND(clc_build!S$39 > 0.65, clc_build!S$39 <= 0.77),\n\" 50 Prozent mehr \",\n    AND(clc_build!S$39 > 0.5, clc_build!S$39 <= 0.65),\n\" doppelt so viel \",\nclc_build!S$39 <= 0.5,\n\" deutlich mehr \"\n)",
  "U8":  /* formula */ " _xlfn.IFS(\n    clc_build!T$39>0.85,\n\" spürbar mehr \",\n    AND(clc_build!T$39 >0.77,clc_build!T$39<=0.85),\n\" 30 Prozent mehr\",\n    AND(clc_build!T$39 > 0.65, clc_build!T$39 <= 0.77),\n\" 50 Prozent mehr \",\n    AND(clc_build!T$39 > 0.5, clc_build!T$39 <= 0.65),\n\" doppelt so viel \",\nclc_build!T$39 <= 0.5,\n\" deutlich mehr \"\n)",
  "V8":  /* formula */ " _xlfn.IFS(\n    clc_build!U$39>0.85,\n\" spürbar mehr \",\n    AND(clc_build!U$39 >0.77,clc_build!U$39<=0.85),\n\" 30 Prozent mehr\",\n    AND(clc_build!U$39 > 0.65, clc_build!U$39 <= 0.77),\n\" 50 Prozent mehr \",\n    AND(clc_build!U$39 > 0.5, clc_build!U$39 <= 0.65),\n\" doppelt so viel \",\nclc_build!U$39 <= 0.5,\n\" deutlich mehr \"\n)",
  "A9":  /* unknown */ "Lückentext Bewertung Heizkörpertausch Raumebene 3",
  "D9":  /* unknown */ "TXT_room_R3_fill_3",
  "G9":  /* unknown */ "R3",
  "H9":  /* formula */ "_xlfn.IFS(clc_build!G$40 > 0.77,\n\", sondern müsste etwas größer sein.\",\nAND(clc_build!G$40 > 0.65, clc_build!G$40 <= 0.77),\n\", sondern müsste ein Drittel größer sein.\",\nAND(clc_build!G$40 > 0.5, clc_build!G$40 <= 0.65),\n\", sondern müsste 50 Prozent größer sein.\",\nclc_build!G$40 <= 0.5,\n\", sondern müsste mindestens doppelt so groß sein.\")\n&\n\" Hinweis: Eine Gebläseunterstützung (siehe Wärmepumpen-Heizkörper) kann die Heizleistung weiter steigern. Für diese Heizkörper-Modelle ist ein zusätzlicher Stromanschluss für die Gebläse erforderlich.\"",
  "I9":  /* formula */ "_xlfn.IFS(clc_build!H$40 > 0.77,\n\", sondern müsste etwas größer sein.\",\nAND(clc_build!H$40 > 0.65, clc_build!H$40 <= 0.77),\n\", sondern müsste ein Drittel größer sein.\",\nAND(clc_build!H$40 > 0.5, clc_build!H$40 <= 0.65),\n\", sondern müsste 50 Prozent größer sein.\",\nclc_build!H$40 <= 0.5,\n\", sondern müsste mindestens doppelt so groß sein.\")\n&\n\" Hinweis: Eine Gebläseunterstützung (siehe Wärmepumpen-Heizkörper) kann die Heizleistung weiter steigern. Für diese Heizkörper-Modelle ist ein zusätzlicher Stromanschluss für die Gebläse erforderlich.\"",
  "J9":  /* formula */ "_xlfn.IFS(clc_build!I$40 > 0.77,\n\", sondern müsste etwas größer sein.\",\nAND(clc_build!I$40 > 0.65, clc_build!I$40 <= 0.77),\n\", sondern müsste ein Drittel größer sein.\",\nAND(clc_build!I$40 > 0.5, clc_build!I$40 <= 0.65),\n\", sondern müsste 50 Prozent größer sein.\",\nclc_build!I$40 <= 0.5,\n\", sondern müsste mindestens doppelt so groß sein.\")\n&\n\" Hinweis: Eine Gebläseunterstützung (siehe Wärmepumpen-Heizkörper) kann die Heizleistung weiter steigern. Für diese Heizkörper-Modelle ist ein zusätzlicher Stromanschluss für die Gebläse erforderlich.\"",
  "K9":  /* formula */ "_xlfn.IFS(clc_build!J$40 > 0.77,\n\", sondern müsste etwas größer sein.\",\nAND(clc_build!J$40 > 0.65, clc_build!J$40 <= 0.77),\n\", sondern müsste ein Drittel größer sein.\",\nAND(clc_build!J$40 > 0.5, clc_build!J$40 <= 0.65),\n\", sondern müsste 50 Prozent größer sein.\",\nclc_build!J$40 <= 0.5,\n\", sondern müsste mindestens doppelt so groß sein.\")\n&\n\" Hinweis: Eine Gebläseunterstützung (siehe Wärmepumpen-Heizkörper) kann die Heizleistung weiter steigern. Für diese Heizkörper-Modelle ist ein zusätzlicher Stromanschluss für die Gebläse erforderlich.\"",
  "L9":  /* formula */ "_xlfn.IFS(clc_build!K$40 > 0.77,\n\", sondern müsste etwas größer sein.\",\nAND(clc_build!K$40 > 0.65, clc_build!K$40 <= 0.77),\n\", sondern müsste ein Drittel größer sein.\",\nAND(clc_build!K$40 > 0.5, clc_build!K$40 <= 0.65),\n\", sondern müsste 50 Prozent größer sein.\",\nclc_build!K$40 <= 0.5,\n\", sondern müsste mindestens doppelt so groß sein.\")\n&\n\" Hinweis: Eine Gebläseunterstützung (siehe Wärmepumpen-Heizkörper) kann die Heizleistung weiter steigern. Für diese Heizkörper-Modelle ist ein zusätzlicher Stromanschluss für die Gebläse erforderlich.\"",
  "M9":  /* formula */ "_xlfn.IFS(clc_build!L$40 > 0.77,\n\", sondern müsste etwas größer sein.\",\nAND(clc_build!L$40 > 0.65, clc_build!L$40 <= 0.77),\n\", sondern müsste ein Drittel größer sein.\",\nAND(clc_build!L$40 > 0.5, clc_build!L$40 <= 0.65),\n\", sondern müsste 50 Prozent größer sein.\",\nclc_build!L$40 <= 0.5,\n\", sondern müsste mindestens doppelt so groß sein.\")\n&\n\" Hinweis: Eine Gebläseunterstützung (siehe Wärmepumpen-Heizkörper) kann die Heizleistung weiter steigern. Für diese Heizkörper-Modelle ist ein zusätzlicher Stromanschluss für die Gebläse erforderlich.\"",
  "N9":  /* formula */ "_xlfn.IFS(clc_build!M$40 > 0.77,\n\", sondern müsste etwas größer sein.\",\nAND(clc_build!M$40 > 0.65, clc_build!M$40 <= 0.77),\n\", sondern müsste ein Drittel größer sein.\",\nAND(clc_build!M$40 > 0.5, clc_build!M$40 <= 0.65),\n\", sondern müsste 50 Prozent größer sein.\",\nclc_build!M$40 <= 0.5,\n\", sondern müsste mindestens doppelt so groß sein.\")\n&\n\" Hinweis: Eine Gebläseunterstützung (siehe Wärmepumpen-Heizkörper) kann die Heizleistung weiter steigern. Für diese Heizkörper-Modelle ist ein zusätzlicher Stromanschluss für die Gebläse erforderlich.\"",
  "O9":  /* formula */ "_xlfn.IFS(clc_build!N$40 > 0.77,\n\", sondern müsste etwas größer sein.\",\nAND(clc_build!N$40 > 0.65, clc_build!N$40 <= 0.77),\n\", sondern müsste ein Drittel größer sein.\",\nAND(clc_build!N$40 > 0.5, clc_build!N$40 <= 0.65),\n\", sondern müsste 50 Prozent größer sein.\",\nclc_build!N$40 <= 0.5,\n\", sondern müsste mindestens doppelt so groß sein.\")\n&\n\" Hinweis: Eine Gebläseunterstützung (siehe Wärmepumpen-Heizkörper) kann die Heizleistung weiter steigern. Für diese Heizkörper-Modelle ist ein zusätzlicher Stromanschluss für die Gebläse erforderlich.\"",
  "P9":  /* formula */ "_xlfn.IFS(clc_build!O$40 > 0.77,\n\", sondern müsste etwas größer sein.\",\nAND(clc_build!O$40 > 0.65, clc_build!O$40 <= 0.77),\n\", sondern müsste ein Drittel größer sein.\",\nAND(clc_build!O$40 > 0.5, clc_build!O$40 <= 0.65),\n\", sondern müsste 50 Prozent größer sein.\",\nclc_build!O$40 <= 0.5,\n\", sondern müsste mindestens doppelt so groß sein.\")\n&\n\" Hinweis: Eine Gebläseunterstützung (siehe Wärmepumpen-Heizkörper) kann die Heizleistung weiter steigern. Für diese Heizkörper-Modelle ist ein zusätzlicher Stromanschluss für die Gebläse erforderlich.\"",
  "Q9":  /* formula */ "_xlfn.IFS(clc_build!P$40 > 0.77,\n\", sondern müsste etwas größer sein.\",\nAND(clc_build!P$40 > 0.65, clc_build!P$40 <= 0.77),\n\", sondern müsste ein Drittel größer sein.\",\nAND(clc_build!P$40 > 0.5, clc_build!P$40 <= 0.65),\n\", sondern müsste 50 Prozent größer sein.\",\nclc_build!P$40 <= 0.5,\n\", sondern müsste mindestens doppelt so groß sein.\")\n&\n\" Hinweis: Eine Gebläseunterstützung (siehe Wärmepumpen-Heizkörper) kann die Heizleistung weiter steigern. Für diese Heizkörper-Modelle ist ein zusätzlicher Stromanschluss für die Gebläse erforderlich.\"",
  "R9":  /* formula */ "_xlfn.IFS(clc_build!Q$40 > 0.77,\n\", sondern müsste etwas größer sein.\",\nAND(clc_build!Q$40 > 0.65, clc_build!Q$40 <= 0.77),\n\", sondern müsste ein Drittel größer sein.\",\nAND(clc_build!Q$40 > 0.5, clc_build!Q$40 <= 0.65),\n\", sondern müsste 50 Prozent größer sein.\",\nclc_build!Q$40 <= 0.5,\n\", sondern müsste mindestens doppelt so groß sein.\")\n&\n\" Hinweis: Eine Gebläseunterstützung (siehe Wärmepumpen-Heizkörper) kann die Heizleistung weiter steigern. Für diese Heizkörper-Modelle ist ein zusätzlicher Stromanschluss für die Gebläse erforderlich.\"",
  "S9":  /* formula */ "_xlfn.IFS(clc_build!R$40 > 0.77,\n\", sondern müsste etwas größer sein.\",\nAND(clc_build!R$40 > 0.65, clc_build!R$40 <= 0.77),\n\", sondern müsste ein Drittel größer sein.\",\nAND(clc_build!R$40 > 0.5, clc_build!R$40 <= 0.65),\n\", sondern müsste 50 Prozent größer sein.\",\nclc_build!R$40 <= 0.5,\n\", sondern müsste mindestens doppelt so groß sein.\")\n&\n\" Hinweis: Eine Gebläseunterstützung (siehe Wärmepumpen-Heizkörper) kann die Heizleistung weiter steigern. Für diese Heizkörper-Modelle ist ein zusätzlicher Stromanschluss für die Gebläse erforderlich.\"",
  "T9":  /* formula */ "_xlfn.IFS(clc_build!S$40 > 0.77,\n\", sondern müsste etwas größer sein.\",\nAND(clc_build!S$40 > 0.65, clc_build!S$40 <= 0.77),\n\", sondern müsste ein Drittel größer sein.\",\nAND(clc_build!S$40 > 0.5, clc_build!S$40 <= 0.65),\n\", sondern müsste 50 Prozent größer sein.\",\nclc_build!S$40 <= 0.5,\n\", sondern müsste mindestens doppelt so groß sein.\")\n&\n\" Hinweis: Eine Gebläseunterstützung (siehe Wärmepumpen-Heizkörper) kann die Heizleistung weiter steigern. Für diese Heizkörper-Modelle ist ein zusätzlicher Stromanschluss für die Gebläse erforderlich.\"",
  "U9":  /* formula */ "_xlfn.IFS(clc_build!T$40 > 0.77,\n\", sondern müsste etwas größer sein.\",\nAND(clc_build!T$40 > 0.65, clc_build!T$40 <= 0.77),\n\", sondern müsste ein Drittel größer sein.\",\nAND(clc_build!T$40 > 0.5, clc_build!T$40 <= 0.65),\n\", sondern müsste 50 Prozent größer sein.\",\nclc_build!T$40 <= 0.5,\n\", sondern müsste mindestens doppelt so groß sein.\")\n&\n\" Hinweis: Eine Gebläseunterstützung (siehe Wärmepumpen-Heizkörper) kann die Heizleistung weiter steigern. Für diese Heizkörper-Modelle ist ein zusätzlicher Stromanschluss für die Gebläse erforderlich.\"",
  "V9":  /* formula */ "_xlfn.IFS(clc_build!U$40 > 0.77,\n\", sondern müsste etwas größer sein.\",\nAND(clc_build!U$40 > 0.65, clc_build!U$40 <= 0.77),\n\", sondern müsste ein Drittel größer sein.\",\nAND(clc_build!U$40 > 0.5, clc_build!U$40 <= 0.65),\n\", sondern müsste 50 Prozent größer sein.\",\nclc_build!U$40 <= 0.5,\n\", sondern müsste mindestens doppelt so groß sein.\")\n&\n\" Hinweis: Eine Gebläseunterstützung (siehe Wärmepumpen-Heizkörper) kann die Heizleistung weiter steigern. Für diese Heizkörper-Modelle ist ein zusätzlicher Stromanschluss für die Gebläse erforderlich.\"",
  "A10":  /* unknown */ "Ausgabe Heizkörpertausch Raumebene",
  "B10":  /* unknown */ "room",
  "D10":  /* unknown */ "TXT_room__R3_Qdot",
  "G10":  /* unknown */ "R3",
  "H10":  /* formula */ "_xlfn.IFS(\nclc_build!G$39 > 1,\nTXT_rooms!$E$19,\nclc_build!G$40<0.5,\nTXT_rooms!$E$13 & H7 & TXT_rooms!$E$14,\nclc_build!G$40 < 1,\nTXT_rooms!$E$15&H$8&TXT_rooms!$E$16 & H$9,\nAND(clc_build!G$40 > 1,clc_build!G$39 < 1),TXT_rooms!$E$17&H$8&TXT_rooms!$E$18\n)",
  "I10":  /* formula */ "_xlfn.IFS(\nclc_build!H$39 > 1,\nTXT_rooms!$E$19,\nclc_build!H$40<0.5,\nTXT_rooms!$E$13 & I7 & TXT_rooms!$E$14,\nclc_build!H$40 < 1,\nTXT_rooms!$E$15&I$8&TXT_rooms!$E$16 & I$9,\nAND(clc_build!H$40 > 1,clc_build!H$39 < 1),TXT_rooms!$E$17&I$8&TXT_rooms!$E$18\n)",
  "J10":  /* formula */ "_xlfn.IFS(\nclc_build!I$39 > 1,\nTXT_rooms!$E$19,\nclc_build!I$40<0.5,\nTXT_rooms!$E$13 & J7 & TXT_rooms!$E$14,\nclc_build!I$40 < 1,\nTXT_rooms!$E$15&J$8&TXT_rooms!$E$16 & J$9,\nAND(clc_build!I$40 > 1,clc_build!I$39 < 1),TXT_rooms!$E$17&J$8&TXT_rooms!$E$18\n)",
  "K10":  /* formula */ "_xlfn.IFS(\nclc_build!J$39 > 1,\nTXT_rooms!$E$19,\nclc_build!J$40<0.5,\nTXT_rooms!$E$13 & K7 & TXT_rooms!$E$14,\nclc_build!J$40 < 1,\nTXT_rooms!$E$15&K$8&TXT_rooms!$E$16 & K$9,\nAND(clc_build!J$40 > 1,clc_build!J$39 < 1),TXT_rooms!$E$17&K$8&TXT_rooms!$E$18\n)",
  "L10":  /* formula */ "_xlfn.IFS(\nclc_build!K$39 > 1,\nTXT_rooms!$E$19,\nclc_build!K$40<0.5,\nTXT_rooms!$E$13 & L7 & TXT_rooms!$E$14,\nclc_build!K$40 < 1,\nTXT_rooms!$E$15&L$8&TXT_rooms!$E$16 & L$9,\nAND(clc_build!K$40 > 1,clc_build!K$39 < 1),TXT_rooms!$E$17&L$8&TXT_rooms!$E$18\n)",
  "M10":  /* formula */ "_xlfn.IFS(\nclc_build!L$39 > 1,\nTXT_rooms!$E$19,\nclc_build!L$40<0.5,\nTXT_rooms!$E$13 & M7 & TXT_rooms!$E$14,\nclc_build!L$40 < 1,\nTXT_rooms!$E$15&M$8&TXT_rooms!$E$16 & M$9,\nAND(clc_build!L$40 > 1,clc_build!L$39 < 1),TXT_rooms!$E$17&M$8&TXT_rooms!$E$18\n)",
  "N10":  /* formula */ "_xlfn.IFS(\nclc_build!M$39 > 1,\nTXT_rooms!$E$19,\nclc_build!M$40<0.5,\nTXT_rooms!$E$13 & N7 & TXT_rooms!$E$14,\nclc_build!M$40 < 1,\nTXT_rooms!$E$15&N$8&TXT_rooms!$E$16 & N$9,\nAND(clc_build!M$40 > 1,clc_build!M$39 < 1),TXT_rooms!$E$17&N$8&TXT_rooms!$E$18\n)",
  "O10":  /* formula */ "_xlfn.IFS(\nclc_build!N$39 > 1,\nTXT_rooms!$E$19,\nclc_build!N$40<0.5,\nTXT_rooms!$E$13 & O7 & TXT_rooms!$E$14,\nclc_build!N$40 < 1,\nTXT_rooms!$E$15&O$8&TXT_rooms!$E$16 & O$9,\nAND(clc_build!N$40 > 1,clc_build!N$39 < 1),TXT_rooms!$E$17&O$8&TXT_rooms!$E$18\n)",
  "P10":  /* formula */ "_xlfn.IFS(\nclc_build!O$39 > 1,\nTXT_rooms!$E$19,\nclc_build!O$40<0.5,\nTXT_rooms!$E$13 & P7 & TXT_rooms!$E$14,\nclc_build!O$40 < 1,\nTXT_rooms!$E$15&P$8&TXT_rooms!$E$16 & P$9,\nAND(clc_build!O$40 > 1,clc_build!O$39 < 1),TXT_rooms!$E$17&P$8&TXT_rooms!$E$18\n)",
  "Q10":  /* formula */ "_xlfn.IFS(\nclc_build!P$39 > 1,\nTXT_rooms!$E$19,\nclc_build!P$40<0.5,\nTXT_rooms!$E$13 & Q7 & TXT_rooms!$E$14,\nclc_build!P$40 < 1,\nTXT_rooms!$E$15&Q$8&TXT_rooms!$E$16 & Q$9,\nAND(clc_build!P$40 > 1,clc_build!P$39 < 1),TXT_rooms!$E$17&Q$8&TXT_rooms!$E$18\n)",
  "R10":  /* formula */ "_xlfn.IFS(\nclc_build!Q$39 > 1,\nTXT_rooms!$E$19,\nclc_build!Q$40<0.5,\nTXT_rooms!$E$13 & R7 & TXT_rooms!$E$14,\nclc_build!Q$40 < 1,\nTXT_rooms!$E$15&R$8&TXT_rooms!$E$16 & R$9,\nAND(clc_build!Q$40 > 1,clc_build!Q$39 < 1),TXT_rooms!$E$17&R$8&TXT_rooms!$E$18\n)",
  "S10":  /* formula */ "_xlfn.IFS(\nclc_build!R$39 > 1,\nTXT_rooms!$E$19,\nclc_build!R$40<0.5,\nTXT_rooms!$E$13 & S7 & TXT_rooms!$E$14,\nclc_build!R$40 < 1,\nTXT_rooms!$E$15&S$8&TXT_rooms!$E$16 & S$9,\nAND(clc_build!R$40 > 1,clc_build!R$39 < 1),TXT_rooms!$E$17&S$8&TXT_rooms!$E$18\n)",
  "T10":  /* formula */ "_xlfn.IFS(\nclc_build!S$39 > 1,\nTXT_rooms!$E$19,\nclc_build!S$40<0.5,\nTXT_rooms!$E$13 & T7 & TXT_rooms!$E$14,\nclc_build!S$40 < 1,\nTXT_rooms!$E$15&T$8&TXT_rooms!$E$16 & T$9,\nAND(clc_build!S$40 > 1,clc_build!S$39 < 1),TXT_rooms!$E$17&T$8&TXT_rooms!$E$18\n)",
  "U10":  /* formula */ "_xlfn.IFS(\nclc_build!T$39 > 1,\nTXT_rooms!$E$19,\nclc_build!T$40<0.5,\nTXT_rooms!$E$13 & U7 & TXT_rooms!$E$14,\nclc_build!T$40 < 1,\nTXT_rooms!$E$15&U$8&TXT_rooms!$E$16 & U$9,\nAND(clc_build!T$40 > 1,clc_build!T$39 < 1),TXT_rooms!$E$17&U$8&TXT_rooms!$E$18\n)",
  "V10":  /* formula */ "_xlfn.IFS(\nclc_build!U$39 > 1,\nTXT_rooms!$E$19,\nclc_build!U$40<0.5,\nTXT_rooms!$E$13 & V7 & TXT_rooms!$E$14,\nclc_build!U$40 < 1,\nTXT_rooms!$E$15&V$8&TXT_rooms!$E$16 & V$9,\nAND(clc_build!U$40 > 1,clc_build!U$39 < 1),TXT_rooms!$E$17&V$8&TXT_rooms!$E$18\n)",
  "A11":  /* unknown */ "\"Kalkulierte Raumheizlast\" - Wert 1",
  "B11":  /* unknown */ "room",
  "D11":  /* unknown */ "Qdot_room_cor",
  "H11":  /* formula */ "clc_build!G7",
  "I11":  /* formula */ "clc_build!H7",
  "J11":  /* formula */ "clc_build!I7",
  "K11":  /* formula */ "clc_build!J7",
  "L11":  /* formula */ "clc_build!K7",
  "M11":  /* formula */ "clc_build!L7",
  "N11":  /* formula */ "clc_build!M7",
  "O11":  /* formula */ "clc_build!N7",
  "P11":  /* formula */ "clc_build!O7",
  "Q11":  /* formula */ "clc_build!P7",
  "R11":  /* formula */ "clc_build!Q7",
  "S11":  /* formula */ "clc_build!R7",
  "T11":  /* formula */ "clc_build!S7",
  "U11":  /* formula */ "clc_build!T7",
  "V11":  /* formula */ "clc_build!U7",
  "A12":  /* unknown */ "\"Kalkulierte Raumheizlast\" - Wert 2",
  "D12":  /* unknown */ "qdot_room_cor",
  "H12":  /* formula */ "clc_build!G8",
  "I12":  /* formula */ "clc_build!H8",
  "J12":  /* formula */ "clc_build!I8",
  "K12":  /* formula */ "clc_build!J8",
  "L12":  /* formula */ "clc_build!K8",
  "M12":  /* formula */ "clc_build!L8",
  "N12":  /* formula */ "clc_build!M8",
  "O12":  /* formula */ "clc_build!N8",
  "P12":  /* formula */ "clc_build!O8",
  "Q12":  /* formula */ "clc_build!P8",
  "R12":  /* formula */ "clc_build!Q8",
  "S12":  /* formula */ "clc_build!R8",
  "T12":  /* formula */ "clc_build!S8",
  "U12":  /* formula */ "clc_build!T8",
  "V12":  /* formula */ "clc_build!U8",
  "A13":  /* unknown */ "Ausgabewert \"Kalkulierte Raumheizlast\" als String",
  "D13":  /* unknown */ "TXT_qdot_room",
  "H13":  /* formula */ "TEXT(H11,\"0\")&\" Watt | \" & TEXT(H12,\"0\") & \" W/m²\"",
  "I13":  /* formula */ "TEXT(I11,\"0\")&\" Watt | \" & TEXT(I12,\"0\") & \" W/m²\"",
  "J13":  /* formula */ "TEXT(J11,\"0\")&\" Watt | \" & TEXT(J12,\"0\") & \" W/m²\"",
  "K13":  /* formula */ "TEXT(K11,\"0\")&\" Watt | \" & TEXT(K12,\"0\") & \" W/m²\"",
  "L13":  /* formula */ "TEXT(L11,\"0\")&\" Watt | \" & TEXT(L12,\"0\") & \" W/m²\"",
  "M13":  /* formula */ "TEXT(M11,\"0\")&\" Watt | \" & TEXT(M12,\"0\") & \" W/m²\"",
  "N13":  /* formula */ "TEXT(N11,\"0\")&\" Watt | \" & TEXT(N12,\"0\") & \" W/m²\"",
  "O13":  /* formula */ "TEXT(O11,\"0\")&\" Watt | \" & TEXT(O12,\"0\") & \" W/m²\"",
  "P13":  /* formula */ "TEXT(P11,\"0\")&\" Watt | \" & TEXT(P12,\"0\") & \" W/m²\"",
  "Q13":  /* formula */ "TEXT(Q11,\"0\")&\" Watt | \" & TEXT(Q12,\"0\") & \" W/m²\"",
  "R13":  /* formula */ "TEXT(R11,\"0\")&\" Watt | \" & TEXT(R12,\"0\") & \" W/m²\"",
  "S13":  /* formula */ "TEXT(S11,\"0\")&\" Watt | \" & TEXT(S12,\"0\") & \" W/m²\"",
  "T13":  /* formula */ "TEXT(T11,\"0\")&\" Watt | \" & TEXT(T12,\"0\") & \" W/m²\"",
  "U13":  /* formula */ "TEXT(U11,\"0\")&\" Watt | \" & TEXT(U12,\"0\") & \" W/m²\"",
  "V13":  /* formula */ "TEXT(V11,\"0\")&\" Watt | \" & TEXT(V12,\"0\") & \" W/m²\"",
  "A14":  /* unknown */ "\"Wie gut sind die Heizkörper geeignet?\" - Leistung Aktueller Heizkörper",
  "D14":  /* unknown */ "TXT_Qdot_rad_act",
  "H14":  /* formula */ "TEXT(clc_build!G37,\"0\") & \" Watt\"",
  "I14":  /* formula */ "TEXT(clc_build!H37,\"0\") & \" Watt\"",
  "J14":  /* formula */ "TEXT(clc_build!I37,\"0\") & \" Watt\"",
  "K14":  /* formula */ "TEXT(clc_build!J37,\"0\") & \" Watt\"",
  "L14":  /* formula */ "TEXT(clc_build!K37,\"0\") & \" Watt\"",
  "M14":  /* formula */ "TEXT(clc_build!L37,\"0\") & \" Watt\"",
  "N14":  /* formula */ "TEXT(clc_build!M37,\"0\") & \" Watt\"",
  "O14":  /* formula */ "TEXT(clc_build!N37,\"0\") & \" Watt\"",
  "P14":  /* formula */ "TEXT(clc_build!O37,\"0\") & \" Watt\"",
  "Q14":  /* formula */ "TEXT(clc_build!P37,\"0\") & \" Watt\"",
  "R14":  /* formula */ "TEXT(clc_build!Q37,\"0\") & \" Watt\"",
  "S14":  /* formula */ "TEXT(clc_build!R37,\"0\") & \" Watt\"",
  "T14":  /* formula */ "TEXT(clc_build!S37,\"0\") & \" Watt\"",
  "U14":  /* formula */ "TEXT(clc_build!T37,\"0\") & \" Watt\"",
  "V14":  /* formula */ "TEXT(clc_build!U37,\"0\") & \" Watt\"",
  "A15":  /* unknown */ "\"Wie gut sind die Heizkörper geeignet?\" - Leistung Besserer heizkörper (Typ 33)",
  "D15":  /* unknown */ "TXT_Qdot_rad_typ33",
  "H15":  /* formula */ "TEXT(clc_build!G38,\"0\") & \" Watt\"",
  "I15":  /* formula */ "TEXT(clc_build!H38,\"0\") & \" Watt\"",
  "J15":  /* formula */ "TEXT(clc_build!I38,\"0\") & \" Watt\"",
  "K15":  /* formula */ "TEXT(clc_build!J38,\"0\") & \" Watt\"",
  "L15":  /* formula */ "TEXT(clc_build!K38,\"0\") & \" Watt\"",
  "M15":  /* formula */ "TEXT(clc_build!L38,\"0\") & \" Watt\"",
  "N15":  /* formula */ "TEXT(clc_build!M38,\"0\") & \" Watt\"",
  "O15":  /* formula */ "TEXT(clc_build!N38,\"0\") & \" Watt\"",
  "P15":  /* formula */ "TEXT(clc_build!O38,\"0\") & \" Watt\"",
  "Q15":  /* formula */ "TEXT(clc_build!P38,\"0\") & \" Watt\"",
  "R15":  /* formula */ "TEXT(clc_build!Q38,\"0\") & \" Watt\"",
  "S15":  /* formula */ "TEXT(clc_build!R38,\"0\") & \" Watt\"",
  "T15":  /* formula */ "TEXT(clc_build!S38,\"0\") & \" Watt\"",
  "U15":  /* formula */ "TEXT(clc_build!T38,\"0\") & \" Watt\"",
  "V15":  /* formula */ "TEXT(clc_build!U38,\"0\") & \" Watt\"",
  "A16":  /* unknown */ "\"Wie gut sind die Heizkörper geeignet?\" - Deckung Aktueller Heizkörper",
  "D16":  /* unknown */ "TXT_r_rad_act",
  "H16":  /* formula */ "TEXT(clc_build!G39*100,\"0\") & \" % Deckung\"",
  "I16":  /* formula */ "TEXT(clc_build!H39*100,\"0\") & \" % Deckung\"",
  "J16":  /* formula */ "TEXT(clc_build!I39*100,\"0\") & \" % Deckung\"",
  "K16":  /* formula */ "TEXT(clc_build!J39*100,\"0\") & \" % Deckung\"",
  "L16":  /* formula */ "TEXT(clc_build!K39*100,\"0\") & \" % Deckung\"",
  "M16":  /* formula */ "TEXT(clc_build!L39*100,\"0\") & \" % Deckung\"",
  "N16":  /* formula */ "TEXT(clc_build!M39*100,\"0\") & \" % Deckung\"",
  "O16":  /* formula */ "TEXT(clc_build!N39*100,\"0\") & \" % Deckung\"",
  "P16":  /* formula */ "TEXT(clc_build!O39*100,\"0\") & \" % Deckung\"",
  "Q16":  /* formula */ "TEXT(clc_build!P39*100,\"0\") & \" % Deckung\"",
  "R16":  /* formula */ "TEXT(clc_build!Q39*100,\"0\") & \" % Deckung\"",
  "S16":  /* formula */ "TEXT(clc_build!R39*100,\"0\") & \" % Deckung\"",
  "T16":  /* formula */ "TEXT(clc_build!S39*100,\"0\") & \" % Deckung\"",
  "U16":  /* formula */ "TEXT(clc_build!T39*100,\"0\") & \" % Deckung\"",
  "V16":  /* formula */ "TEXT(clc_build!U39*100,\"0\") & \" % Deckung\"",
  "A17":  /* unknown */ "\"Wie gut sind die Heizkörper geeignet?\" - Deckung Besserer heizkörper (Typ 33)",
  "D17":  /* unknown */ "TXT_r_rad_typ33",
  "H17":  /* formula */ "TEXT(clc_build!G40*100,\"0\") & \" % Deckung\"",
  "I17":  /* formula */ "TEXT(clc_build!H40*100,\"0\") & \" % Deckung\"",
  "J17":  /* formula */ "TEXT(clc_build!I40*100,\"0\") & \" % Deckung\"",
  "K17":  /* formula */ "TEXT(clc_build!J40*100,\"0\") & \" % Deckung\"",
  "L17":  /* formula */ "TEXT(clc_build!K40*100,\"0\") & \" % Deckung\"",
  "M17":  /* formula */ "TEXT(clc_build!L40*100,\"0\") & \" % Deckung\"",
  "N17":  /* formula */ "TEXT(clc_build!M40*100,\"0\") & \" % Deckung\"",
  "O17":  /* formula */ "TEXT(clc_build!N40*100,\"0\") & \" % Deckung\"",
  "P17":  /* formula */ "TEXT(clc_build!O40*100,\"0\") & \" % Deckung\"",
  "Q17":  /* formula */ "TEXT(clc_build!P40*100,\"0\") & \" % Deckung\"",
  "R17":  /* formula */ "TEXT(clc_build!Q40*100,\"0\") & \" % Deckung\"",
  "S17":  /* formula */ "TEXT(clc_build!R40*100,\"0\") & \" % Deckung\"",
  "T17":  /* formula */ "TEXT(clc_build!S40*100,\"0\") & \" % Deckung\"",
  "U17":  /* formula */ "TEXT(clc_build!T40*100,\"0\") & \" % Deckung\"",
  "V17":  /* formula */ "TEXT(clc_build!U40*100,\"0\") & \" % Deckung\"",
  "A19":  /* unknown */ "Output Dashboard",
  "A20":  /* unknown */ "kalkulierte Raumheizlast ",
  "D20":  /* unknown */ "TXT_build_G2_load_spez",
  "H20":  /* formula */ "TEXT(H11,\"0\")&\" Watt\"",
  "I20":  /* formula */ "TEXT(I11,\"0\")&\" Watt\"",
  "J20":  /* formula */ "TEXT(J11,\"0\")&\" Watt\"",
  "K20":  /* formula */ "TEXT(K11,\"0\")&\" Watt\"",
  "L20":  /* formula */ "TEXT(L11,\"0\")&\" Watt\"",
  "M20":  /* formula */ "TEXT(M11,\"0\")&\" Watt\"",
  "N20":  /* formula */ "TEXT(N11,\"0\")&\" Watt\"",
  "O20":  /* formula */ "TEXT(O11,\"0\")&\" Watt\"",
  "P20":  /* formula */ "TEXT(P11,\"0\")&\" Watt\"",
  "Q20":  /* formula */ "TEXT(Q11,\"0\")&\" Watt\"",
  "R20":  /* formula */ "TEXT(R11,\"0\")&\" Watt\"",
  "S20":  /* formula */ "TEXT(S11,\"0\")&\" Watt\"",
  "T20":  /* formula */ "TEXT(T11,\"0\")&\" Watt\"",
  "U20":  /* formula */ "TEXT(U11,\"0\")&\" Watt\"",
  "V20":  /* formula */ "TEXT(V11,\"0\")&\" Watt\"",
  "A21":  /* unknown */ "Titel Raum mit spezifischer Heizlast",
  "D21":  /* unknown */ "TXT_build_G2_load_abs",
  "H21":  /* formula */ "IN_rooms!R3&\" (Heizlast \"&TEXT(H12,\"0\") & \" W/m²)\"",
  "I21":  /* formula */ "IN_rooms!S3&\" (Heizlast \"&TEXT(I12,\"0\") & \" W/m²)\"",
  "J21":  /* formula */ "IN_rooms!T3&\" (Heizlast \"&TEXT(J12,\"0\") & \" W/m²)\"",
  "K21":  /* formula */ "IN_rooms!U3&\" (Heizlast \"&TEXT(K12,\"0\") & \" W/m²)\"",
  "L21":  /* formula */ "IN_rooms!V3&\" (Heizlast \"&TEXT(L12,\"0\") & \" W/m²)\"",
  "M21":  /* formula */ "IN_rooms!W3&\" (Heizlast \"&TEXT(M12,\"0\") & \" W/m²)\"",
  "N21":  /* formula */ "IN_rooms!X3&\" (Heizlast \"&TEXT(N12,\"0\") & \" W/m²)\"",
  "O21":  /* formula */ "IN_rooms!Y3&\" (Heizlast \"&TEXT(O12,\"0\") & \" W/m²)\"",
  "P21":  /* formula */ "IN_rooms!Z3&\" (Heizlast \"&TEXT(P12,\"0\") & \" W/m²)\"",
  "Q21":  /* formula */ "IN_rooms!AA3&\" (Heizlast \"&TEXT(Q12,\"0\") & \" W/m²)\"",
  "R21":  /* formula */ "IN_rooms!AB3&\" (Heizlast \"&TEXT(R12,\"0\") & \" W/m²)\"",
  "S21":  /* formula */ "IN_rooms!AC3&\" (Heizlast \"&TEXT(S12,\"0\") & \" W/m²)\"",
  "T21":  /* formula */ "IN_rooms!AD3&\" (Heizlast \"&TEXT(T12,\"0\") & \" W/m²)\"",
  "U21":  /* formula */ "IN_rooms!AE3&\" (Heizlast \"&TEXT(U12,\"0\") & \" W/m²)\"",
  "V21":  /* formula */ "IN_rooms!AF3&\" (Heizlast \"&TEXT(V12,\"0\") & \" W/m²)\"",
  "A22":  /* unknown */ "Deckungsgrad",
  "D22":  /* unknown */ "TXT_build_G2_Deckung",
  "H22":  /* formula */ "H16",
  "I22":  /* formula */ "I16",
  "J22":  /* formula */ "J16",
  "K22":  /* formula */ "K16",
  "L22":  /* formula */ "L16",
  "M22":  /* formula */ "M16",
  "N22":  /* formula */ "N16",
  "O22":  /* formula */ "O16",
  "P22":  /* formula */ "P16",
  "Q22":  /* formula */ "Q16",
  "R22":  /* formula */ "R16",
  "S22":  /* formula */ "S16",
  "T22":  /* formula */ "T16",
  "U22":  /* formula */ "U16",
  "V22":  /* formula */ "V16",
  "A23":  /* unknown */ "Heizkörperleistung",
  "D23":  /* unknown */ "TXT_build_G2_Qdot_act",
  "H23":  /* formula */ "H14",
  "I23":  /* formula */ "I14",
  "J23":  /* formula */ "J14",
  "K23":  /* formula */ "K14",
  "L23":  /* formula */ "L14",
  "M23":  /* formula */ "M14",
  "N23":  /* formula */ "N14",
  "O23":  /* formula */ "O14",
  "P23":  /* formula */ "P14",
  "Q23":  /* formula */ "Q14",
  "R23":  /* formula */ "R14",
  "S23":  /* formula */ "S14",
  "T23":  /* formula */ "T14",
  "U23":  /* formula */ "U14",
  "V23":  /* formula */ "V14",
  "A24":  /* unknown */ "U-Wert Bauteil mit höchsten Verlusten",
  "D24":  /* unknown */ "U_build_G2_worst",
  "G24":  /* unknown */ "G2",
  "H24":  /* formula */ "_xlfn.LET(_xlpm.max_HT_share,MAX(clc_build!G$13,clc_build!G$17,clc_build!G$21,clc_build!G$25,clc_build!G$29,clc_build!G$33),\n_xlfn.IFS(clc_build!G$13=_xlpm.max_HT_share,clc_build!G$11,\nclc_build!G$17=_xlpm.max_HT_share,clc_build!G$15,\nclc_build!G$21=_xlpm.max_HT_share,clc_build!G$19*0.8/2.7,\nclc_build!G$25=_xlpm.max_HT_share,clc_build!G$23,\nclc_build!G$29=_xlpm.max_HT_share,clc_build!G$27,\nclc_build!G$33=_xlpm.max_HT_share,clc_build!G$31\n))",
  "I24":  /* formula */ "_xlfn.LET(_xlpm.max_HT_share,MAX(clc_build!H$13,clc_build!H$17,clc_build!H$21,clc_build!H$25,clc_build!H$29,clc_build!H$33),\n_xlfn.IFS(clc_build!H$13=_xlpm.max_HT_share,clc_build!H$11,\nclc_build!H$17=_xlpm.max_HT_share,clc_build!H$15,\nclc_build!H$21=_xlpm.max_HT_share,clc_build!H$19*0.8/2.7,\nclc_build!H$25=_xlpm.max_HT_share,clc_build!H$23,\nclc_build!H$29=_xlpm.max_HT_share,clc_build!H$27,\nclc_build!H$33=_xlpm.max_HT_share,clc_build!H$31\n))",
  "J24":  /* formula */ "_xlfn.LET(_xlpm.max_HT_share,MAX(clc_build!I$13,clc_build!I$17,clc_build!I$21,clc_build!I$25,clc_build!I$29,clc_build!I$33),\n_xlfn.IFS(clc_build!I$13=_xlpm.max_HT_share,clc_build!I$11,\nclc_build!I$17=_xlpm.max_HT_share,clc_build!I$15,\nclc_build!I$21=_xlpm.max_HT_share,clc_build!I$19*0.8/2.7,\nclc_build!I$25=_xlpm.max_HT_share,clc_build!I$23,\nclc_build!I$29=_xlpm.max_HT_share,clc_build!I$27,\nclc_build!I$33=_xlpm.max_HT_share,clc_build!I$31\n))",
  "K24":  /* formula */ "_xlfn.LET(_xlpm.max_HT_share,MAX(clc_build!J$13,clc_build!J$17,clc_build!J$21,clc_build!J$25,clc_build!J$29,clc_build!J$33),\n_xlfn.IFS(clc_build!J$13=_xlpm.max_HT_share,clc_build!J$11,\nclc_build!J$17=_xlpm.max_HT_share,clc_build!J$15,\nclc_build!J$21=_xlpm.max_HT_share,clc_build!J$19*0.8/2.7,\nclc_build!J$25=_xlpm.max_HT_share,clc_build!J$23,\nclc_build!J$29=_xlpm.max_HT_share,clc_build!J$27,\nclc_build!J$33=_xlpm.max_HT_share,clc_build!J$31\n))",
  "L24":  /* formula */ "_xlfn.LET(_xlpm.max_HT_share,MAX(clc_build!K$13,clc_build!K$17,clc_build!K$21,clc_build!K$25,clc_build!K$29,clc_build!K$33),\n_xlfn.IFS(clc_build!K$13=_xlpm.max_HT_share,clc_build!K$11,\nclc_build!K$17=_xlpm.max_HT_share,clc_build!K$15,\nclc_build!K$21=_xlpm.max_HT_share,clc_build!K$19*0.8/2.7,\nclc_build!K$25=_xlpm.max_HT_share,clc_build!K$23,\nclc_build!K$29=_xlpm.max_HT_share,clc_build!K$27,\nclc_build!K$33=_xlpm.max_HT_share,clc_build!K$31\n))",
  "M24":  /* formula */ "_xlfn.LET(_xlpm.max_HT_share,MAX(clc_build!L$13,clc_build!L$17,clc_build!L$21,clc_build!L$25,clc_build!L$29,clc_build!L$33),\n_xlfn.IFS(clc_build!L$13=_xlpm.max_HT_share,clc_build!L$11,\nclc_build!L$17=_xlpm.max_HT_share,clc_build!L$15,\nclc_build!L$21=_xlpm.max_HT_share,clc_build!L$19*0.8/2.7,\nclc_build!L$25=_xlpm.max_HT_share,clc_build!L$23,\nclc_build!L$29=_xlpm.max_HT_share,clc_build!L$27,\nclc_build!L$33=_xlpm.max_HT_share,clc_build!L$31\n))",
  "N24":  /* formula */ "_xlfn.LET(_xlpm.max_HT_share,MAX(clc_build!M$13,clc_build!M$17,clc_build!M$21,clc_build!M$25,clc_build!M$29,clc_build!M$33),\n_xlfn.IFS(clc_build!M$13=_xlpm.max_HT_share,clc_build!M$11,\nclc_build!M$17=_xlpm.max_HT_share,clc_build!M$15,\nclc_build!M$21=_xlpm.max_HT_share,clc_build!M$19*0.8/2.7,\nclc_build!M$25=_xlpm.max_HT_share,clc_build!M$23,\nclc_build!M$29=_xlpm.max_HT_share,clc_build!M$27,\nclc_build!M$33=_xlpm.max_HT_share,clc_build!M$31\n))",
  "O24":  /* formula */ "_xlfn.LET(_xlpm.max_HT_share,MAX(clc_build!N$13,clc_build!N$17,clc_build!N$21,clc_build!N$25,clc_build!N$29,clc_build!N$33),\n_xlfn.IFS(clc_build!N$13=_xlpm.max_HT_share,clc_build!N$11,\nclc_build!N$17=_xlpm.max_HT_share,clc_build!N$15,\nclc_build!N$21=_xlpm.max_HT_share,clc_build!N$19*0.8/2.7,\nclc_build!N$25=_xlpm.max_HT_share,clc_build!N$23,\nclc_build!N$29=_xlpm.max_HT_share,clc_build!N$27,\nclc_build!N$33=_xlpm.max_HT_share,clc_build!N$31\n))",
  "P24":  /* formula */ "_xlfn.LET(_xlpm.max_HT_share,MAX(clc_build!O$13,clc_build!O$17,clc_build!O$21,clc_build!O$25,clc_build!O$29,clc_build!O$33),\n_xlfn.IFS(clc_build!O$13=_xlpm.max_HT_share,clc_build!O$11,\nclc_build!O$17=_xlpm.max_HT_share,clc_build!O$15,\nclc_build!O$21=_xlpm.max_HT_share,clc_build!O$19*0.8/2.7,\nclc_build!O$25=_xlpm.max_HT_share,clc_build!O$23,\nclc_build!O$29=_xlpm.max_HT_share,clc_build!O$27,\nclc_build!O$33=_xlpm.max_HT_share,clc_build!O$31\n))",
  "Q24":  /* formula */ "_xlfn.LET(_xlpm.max_HT_share,MAX(clc_build!P$13,clc_build!P$17,clc_build!P$21,clc_build!P$25,clc_build!P$29,clc_build!P$33),\n_xlfn.IFS(clc_build!P$13=_xlpm.max_HT_share,clc_build!P$11,\nclc_build!P$17=_xlpm.max_HT_share,clc_build!P$15,\nclc_build!P$21=_xlpm.max_HT_share,clc_build!P$19*0.8/2.7,\nclc_build!P$25=_xlpm.max_HT_share,clc_build!P$23,\nclc_build!P$29=_xlpm.max_HT_share,clc_build!P$27,\nclc_build!P$33=_xlpm.max_HT_share,clc_build!P$31\n))",
  "R24":  /* formula */ "_xlfn.LET(_xlpm.max_HT_share,MAX(clc_build!Q$13,clc_build!Q$17,clc_build!Q$21,clc_build!Q$25,clc_build!Q$29,clc_build!Q$33),\n_xlfn.IFS(clc_build!Q$13=_xlpm.max_HT_share,clc_build!Q$11,\nclc_build!Q$17=_xlpm.max_HT_share,clc_build!Q$15,\nclc_build!Q$21=_xlpm.max_HT_share,clc_build!Q$19*0.8/2.7,\nclc_build!Q$25=_xlpm.max_HT_share,clc_build!Q$23,\nclc_build!Q$29=_xlpm.max_HT_share,clc_build!Q$27,\nclc_build!Q$33=_xlpm.max_HT_share,clc_build!Q$31\n))",
  "S24":  /* formula */ "_xlfn.LET(_xlpm.max_HT_share,MAX(clc_build!R$13,clc_build!R$17,clc_build!R$21,clc_build!R$25,clc_build!R$29,clc_build!R$33),\n_xlfn.IFS(clc_build!R$13=_xlpm.max_HT_share,clc_build!R$11,\nclc_build!R$17=_xlpm.max_HT_share,clc_build!R$15,\nclc_build!R$21=_xlpm.max_HT_share,clc_build!R$19*0.8/2.7,\nclc_build!R$25=_xlpm.max_HT_share,clc_build!R$23,\nclc_build!R$29=_xlpm.max_HT_share,clc_build!R$27,\nclc_build!R$33=_xlpm.max_HT_share,clc_build!R$31\n))",
  "T24":  /* formula */ "_xlfn.LET(_xlpm.max_HT_share,MAX(clc_build!S$13,clc_build!S$17,clc_build!S$21,clc_build!S$25,clc_build!S$29,clc_build!S$33),\n_xlfn.IFS(clc_build!S$13=_xlpm.max_HT_share,clc_build!S$11,\nclc_build!S$17=_xlpm.max_HT_share,clc_build!S$15,\nclc_build!S$21=_xlpm.max_HT_share,clc_build!S$19*0.8/2.7,\nclc_build!S$25=_xlpm.max_HT_share,clc_build!S$23,\nclc_build!S$29=_xlpm.max_HT_share,clc_build!S$27,\nclc_build!S$33=_xlpm.max_HT_share,clc_build!S$31\n))",
  "U24":  /* formula */ "_xlfn.LET(_xlpm.max_HT_share,MAX(clc_build!T$13,clc_build!T$17,clc_build!T$21,clc_build!T$25,clc_build!T$29,clc_build!T$33),\n_xlfn.IFS(clc_build!T$13=_xlpm.max_HT_share,clc_build!T$11,\nclc_build!T$17=_xlpm.max_HT_share,clc_build!T$15,\nclc_build!T$21=_xlpm.max_HT_share,clc_build!T$19*0.8/2.7,\nclc_build!T$25=_xlpm.max_HT_share,clc_build!T$23,\nclc_build!T$29=_xlpm.max_HT_share,clc_build!T$27,\nclc_build!T$33=_xlpm.max_HT_share,clc_build!T$31\n))",
  "V24":  /* formula */ "_xlfn.LET(_xlpm.max_HT_share,MAX(clc_build!U$13,clc_build!U$17,clc_build!U$21,clc_build!U$25,clc_build!U$29,clc_build!U$33),\n_xlfn.IFS(clc_build!U$13=_xlpm.max_HT_share,clc_build!U$11,\nclc_build!U$17=_xlpm.max_HT_share,clc_build!U$15,\nclc_build!U$21=_xlpm.max_HT_share,clc_build!U$19*0.8/2.7,\nclc_build!U$25=_xlpm.max_HT_share,clc_build!U$23,\nclc_build!U$29=_xlpm.max_HT_share,clc_build!U$27,\nclc_build!U$33=_xlpm.max_HT_share,clc_build!U$31\n))",
  "A25":  /* unknown */ "Bauteiltausch Empfehlung icon ",
  "D25":  /* unknown */ "pic_build_G2_load",
  "G25":  /* unknown */ "G2",
  "H25":  /* formula */ "IF(OR(H24<0.4,H12<50),\"\",_xlfn.LET(_xlpm.max_HT_share,MAX(clc_build!G$13,clc_build!G$17,clc_build!G$21,clc_build!G$25,clc_build!G$29,clc_build!G$33),\n\"pic_G2_load_\" &\n_xlfn.IFS(clc_build!G$13=_xlpm.max_HT_share,\"wall\",\nclc_build!G$17=_xlpm.max_HT_share,\"innerwall\",\nclc_build!G$21=_xlpm.max_HT_share,\"win\",\nclc_build!G$25=_xlpm.max_HT_share,\"roof\",\nclc_build!G$29=_xlpm.max_HT_share,\"botceil\",\nclc_build!G$33=_xlpm.max_HT_share,\"topceil\"\n)))",
  "I25":  /* formula */ "IF(OR(I24<0.4,I12<50),\"\",_xlfn.LET(_xlpm.max_HT_share,MAX(clc_build!H$13,clc_build!H$17,clc_build!H$21,clc_build!H$25,clc_build!H$29,clc_build!H$33),\n\"pic_G2_load_\" &\n_xlfn.IFS(clc_build!H$13=_xlpm.max_HT_share,\"wall\",\nclc_build!H$17=_xlpm.max_HT_share,\"innerwall\",\nclc_build!H$21=_xlpm.max_HT_share,\"win\",\nclc_build!H$25=_xlpm.max_HT_share,\"roof\",\nclc_build!H$29=_xlpm.max_HT_share,\"botceil\",\nclc_build!H$33=_xlpm.max_HT_share,\"topceil\"\n)))",
  "J25":  /* formula */ "IF(OR(J24<0.4,J12<50),\"\",_xlfn.LET(_xlpm.max_HT_share,MAX(clc_build!I$13,clc_build!I$17,clc_build!I$21,clc_build!I$25,clc_build!I$29,clc_build!I$33),\n\"pic_G2_load_\" &\n_xlfn.IFS(clc_build!I$13=_xlpm.max_HT_share,\"wall\",\nclc_build!I$17=_xlpm.max_HT_share,\"innerwall\",\nclc_build!I$21=_xlpm.max_HT_share,\"win\",\nclc_build!I$25=_xlpm.max_HT_share,\"roof\",\nclc_build!I$29=_xlpm.max_HT_share,\"botceil\",\nclc_build!I$33=_xlpm.max_HT_share,\"topceil\"\n)))",
  "K25":  /* formula */ "IF(OR(K24<0.4,K12<50),\"\",_xlfn.LET(_xlpm.max_HT_share,MAX(clc_build!J$13,clc_build!J$17,clc_build!J$21,clc_build!J$25,clc_build!J$29,clc_build!J$33),\n\"pic_G2_load_\" &\n_xlfn.IFS(clc_build!J$13=_xlpm.max_HT_share,\"wall\",\nclc_build!J$17=_xlpm.max_HT_share,\"innerwall\",\nclc_build!J$21=_xlpm.max_HT_share,\"win\",\nclc_build!J$25=_xlpm.max_HT_share,\"roof\",\nclc_build!J$29=_xlpm.max_HT_share,\"botceil\",\nclc_build!J$33=_xlpm.max_HT_share,\"topceil\"\n)))",
  "L25":  /* formula */ "IF(OR(L24<0.4,L12<50),\"\",_xlfn.LET(_xlpm.max_HT_share,MAX(clc_build!K$13,clc_build!K$17,clc_build!K$21,clc_build!K$25,clc_build!K$29,clc_build!K$33),\n\"pic_G2_load_\" &\n_xlfn.IFS(clc_build!K$13=_xlpm.max_HT_share,\"wall\",\nclc_build!K$17=_xlpm.max_HT_share,\"innerwall\",\nclc_build!K$21=_xlpm.max_HT_share,\"win\",\nclc_build!K$25=_xlpm.max_HT_share,\"roof\",\nclc_build!K$29=_xlpm.max_HT_share,\"botceil\",\nclc_build!K$33=_xlpm.max_HT_share,\"topceil\"\n)))",
  "M25":  /* formula */ "IF(OR(M24<0.4,M12<50),\"\",_xlfn.LET(_xlpm.max_HT_share,MAX(clc_build!L$13,clc_build!L$17,clc_build!L$21,clc_build!L$25,clc_build!L$29,clc_build!L$33),\n\"pic_G2_load_\" &\n_xlfn.IFS(clc_build!L$13=_xlpm.max_HT_share,\"wall\",\nclc_build!L$17=_xlpm.max_HT_share,\"innerwall\",\nclc_build!L$21=_xlpm.max_HT_share,\"win\",\nclc_build!L$25=_xlpm.max_HT_share,\"roof\",\nclc_build!L$29=_xlpm.max_HT_share,\"botceil\",\nclc_build!L$33=_xlpm.max_HT_share,\"topceil\"\n)))",
  "N25":  /* formula */ "IF(OR(N24<0.4,N12<50),\"\",_xlfn.LET(_xlpm.max_HT_share,MAX(clc_build!M$13,clc_build!M$17,clc_build!M$21,clc_build!M$25,clc_build!M$29,clc_build!M$33),\n\"pic_G2_load_\" &\n_xlfn.IFS(clc_build!M$13=_xlpm.max_HT_share,\"wall\",\nclc_build!M$17=_xlpm.max_HT_share,\"innerwall\",\nclc_build!M$21=_xlpm.max_HT_share,\"win\",\nclc_build!M$25=_xlpm.max_HT_share,\"roof\",\nclc_build!M$29=_xlpm.max_HT_share,\"botceil\",\nclc_build!M$33=_xlpm.max_HT_share,\"topceil\"\n)))",
  "O25":  /* formula */ "IF(OR(O24<0.4,O12<50),\"\",_xlfn.LET(_xlpm.max_HT_share,MAX(clc_build!N$13,clc_build!N$17,clc_build!N$21,clc_build!N$25,clc_build!N$29,clc_build!N$33),\n\"pic_G2_load_\" &\n_xlfn.IFS(clc_build!N$13=_xlpm.max_HT_share,\"wall\",\nclc_build!N$17=_xlpm.max_HT_share,\"innerwall\",\nclc_build!N$21=_xlpm.max_HT_share,\"win\",\nclc_build!N$25=_xlpm.max_HT_share,\"roof\",\nclc_build!N$29=_xlpm.max_HT_share,\"botceil\",\nclc_build!N$33=_xlpm.max_HT_share,\"topceil\"\n)))",
  "P25":  /* formula */ "IF(OR(P24<0.4,P12<50),\"\",_xlfn.LET(_xlpm.max_HT_share,MAX(clc_build!O$13,clc_build!O$17,clc_build!O$21,clc_build!O$25,clc_build!O$29,clc_build!O$33),\n\"pic_G2_load_\" &\n_xlfn.IFS(clc_build!O$13=_xlpm.max_HT_share,\"wall\",\nclc_build!O$17=_xlpm.max_HT_share,\"innerwall\",\nclc_build!O$21=_xlpm.max_HT_share,\"win\",\nclc_build!O$25=_xlpm.max_HT_share,\"roof\",\nclc_build!O$29=_xlpm.max_HT_share,\"botceil\",\nclc_build!O$33=_xlpm.max_HT_share,\"topceil\"\n)))",
  "Q25":  /* formula */ "IF(OR(Q24<0.4,Q12<50),\"\",_xlfn.LET(_xlpm.max_HT_share,MAX(clc_build!P$13,clc_build!P$17,clc_build!P$21,clc_build!P$25,clc_build!P$29,clc_build!P$33),\n\"pic_G2_load_\" &\n_xlfn.IFS(clc_build!P$13=_xlpm.max_HT_share,\"wall\",\nclc_build!P$17=_xlpm.max_HT_share,\"innerwall\",\nclc_build!P$21=_xlpm.max_HT_share,\"win\",\nclc_build!P$25=_xlpm.max_HT_share,\"roof\",\nclc_build!P$29=_xlpm.max_HT_share,\"botceil\",\nclc_build!P$33=_xlpm.max_HT_share,\"topceil\"\n)))",
  "R25":  /* formula */ "IF(OR(R24<0.4,R12<50),\"\",_xlfn.LET(_xlpm.max_HT_share,MAX(clc_build!Q$13,clc_build!Q$17,clc_build!Q$21,clc_build!Q$25,clc_build!Q$29,clc_build!Q$33),\n\"pic_G2_load_\" &\n_xlfn.IFS(clc_build!Q$13=_xlpm.max_HT_share,\"wall\",\nclc_build!Q$17=_xlpm.max_HT_share,\"innerwall\",\nclc_build!Q$21=_xlpm.max_HT_share,\"win\",\nclc_build!Q$25=_xlpm.max_HT_share,\"roof\",\nclc_build!Q$29=_xlpm.max_HT_share,\"botceil\",\nclc_build!Q$33=_xlpm.max_HT_share,\"topceil\"\n)))",
  "S25":  /* formula */ "IF(OR(S24<0.4,S12<50),\"\",_xlfn.LET(_xlpm.max_HT_share,MAX(clc_build!R$13,clc_build!R$17,clc_build!R$21,clc_build!R$25,clc_build!R$29,clc_build!R$33),\n\"pic_G2_load_\" &\n_xlfn.IFS(clc_build!R$13=_xlpm.max_HT_share,\"wall\",\nclc_build!R$17=_xlpm.max_HT_share,\"innerwall\",\nclc_build!R$21=_xlpm.max_HT_share,\"win\",\nclc_build!R$25=_xlpm.max_HT_share,\"roof\",\nclc_build!R$29=_xlpm.max_HT_share,\"botceil\",\nclc_build!R$33=_xlpm.max_HT_share,\"topceil\"\n)))",
  "T25":  /* formula */ "IF(OR(T24<0.4,T12<50),\"\",_xlfn.LET(_xlpm.max_HT_share,MAX(clc_build!S$13,clc_build!S$17,clc_build!S$21,clc_build!S$25,clc_build!S$29,clc_build!S$33),\n\"pic_G2_load_\" &\n_xlfn.IFS(clc_build!S$13=_xlpm.max_HT_share,\"wall\",\nclc_build!S$17=_xlpm.max_HT_share,\"innerwall\",\nclc_build!S$21=_xlpm.max_HT_share,\"win\",\nclc_build!S$25=_xlpm.max_HT_share,\"roof\",\nclc_build!S$29=_xlpm.max_HT_share,\"botceil\",\nclc_build!S$33=_xlpm.max_HT_share,\"topceil\"\n)))",
  "U25":  /* formula */ "IF(OR(U24<0.4,U12<50),\"\",_xlfn.LET(_xlpm.max_HT_share,MAX(clc_build!T$13,clc_build!T$17,clc_build!T$21,clc_build!T$25,clc_build!T$29,clc_build!T$33),\n\"pic_G2_load_\" &\n_xlfn.IFS(clc_build!T$13=_xlpm.max_HT_share,\"wall\",\nclc_build!T$17=_xlpm.max_HT_share,\"innerwall\",\nclc_build!T$21=_xlpm.max_HT_share,\"win\",\nclc_build!T$25=_xlpm.max_HT_share,\"roof\",\nclc_build!T$29=_xlpm.max_HT_share,\"botceil\",\nclc_build!T$33=_xlpm.max_HT_share,\"topceil\"\n)))",
  "V25":  /* formula */ "IF(OR(V24<0.4,V12<50),\"\",_xlfn.LET(_xlpm.max_HT_share,MAX(clc_build!U$13,clc_build!U$17,clc_build!U$21,clc_build!U$25,clc_build!U$29,clc_build!U$33),\n\"pic_G2_load_\" &\n_xlfn.IFS(clc_build!U$13=_xlpm.max_HT_share,\"wall\",\nclc_build!U$17=_xlpm.max_HT_share,\"innerwall\",\nclc_build!U$21=_xlpm.max_HT_share,\"win\",\nclc_build!U$25=_xlpm.max_HT_share,\"roof\",\nclc_build!U$29=_xlpm.max_HT_share,\"botceil\",\nclc_build!U$33=_xlpm.max_HT_share,\"topceil\"\n)))",
  "A26":  /* unknown */ "Kategorie Bauteiltausch Empfehlung icon",
  "D26":  /* unknown */ "color_pic_build_G2_load",
  "G26":  /* unknown */ "G2",
  "H26":  /* formula */ "_xlfn.IFS(AND(H12<50,H12>0),\"green\",H24>0.8,\"red\",H24>0.5,\"orange\",H24>0.35,\"yellow\",TRUE,\"\")",
  "I26":  /* formula */ "_xlfn.IFS(AND(I12<50,I12>0),\"green\",I24>0.8,\"red\",I24>0.5,\"orange\",I24>0.35,\"yellow\",TRUE,\"\")",
  "J26":  /* formula */ "_xlfn.IFS(AND(J12<50,J12>0),\"green\",J24>0.8,\"red\",J24>0.5,\"orange\",J24>0.35,\"yellow\",TRUE,\"\")",
  "K26":  /* formula */ "_xlfn.IFS(AND(K12<50,K12>0),\"green\",K24>0.8,\"red\",K24>0.5,\"orange\",K24>0.35,\"yellow\",TRUE,\"\")",
  "L26":  /* formula */ "_xlfn.IFS(AND(L12<50,L12>0),\"green\",L24>0.8,\"red\",L24>0.5,\"orange\",L24>0.35,\"yellow\",TRUE,\"\")",
  "M26":  /* formula */ "_xlfn.IFS(AND(M12<50,M12>0),\"green\",M24>0.8,\"red\",M24>0.5,\"orange\",M24>0.35,\"yellow\",TRUE,\"\")",
  "N26":  /* formula */ "_xlfn.IFS(AND(N12<50,N12>0),\"green\",N24>0.8,\"red\",N24>0.5,\"orange\",N24>0.35,\"yellow\",TRUE,\"\")",
  "O26":  /* formula */ "_xlfn.IFS(AND(O12<50,O12>0),\"green\",O24>0.8,\"red\",O24>0.5,\"orange\",O24>0.35,\"yellow\",TRUE,\"\")",
  "P26":  /* formula */ "_xlfn.IFS(AND(P12<50,P12>0),\"green\",P24>0.8,\"red\",P24>0.5,\"orange\",P24>0.35,\"yellow\",TRUE,\"\")",
  "Q26":  /* formula */ "_xlfn.IFS(AND(Q12<50,Q12>0),\"green\",Q24>0.8,\"red\",Q24>0.5,\"orange\",Q24>0.35,\"yellow\",TRUE,\"\")",
  "R26":  /* formula */ "_xlfn.IFS(AND(R12<50,R12>0),\"green\",R24>0.8,\"red\",R24>0.5,\"orange\",R24>0.35,\"yellow\",TRUE,\"\")",
  "S26":  /* formula */ "_xlfn.IFS(AND(S12<50,S12>0),\"green\",S24>0.8,\"red\",S24>0.5,\"orange\",S24>0.35,\"yellow\",TRUE,\"\")",
  "T26":  /* formula */ "_xlfn.IFS(AND(T12<50,T12>0),\"green\",T24>0.8,\"red\",T24>0.5,\"orange\",T24>0.35,\"yellow\",TRUE,\"\")",
  "U26":  /* formula */ "_xlfn.IFS(AND(U12<50,U12>0),\"green\",U24>0.8,\"red\",U24>0.5,\"orange\",U24>0.35,\"yellow\",TRUE,\"\")",
  "V26":  /* formula */ "_xlfn.IFS(AND(V12<50,V12>0),\"green\",V24>0.8,\"red\",V24>0.5,\"orange\",V24>0.35,\"yellow\",TRUE,\"\")",
  "A27":  /* unknown */ "Ausgabe schlechtestes Bauteil Raum ",
  "D27":  /* unknown */ "TXT_build_G2_load",
  "G27":  /* unknown */ "G2",
  "H27":  /* formula */ "_xlfn.IFS(\nH12<=0,\"\",\nH12<50,TXT_build!$D$6,\nH12<70,TXT_build!$D$7 &OUT_rooms!H4&TXT_build!$D$10,\nH12<90,TXT_build!$D$8 &OUT_rooms!H4&TXT_build!$D$10,\nTRUE,TXT_build!$D$9 &OUT_rooms!H4&TXT_build!$D$10)",
  "I27":  /* formula */ "_xlfn.IFS(\nI12<=0,\"\",\nI12<50,TXT_build!$D$6,\nI12<70,TXT_build!$D$7 &OUT_rooms!I4&TXT_build!$D$10,\nI12<90,TXT_build!$D$8 &OUT_rooms!I4&TXT_build!$D$10,\nTRUE,TXT_build!$D$9 &OUT_rooms!I4&TXT_build!$D$10)",
  "J27":  /* formula */ "_xlfn.IFS(\nJ12<=0,\"\",\nJ12<50,TXT_build!$D$6,\nJ12<70,TXT_build!$D$7 &OUT_rooms!J4&TXT_build!$D$10,\nJ12<90,TXT_build!$D$8 &OUT_rooms!J4&TXT_build!$D$10,\nTRUE,TXT_build!$D$9 &OUT_rooms!J4&TXT_build!$D$10)",
  "K27":  /* formula */ "_xlfn.IFS(\nK12<=0,\"\",\nK12<50,TXT_build!$D$6,\nK12<70,TXT_build!$D$7 &OUT_rooms!K4&TXT_build!$D$10,\nK12<90,TXT_build!$D$8 &OUT_rooms!K4&TXT_build!$D$10,\nTRUE,TXT_build!$D$9 &OUT_rooms!K4&TXT_build!$D$10)",
  "L27":  /* formula */ "_xlfn.IFS(\nL12<=0,\"\",\nL12<50,TXT_build!$D$6,\nL12<70,TXT_build!$D$7 &OUT_rooms!L4&TXT_build!$D$10,\nL12<90,TXT_build!$D$8 &OUT_rooms!L4&TXT_build!$D$10,\nTRUE,TXT_build!$D$9 &OUT_rooms!L4&TXT_build!$D$10)",
  "M27":  /* formula */ "_xlfn.IFS(\nM12<=0,\"\",\nM12<50,TXT_build!$D$6,\nM12<70,TXT_build!$D$7 &OUT_rooms!M4&TXT_build!$D$10,\nM12<90,TXT_build!$D$8 &OUT_rooms!M4&TXT_build!$D$10,\nTRUE,TXT_build!$D$9 &OUT_rooms!M4&TXT_build!$D$10)",
  "N27":  /* formula */ "_xlfn.IFS(\nN12<=0,\"\",\nN12<50,TXT_build!$D$6,\nN12<70,TXT_build!$D$7 &OUT_rooms!N4&TXT_build!$D$10,\nN12<90,TXT_build!$D$8 &OUT_rooms!N4&TXT_build!$D$10,\nTRUE,TXT_build!$D$9 &OUT_rooms!N4&TXT_build!$D$10)",
  "O27":  /* formula */ "_xlfn.IFS(\nO12<=0,\"\",\nO12<50,TXT_build!$D$6,\nO12<70,TXT_build!$D$7 &OUT_rooms!O4&TXT_build!$D$10,\nO12<90,TXT_build!$D$8 &OUT_rooms!O4&TXT_build!$D$10,\nTRUE,TXT_build!$D$9 &OUT_rooms!O4&TXT_build!$D$10)",
  "P27":  /* formula */ "_xlfn.IFS(\nP12<=0,\"\",\nP12<50,TXT_build!$D$6,\nP12<70,TXT_build!$D$7 &OUT_rooms!P4&TXT_build!$D$10,\nP12<90,TXT_build!$D$8 &OUT_rooms!P4&TXT_build!$D$10,\nTRUE,TXT_build!$D$9 &OUT_rooms!P4&TXT_build!$D$10)",
  "Q27":  /* formula */ "_xlfn.IFS(\nQ12<=0,\"\",\nQ12<50,TXT_build!$D$6,\nQ12<70,TXT_build!$D$7 &OUT_rooms!Q4&TXT_build!$D$10,\nQ12<90,TXT_build!$D$8 &OUT_rooms!Q4&TXT_build!$D$10,\nTRUE,TXT_build!$D$9 &OUT_rooms!Q4&TXT_build!$D$10)",
  "R27":  /* formula */ "_xlfn.IFS(\nR12<=0,\"\",\nR12<50,TXT_build!$D$6,\nR12<70,TXT_build!$D$7 &OUT_rooms!R4&TXT_build!$D$10,\nR12<90,TXT_build!$D$8 &OUT_rooms!R4&TXT_build!$D$10,\nTRUE,TXT_build!$D$9 &OUT_rooms!R4&TXT_build!$D$10)",
  "S27":  /* formula */ "_xlfn.IFS(\nS12<=0,\"\",\nS12<50,TXT_build!$D$6,\nS12<70,TXT_build!$D$7 &OUT_rooms!S4&TXT_build!$D$10,\nS12<90,TXT_build!$D$8 &OUT_rooms!S4&TXT_build!$D$10,\nTRUE,TXT_build!$D$9 &OUT_rooms!S4&TXT_build!$D$10)",
  "T27":  /* formula */ "_xlfn.IFS(\nT12<=0,\"\",\nT12<50,TXT_build!$D$6,\nT12<70,TXT_build!$D$7 &OUT_rooms!T4&TXT_build!$D$10,\nT12<90,TXT_build!$D$8 &OUT_rooms!T4&TXT_build!$D$10,\nTRUE,TXT_build!$D$9 &OUT_rooms!T4&TXT_build!$D$10)",
  "U27":  /* formula */ "_xlfn.IFS(\nU12<=0,\"\",\nU12<50,TXT_build!$D$6,\nU12<70,TXT_build!$D$7 &OUT_rooms!U4&TXT_build!$D$10,\nU12<90,TXT_build!$D$8 &OUT_rooms!U4&TXT_build!$D$10,\nTRUE,TXT_build!$D$9 &OUT_rooms!U4&TXT_build!$D$10)",
  "V27":  /* formula */ "_xlfn.IFS(\nV12<=0,\"\",\nV12<50,TXT_build!$D$6,\nV12<70,TXT_build!$D$7 &OUT_rooms!V4&TXT_build!$D$10,\nV12<90,TXT_build!$D$8 &OUT_rooms!V4&TXT_build!$D$10,\nTRUE,TXT_build!$D$9 &OUT_rooms!V4&TXT_build!$D$10)",
  "A28":  /* unknown */ "Heizkörpertausch Empfehlung icon",
  "D28":  /* unknown */ "pic_build_G2_rad",
  "G28":  /* unknown */ "G2",
  "H28":  /* formula */ "\"pic_G2_rad_\" &\n_xlfn.IFS(clc_build!G40<0.5,\"bigger_warning\",\nclc_build!G40<1,\"bigger\",\nAND(clc_build!G40>=1,clc_build!G39<1),\"better\",\nclc_build!G39>=1,\"suff\")",
  "I28":  /* formula */ "\"pic_G2_rad_\" &\n_xlfn.IFS(clc_build!H40<0.5,\"bigger_warning\",\nclc_build!H40<1,\"bigger\",\nAND(clc_build!H40>=1,clc_build!H39<1),\"better\",\nclc_build!H39>=1,\"suff\")",
  "J28":  /* formula */ "\"pic_G2_rad_\" &\n_xlfn.IFS(clc_build!I40<0.5,\"bigger_warning\",\nclc_build!I40<1,\"bigger\",\nAND(clc_build!I40>=1,clc_build!I39<1),\"better\",\nclc_build!I39>=1,\"suff\")",
  "K28":  /* formula */ "\"pic_G2_rad_\" &\n_xlfn.IFS(clc_build!J40<0.5,\"bigger_warning\",\nclc_build!J40<1,\"bigger\",\nAND(clc_build!J40>=1,clc_build!J39<1),\"better\",\nclc_build!J39>=1,\"suff\")",
  "L28":  /* formula */ "\"pic_G2_rad_\" &\n_xlfn.IFS(clc_build!K40<0.5,\"bigger_warning\",\nclc_build!K40<1,\"bigger\",\nAND(clc_build!K40>=1,clc_build!K39<1),\"better\",\nclc_build!K39>=1,\"suff\")",
  "M28":  /* formula */ "\"pic_G2_rad_\" &\n_xlfn.IFS(clc_build!L40<0.5,\"bigger_warning\",\nclc_build!L40<1,\"bigger\",\nAND(clc_build!L40>=1,clc_build!L39<1),\"better\",\nclc_build!L39>=1,\"suff\")",
  "N28":  /* formula */ "\"pic_G2_rad_\" &\n_xlfn.IFS(clc_build!M40<0.5,\"bigger_warning\",\nclc_build!M40<1,\"bigger\",\nAND(clc_build!M40>=1,clc_build!M39<1),\"better\",\nclc_build!M39>=1,\"suff\")",
  "O28":  /* formula */ "\"pic_G2_rad_\" &\n_xlfn.IFS(clc_build!N40<0.5,\"bigger_warning\",\nclc_build!N40<1,\"bigger\",\nAND(clc_build!N40>=1,clc_build!N39<1),\"better\",\nclc_build!N39>=1,\"suff\")",
  "P28":  /* formula */ "\"pic_G2_rad_\" &\n_xlfn.IFS(clc_build!O40<0.5,\"bigger_warning\",\nclc_build!O40<1,\"bigger\",\nAND(clc_build!O40>=1,clc_build!O39<1),\"better\",\nclc_build!O39>=1,\"suff\")",
  "Q28":  /* formula */ "\"pic_G2_rad_\" &\n_xlfn.IFS(clc_build!P40<0.5,\"bigger_warning\",\nclc_build!P40<1,\"bigger\",\nAND(clc_build!P40>=1,clc_build!P39<1),\"better\",\nclc_build!P39>=1,\"suff\")",
  "R28":  /* formula */ "\"pic_G2_rad_\" &\n_xlfn.IFS(clc_build!Q40<0.5,\"bigger_warning\",\nclc_build!Q40<1,\"bigger\",\nAND(clc_build!Q40>=1,clc_build!Q39<1),\"better\",\nclc_build!Q39>=1,\"suff\")",
  "S28":  /* formula */ "\"pic_G2_rad_\" &\n_xlfn.IFS(clc_build!R40<0.5,\"bigger_warning\",\nclc_build!R40<1,\"bigger\",\nAND(clc_build!R40>=1,clc_build!R39<1),\"better\",\nclc_build!R39>=1,\"suff\")",
  "T28":  /* formula */ "\"pic_G2_rad_\" &\n_xlfn.IFS(clc_build!S40<0.5,\"bigger_warning\",\nclc_build!S40<1,\"bigger\",\nAND(clc_build!S40>=1,clc_build!S39<1),\"better\",\nclc_build!S39>=1,\"suff\")",
  "U28":  /* formula */ "\"pic_G2_rad_\" &\n_xlfn.IFS(clc_build!T40<0.5,\"bigger_warning\",\nclc_build!T40<1,\"bigger\",\nAND(clc_build!T40>=1,clc_build!T39<1),\"better\",\nclc_build!T39>=1,\"suff\")",
  "V28":  /* formula */ "\"pic_G2_rad_\" &\n_xlfn.IFS(clc_build!U40<0.5,\"bigger_warning\",\nclc_build!U40<1,\"bigger\",\nAND(clc_build!U40>=1,clc_build!U39<1),\"better\",\nclc_build!U39>=1,\"suff\")",
  "A29":  /* unknown */ "Ausgabe Heizkörpertausch Raum",
  "B29":  /* unknown */ "build",
  "D29":  /* unknown */ "TXT_build_G2_rad",
  "G29":  /* unknown */ "G2",
  "H29":  /* formula */ "_xlfn.IFS(clc_build!G40<0.5,TXT_build!$D$11,\nclc_build!G40<1,TXT_build!$D$12,\nAND(clc_build!G40>=1,clc_build!G39<1),TXT_build!$D$13,\nclc_build!G39>=1,TXT_build!$D$14)",
  "I29":  /* formula */ "_xlfn.IFS(clc_build!H40<0.5,TXT_build!$D$11,\nclc_build!H40<1,TXT_build!$D$12,\nAND(clc_build!H40>=1,clc_build!H39<1),TXT_build!$D$13,\nclc_build!H39>=1,TXT_build!$D$14)",
  "J29":  /* formula */ "_xlfn.IFS(clc_build!I40<0.5,TXT_build!$D$11,\nclc_build!I40<1,TXT_build!$D$12,\nAND(clc_build!I40>=1,clc_build!I39<1),TXT_build!$D$13,\nclc_build!I39>=1,TXT_build!$D$14)",
  "K29":  /* formula */ "_xlfn.IFS(clc_build!J40<0.5,TXT_build!$D$11,\nclc_build!J40<1,TXT_build!$D$12,\nAND(clc_build!J40>=1,clc_build!J39<1),TXT_build!$D$13,\nclc_build!J39>=1,TXT_build!$D$14)",
  "L29":  /* formula */ "_xlfn.IFS(clc_build!K40<0.5,TXT_build!$D$11,\nclc_build!K40<1,TXT_build!$D$12,\nAND(clc_build!K40>=1,clc_build!K39<1),TXT_build!$D$13,\nclc_build!K39>=1,TXT_build!$D$14)",
  "M29":  /* formula */ "_xlfn.IFS(clc_build!L40<0.5,TXT_build!$D$11,\nclc_build!L40<1,TXT_build!$D$12,\nAND(clc_build!L40>=1,clc_build!L39<1),TXT_build!$D$13,\nclc_build!L39>=1,TXT_build!$D$14)",
  "N29":  /* formula */ "_xlfn.IFS(clc_build!M40<0.5,TXT_build!$D$11,\nclc_build!M40<1,TXT_build!$D$12,\nAND(clc_build!M40>=1,clc_build!M39<1),TXT_build!$D$13,\nclc_build!M39>=1,TXT_build!$D$14)",
  "O29":  /* formula */ "_xlfn.IFS(clc_build!N40<0.5,TXT_build!$D$11,\nclc_build!N40<1,TXT_build!$D$12,\nAND(clc_build!N40>=1,clc_build!N39<1),TXT_build!$D$13,\nclc_build!N39>=1,TXT_build!$D$14)",
  "P29":  /* formula */ "_xlfn.IFS(clc_build!O40<0.5,TXT_build!$D$11,\nclc_build!O40<1,TXT_build!$D$12,\nAND(clc_build!O40>=1,clc_build!O39<1),TXT_build!$D$13,\nclc_build!O39>=1,TXT_build!$D$14)",
  "Q29":  /* formula */ "_xlfn.IFS(clc_build!P40<0.5,TXT_build!$D$11,\nclc_build!P40<1,TXT_build!$D$12,\nAND(clc_build!P40>=1,clc_build!P39<1),TXT_build!$D$13,\nclc_build!P39>=1,TXT_build!$D$14)",
  "R29":  /* formula */ "_xlfn.IFS(clc_build!Q40<0.5,TXT_build!$D$11,\nclc_build!Q40<1,TXT_build!$D$12,\nAND(clc_build!Q40>=1,clc_build!Q39<1),TXT_build!$D$13,\nclc_build!Q39>=1,TXT_build!$D$14)",
  "S29":  /* formula */ "_xlfn.IFS(clc_build!R40<0.5,TXT_build!$D$11,\nclc_build!R40<1,TXT_build!$D$12,\nAND(clc_build!R40>=1,clc_build!R39<1),TXT_build!$D$13,\nclc_build!R39>=1,TXT_build!$D$14)",
  "T29":  /* formula */ "_xlfn.IFS(clc_build!S40<0.5,TXT_build!$D$11,\nclc_build!S40<1,TXT_build!$D$12,\nAND(clc_build!S40>=1,clc_build!S39<1),TXT_build!$D$13,\nclc_build!S39>=1,TXT_build!$D$14)",
  "U29":  /* formula */ "_xlfn.IFS(clc_build!T40<0.5,TXT_build!$D$11,\nclc_build!T40<1,TXT_build!$D$12,\nAND(clc_build!T40>=1,clc_build!T39<1),TXT_build!$D$13,\nclc_build!T39>=1,TXT_build!$D$14)",
  "V29":  /* formula */ "_xlfn.IFS(clc_build!U40<0.5,TXT_build!$D$11,\nclc_build!U40<1,TXT_build!$D$12,\nAND(clc_build!U40>=1,clc_build!U39<1),TXT_build!$D$13,\nclc_build!U39>=1,TXT_build!$D$14)",
  "A30":  /* unknown */ "color Raumheizlast ",
  "H30":  /* formula */ "_xlfn.IFS(\nH12<=0,\"\",\nH12<50,\"green\",\nH12<70,\"yellow\",\nH12<90,\"orange\",\nTRUE,\"red\")",
  "I30":  /* formula */ "_xlfn.IFS(\nI12<=0,\"\",\nI12<50,\"green\",\nI12<70,\"yellow\",\nI12<90,\"orange\",\nTRUE,\"red\")",
  "J30":  /* formula */ "_xlfn.IFS(\nJ12<=0,\"\",\nJ12<50,\"green\",\nJ12<70,\"yellow\",\nJ12<90,\"orange\",\nTRUE,\"red\")",
  "K30":  /* formula */ "_xlfn.IFS(\nK12<=0,\"\",\nK12<50,\"green\",\nK12<70,\"yellow\",\nK12<90,\"orange\",\nTRUE,\"red\")",
  "L30":  /* formula */ "_xlfn.IFS(\nL12<=0,\"\",\nL12<50,\"green\",\nL12<70,\"yellow\",\nL12<90,\"orange\",\nTRUE,\"red\")",
  "M30":  /* formula */ "_xlfn.IFS(\nM12<=0,\"\",\nM12<50,\"green\",\nM12<70,\"yellow\",\nM12<90,\"orange\",\nTRUE,\"red\")",
  "N30":  /* formula */ "_xlfn.IFS(\nN12<=0,\"\",\nN12<50,\"green\",\nN12<70,\"yellow\",\nN12<90,\"orange\",\nTRUE,\"red\")",
  "O30":  /* formula */ "_xlfn.IFS(\nO12<=0,\"\",\nO12<50,\"green\",\nO12<70,\"yellow\",\nO12<90,\"orange\",\nTRUE,\"red\")",
  "P30":  /* formula */ "_xlfn.IFS(\nP12<=0,\"\",\nP12<50,\"green\",\nP12<70,\"yellow\",\nP12<90,\"orange\",\nTRUE,\"red\")",
  "Q30":  /* formula */ "_xlfn.IFS(\nQ12<=0,\"\",\nQ12<50,\"green\",\nQ12<70,\"yellow\",\nQ12<90,\"orange\",\nTRUE,\"red\")",
  "R30":  /* formula */ "_xlfn.IFS(\nR12<=0,\"\",\nR12<50,\"green\",\nR12<70,\"yellow\",\nR12<90,\"orange\",\nTRUE,\"red\")",
  "S30":  /* formula */ "_xlfn.IFS(\nS12<=0,\"\",\nS12<50,\"green\",\nS12<70,\"yellow\",\nS12<90,\"orange\",\nTRUE,\"red\")",
  "T30":  /* formula */ "_xlfn.IFS(\nT12<=0,\"\",\nT12<50,\"green\",\nT12<70,\"yellow\",\nT12<90,\"orange\",\nTRUE,\"red\")",
  "U30":  /* formula */ "_xlfn.IFS(\nU12<=0,\"\",\nU12<50,\"green\",\nU12<70,\"yellow\",\nU12<90,\"orange\",\nTRUE,\"red\")",
  "V30":  /* formula */ "_xlfn.IFS(\nV12<=0,\"\",\nV12<50,\"green\",\nV12<70,\"yellow\",\nV12<90,\"orange\",\nTRUE,\"red\")",
  "A31":  /* unknown */ "color Heizkörleistung ",
  "H31":  /* formula */ "_xlfn.IFS(clc_build!G40<0.5,\"red\",\nclc_build!G40<1,\"orange\",\nAND(clc_build!G40>=1,clc_build!G39<1),\"yellow\",\nclc_build!G39>=1,\"green\")",
  "I31":  /* formula */ "_xlfn.IFS(clc_build!H40<0.5,\"red\",\nclc_build!H40<1,\"orange\",\nAND(clc_build!H40>=1,clc_build!H39<1),\"yellow\",\nclc_build!H39>=1,\"green\")",
  "J31":  /* formula */ "_xlfn.IFS(clc_build!I40<0.5,\"red\",\nclc_build!I40<1,\"orange\",\nAND(clc_build!I40>=1,clc_build!I39<1),\"yellow\",\nclc_build!I39>=1,\"green\")",
  "K31":  /* formula */ "_xlfn.IFS(clc_build!J40<0.5,\"red\",\nclc_build!J40<1,\"orange\",\nAND(clc_build!J40>=1,clc_build!J39<1),\"yellow\",\nclc_build!J39>=1,\"green\")",
  "L31":  /* formula */ "_xlfn.IFS(clc_build!K40<0.5,\"red\",\nclc_build!K40<1,\"orange\",\nAND(clc_build!K40>=1,clc_build!K39<1),\"yellow\",\nclc_build!K39>=1,\"green\")",
  "M31":  /* formula */ "_xlfn.IFS(clc_build!L40<0.5,\"red\",\nclc_build!L40<1,\"orange\",\nAND(clc_build!L40>=1,clc_build!L39<1),\"yellow\",\nclc_build!L39>=1,\"green\")",
  "N31":  /* formula */ "_xlfn.IFS(clc_build!M40<0.5,\"red\",\nclc_build!M40<1,\"orange\",\nAND(clc_build!M40>=1,clc_build!M39<1),\"yellow\",\nclc_build!M39>=1,\"green\")",
  "O31":  /* formula */ "_xlfn.IFS(clc_build!N40<0.5,\"red\",\nclc_build!N40<1,\"orange\",\nAND(clc_build!N40>=1,clc_build!N39<1),\"yellow\",\nclc_build!N39>=1,\"green\")",
  "P31":  /* formula */ "_xlfn.IFS(clc_build!O40<0.5,\"red\",\nclc_build!O40<1,\"orange\",\nAND(clc_build!O40>=1,clc_build!O39<1),\"yellow\",\nclc_build!O39>=1,\"green\")",
  "Q31":  /* formula */ "_xlfn.IFS(clc_build!P40<0.5,\"red\",\nclc_build!P40<1,\"orange\",\nAND(clc_build!P40>=1,clc_build!P39<1),\"yellow\",\nclc_build!P39>=1,\"green\")",
  "R31":  /* formula */ "_xlfn.IFS(clc_build!Q40<0.5,\"red\",\nclc_build!Q40<1,\"orange\",\nAND(clc_build!Q40>=1,clc_build!Q39<1),\"yellow\",\nclc_build!Q39>=1,\"green\")",
  "S31":  /* formula */ "_xlfn.IFS(clc_build!R40<0.5,\"red\",\nclc_build!R40<1,\"orange\",\nAND(clc_build!R40>=1,clc_build!R39<1),\"yellow\",\nclc_build!R39>=1,\"green\")",
  "T31":  /* formula */ "_xlfn.IFS(clc_build!S40<0.5,\"red\",\nclc_build!S40<1,\"orange\",\nAND(clc_build!S40>=1,clc_build!S39<1),\"yellow\",\nclc_build!S39>=1,\"green\")",
  "U31":  /* formula */ "_xlfn.IFS(clc_build!T40<0.5,\"red\",\nclc_build!T40<1,\"orange\",\nAND(clc_build!T40>=1,clc_build!T39<1),\"yellow\",\nclc_build!T39>=1,\"green\")",
  "V31":  /* formula */ "_xlfn.IFS(clc_build!U40<0.5,\"red\",\nclc_build!U40<1,\"orange\",\nAND(clc_build!U40>=1,clc_build!U39<1),\"yellow\",\nclc_build!U39>=1,\"green\")",
  "A32":  /* unknown */ "Maßnahme Heizkörper",
  "H32":  /* formula */ "_xlfn.IFS(clc_build!G40<0.5,\"stark vergrößern\",\nclc_build!G40<1,\"vergrößern\",\nAND(clc_build!G40>=1,clc_build!G39<1),\"verbessern\",\nclc_build!G39>=1,\"\")",
  "I32":  /* formula */ "_xlfn.IFS(clc_build!H40<0.5,\"stark vergrößern\",\nclc_build!H40<1,\"vergrößern\",\nAND(clc_build!H40>=1,clc_build!H39<1),\"verbessern\",\nclc_build!H39>=1,\"\")",
  "J32":  /* formula */ "_xlfn.IFS(clc_build!I40<0.5,\"stark vergrößern\",\nclc_build!I40<1,\"vergrößern\",\nAND(clc_build!I40>=1,clc_build!I39<1),\"verbessern\",\nclc_build!I39>=1,\"\")",
  "K32":  /* formula */ "_xlfn.IFS(clc_build!J40<0.5,\"stark vergrößern\",\nclc_build!J40<1,\"vergrößern\",\nAND(clc_build!J40>=1,clc_build!J39<1),\"verbessern\",\nclc_build!J39>=1,\"\")",
  "L32":  /* formula */ "_xlfn.IFS(clc_build!K40<0.5,\"stark vergrößern\",\nclc_build!K40<1,\"vergrößern\",\nAND(clc_build!K40>=1,clc_build!K39<1),\"verbessern\",\nclc_build!K39>=1,\"\")",
  "M32":  /* formula */ "_xlfn.IFS(clc_build!L40<0.5,\"stark vergrößern\",\nclc_build!L40<1,\"vergrößern\",\nAND(clc_build!L40>=1,clc_build!L39<1),\"verbessern\",\nclc_build!L39>=1,\"\")",
  "N32":  /* formula */ "_xlfn.IFS(clc_build!M40<0.5,\"stark vergrößern\",\nclc_build!M40<1,\"vergrößern\",\nAND(clc_build!M40>=1,clc_build!M39<1),\"verbessern\",\nclc_build!M39>=1,\"\")",
  "O32":  /* formula */ "_xlfn.IFS(clc_build!N40<0.5,\"stark vergrößern\",\nclc_build!N40<1,\"vergrößern\",\nAND(clc_build!N40>=1,clc_build!N39<1),\"verbessern\",\nclc_build!N39>=1,\"\")",
  "P32":  /* formula */ "_xlfn.IFS(clc_build!O40<0.5,\"stark vergrößern\",\nclc_build!O40<1,\"vergrößern\",\nAND(clc_build!O40>=1,clc_build!O39<1),\"verbessern\",\nclc_build!O39>=1,\"\")",
  "Q32":  /* formula */ "_xlfn.IFS(clc_build!P40<0.5,\"stark vergrößern\",\nclc_build!P40<1,\"vergrößern\",\nAND(clc_build!P40>=1,clc_build!P39<1),\"verbessern\",\nclc_build!P39>=1,\"\")",
  "R32":  /* formula */ "_xlfn.IFS(clc_build!Q40<0.5,\"stark vergrößern\",\nclc_build!Q40<1,\"vergrößern\",\nAND(clc_build!Q40>=1,clc_build!Q39<1),\"verbessern\",\nclc_build!Q39>=1,\"\")",
  "S32":  /* formula */ "_xlfn.IFS(clc_build!R40<0.5,\"stark vergrößern\",\nclc_build!R40<1,\"vergrößern\",\nAND(clc_build!R40>=1,clc_build!R39<1),\"verbessern\",\nclc_build!R39>=1,\"\")",
  "T32":  /* formula */ "_xlfn.IFS(clc_build!S40<0.5,\"stark vergrößern\",\nclc_build!S40<1,\"vergrößern\",\nAND(clc_build!S40>=1,clc_build!S39<1),\"verbessern\",\nclc_build!S39>=1,\"\")",
  "U32":  /* formula */ "_xlfn.IFS(clc_build!T40<0.5,\"stark vergrößern\",\nclc_build!T40<1,\"vergrößern\",\nAND(clc_build!T40>=1,clc_build!T39<1),\"verbessern\",\nclc_build!T39>=1,\"\")",
  "V32":  /* formula */ "_xlfn.IFS(clc_build!U40<0.5,\"stark vergrößern\",\nclc_build!U40<1,\"vergrößern\",\nAND(clc_build!U40>=1,clc_build!U39<1),\"verbessern\",\nclc_build!U39>=1,\"\")",
  "A34":  /* unknown */ "Position Marker Skalen ",
  "A35":  /* unknown */ "Aktueller Heizkörper",
  "B35":  /* unknown */ "room",
  "D35":  /* unknown */ "pos_room_mark_isTYP",
  "G35":  /* unknown */ "R1/2",
  "H35":  /* formula */ "_xlfn.LET(\n  _xlpm.deck,clc_build!G$39,\n\n   _xlfn.IFS(\n1<=clc_build!G$39,\nMAX(0, MIN(0.25, (1.5 - _xlpm.deck)*0.25/0.5)),\n\n AND(1>clc_build!G$39,clc_build!G$39>=0.8),\nMAX(0.27, MIN(0.5, 0.25 + (1 - _xlpm.deck)*0.25/0.2)),\n\n  OR(AND(0.8>clc_build!G$39,clc_build!G$39>=0.6),clc_build!G$38>clc_build!G$7),\nMAX(0.52, MIN(0.75, 0.5 + (0.8 - _xlpm.deck)*0.25/0.2)),\n\n   AND(clc_build!G$39<0.6,clc_build!G$38<clc_build!G$7),\nMAX(0.77, MIN(1, 0.75 + (0.6 - _xlpm.deck)*0.25/0.2))))",
  "A36":  /* unknown */ "Besserer Heizkörper",
  "B36":  /* unknown */ "room",
  "D36":  /* unknown */ "pos_room_mark_TYP33",
  "G36":  /* unknown */ "R1/2",
  "H36":  /* formula */ "_xlfn.LET(\n\n  _xlpm.deck,clc_build!G$40,\n\n    IF(\n1<=clc_build!G$39,\nMAX(0, MIN(0.25, (1.5 - _xlpm.deck)*0.25/0.5)),\nMAX(0.27, MIN(1, 0.25 + (1 - _xlpm.deck) *0.75/0.6))))",
  "A37":  /* unknown */ "Kakulierte Raumheizlast",
  "B37":  /* unknown */ "room",
  "D37":  /* unknown */ "pos_room_mark_load",
  "G37":  /* unknown */ "R3",
  "H37":  /* formula */ "MAX(30,MIN(110,clc_build!G$8))",
  "A41":  /* unknown */ "Warnhinweis Raumebene",
  "B41":  /* unknown */ "room",
  "D41":  /* unknown */ "TXT_room_RW",
  "G41":  /* unknown */ "RW",
  "H41":  /* formula */ "IF(\n  OR(\n   AND(\n    IN_rooms!$R3=\"Badezimmer\",IN_rooms!R$6>24),\n     AND(IN_rooms!$R3<>\"Badezimmer\",IN_rooms!R$6>20)),TXT_rooms!$E$20,\"\")",
  "I41":  /* formula */ "IF(clc_load!J$5=\"Bad*\",\nIF(clc_load!J$10>24,TXT_rooms!$E$20,\"\"),\nIF(clc_load!J$10>20,TXT_rooms!$E$20,\"\")\n)",
  "J41":  /* formula */ "IF(clc_load!K$5=\"Bad*\",\nIF(clc_load!K$10>24,TXT_rooms!$E$20,\"\"),\nIF(clc_load!K$10>20,TXT_rooms!$E$20,\"\")\n)",
  "K41":  /* formula */ "IF(clc_load!L$5=\"Bad*\",\nIF(clc_load!L$10>24,TXT_rooms!$E$20,\"\"),\nIF(clc_load!L$10>20,TXT_rooms!$E$20,\"\")\n)",
  "L41":  /* formula */ "IF(clc_load!M$5=\"Bad*\",\nIF(clc_load!M$10>24,TXT_rooms!$E$20,\"\"),\nIF(clc_load!M$10>20,TXT_rooms!$E$20,\"\")\n)",
  "M41":  /* formula */ "IF(clc_load!N$5=\"Bad*\",\nIF(clc_load!N$10>24,TXT_rooms!$E$20,\"\"),\nIF(clc_load!N$10>20,TXT_rooms!$E$20,\"\")\n)",
  "A45":  /* unknown */ "Input Warnungen >> @Till: keine Priorität, wird nach OUT_build umgesetzt",
  "A46":  /* unknown */ "AW-Länge > Kantenlänge Quadrat mit Raumfläche ",
  "A47":  /* unknown */ "A_win > A_wall ",
  "A48":  /* unknown */ "A_roof_win > A_roof ",
  "A49":  /* unknown */ "kein Heizkörper angelegt ",
  "A50":  /* unknown */ "L_roof_jamb_hei > L_wall_hei",
  "A51":  /* unknown */ "Geometrie Dachfläche (Hypotenuse <Ankatete)",
} as const;
