// Sheet: OUT_build
export const data = {
  "A1":  /* unknown */ "Bezeichnung",
  "B1":  /* unknown */ "Gruppe",
  "C1":  /* unknown */ "Subgruppe",
  "D1":  /* unknown */ "Variable ",
  "E1":  /* unknown */ "Einheit",
  "F1":  /* unknown */ "Kommentar",
  "G1":  /* unknown */ "Position Mockup",
  "H1":  /* unknown */ "Ausgabe",
  "A2":  /* unknown */ "NT-Readiness Gesamtgebäude ",
  "B2":  /* unknown */ "G1 ",
  "D2":  /* unknown */ "TXT_build_G1",
  "G2":  /* unknown */ "G1",
  "H2":  /* formula */ "_xlfn.IFS(OR(clc_build!G73>=0.5,clc_build!G75>=0.75),TXT_build!D2,\nOR(clc_build!G66>0,clc_build!G76>=0.75),TXT_build!D3,\nclc_build!G68>0,TXT_build!D4,\nclc_build!G78>=1,TXT_build!D5)",
  "A3":  /* unknown */ "Heizkörpertausch",
  "B3":  /* unknown */ "G3",
  "D3":  /* unknown */ "TXT_build_G3",
  "A6":  /* unknown */ "Lückentext Bewertung Heizkörpertausch Raumebene 1",
  "D6":  /* unknown */ "TXT_room_R3_fill_1",
  "G6":  /* unknown */ "R3",
  "A7":  /* unknown */ "Lückentext Bewertung Heizkörpertausch Raumebene 2",
  "D7":  /* unknown */ "TXT_room_R3_fill_2",
  "G7":  /* unknown */ "R3",
  "A8":  /* unknown */ "Lückentext Bewertung Heizkörpertausch Raumebene 3",
  "D8":  /* unknown */ "TXT_room_R3_fill_3",
  "G8":  /* unknown */ "R3",
  "A9":  /* unknown */ "Ausgabe Heizkörpertausch Raumebene",
  "D9":  /* unknown */ "TXT_room__R3_Qdot",
  "G9":  /* unknown */ "R3",
  "A10":  /* unknown */ "\"Kalkulierte Raumheizlast\" - Wert 1",
  "D10":  /* unknown */ "Qdot_room_cor",
  "A11":  /* unknown */ "\"Kalkulierte Raumheizlast\" - Wert 2",
  "D11":  /* unknown */ "qdot_room_cor",
  "A12":  /* unknown */ "Ausgabewert \"Kalkulierte Raumheizlast\" als String",
  "D12":  /* unknown */ "TXT_qdot_room",
  "A13":  /* unknown */ "\"Wie gut sind die Heizkörper geeignet?\" - Leistung Aktueller Heizkörper",
  "D13":  /* unknown */ "TXT_Qdot_rad_act",
  "H13":  /* formula */ "TEXT(clc_build!G37,\"0\") & \" Watt\"",
  "A14":  /* unknown */ "\"Wie gut sind die Heizkörper geeignet?\" - Leistung Besserer heizkörper (Typ 33)",
  "D14":  /* unknown */ "TXT_Qdot_rad_typ33",
  "H14":  /* formula */ "TEXT(clc_build!G38,\"0\") & \" Watt\"",
  "A15":  /* unknown */ "\"Wie gut sind die Heizkörper geeignet?\" - Deckung Aktueller Heizkörper",
  "D15":  /* unknown */ "TXT_r_rad_act",
  "H15":  /* formula */ "TEXT(clc_build!G39*100,\"0\") & \" % Deckung\"",
  "A16":  /* unknown */ "\"Wie gut sind die Heizkörper geeignet?\" - Deckung Besserer heizkörper (Typ 33)",
  "D16":  /* unknown */ "TXT_r_rad_typ33",
  "H16":  /* formula */ "TEXT(clc_build!G40*100,\"0\") & \" % Deckung\"",
  "A22":  /* unknown */ "Todo: ",
  "A23":  /* unknown */ "Output Dashboard in OUT_rooms ergänzen ",
} as const;
