// Sheet: OUT_build
export const data = {
  "A1":  /* unknown */ "Bezeichnung",
  "B1":  /* unknown */ "Gruppe",
  "C1":  /* unknown */ "Subgruppe",
  "D1":  /* unknown */ "Variable ",
  "E1":  /* unknown */ "Einheit",
  "F1":  /* unknown */ "Kommentar",
  "G1":  /* unknown */ "Position Mockup",
  "H1":  /* unknown */ "Ausgabe",
  "A2":  /* unknown */ "Real Wert Position NT-readiness Skala",
  "G2":  /* unknown */ "G1",
  "A3":  /* unknown */ "NT-Readiness Gesamtgebäude ",
  "B3":  /* unknown */ "G1 ",
  "D3":  /* unknown */ "TXT_build_G1",
  "G3":  /* unknown */ "G1",
  "H3":  /* formula */ "_xlfn.IFS(OR(clc_build!G73>=0.5,clc_build!G75>=0.75),TXT_build!D2,\nOR(clc_build!G66>0,clc_build!G76>=0.75),TXT_build!D3,\nclc_build!G68>0,TXT_build!D4,\nclc_build!G78>=1,TXT_build!D5)",
  "A4":  /* unknown */ "Anzahl betroffene Räume HK-Tausch",
  "B4":  /* unknown */ "G3",
  "D4":  /* unknown */ "TXT_NO_build_G3_change",
  "H4":  /* formula */ "IF(clc_build!G76=1,\"Alle \",TEXT(clc_build!$G$66,\"0\")&\" von \"&TEXT(clc_build!$G$49,\"0\")&\" der \")",
  "A5":  /* unknown */ "Heizkörpertausch",
  "B5":  /* unknown */ "G3",
  "D5":  /* unknown */ "TXT_build_G3",
  "G5":  /* unknown */ "G3",
  "H5":  /* formula */ "_xlfn.IFS(\nOR(clc_build!$G$73>=0.5,AND(clc_build!$G$74>=0.75,clc_build!$G$71>=1)),TXT_build!$D$15&H4&TXT_build!$D$16,\nclc_build!$G$74>=0.25,TXT_build!$D$17,\nOR(clc_build!$G$74<0.25,clc_build!$G$68>=1),TXT_build!$D$18,\nclc_build!$G$78>1,TXT_build!$D$19,\nTRUE,\"FEHLER - keine eindeutige Bewertung der Heizkörper möglich\")",
  "A6":  /* unknown */ "summiert Transmissionswärmeverluste",
  "B6":  /* unknown */ "G4",
  "H6":  /* formula */ "SUM(clc_build!G3:AA3)",
  "A7":  /* unknown */ "Bauteil max. Heizlast",
  "B7":  /* unknown */ "G4",
  "H7":  /* formula */ " MAX(SUM(clc_build!$G$12:$AA$12), SUM(clc_build!$G$16:$AA$16),SUM(clc_build!$G$20:$AA$20), SUM(clc_build!$G$24:$AA$24), SUM(clc_build!$G$28:$AA$28), SUM(clc_build!$G$32:$AA$32))",
  "A8":  /* unknown */ "Bauteil 2. größte Heizlast",
  "H8":  /* formula */ "LARGE(CHOOSE({1,2,3,4,5,6},\nSUM(clc_build!$G$12:$AA$12),\nSUM(clc_build!$G$16:$AA$16),\nSUM(clc_build!$G$20:$AA$20),\nSUM(clc_build!$G$24:$AA$24),\nSUM(clc_build!$G$28:$AA$28),\nSUM(clc_build!$G$32:$AA$32)\n),2)",
  "A9":  /* unknown */ "Bauteil 3. größte Heizlast",
  "H9":  /* formula */ "LARGE(CHOOSE({1,2,3,4,5,6},\nSUM(clc_build!$G$12:$AA$12),\nSUM(clc_build!$G$16:$AA$16),\nSUM(clc_build!$G$20:$AA$20),\nSUM(clc_build!$G$24:$AA$24),\nSUM(clc_build!$G$28:$AA$28),\nSUM(clc_build!$G$32:$AA$32)\n),3)",
  "A10":  /* unknown */ "Außenwand Anteil Heizlast",
  "B10":  /* unknown */ "G4",
  "C10":  /* unknown */ "wall",
  "D10":  /* unknown */ "TXT_build_G4_wall_fill",
  "H10":  /* formula */ "IF(ROUND(SUM(clc_build!$G$12:$AA$12)/H6,1)<0.15,\"unter 10 Prozent\", TEXT(ROUND(SUM(clc_build!$G$12:$AA$12)/H6,1)*100,0)&\" Prozent\")",
  "A11":  /* unknown */ "Innenwand Anteil Heizlast",
  "B11":  /* unknown */ "G4",
  "C11":  /* unknown */ "innerwall",
  "D11":  /* unknown */ "TXT_build_G4_innerwall_fill",
  "H11":  /* formula */ "IF(ROUND(SUM(clc_build!$G$16:$AA$16)/H6,1)<0.15,\"unter 10 Prozent\", TEXT(ROUND(SUM(clc_build!$G$16:$AA$16)/H6,1)*100,0)&\" Prozent\")",
  "A12":  /* unknown */ "Fenster Anteil Heizlast",
  "B12":  /* unknown */ "G4",
  "C12":  /* unknown */ "win",
  "D12":  /* unknown */ "TXT_build_G4_win_fill",
  "H12":  /* formula */ "IF(ROUND(SUM(clc_build!$G$20:$AA$20)/H6,1)<0.15,\"unter 10 Prozent\", TEXT(ROUND(SUM(clc_build!$G$20:$AA$20)/H6,1)*100,0)&\" Prozent\")",
  "A13":  /* unknown */ "Dach Anteil Heizlast",
  "B13":  /* unknown */ "G4",
  "C13":  /* unknown */ "roof",
  "D13":  /* unknown */ "TXT_build_G4_roof_fill",
  "H13":  /* formula */ "IF(ROUND(SUM(clc_build!$G$24:$AA$24)/H6,1)<0.15,\"unter 10 Prozent\", TEXT(ROUND(SUM(clc_build!$G$24:$AA$24)/H6,1)*100,0)&\" Prozent\")",
  "A14":  /* unknown */ "Fußboden Anteil Heizlast",
  "B14":  /* unknown */ "G4",
  "C14":  /* unknown */ "botceil",
  "D14":  /* unknown */ "TXT_build_G4_botceil_fill",
  "H14":  /* formula */ "IF(ROUND(SUM(clc_build!$G$28:$AA$28)/H6,1)<0.15,\"unter 10 Prozent\", TEXT(ROUND(SUM(clc_build!$G$28:$AA$28)/H6,1)*100,0)&\" Prozent\")",
  "A15":  /* unknown */ "Decke Anteil Heizlast",
  "B15":  /* unknown */ "G4",
  "C15":  /* unknown */ "topceil",
  "D15":  /* unknown */ "TXT_build_G4_topceil_fill",
  "H15":  /* formula */ "IF(ROUND(SUM(clc_build!$G$32:$AA$32)/H6,1)<0.15,\"unter 10 Prozent\", TEXT(ROUND(SUM(clc_build!$G$32:$AA$32)/H6,1)*100,0)&\" Prozent\")",
  "A16":  /* unknown */ "Wärmeschutz intro",
  "B16":  /* unknown */ "G4",
  "D16":  /* unknown */ "TXT_build_G4_intro_fill",
  "H16":  /* formula */ "_xlfn.LET(\n  _xlpm.Bauteil1, _xlfn.IFS(\n    SUM(clc_build!$G$12:$AA$12)=H7, \"Außenwand\",\n    SUM(clc_build!$G$20:$AA$20)=H7, \"Fenster\",\n    SUM(clc_build!$G$24:$AA$24)=H7, \"Dach\",\n    SUM(clc_build!$G$28:$AA$28)=H7, \"Fußboden\",\n    SUM(clc_build!$G$32:$AA$32)=H7, \"Decke\"\n  ),\n  _xlpm.Bauteil2, _xlfn.IFS(\n    SUM(clc_build!$G$12:$AA$12)=H8, \"Außenwand\",\n    SUM(clc_build!$G$20:$AA$20)=H8, \"Fenster\",\n    SUM(clc_build!$G$24:$AA$24)=H8, \"Dach\",\n    SUM(clc_build!$G$28:$AA$28)=H8, \"Fußboden\",\n    SUM(clc_build!$G$32:$AA$32)=H8, \"Decke\"\n  ),\n  _xlpm.Bauteil3, _xlfn.IFS(\n    SUM(clc_build!$G$12:$AA$12)=H9, \"Außenwand\",\n    SUM(clc_build!$G$20:$AA$20)=H9, \"Fenster\",\n    SUM(clc_build!$G$24:$AA$24)=H9, \"Dach\",\n    SUM(clc_build!$G$28:$AA$28)=H9, \"Fußboden\",\n    SUM(clc_build!$G$32:$AA$32)=H9, \"Decke\"\n  ),\n  _xlpm.GedA, INDEX(IN_build!Q7:Q11, MATCH(_xlpm.Bauteil1, IN_build!E7:E11, 0)),\n  _xlpm.GedB, INDEX(IN_build!Q7:Q11, MATCH(_xlpm.Bauteil2, IN_build!E7:E11, 0)),\n  _xlpm.GedC, INDEX(IN_build!Q7:Q11, MATCH(_xlpm.Bauteil3, IN_build!E7:E11, 0)),\n\n  _xlpm.output, IF(_xlpm.GedA<>\"Ja\", _xlpm.Bauteil1,IF(_xlpm.GedB<>\"Ja\", _xlpm.Bauteil2,IF(_xlpm.GedC<>\"Ja\", _xlpm.Bauteil3, \"\"))),\n\n  _xlfn.IFS(\n  _xlpm.output=\"Außenwand\", \" hat die Außenwand.\",\n  _xlpm.output=\"Innenwand\", \" hat die Innenwand.\",\n  _xlpm.output=\"Fenster\", \" haben die Fenster.\",\n  _xlpm.output=\"Dach\", \" hat das Dach.\",\n  _xlpm.output=\"Fußboden\", \" hat der Fußboden.\",\n  _xlpm.output=\"Decke\", \" hat die Decke.\"\n))",
  "A17":  /* unknown */ "Mittlerer U-Wert Außenwand",
  "B17":  /* unknown */ "G4",
  "C17":  /* unknown */ "wall",
  "H17":  /* formula */ "AVERAGE(clc_build!G11:'clc_build'!AA11)",
  "A18":  /* unknown */ "Mittlerer U-Wert Fenster",
  "B18":  /* unknown */ "G4",
  "C18":  /* unknown */ "win",
  "H18":  /* formula */ "AVERAGE(clc_build!G19:'clc_build'!AA19)",
  "A19":  /* unknown */ "Mittelwert U-Wert Dach",
  "B19":  /* unknown */ "G4",
  "C19":  /* unknown */ "roof",
  "H19":  /* formula */ "AVERAGE(clc_build!G23:'clc_build'!AA23)",
  "A20":  /* unknown */ "Mittelwert U-Wert Fußboden",
  "B20":  /* unknown */ "G4",
  "C20":  /* unknown */ "botceil",
  "H20":  /* formula */ "AVERAGE(clc_build!G27:'clc_build'!AA27)",
  "A21":  /* unknown */ "Mittelwert U-Wert Decke",
  "B21":  /* unknown */ "G4",
  "C21":  /* unknown */ "topceil",
  "H21":  /* formula */ "AVERAGE(clc_build!G31:'clc_build'!AA31)",
  "A22":  /* unknown */ "Bildunterschrift - Außenwand Anteil Heizlast",
  "B22":  /* unknown */ "G4",
  "C22":  /* unknown */ "wall",
  "D22":  /* unknown */ "TXT_pic_build_G4_wall",
  "H22":  /* formula */ "IF(ROUND(SUM(clc_build!$G$12:$AA$12)/H6,1)<0.15,\"< 10 % der Verluste\", TEXT(ROUND(SUM(clc_build!$G$12:$AA$12)/H6,1)*100,0)&\" % der Verluste\")",
  "A23":  /* unknown */ "Bildunterschrift - Fenster Anteil Heizlast",
  "B23":  /* unknown */ "G4",
  "C23":  /* unknown */ "win",
  "D23":  /* unknown */ "TXT_pic_build_G4_win",
  "H23":  /* formula */ "IF(ROUND(SUM(clc_build!$G$20:$AA$20)/H6,1)<0.15,\"< 10 % der Verluste\", TEXT(ROUND(SUM(clc_build!$G$20:$AA$20)/H6,1)*100,0)&\" % der Verluste\")",
  "A24":  /* unknown */ "Bildunterschrift - Dach Anteil Heizlast",
  "B24":  /* unknown */ "G4",
  "C24":  /* unknown */ "roof",
  "D24":  /* unknown */ "TXT_pic_build_G4_roof",
  "H24":  /* formula */ "IF(ROUND(SUM(clc_build!$G$24:$AA$24)/H6,1)<0.15,\"< 10 % der Verluste\", TEXT(ROUND(SUM(clc_build!$G$24:$AA$24)/H6,1)*100,0)&\" % der Verluste\")",
  "A25":  /* unknown */ "Bildunterschrift - Fußboden / Decke Anteil Heizlast",
  "B25":  /* unknown */ "G4",
  "C25":  /* unknown */ "ceil",
  "D25":  /* unknown */ "TXT_pic_build_G4_ceil",
  "H25":  /* formula */ "IF(ROUND((SUM(clc_build!$G$28:$AA$28)+SUM(clc_build!$G$32:$AA$32))/H6,1)<0.15,\"< 10 % der Verluste\", TEXT(ROUND((SUM(clc_build!$G$28:$AA$28)+SUM(clc_build!$G$32:$AA$32))/H6,1)*100,0)&\" % der Verluste\")",
  "A26":  /* unknown */ "Bewertung Hülle gesamt",
  "D26":  /* unknown */ "color_G4_intro",
  "H26":  /* formula */ "_xlfn.IFS(clc_build!G88>=0.75,\"red\",\nOR(clc_build!G88>=0.5,clc_build!G87>=0.75),\"orange\",\nOR(clc_build!G88>0,(clc_build!G87+clc_build!G88)>=0.25,clc_build!G83<0.5),\"yellow\",\nTRUE,\"green\")",
  "A27":  /* unknown */ "Bewertung Außenwand",
  "C27":  /* unknown */ "wall",
  "D27":  /* unknown */ "color_pic_G4_wall",
  "H27":  /* formula */ "_xlfn.IFS(H17>0.8,\"red\",\nH17>0.5,\"orange\",\nH17>0.35,\"yellow\",\nH17<=0.35,\"green\")",
  "A28":  /* unknown */ "Bewertung Fenster",
  "C28":  /* unknown */ "win",
  "D28":  /* unknown */ "color_pic_G4_win",
  "H28":  /* formula */ "_xlfn.LET(\n_xlpm.r_win_27, COUNTIF(clc_build!G19:AA19,\">2,7\")/clc_build!$G$49,\n_xlpm.r_win_21, COUNTIF(clc_build!G19:AA19,\">2,1\")/clc_build!$G$49,\n_xlpm.r_win_17,COUNTIF(clc_build!G19:AA19,\">1,3\")/clc_build!$G$49,\n_xlpm.r_win_13,COUNTIF(clc_build!G19:AA19,\"<=1,3\")/clc_build!$G$49,\n_xlfn.IFS(\n_xlpm.r_win_27>=0.5,\"red\",\nOR(_xlpm.r_win_27>=0.25,_xlpm.r_win_21>=0.5),\"orange\",\nOR(_xlpm.r_win_21>=0.1,_xlpm.r_win_17>=0.5),\"yellow\",\nTRUE,\"green\"))",
  "A29":  /* unknown */ "Bewertung Dach",
  "C29":  /* unknown */ "roof",
  "D29":  /* unknown */ "color_pic_G4_roof",
  "H29":  /* formula */ "_xlfn.IFS(H19>0.8,\"red\",\nH19>0.5,\"orange\",\nH19>0.3,\"yellow\",\nH19<=0.3,\"green\")",
  "A30":  /* unknown */ "Bewertung Fußboden ",
  "C30":  /* unknown */ "botceil",
  "D30":  /* unknown */ "color_pic_G4_botceil",
  "H30":  /* formula */ "_xlfn.IFS(AND(H20>0.8,NOT(LEFT(H14,1)=\"u\")),\"red\",\nAND(H20>0.5,NOT(LEFT(H14,1)=\"u\")),\"orange\",\nH20>0.4,\"yellow\",\nH20<=0.4,\"green\")",
  "A31":  /* unknown */ "Bewertung Decke",
  "C31":  /* unknown */ "topceil",
  "D31":  /* unknown */ "color_pic_G4_topceil",
  "H31":  /* formula */ "_xlfn.IFS(AND(H21>0.8,NOT(LEFT(H15,1)=\"u\")),\"red\",\nAND(H21>0.5,NOT(LEFT(H15,1)=\"u\")),\"orange\",\nH21>0.3,\"yellow\",\nH21<=0.3,\"green\")",
  "A32":  /* unknown */ "Bewertung obere Geschossdecke und Fußboden",
  "C32":  /* unknown */ "ceil",
  "D32":  /* unknown */ "color_pic_G4_ceil",
  "H32":  /* formula */ "_xlfn.IFS(AND(H30=\"red\",H31=\"red\"),\"red\",\nOR(H30=\"red\",H31=\"red\",H30=\"orange\",H31=\"orange\"),\"orange\",\nOR(H30=\"yellow\",H31=\"yellow\"),\"yellow\",\nTRUE,\"green\")",
  "A33":  /* unknown */ "Wärmeschutz intro",
  "B33":  /* unknown */ "G4",
  "D33":  /* unknown */ "TXT_build_G4_intro",
  "G33":  /* unknown */ "G4",
  "H33":  /* formula */ "_xlfn.IFS(H26=\"red\",TXT_build!D20&H16,\nH26=\"orange\",TXT_build!D22&H16,\nH26=\"yellow\",TXT_build!D24&H16,\nTRUE,TXT_build!D26)",
  "A34":  /* unknown */ "Wärmeschutz Außenwand",
  "B34":  /* unknown */ "G4",
  "C34":  /* unknown */ "wall",
  "D34":  /* unknown */ "TXT_build_G4_wall",
  "G34":  /* unknown */ "G4",
  "H34":  /* formula */ "_xlfn.IFS(H27=\"red\",TXT_build!D28&H10&TXT_build!D29,\nH27=\"orange\",TXT_build!D30&H10&TXT_build!D31,\nH27=\"yellow\",TXT_build!D32&H10&TXT_build!D33,\nH27=\"green\",TXT_build!D34)",
  "A35":  /* unknown */ "Wärmeschutz Fenster",
  "B35":  /* unknown */ "G4",
  "C35":  /* unknown */ "win",
  "D35":  /* unknown */ "TXT_build_G4_win",
  "G35":  /* unknown */ "G4",
  "H35":  /* formula */ "_xlfn.IFS(H28=\"red\",TXT_build!D35&H12&TXT_build!D36,\nH28=\"orange\",TXT_build!D37&H12&TXT_build!D38,\nH28=\"yellow\",TXT_build!D39,\nTRUE,TXT_build!D40)",
  "A36":  /* unknown */ "Wärmeschutz Dach",
  "B36":  /* unknown */ "G4",
  "C36":  /* unknown */ "roof",
  "D36":  /* unknown */ "TXT_build_G4_roof",
  "G36":  /* unknown */ "G4",
  "H36":  /* formula */ "_xlfn.IFS(H29=\"red\",TXT_build!D41&H13&TXT_build!D42,\nH29=\"orange\",TXT_build!D43&H13&TXT_build!D44,\nH29=\"yellow\",TXT_build!D45,\nH29=\"green\",TXT_build!D46)",
  "A37":  /* unknown */ "Wärmeschutz Fußboden ",
  "B37":  /* unknown */ "G4",
  "C37":  /* unknown */ "botceil",
  "D37":  /* unknown */ "TXT_build_G4_botceil",
  "G37":  /* unknown */ "G4",
  "H37":  /* formula */ "_xlfn.IFS(H30=\"red\",TXT_build!D51&H14&TXT_build!D52,\nH30=\"orange\",TXT_build!D53&H14&TXT_build!D54,\nH30=\"yellow\",TXT_build!D55,\nH30=\"green\",TXT_build!D56)",
  "A38":  /* unknown */ "Wärmeschutz obere Geschossdecke",
  "B38":  /* unknown */ "G4",
  "C38":  /* unknown */ "topceil",
  "D38":  /* unknown */ "TXT_build_G4_topceil",
  "G38":  /* unknown */ "G4",
  "H38":  /* formula */ "_xlfn.IFS(H31=\"red\",TXT_build!D57&H15&TXT_build!D58,\nH31=\"orange\",TXT_build!D59&H15&TXT_build!D60,\nH31=\"yellow\",TXT_build!D61,\nH31=\"green\",TXT_build!D62)",
  "A39":  /* unknown */ "Wärmeschutz horizontaler Gebäudeabschluss",
  "B39":  /* unknown */ "G4",
  "C39":  /* unknown */ "ceil",
  "D39":  /* unknown */ "TXT_build_G4_ceil",
  "G39":  /* unknown */ "G4",
  "H39":  /* formula */ "_xlfn.IFS(H32=\"red\",TXT_build!D47,\nH32=\"orange\",TXT_build!D48,\nH32=\"yellow\",TXT_build!D49,\nTRUE,TXT_build!D50) & H38 & H37",
  "A40":  /* unknown */ "Hinweis ergänzung weitere Räume ",
  "B40":  /* unknown */ "G4",
  "D40":  /* unknown */ "TXT_build_G4_notation",
  "H40":  /* unknown */ "💡 Hinweis: Für eine genauere Bewertung können weitere Räume ergänzt oder im Planungsprozess detailliert betrachtet werden.",
} as const;
