// Sheet: OUT_rooms
export const data = {
  "A1":  /* unknown */ "Bezeichnung",
  "B1":  /* unknown */ "Gruppe",
  "C1":  /* unknown */ "Subgruppe",
  "D1":  /* unknown */ "Variable ",
  "E1":  /* unknown */ "Einheit",
  "F1":  /* unknown */ "Kommentar",
  "G1":  /* unknown */ "Position Mockup",
  "H1":  /* unknown */ "Werte Raum",
  "I1":  /* unknown */ "Werte Raum",
  "J1":  /* unknown */ "Werte Raum",
  "K1":  /* unknown */ "Werte Raum",
  "L1":  /* unknown */ "Werte Raum",
  "M1":  /* unknown */ "Werte Raum",
  "A2":  /* unknown */ "Raumindex",
  "D2":  /* unknown */ "ID_R#",
  "H2":  /* unknown */ 1,
  "I2":  /* unknown */ 2,
  "J2":  /* unknown */ 3,
  "K2":  /* unknown */ 4,
  "L2":  /* unknown */ 5,
  "M2":  /* unknown */ 6,
  "N2":  /* unknown */ 7,
  "O2":  /* unknown */ 8,
  "P2":  /* unknown */ 9,
  "Q2":  /* unknown */ 10,
  "R2":  /* unknown */ 11,
  "S2":  /* unknown */ 12,
  "T2":  /* unknown */ 13,
  "U2":  /* unknown */ 14,
  "V2":  /* unknown */ 15,
  "A3":  /* unknown */ "Ausgabe zur Wärmepumpeneignung",
  "B3":  /* unknown */ "room",
  "D3":  /* unknown */ "TXT_room_R1",
  "G3":  /* unknown */ "R1",
  "H3":  /* formula */ "_xlfn.IFS(\n1<=clc_build!G$39,TXT_rooms!$E$5,\nAND(1>clc_build!G$39,clc_build!G$39>=0.8),TXT_rooms!$E$4,\nOR(AND(0.8>clc_build!G$39,clc_build!G$39>=0.6),clc_build!G$38>clc_build!G$7),TXT_rooms!$E$3,\nAND(clc_build!G$39<0.6,clc_build!G$38<clc_build!G$7),TXT_rooms!$E$2\n)",
  "I3":  /* formula */ "_xlfn.IFS(\n1<=clc_build!H$39,TXT_rooms!$E$5,\nAND(1>clc_build!H$39,clc_build!H$39>=0.8),TXT_rooms!$E$4,\nOR(AND(0.8>clc_build!H$39,clc_build!H$39>=0.6),clc_build!H$38>clc_build!H$5),TXT_rooms!$E$3,\nAND(clc_build!H$39<0.6,clc_build!H$38<clc_build!H$5),TXT_rooms!$E$2\n)",
  "J3":  /* formula */ "_xlfn.IFS(\n1<=clc_build!I$39,TXT_rooms!$E$5,\nAND(1>clc_build!I$39,clc_build!I$39>=0.8),TXT_rooms!$E$4,\nOR(AND(0.8>clc_build!I$39,clc_build!I$39>=0.6),clc_build!I$38>clc_build!I$5),TXT_rooms!$E$3,\nAND(clc_build!I$39<0.6,clc_build!I$38<clc_build!I$5),TXT_rooms!$E$2\n)",
  "K3":  /* formula */ "_xlfn.IFS(\n1<=clc_build!J$39,TXT_rooms!$E$5,\nAND(1>clc_build!J$39,clc_build!J$39>=0.8),TXT_rooms!$E$4,\nOR(AND(0.8>clc_build!J$39,clc_build!J$39>=0.6),clc_build!J$38>clc_build!J$5),TXT_rooms!$E$3,\nAND(clc_build!J$39<0.6,clc_build!J$38<clc_build!J$5),TXT_rooms!$E$2\n)",
  "L3":  /* formula */ "_xlfn.IFS(\n1<=clc_build!K$39,TXT_rooms!$E$5,\nAND(1>clc_build!K$39,clc_build!K$39>=0.8),TXT_rooms!$E$4,\nOR(AND(0.8>clc_build!K$39,clc_build!K$39>=0.6),clc_build!K$38>clc_build!K$5),TXT_rooms!$E$3,\nAND(clc_build!K$39<0.6,clc_build!K$38<clc_build!K$5),TXT_rooms!$E$2\n)",
  "M3":  /* formula */ "_xlfn.IFS(\n1<=clc_build!L$39,TXT_rooms!$E$5,\nAND(1>clc_build!L$39,clc_build!L$39>=0.8),TXT_rooms!$E$4,\nOR(AND(0.8>clc_build!L$39,clc_build!L$39>=0.6),clc_build!L$38>clc_build!L$5),TXT_rooms!$E$3,\nAND(clc_build!L$39<0.6,clc_build!L$38<clc_build!L$5),TXT_rooms!$E$2\n)",
  "N3":  /* formula */ "_xlfn.IFS(\n1<=clc_build!M$39,TXT_rooms!$E$5,\nAND(1>clc_build!M$39,clc_build!M$39>=0.8),TXT_rooms!$E$4,\nOR(AND(0.8>clc_build!M$39,clc_build!M$39>=0.6),clc_build!M$38>clc_build!M$5),TXT_rooms!$E$3,\nAND(clc_build!M$39<0.6,clc_build!M$38<clc_build!M$5),TXT_rooms!$E$2\n)",
  "O3":  /* formula */ "_xlfn.IFS(\n1<=clc_build!N$39,TXT_rooms!$E$5,\nAND(1>clc_build!N$39,clc_build!N$39>=0.8),TXT_rooms!$E$4,\nOR(AND(0.8>clc_build!N$39,clc_build!N$39>=0.6),clc_build!N$38>clc_build!N$5),TXT_rooms!$E$3,\nAND(clc_build!N$39<0.6,clc_build!N$38<clc_build!N$5),TXT_rooms!$E$2\n)",
  "P3":  /* formula */ "_xlfn.IFS(\n1<=clc_build!O$39,TXT_rooms!$E$5,\nAND(1>clc_build!O$39,clc_build!O$39>=0.8),TXT_rooms!$E$4,\nOR(AND(0.8>clc_build!O$39,clc_build!O$39>=0.6),clc_build!O$38>clc_build!O$5),TXT_rooms!$E$3,\nAND(clc_build!O$39<0.6,clc_build!O$38<clc_build!O$5),TXT_rooms!$E$2\n)",
  "Q3":  /* formula */ "_xlfn.IFS(\n1<=clc_build!P$39,TXT_rooms!$E$5,\nAND(1>clc_build!P$39,clc_build!P$39>=0.8),TXT_rooms!$E$4,\nOR(AND(0.8>clc_build!P$39,clc_build!P$39>=0.6),clc_build!P$38>clc_build!P$5),TXT_rooms!$E$3,\nAND(clc_build!P$39<0.6,clc_build!P$38<clc_build!P$5),TXT_rooms!$E$2\n)",
  "R3":  /* formula */ "_xlfn.IFS(\n1<=clc_build!Q$39,TXT_rooms!$E$5,\nAND(1>clc_build!Q$39,clc_build!Q$39>=0.8),TXT_rooms!$E$4,\nOR(AND(0.8>clc_build!Q$39,clc_build!Q$39>=0.6),clc_build!Q$38>clc_build!Q$5),TXT_rooms!$E$3,\nAND(clc_build!Q$39<0.6,clc_build!Q$38<clc_build!Q$5),TXT_rooms!$E$2\n)",
  "S3":  /* formula */ "_xlfn.IFS(\n1<=clc_build!R$39,TXT_rooms!$E$5,\nAND(1>clc_build!R$39,clc_build!R$39>=0.8),TXT_rooms!$E$4,\nOR(AND(0.8>clc_build!R$39,clc_build!R$39>=0.6),clc_build!R$38>clc_build!R$5),TXT_rooms!$E$3,\nAND(clc_build!R$39<0.6,clc_build!R$38<clc_build!R$5),TXT_rooms!$E$2\n)",
  "T3":  /* formula */ "_xlfn.IFS(\n1<=clc_build!S$39,TXT_rooms!$E$5,\nAND(1>clc_build!S$39,clc_build!S$39>=0.8),TXT_rooms!$E$4,\nOR(AND(0.8>clc_build!S$39,clc_build!S$39>=0.6),clc_build!S$38>clc_build!S$5),TXT_rooms!$E$3,\nAND(clc_build!S$39<0.6,clc_build!S$38<clc_build!S$5),TXT_rooms!$E$2\n)",
  "U3":  /* formula */ "_xlfn.IFS(\n1<=clc_build!T$39,TXT_rooms!$E$5,\nAND(1>clc_build!T$39,clc_build!T$39>=0.8),TXT_rooms!$E$4,\nOR(AND(0.8>clc_build!T$39,clc_build!T$39>=0.6),clc_build!T$38>clc_build!T$5),TXT_rooms!$E$3,\nAND(clc_build!T$39<0.6,clc_build!T$38<clc_build!T$5),TXT_rooms!$E$2\n)",
  "V3":  /* formula */ "_xlfn.IFS(\n1<=clc_build!U$39,TXT_rooms!$E$5,\nAND(1>clc_build!U$39,clc_build!U$39>=0.8),TXT_rooms!$E$4,\nOR(AND(0.8>clc_build!U$39,clc_build!U$39>=0.6),clc_build!U$38>clc_build!U$5),TXT_rooms!$E$3,\nAND(clc_build!U$39<0.6,clc_build!U$38<clc_build!U$5),TXT_rooms!$E$2\n)",
  "A4":  /* unknown */ "Lückentext Bauteilbewertung Raumebene 1",
  "B4":  /* unknown */ "room",
  "D4":  /* unknown */ "TXT_room_R2_fill_1",
  "G4":  /* unknown */ "R2",
  "H4":  /* formula */ "_xlfn.LET(_xlpm.max_HT_share,MAX(clc_build!G$13,clc_build!G$17,clc_build!G$21,clc_build!G$25,clc_build!G$29,clc_build!G$33),\n_xlfn.IFS(clc_load!I$18=_xlpm.max_HT_share,\" Außenwand \",\nclc_load!I$23=_xlpm.max_HT_share,\" Innenwand \",\nclc_load!I$30=_xlpm.max_HT_share,\" Dachfläche \",\nclc_load!I$36=_xlpm.max_HT_share,\" Decke \",\nclc_load!I$41=_xlpm.max_HT_share,\" Fußbodenfläche \",\nclc_build!G$21,\" Fenster \"\n))",
  "I4":  /* formula */ "_xlfn.LET(_xlpm.max_HT_share,MAX(clc_build!H$13,clc_build!H$17,clc_build!H$21,clc_build!H$25,clc_build!H$29,clc_build!H$33),\n_xlfn.IFS(clc_load!J$18=_xlpm.max_HT_share,\" Außenwand \",\nclc_load!J$23=_xlpm.max_HT_share,\" Innenwand \",\nclc_load!J$30=_xlpm.max_HT_share,\" Dachfläche \",\nclc_load!J$36=_xlpm.max_HT_share,\" Decke \",\nclc_load!J$41=_xlpm.max_HT_share,\" Fußbodenfläche \",\nclc_build!H$21,\" Fenster \"\n))",
  "J4":  /* formula */ "_xlfn.LET(_xlpm.max_HT_share,MAX(clc_build!I$13,clc_build!I$17,clc_build!I$21,clc_build!I$25,clc_build!I$29,clc_build!I$33),\n_xlfn.IFS(clc_load!K$18=_xlpm.max_HT_share,\" Außenwand \",\nclc_load!K$23=_xlpm.max_HT_share,\" Innenwand \",\nclc_load!K$30=_xlpm.max_HT_share,\" Dachfläche \",\nclc_load!K$36=_xlpm.max_HT_share,\" Decke \",\nclc_load!K$41=_xlpm.max_HT_share,\" Fußbodenfläche \",\nclc_build!I$21,\" Fenster \"\n))",
  "K4":  /* formula */ "_xlfn.LET(_xlpm.max_HT_share,MAX(clc_build!J$13,clc_build!J$17,clc_build!J$21,clc_build!J$25,clc_build!J$29,clc_build!J$33),\n_xlfn.IFS(clc_load!L$18=_xlpm.max_HT_share,\" Außenwand \",\nclc_load!L$23=_xlpm.max_HT_share,\" Innenwand \",\nclc_load!L$30=_xlpm.max_HT_share,\" Dachfläche \",\nclc_load!L$36=_xlpm.max_HT_share,\" Decke \",\nclc_load!L$41=_xlpm.max_HT_share,\" Fußbodenfläche \",\nclc_build!J$21,\" Fenster \"\n))",
  "L4":  /* formula */ "_xlfn.LET(_xlpm.max_HT_share,MAX(clc_build!K$13,clc_build!K$17,clc_build!K$21,clc_build!K$25,clc_build!K$29,clc_build!K$33),\n_xlfn.IFS(clc_load!M$18=_xlpm.max_HT_share,\" Außenwand \",\nclc_load!M$23=_xlpm.max_HT_share,\" Innenwand \",\nclc_load!M$30=_xlpm.max_HT_share,\" Dachfläche \",\nclc_load!M$36=_xlpm.max_HT_share,\" Decke \",\nclc_load!M$41=_xlpm.max_HT_share,\" Fußbodenfläche \",\nclc_build!K$21,\" Fenster \"\n))",
  "M4":  /* formula */ "_xlfn.LET(_xlpm.max_HT_share,MAX(clc_build!L$13,clc_build!L$17,clc_build!L$21,clc_build!L$25,clc_build!L$29,clc_build!L$33),\n_xlfn.IFS(clc_load!N$18=_xlpm.max_HT_share,\" Außenwand \",\nclc_load!N$23=_xlpm.max_HT_share,\" Innenwand \",\nclc_load!N$30=_xlpm.max_HT_share,\" Dachfläche \",\nclc_load!N$36=_xlpm.max_HT_share,\" Decke \",\nclc_load!N$41=_xlpm.max_HT_share,\" Fußbodenfläche \",\nclc_build!L$21,\" Fenster \"\n))",
  "N4":  /* formula */ "_xlfn.LET(_xlpm.max_HT_share,MAX(clc_build!M$13,clc_build!M$17,clc_build!M$21,clc_build!M$25,clc_build!M$29,clc_build!M$33),\n_xlfn.IFS(clc_load!O$18=_xlpm.max_HT_share,\" Außenwand \",\nclc_load!O$23=_xlpm.max_HT_share,\" Innenwand \",\nclc_load!O$30=_xlpm.max_HT_share,\" Dachfläche \",\nclc_load!O$36=_xlpm.max_HT_share,\" Decke \",\nclc_load!O$41=_xlpm.max_HT_share,\" Fußbodenfläche \",\nclc_build!M$21,\" Fenster \"\n))",
  "O4":  /* formula */ "_xlfn.LET(_xlpm.max_HT_share,MAX(clc_build!N$13,clc_build!N$17,clc_build!N$21,clc_build!N$25,clc_build!N$29,clc_build!N$33),\n_xlfn.IFS(clc_load!P$18=_xlpm.max_HT_share,\" Außenwand \",\nclc_load!P$23=_xlpm.max_HT_share,\" Innenwand \",\nclc_load!P$30=_xlpm.max_HT_share,\" Dachfläche \",\nclc_load!P$36=_xlpm.max_HT_share,\" Decke \",\nclc_load!P$41=_xlpm.max_HT_share,\" Fußbodenfläche \",\nclc_build!N$21,\" Fenster \"\n))",
  "P4":  /* formula */ "_xlfn.LET(_xlpm.max_HT_share,MAX(clc_build!O$13,clc_build!O$17,clc_build!O$21,clc_build!O$25,clc_build!O$29,clc_build!O$33),\n_xlfn.IFS(clc_load!Q$18=_xlpm.max_HT_share,\" Außenwand \",\nclc_load!Q$23=_xlpm.max_HT_share,\" Innenwand \",\nclc_load!Q$30=_xlpm.max_HT_share,\" Dachfläche \",\nclc_load!Q$36=_xlpm.max_HT_share,\" Decke \",\nclc_load!Q$41=_xlpm.max_HT_share,\" Fußbodenfläche \",\nclc_build!O$21,\" Fenster \"\n))",
  "Q4":  /* formula */ "_xlfn.LET(_xlpm.max_HT_share,MAX(clc_build!P$13,clc_build!P$17,clc_build!P$21,clc_build!P$25,clc_build!P$29,clc_build!P$33),\n_xlfn.IFS(clc_load!R$18=_xlpm.max_HT_share,\" Außenwand \",\nclc_load!R$23=_xlpm.max_HT_share,\" Innenwand \",\nclc_load!R$30=_xlpm.max_HT_share,\" Dachfläche \",\nclc_load!R$36=_xlpm.max_HT_share,\" Decke \",\nclc_load!R$41=_xlpm.max_HT_share,\" Fußbodenfläche \",\nclc_build!P$21,\" Fenster \"\n))",
  "R4":  /* formula */ "_xlfn.LET(_xlpm.max_HT_share,MAX(clc_build!Q$13,clc_build!Q$17,clc_build!Q$21,clc_build!Q$25,clc_build!Q$29,clc_build!Q$33),\n_xlfn.IFS(clc_load!S$18=_xlpm.max_HT_share,\" Außenwand \",\nclc_load!S$23=_xlpm.max_HT_share,\" Innenwand \",\nclc_load!S$30=_xlpm.max_HT_share,\" Dachfläche \",\nclc_load!S$36=_xlpm.max_HT_share,\" Decke \",\nclc_load!S$41=_xlpm.max_HT_share,\" Fußbodenfläche \",\nclc_build!Q$21,\" Fenster \"\n))",
  "S4":  /* formula */ "_xlfn.LET(_xlpm.max_HT_share,MAX(clc_build!R$13,clc_build!R$17,clc_build!R$21,clc_build!R$25,clc_build!R$29,clc_build!R$33),\n_xlfn.IFS(clc_load!T$18=_xlpm.max_HT_share,\" Außenwand \",\nclc_load!T$23=_xlpm.max_HT_share,\" Innenwand \",\nclc_load!T$30=_xlpm.max_HT_share,\" Dachfläche \",\nclc_load!T$36=_xlpm.max_HT_share,\" Decke \",\nclc_load!T$41=_xlpm.max_HT_share,\" Fußbodenfläche \",\nclc_build!R$21,\" Fenster \"\n))",
  "T4":  /* formula */ "_xlfn.LET(_xlpm.max_HT_share,MAX(clc_build!S$13,clc_build!S$17,clc_build!S$21,clc_build!S$25,clc_build!S$29,clc_build!S$33),\n_xlfn.IFS(clc_load!U$18=_xlpm.max_HT_share,\" Außenwand \",\nclc_load!U$23=_xlpm.max_HT_share,\" Innenwand \",\nclc_load!U$30=_xlpm.max_HT_share,\" Dachfläche \",\nclc_load!U$36=_xlpm.max_HT_share,\" Decke \",\nclc_load!U$41=_xlpm.max_HT_share,\" Fußbodenfläche \",\nclc_build!S$21,\" Fenster \"\n))",
  "U4":  /* formula */ "_xlfn.LET(_xlpm.max_HT_share,MAX(clc_build!T$13,clc_build!T$17,clc_build!T$21,clc_build!T$25,clc_build!T$29,clc_build!T$33),\n_xlfn.IFS(clc_load!V$18=_xlpm.max_HT_share,\" Außenwand \",\nclc_load!V$23=_xlpm.max_HT_share,\" Innenwand \",\nclc_load!V$30=_xlpm.max_HT_share,\" Dachfläche \",\nclc_load!V$36=_xlpm.max_HT_share,\" Decke \",\nclc_load!V$41=_xlpm.max_HT_share,\" Fußbodenfläche \",\nclc_build!T$21,\" Fenster \"\n))",
  "V4":  /* formula */ "_xlfn.LET(_xlpm.max_HT_share,MAX(clc_build!U$13,clc_build!U$17,clc_build!U$21,clc_build!U$25,clc_build!U$29,clc_build!U$33),\n_xlfn.IFS(clc_load!W$18=_xlpm.max_HT_share,\" Außenwand \",\nclc_load!W$23=_xlpm.max_HT_share,\" Innenwand \",\nclc_load!W$30=_xlpm.max_HT_share,\" Dachfläche \",\nclc_load!W$36=_xlpm.max_HT_share,\" Decke \",\nclc_load!W$41=_xlpm.max_HT_share,\" Fußbodenfläche \",\nclc_build!U$21,\" Fenster \"\n))",
  "A5":  /* unknown */ "Lückentext Bauteilbewertung Raumebene 2",
  "B5":  /* unknown */ "room",
  "D5":  /* unknown */ "TXT_room_R2_fill_2",
  "G5":  /* unknown */ "R2",
  "H5":  /* formula */ "_xlfn.LET(\n_xlpm.second_HT_share,LARGE((clc_build!G$13,clc_build!G$17,clc_build!G$21,clc_build!G$25,clc_build!G$29,clc_build!G$33),2),\n_xlfn.IFS(clc_load!I$18=_xlpm.second_HT_share,\" Außenwand \",\nclc_load!I$23=_xlpm.second_HT_share,\" Innenwand \",\nclc_load!I$30=_xlpm.second_HT_share,\" Dachfläche \",\nclc_load!I$36=_xlpm.second_HT_share,\" Decke \",\nclc_load!I$41=_xlpm.second_HT_share,\" Fußbodenfläche \",\nclc_build!G$21=_xlpm.second_HT_share,\" Fenster \"))",
  "I5":  /* formula */ "_xlfn.LET(\n_xlpm.second_HT_share,LARGE((clc_build!H$13,clc_build!H$17,clc_build!H$21,clc_build!H$25,clc_build!H$29,clc_build!H$33),2),\n_xlfn.IFS(clc_load!J$18=_xlpm.second_HT_share,\" Außenwand \",\nclc_load!J$23=_xlpm.second_HT_share,\" Innenwand \",\nclc_load!J$30=_xlpm.second_HT_share,\" Dachfläche \",\nclc_load!J$36=_xlpm.second_HT_share,\" Decke \",\nclc_load!J$41=_xlpm.second_HT_share,\" Fußbodenfläche \",\nclc_build!H$21=_xlpm.second_HT_share,\" Fenster \"))",
  "J5":  /* formula */ "_xlfn.LET(\n_xlpm.second_HT_share,LARGE((clc_build!I$13,clc_build!I$17,clc_build!I$21,clc_build!I$25,clc_build!I$29,clc_build!I$33),2),\n_xlfn.IFS(clc_load!K$18=_xlpm.second_HT_share,\" Außenwand \",\nclc_load!K$23=_xlpm.second_HT_share,\" Innenwand \",\nclc_load!K$30=_xlpm.second_HT_share,\" Dachfläche \",\nclc_load!K$36=_xlpm.second_HT_share,\" Decke \",\nclc_load!K$41=_xlpm.second_HT_share,\" Fußbodenfläche \",\nclc_build!I$21=_xlpm.second_HT_share,\" Fenster \"))",
  "K5":  /* formula */ "_xlfn.LET(\n_xlpm.second_HT_share,LARGE((clc_build!J$13,clc_build!J$17,clc_build!J$21,clc_build!J$25,clc_build!J$29,clc_build!J$33),2),\n_xlfn.IFS(clc_load!L$18=_xlpm.second_HT_share,\" Außenwand \",\nclc_load!L$23=_xlpm.second_HT_share,\" Innenwand \",\nclc_load!L$30=_xlpm.second_HT_share,\" Dachfläche \",\nclc_load!L$36=_xlpm.second_HT_share,\" Decke \",\nclc_load!L$41=_xlpm.second_HT_share,\" Fußbodenfläche \",\nclc_build!J$21=_xlpm.second_HT_share,\" Fenster \"))",
  "L5":  /* formula */ "_xlfn.LET(\n_xlpm.second_HT_share,LARGE((clc_build!K$13,clc_build!K$17,clc_build!K$21,clc_build!K$25,clc_build!K$29,clc_build!K$33),2),\n_xlfn.IFS(clc_load!M$18=_xlpm.second_HT_share,\" Außenwand \",\nclc_load!M$23=_xlpm.second_HT_share,\" Innenwand \",\nclc_load!M$30=_xlpm.second_HT_share,\" Dachfläche \",\nclc_load!M$36=_xlpm.second_HT_share,\" Decke \",\nclc_load!M$41=_xlpm.second_HT_share,\" Fußbodenfläche \",\nclc_build!K$21=_xlpm.second_HT_share,\" Fenster \"))",
  "M5":  /* formula */ "_xlfn.LET(\n_xlpm.second_HT_share,LARGE((clc_build!L$13,clc_build!L$17,clc_build!L$21,clc_build!L$25,clc_build!L$29,clc_build!L$33),2),\n_xlfn.IFS(clc_load!N$18=_xlpm.second_HT_share,\" Außenwand \",\nclc_load!N$23=_xlpm.second_HT_share,\" Innenwand \",\nclc_load!N$30=_xlpm.second_HT_share,\" Dachfläche \",\nclc_load!N$36=_xlpm.second_HT_share,\" Decke \",\nclc_load!N$41=_xlpm.second_HT_share,\" Fußbodenfläche \",\nclc_build!L$21=_xlpm.second_HT_share,\" Fenster \"))",
  "N5":  /* formula */ "_xlfn.LET(\n_xlpm.second_HT_share,LARGE((clc_build!M$13,clc_build!M$17,clc_build!M$21,clc_build!M$25,clc_build!M$29,clc_build!M$33),2),\n_xlfn.IFS(clc_load!O$18=_xlpm.second_HT_share,\" Außenwand \",\nclc_load!O$23=_xlpm.second_HT_share,\" Innenwand \",\nclc_load!O$30=_xlpm.second_HT_share,\" Dachfläche \",\nclc_load!O$36=_xlpm.second_HT_share,\" Decke \",\nclc_load!O$41=_xlpm.second_HT_share,\" Fußbodenfläche \",\nclc_build!M$21=_xlpm.second_HT_share,\" Fenster \"))",
  "O5":  /* formula */ "_xlfn.LET(\n_xlpm.second_HT_share,LARGE((clc_build!N$13,clc_build!N$17,clc_build!N$21,clc_build!N$25,clc_build!N$29,clc_build!N$33),2),\n_xlfn.IFS(clc_load!P$18=_xlpm.second_HT_share,\" Außenwand \",\nclc_load!P$23=_xlpm.second_HT_share,\" Innenwand \",\nclc_load!P$30=_xlpm.second_HT_share,\" Dachfläche \",\nclc_load!P$36=_xlpm.second_HT_share,\" Decke \",\nclc_load!P$41=_xlpm.second_HT_share,\" Fußbodenfläche \",\nclc_build!N$21=_xlpm.second_HT_share,\" Fenster \"))",
  "P5":  /* formula */ "_xlfn.LET(\n_xlpm.second_HT_share,LARGE((clc_build!O$13,clc_build!O$17,clc_build!O$21,clc_build!O$25,clc_build!O$29,clc_build!O$33),2),\n_xlfn.IFS(clc_load!Q$18=_xlpm.second_HT_share,\" Außenwand \",\nclc_load!Q$23=_xlpm.second_HT_share,\" Innenwand \",\nclc_load!Q$30=_xlpm.second_HT_share,\" Dachfläche \",\nclc_load!Q$36=_xlpm.second_HT_share,\" Decke \",\nclc_load!Q$41=_xlpm.second_HT_share,\" Fußbodenfläche \",\nclc_build!O$21=_xlpm.second_HT_share,\" Fenster \"))",
  "Q5":  /* formula */ "_xlfn.LET(\n_xlpm.second_HT_share,LARGE((clc_build!P$13,clc_build!P$17,clc_build!P$21,clc_build!P$25,clc_build!P$29,clc_build!P$33),2),\n_xlfn.IFS(clc_load!R$18=_xlpm.second_HT_share,\" Außenwand \",\nclc_load!R$23=_xlpm.second_HT_share,\" Innenwand \",\nclc_load!R$30=_xlpm.second_HT_share,\" Dachfläche \",\nclc_load!R$36=_xlpm.second_HT_share,\" Decke \",\nclc_load!R$41=_xlpm.second_HT_share,\" Fußbodenfläche \",\nclc_build!P$21=_xlpm.second_HT_share,\" Fenster \"))",
  "R5":  /* formula */ "_xlfn.LET(\n_xlpm.second_HT_share,LARGE((clc_build!Q$13,clc_build!Q$17,clc_build!Q$21,clc_build!Q$25,clc_build!Q$29,clc_build!Q$33),2),\n_xlfn.IFS(clc_load!S$18=_xlpm.second_HT_share,\" Außenwand \",\nclc_load!S$23=_xlpm.second_HT_share,\" Innenwand \",\nclc_load!S$30=_xlpm.second_HT_share,\" Dachfläche \",\nclc_load!S$36=_xlpm.second_HT_share,\" Decke \",\nclc_load!S$41=_xlpm.second_HT_share,\" Fußbodenfläche \",\nclc_build!Q$21=_xlpm.second_HT_share,\" Fenster \"))",
  "S5":  /* formula */ "_xlfn.LET(\n_xlpm.second_HT_share,LARGE((clc_build!R$13,clc_build!R$17,clc_build!R$21,clc_build!R$25,clc_build!R$29,clc_build!R$33),2),\n_xlfn.IFS(clc_load!T$18=_xlpm.second_HT_share,\" Außenwand \",\nclc_load!T$23=_xlpm.second_HT_share,\" Innenwand \",\nclc_load!T$30=_xlpm.second_HT_share,\" Dachfläche \",\nclc_load!T$36=_xlpm.second_HT_share,\" Decke \",\nclc_load!T$41=_xlpm.second_HT_share,\" Fußbodenfläche \",\nclc_build!R$21=_xlpm.second_HT_share,\" Fenster \"))",
  "T5":  /* formula */ "_xlfn.LET(\n_xlpm.second_HT_share,LARGE((clc_build!S$13,clc_build!S$17,clc_build!S$21,clc_build!S$25,clc_build!S$29,clc_build!S$33),2),\n_xlfn.IFS(clc_load!U$18=_xlpm.second_HT_share,\" Außenwand \",\nclc_load!U$23=_xlpm.second_HT_share,\" Innenwand \",\nclc_load!U$30=_xlpm.second_HT_share,\" Dachfläche \",\nclc_load!U$36=_xlpm.second_HT_share,\" Decke \",\nclc_load!U$41=_xlpm.second_HT_share,\" Fußbodenfläche \",\nclc_build!S$21=_xlpm.second_HT_share,\" Fenster \"))",
  "U5":  /* formula */ "_xlfn.LET(\n_xlpm.second_HT_share,LARGE((clc_build!T$13,clc_build!T$17,clc_build!T$21,clc_build!T$25,clc_build!T$29,clc_build!T$33),2),\n_xlfn.IFS(clc_load!V$18=_xlpm.second_HT_share,\" Außenwand \",\nclc_load!V$23=_xlpm.second_HT_share,\" Innenwand \",\nclc_load!V$30=_xlpm.second_HT_share,\" Dachfläche \",\nclc_load!V$36=_xlpm.second_HT_share,\" Decke \",\nclc_load!V$41=_xlpm.second_HT_share,\" Fußbodenfläche \",\nclc_build!T$21=_xlpm.second_HT_share,\" Fenster \"))",
  "V5":  /* formula */ "_xlfn.LET(\n_xlpm.second_HT_share,LARGE((clc_build!U$13,clc_build!U$17,clc_build!U$21,clc_build!U$25,clc_build!U$29,clc_build!U$33),2),\n_xlfn.IFS(clc_load!W$18=_xlpm.second_HT_share,\" Außenwand \",\nclc_load!W$23=_xlpm.second_HT_share,\" Innenwand \",\nclc_load!W$30=_xlpm.second_HT_share,\" Dachfläche \",\nclc_load!W$36=_xlpm.second_HT_share,\" Decke \",\nclc_load!W$41=_xlpm.second_HT_share,\" Fußbodenfläche \",\nclc_build!U$21=_xlpm.second_HT_share,\" Fenster \"))",
  "A6":  /* unknown */ "Ausgabe Bauteilbewertung Raumebene",
  "B6":  /* unknown */ "room",
  "D6":  /* unknown */ "TXT_room_R2_Qdot",
  "G6":  /* unknown */ "R2",
  "H6":  /* formula */ "_xlfn.IFS(\nclc_build!G$8<50,TXT_rooms!$E$6,\nAND(clc_build!G$8>=50,clc_build!G$6<70),TXT_rooms!$E$7&OUT_rooms!H$4&TXT_rooms!$E$8,\nAND(clc_build!G$8>=70,clc_build!G$6<90),TXT_rooms!$E$9&OUT_rooms!H$4&TXT_rooms!$E$10,\nclc_build!G$8>=90,TXT_rooms!$E$11&OUT_rooms!H$4&\"und die\"&H$5&TXT_rooms!$E$12\n)",
  "I6":  /* formula */ "_xlfn.IFS(\nclc_build!H$6<50,TXT_rooms!$E$6,\nAND(clc_build!H$6>=50,clc_build!H$6<70),TXT_rooms!$E$7&OUT_rooms!I$4&TXT_rooms!$E$8,\nAND(clc_build!H$6>=70,clc_build!H$6<90),TXT_rooms!$E$9&OUT_rooms!I$4&TXT_rooms!$E$10,\nclc_build!H$6>=90,TXT_rooms!$E$11&OUT_rooms!I$4&\"und die\"&I$5&TXT_rooms!$E$12\n)",
  "J6":  /* formula */ "_xlfn.IFS(\nclc_build!I$6<50,TXT_rooms!$E$6,\nAND(clc_build!I$6>=50,clc_build!I$6<70),TXT_rooms!$E$7&OUT_rooms!J$4&TXT_rooms!$E$8,\nAND(clc_build!I$6>=70,clc_build!I$6<90),TXT_rooms!$E$9&OUT_rooms!J$4&TXT_rooms!$E$10,\nclc_build!I$6>=90,TXT_rooms!$E$11&OUT_rooms!J$4&\"und die\"&J$5&TXT_rooms!$E$12\n)",
  "K6":  /* formula */ "_xlfn.IFS(\nclc_build!J$6<50,TXT_rooms!$E$6,\nAND(clc_build!J$6>=50,clc_build!J$6<70),TXT_rooms!$E$7&OUT_rooms!K$4&TXT_rooms!$E$8,\nAND(clc_build!J$6>=70,clc_build!J$6<90),TXT_rooms!$E$9&OUT_rooms!K$4&TXT_rooms!$E$10,\nclc_build!J$6>=90,TXT_rooms!$E$11&OUT_rooms!K$4&\"und die\"&K$5&TXT_rooms!$E$12\n)",
  "L6":  /* formula */ "_xlfn.IFS(\nclc_build!K$6<50,TXT_rooms!$E$6,\nAND(clc_build!K$6>=50,clc_build!K$6<70),TXT_rooms!$E$7&OUT_rooms!L$4&TXT_rooms!$E$8,\nAND(clc_build!K$6>=70,clc_build!K$6<90),TXT_rooms!$E$9&OUT_rooms!L$4&TXT_rooms!$E$10,\nclc_build!K$6>=90,TXT_rooms!$E$11&OUT_rooms!L$4&\"und die\"&L$5&TXT_rooms!$E$12\n)",
  "M6":  /* formula */ "_xlfn.IFS(\nclc_build!L$6<50,TXT_rooms!$E$6,\nAND(clc_build!L$6>=50,clc_build!L$6<70),TXT_rooms!$E$7&OUT_rooms!M$4&TXT_rooms!$E$8,\nAND(clc_build!L$6>=70,clc_build!L$6<90),TXT_rooms!$E$9&OUT_rooms!M$4&TXT_rooms!$E$10,\nclc_build!L$6>=90,TXT_rooms!$E$11&OUT_rooms!M$4&\"und die\"&M$5&TXT_rooms!$E$12\n)",
  "N6":  /* formula */ "_xlfn.IFS(\nclc_build!M$6<50,TXT_rooms!$E$6,\nAND(clc_build!M$6>=50,clc_build!M$6<70),TXT_rooms!$E$7&OUT_rooms!N$4&TXT_rooms!$E$8,\nAND(clc_build!M$6>=70,clc_build!M$6<90),TXT_rooms!$E$9&OUT_rooms!N$4&TXT_rooms!$E$10,\nclc_build!M$6>=90,TXT_rooms!$E$11&OUT_rooms!N$4&\"und die\"&N$5&TXT_rooms!$E$12\n)",
  "O6":  /* formula */ "_xlfn.IFS(\nclc_build!N$6<50,TXT_rooms!$E$6,\nAND(clc_build!N$6>=50,clc_build!N$6<70),TXT_rooms!$E$7&OUT_rooms!O$4&TXT_rooms!$E$8,\nAND(clc_build!N$6>=70,clc_build!N$6<90),TXT_rooms!$E$9&OUT_rooms!O$4&TXT_rooms!$E$10,\nclc_build!N$6>=90,TXT_rooms!$E$11&OUT_rooms!O$4&\"und die\"&O$5&TXT_rooms!$E$12\n)",
  "P6":  /* formula */ "_xlfn.IFS(\nclc_build!O$6<50,TXT_rooms!$E$6,\nAND(clc_build!O$6>=50,clc_build!O$6<70),TXT_rooms!$E$7&OUT_rooms!P$4&TXT_rooms!$E$8,\nAND(clc_build!O$6>=70,clc_build!O$6<90),TXT_rooms!$E$9&OUT_rooms!P$4&TXT_rooms!$E$10,\nclc_build!O$6>=90,TXT_rooms!$E$11&OUT_rooms!P$4&\"und die\"&P$5&TXT_rooms!$E$12\n)",
  "Q6":  /* formula */ "_xlfn.IFS(\nclc_build!P$6<50,TXT_rooms!$E$6,\nAND(clc_build!P$6>=50,clc_build!P$6<70),TXT_rooms!$E$7&OUT_rooms!Q$4&TXT_rooms!$E$8,\nAND(clc_build!P$6>=70,clc_build!P$6<90),TXT_rooms!$E$9&OUT_rooms!Q$4&TXT_rooms!$E$10,\nclc_build!P$6>=90,TXT_rooms!$E$11&OUT_rooms!Q$4&\"und die\"&Q$5&TXT_rooms!$E$12\n)",
  "R6":  /* formula */ "_xlfn.IFS(\nclc_build!Q$6<50,TXT_rooms!$E$6,\nAND(clc_build!Q$6>=50,clc_build!Q$6<70),TXT_rooms!$E$7&OUT_rooms!R$4&TXT_rooms!$E$8,\nAND(clc_build!Q$6>=70,clc_build!Q$6<90),TXT_rooms!$E$9&OUT_rooms!R$4&TXT_rooms!$E$10,\nclc_build!Q$6>=90,TXT_rooms!$E$11&OUT_rooms!R$4&\"und die\"&R$5&TXT_rooms!$E$12\n)",
  "S6":  /* formula */ "_xlfn.IFS(\nclc_build!R$6<50,TXT_rooms!$E$6,\nAND(clc_build!R$6>=50,clc_build!R$6<70),TXT_rooms!$E$7&OUT_rooms!S$4&TXT_rooms!$E$8,\nAND(clc_build!R$6>=70,clc_build!R$6<90),TXT_rooms!$E$9&OUT_rooms!S$4&TXT_rooms!$E$10,\nclc_build!R$6>=90,TXT_rooms!$E$11&OUT_rooms!S$4&\"und die\"&S$5&TXT_rooms!$E$12\n)",
  "T6":  /* formula */ "_xlfn.IFS(\nclc_build!S$6<50,TXT_rooms!$E$6,\nAND(clc_build!S$6>=50,clc_build!S$6<70),TXT_rooms!$E$7&OUT_rooms!T$4&TXT_rooms!$E$8,\nAND(clc_build!S$6>=70,clc_build!S$6<90),TXT_rooms!$E$9&OUT_rooms!T$4&TXT_rooms!$E$10,\nclc_build!S$6>=90,TXT_rooms!$E$11&OUT_rooms!T$4&\"und die\"&T$5&TXT_rooms!$E$12\n)",
  "U6":  /* formula */ "_xlfn.IFS(\nclc_build!T$6<50,TXT_rooms!$E$6,\nAND(clc_build!T$6>=50,clc_build!T$6<70),TXT_rooms!$E$7&OUT_rooms!U$4&TXT_rooms!$E$8,\nAND(clc_build!T$6>=70,clc_build!T$6<90),TXT_rooms!$E$9&OUT_rooms!U$4&TXT_rooms!$E$10,\nclc_build!T$6>=90,TXT_rooms!$E$11&OUT_rooms!U$4&\"und die\"&U$5&TXT_rooms!$E$12\n)",
  "V6":  /* formula */ "_xlfn.IFS(\nclc_build!U$6<50,TXT_rooms!$E$6,\nAND(clc_build!U$6>=50,clc_build!U$6<70),TXT_rooms!$E$7&OUT_rooms!V$4&TXT_rooms!$E$8,\nAND(clc_build!U$6>=70,clc_build!U$6<90),TXT_rooms!$E$9&OUT_rooms!V$4&TXT_rooms!$E$10,\nclc_build!U$6>=90,TXT_rooms!$E$11&OUT_rooms!V$4&\"und die\"&V$5&TXT_rooms!$E$12\n)",
  "A7":  /* unknown */ "Lückentext Bewertung Heizkörpertausch Raumebene 1",
  "B7":  /* unknown */ "room",
  "D7":  /* unknown */ "TXT_room_R3_fill_1",
  "G7":  /* unknown */ "R3",
  "H7":  /* formula */ " _xlfn.IFS(\n    clc_build!G$39>0.5,\n\" größerer \",\n    AND(clc_build!G$39 >0.45,clc_build!G$39<=0.5),\n\" mindestens doppelt so großer \",\n    AND(clc_build!G$39 >0.34,clc_build!G$39<=0.45),\n\" dreimal so großer \",\n   clc_build!G$39<=0.34,\n\" sehr viel größerer \"\n)",
  "I7":  /* formula */ " _xlfn.IFS(\n    clc_build!H$39>0.5,\n\" größerer \",\n    AND(clc_build!H$39 >0.45,clc_build!H$39<=0.5),\n\" mindestens doppelt so großer \",\n    AND(clc_build!H$39 >0.34,clc_build!H$39<=0.45),\n\" dreimal so großer \",\n   clc_build!H$39<=0.34,\n\" sehr viel größerer \"\n)",
  "J7":  /* formula */ " _xlfn.IFS(\n    clc_build!I$39>0.5,\n\" größerer \",\n    AND(clc_build!I$39 >0.45,clc_build!I$39<=0.5),\n\" mindestens doppelt so großer \",\n    AND(clc_build!I$39 >0.34,clc_build!I$39<=0.45),\n\" dreimal so großer \",\n   clc_build!I$39<=0.34,\n\" sehr viel größerer \"\n)",
  "K7":  /* formula */ " _xlfn.IFS(\n    clc_build!J$39>0.5,\n\" größerer \",\n    AND(clc_build!J$39 >0.45,clc_build!J$39<=0.5),\n\" mindestens doppelt so großer \",\n    AND(clc_build!J$39 >0.34,clc_build!J$39<=0.45),\n\" dreimal so großer \",\n   clc_build!J$39<=0.34,\n\" sehr viel größerer \"\n)",
  "L7":  /* formula */ " _xlfn.IFS(\n    clc_build!K$39>0.5,\n\" größerer \",\n    AND(clc_build!K$39 >0.45,clc_build!K$39<=0.5),\n\" mindestens doppelt so großer \",\n    AND(clc_build!K$39 >0.34,clc_build!K$39<=0.45),\n\" dreimal so großer \",\n   clc_build!K$39<=0.34,\n\" sehr viel größerer \"\n)",
  "M7":  /* formula */ " _xlfn.IFS(\n    clc_build!L$39>0.5,\n\" größerer \",\n    AND(clc_build!L$39 >0.45,clc_build!L$39<=0.5),\n\" mindestens doppelt so großer \",\n    AND(clc_build!L$39 >0.34,clc_build!L$39<=0.45),\n\" dreimal so großer \",\n   clc_build!L$39<=0.34,\n\" sehr viel größerer \"\n)",
  "N7":  /* formula */ " _xlfn.IFS(\n    clc_build!M$39>0.5,\n\" größerer \",\n    AND(clc_build!M$39 >0.45,clc_build!M$39<=0.5),\n\" mindestens doppelt so großer \",\n    AND(clc_build!M$39 >0.34,clc_build!M$39<=0.45),\n\" dreimal so großer \",\n   clc_build!M$39<=0.34,\n\" sehr viel größerer \"\n)",
  "O7":  /* formula */ " _xlfn.IFS(\n    clc_build!N$39>0.5,\n\" größerer \",\n    AND(clc_build!N$39 >0.45,clc_build!N$39<=0.5),\n\" mindestens doppelt so großer \",\n    AND(clc_build!N$39 >0.34,clc_build!N$39<=0.45),\n\" dreimal so großer \",\n   clc_build!N$39<=0.34,\n\" sehr viel größerer \"\n)",
  "P7":  /* formula */ " _xlfn.IFS(\n    clc_build!O$39>0.5,\n\" größerer \",\n    AND(clc_build!O$39 >0.45,clc_build!O$39<=0.5),\n\" mindestens doppelt so großer \",\n    AND(clc_build!O$39 >0.34,clc_build!O$39<=0.45),\n\" dreimal so großer \",\n   clc_build!O$39<=0.34,\n\" sehr viel größerer \"\n)",
  "Q7":  /* formula */ " _xlfn.IFS(\n    clc_build!P$39>0.5,\n\" größerer \",\n    AND(clc_build!P$39 >0.45,clc_build!P$39<=0.5),\n\" mindestens doppelt so großer \",\n    AND(clc_build!P$39 >0.34,clc_build!P$39<=0.45),\n\" dreimal so großer \",\n   clc_build!P$39<=0.34,\n\" sehr viel größerer \"\n)",
  "R7":  /* formula */ " _xlfn.IFS(\n    clc_build!Q$39>0.5,\n\" größerer \",\n    AND(clc_build!Q$39 >0.45,clc_build!Q$39<=0.5),\n\" mindestens doppelt so großer \",\n    AND(clc_build!Q$39 >0.34,clc_build!Q$39<=0.45),\n\" dreimal so großer \",\n   clc_build!Q$39<=0.34,\n\" sehr viel größerer \"\n)",
  "S7":  /* formula */ " _xlfn.IFS(\n    clc_build!R$39>0.5,\n\" größerer \",\n    AND(clc_build!R$39 >0.45,clc_build!R$39<=0.5),\n\" mindestens doppelt so großer \",\n    AND(clc_build!R$39 >0.34,clc_build!R$39<=0.45),\n\" dreimal so großer \",\n   clc_build!R$39<=0.34,\n\" sehr viel größerer \"\n)",
  "T7":  /* formula */ " _xlfn.IFS(\n    clc_build!S$39>0.5,\n\" größerer \",\n    AND(clc_build!S$39 >0.45,clc_build!S$39<=0.5),\n\" mindestens doppelt so großer \",\n    AND(clc_build!S$39 >0.34,clc_build!S$39<=0.45),\n\" dreimal so großer \",\n   clc_build!S$39<=0.34,\n\" sehr viel größerer \"\n)",
  "U7":  /* formula */ " _xlfn.IFS(\n    clc_build!T$39>0.5,\n\" größerer \",\n    AND(clc_build!T$39 >0.45,clc_build!T$39<=0.5),\n\" mindestens doppelt so großer \",\n    AND(clc_build!T$39 >0.34,clc_build!T$39<=0.45),\n\" dreimal so großer \",\n   clc_build!T$39<=0.34,\n\" sehr viel größerer \"\n)",
  "V7":  /* formula */ " _xlfn.IFS(\n    clc_build!U$39>0.5,\n\" größerer \",\n    AND(clc_build!U$39 >0.45,clc_build!U$39<=0.5),\n\" mindestens doppelt so großer \",\n    AND(clc_build!U$39 >0.34,clc_build!U$39<=0.45),\n\" dreimal so großer \",\n   clc_build!U$39<=0.34,\n\" sehr viel größerer \"\n)",
  "A8":  /* unknown */ "Lückentext Bewertung Heizkörpertausch Raumebene 2",
  "B8":  /* unknown */ "room",
  "D8":  /* unknown */ "TXT_room_R3_fill_2",
  "G8":  /* unknown */ "R3",
  "H8":  /* formula */ " _xlfn.IFS(\n    clc_build!G$39>0.85,\n\" spürbar mehr \",\n    AND(clc_build!G$39 >0.77,clc_build!G$39<=0.85),\n\" 30 Prozent mehr\",\n    AND(clc_build!G$39 > 0.65, clc_build!G$39 <= 0.77),\n\" 50 Prozent mehr \",\n    AND(clc_build!G$39 > 0.5, clc_build!G$39 <= 0.65),\n\" doppelt so viel \",\nclc_build!G$39 <= 0.5,\n\" deutlich mehr \"\n)",
  "I8":  /* formula */ " _xlfn.IFS(\n    clc_build!H$39>0.85,\n\" spürbar mehr \",\n    AND(clc_build!H$39 >0.77,clc_build!H$39<=0.85),\n\" 30 Prozent mehr\",\n    AND(clc_build!H$39 > 0.65, clc_build!H$39 <= 0.77),\n\" 50 Prozent mehr \",\n    AND(clc_build!H$39 > 0.5, clc_build!H$39 <= 0.65),\n\" doppelt so viel \",\nclc_build!H$39 <= 0.5,\n\" deutlich mehr \"\n)",
  "J8":  /* formula */ " _xlfn.IFS(\n    clc_build!I$39>0.85,\n\" spürbar mehr \",\n    AND(clc_build!I$39 >0.77,clc_build!I$39<=0.85),\n\" 30 Prozent mehr\",\n    AND(clc_build!I$39 > 0.65, clc_build!I$39 <= 0.77),\n\" 50 Prozent mehr \",\n    AND(clc_build!I$39 > 0.5, clc_build!I$39 <= 0.65),\n\" doppelt so viel \",\nclc_build!I$39 <= 0.5,\n\" deutlich mehr \"\n)",
  "K8":  /* formula */ " _xlfn.IFS(\n    clc_build!J$39>0.85,\n\" spürbar mehr \",\n    AND(clc_build!J$39 >0.77,clc_build!J$39<=0.85),\n\" 30 Prozent mehr\",\n    AND(clc_build!J$39 > 0.65, clc_build!J$39 <= 0.77),\n\" 50 Prozent mehr \",\n    AND(clc_build!J$39 > 0.5, clc_build!J$39 <= 0.65),\n\" doppelt so viel \",\nclc_build!J$39 <= 0.5,\n\" deutlich mehr \"\n)",
  "L8":  /* formula */ " _xlfn.IFS(\n    clc_build!K$39>0.85,\n\" spürbar mehr \",\n    AND(clc_build!K$39 >0.77,clc_build!K$39<=0.85),\n\" 30 Prozent mehr\",\n    AND(clc_build!K$39 > 0.65, clc_build!K$39 <= 0.77),\n\" 50 Prozent mehr \",\n    AND(clc_build!K$39 > 0.5, clc_build!K$39 <= 0.65),\n\" doppelt so viel \",\nclc_build!K$39 <= 0.5,\n\" deutlich mehr \"\n)",
  "M8":  /* formula */ " _xlfn.IFS(\n    clc_build!L$39>0.85,\n\" spürbar mehr \",\n    AND(clc_build!L$39 >0.77,clc_build!L$39<=0.85),\n\" 30 Prozent mehr\",\n    AND(clc_build!L$39 > 0.65, clc_build!L$39 <= 0.77),\n\" 50 Prozent mehr \",\n    AND(clc_build!L$39 > 0.5, clc_build!L$39 <= 0.65),\n\" doppelt so viel \",\nclc_build!L$39 <= 0.5,\n\" deutlich mehr \"\n)",
  "N8":  /* formula */ " _xlfn.IFS(\n    clc_build!M$39>0.85,\n\" spürbar mehr \",\n    AND(clc_build!M$39 >0.77,clc_build!M$39<=0.85),\n\" 30 Prozent mehr\",\n    AND(clc_build!M$39 > 0.65, clc_build!M$39 <= 0.77),\n\" 50 Prozent mehr \",\n    AND(clc_build!M$39 > 0.5, clc_build!M$39 <= 0.65),\n\" doppelt so viel \",\nclc_build!M$39 <= 0.5,\n\" deutlich mehr \"\n)",
  "O8":  /* formula */ " _xlfn.IFS(\n    clc_build!N$39>0.85,\n\" spürbar mehr \",\n    AND(clc_build!N$39 >0.77,clc_build!N$39<=0.85),\n\" 30 Prozent mehr\",\n    AND(clc_build!N$39 > 0.65, clc_build!N$39 <= 0.77),\n\" 50 Prozent mehr \",\n    AND(clc_build!N$39 > 0.5, clc_build!N$39 <= 0.65),\n\" doppelt so viel \",\nclc_build!N$39 <= 0.5,\n\" deutlich mehr \"\n)",
  "P8":  /* formula */ " _xlfn.IFS(\n    clc_build!O$39>0.85,\n\" spürbar mehr \",\n    AND(clc_build!O$39 >0.77,clc_build!O$39<=0.85),\n\" 30 Prozent mehr\",\n    AND(clc_build!O$39 > 0.65, clc_build!O$39 <= 0.77),\n\" 50 Prozent mehr \",\n    AND(clc_build!O$39 > 0.5, clc_build!O$39 <= 0.65),\n\" doppelt so viel \",\nclc_build!O$39 <= 0.5,\n\" deutlich mehr \"\n)",
  "Q8":  /* formula */ " _xlfn.IFS(\n    clc_build!P$39>0.85,\n\" spürbar mehr \",\n    AND(clc_build!P$39 >0.77,clc_build!P$39<=0.85),\n\" 30 Prozent mehr\",\n    AND(clc_build!P$39 > 0.65, clc_build!P$39 <= 0.77),\n\" 50 Prozent mehr \",\n    AND(clc_build!P$39 > 0.5, clc_build!P$39 <= 0.65),\n\" doppelt so viel \",\nclc_build!P$39 <= 0.5,\n\" deutlich mehr \"\n)",
  "R8":  /* formula */ " _xlfn.IFS(\n    clc_build!Q$39>0.85,\n\" spürbar mehr \",\n    AND(clc_build!Q$39 >0.77,clc_build!Q$39<=0.85),\n\" 30 Prozent mehr\",\n    AND(clc_build!Q$39 > 0.65, clc_build!Q$39 <= 0.77),\n\" 50 Prozent mehr \",\n    AND(clc_build!Q$39 > 0.5, clc_build!Q$39 <= 0.65),\n\" doppelt so viel \",\nclc_build!Q$39 <= 0.5,\n\" deutlich mehr \"\n)",
  "S8":  /* formula */ " _xlfn.IFS(\n    clc_build!R$39>0.85,\n\" spürbar mehr \",\n    AND(clc_build!R$39 >0.77,clc_build!R$39<=0.85),\n\" 30 Prozent mehr\",\n    AND(clc_build!R$39 > 0.65, clc_build!R$39 <= 0.77),\n\" 50 Prozent mehr \",\n    AND(clc_build!R$39 > 0.5, clc_build!R$39 <= 0.65),\n\" doppelt so viel \",\nclc_build!R$39 <= 0.5,\n\" deutlich mehr \"\n)",
  "T8":  /* formula */ " _xlfn.IFS(\n    clc_build!S$39>0.85,\n\" spürbar mehr \",\n    AND(clc_build!S$39 >0.77,clc_build!S$39<=0.85),\n\" 30 Prozent mehr\",\n    AND(clc_build!S$39 > 0.65, clc_build!S$39 <= 0.77),\n\" 50 Prozent mehr \",\n    AND(clc_build!S$39 > 0.5, clc_build!S$39 <= 0.65),\n\" doppelt so viel \",\nclc_build!S$39 <= 0.5,\n\" deutlich mehr \"\n)",
  "U8":  /* formula */ " _xlfn.IFS(\n    clc_build!T$39>0.85,\n\" spürbar mehr \",\n    AND(clc_build!T$39 >0.77,clc_build!T$39<=0.85),\n\" 30 Prozent mehr\",\n    AND(clc_build!T$39 > 0.65, clc_build!T$39 <= 0.77),\n\" 50 Prozent mehr \",\n    AND(clc_build!T$39 > 0.5, clc_build!T$39 <= 0.65),\n\" doppelt so viel \",\nclc_build!T$39 <= 0.5,\n\" deutlich mehr \"\n)",
  "V8":  /* formula */ " _xlfn.IFS(\n    clc_build!U$39>0.85,\n\" spürbar mehr \",\n    AND(clc_build!U$39 >0.77,clc_build!U$39<=0.85),\n\" 30 Prozent mehr\",\n    AND(clc_build!U$39 > 0.65, clc_build!U$39 <= 0.77),\n\" 50 Prozent mehr \",\n    AND(clc_build!U$39 > 0.5, clc_build!U$39 <= 0.65),\n\" doppelt so viel \",\nclc_build!U$39 <= 0.5,\n\" deutlich mehr \"\n)",
  "A9":  /* unknown */ "Lückentext Bewertung Heizkörpertausch Raumebene 3",
  "D9":  /* unknown */ "TXT_room_R3_fill_3",
  "G9":  /* unknown */ "R3",
  "H9":  /* formula */ "_xlfn.IFS(clc_build!G$40 > 0.77,\n\", sondern müsste etwas größer sein.\",\nAND(clc_build!G$40 > 0.65, clc_build!G$40 <= 0.77),\n\", sondern müsste ein Drittel größer sein.\",\nAND(clc_build!G$40 > 0.5, clc_build!G$40 <= 0.65),\n\", sondern müsste 50 Prozent größer sein.\",\nclc_build!G$40 <= 0.5,\n\", sondern müsste mindestens doppelt so groß sein.\")",
  "I9":  /* formula */ "_xlfn.IFS(clc_build!H$40 > 0.77,\n\", sondern müsste etwas größer sein.\",\nAND(clc_build!H$40 > 0.65, clc_build!H$40 <= 0.77),\n\", sondern müsste ein Drittel größer sein.\",\nAND(clc_build!H$40 > 0.5, clc_build!H$40 <= 0.65),\n\", sondern müsste 50 Prozent größer sein.\",\nclc_build!H$40 <= 0.5,\n\", sondern müsste mindestens doppelt so groß sein.\")",
  "J9":  /* formula */ "_xlfn.IFS(clc_build!I$40 > 0.77,\n\", sondern müsste etwas größer sein.\",\nAND(clc_build!I$40 > 0.65, clc_build!I$40 <= 0.77),\n\", sondern müsste ein Drittel größer sein.\",\nAND(clc_build!I$40 > 0.5, clc_build!I$40 <= 0.65),\n\", sondern müsste 50 Prozent größer sein.\",\nclc_build!I$40 <= 0.5,\n\", sondern müsste mindestens doppelt so groß sein.\")",
  "K9":  /* formula */ "_xlfn.IFS(clc_build!J$40 > 0.77,\n\", sondern müsste etwas größer sein.\",\nAND(clc_build!J$40 > 0.65, clc_build!J$40 <= 0.77),\n\", sondern müsste ein Drittel größer sein.\",\nAND(clc_build!J$40 > 0.5, clc_build!J$40 <= 0.65),\n\", sondern müsste 50 Prozent größer sein.\",\nclc_build!J$40 <= 0.5,\n\", sondern müsste mindestens doppelt so groß sein.\")",
  "L9":  /* formula */ "_xlfn.IFS(clc_build!K$40 > 0.77,\n\", sondern müsste etwas größer sein.\",\nAND(clc_build!K$40 > 0.65, clc_build!K$40 <= 0.77),\n\", sondern müsste ein Drittel größer sein.\",\nAND(clc_build!K$40 > 0.5, clc_build!K$40 <= 0.65),\n\", sondern müsste 50 Prozent größer sein.\",\nclc_build!K$40 <= 0.5,\n\", sondern müsste mindestens doppelt so groß sein.\")",
  "M9":  /* formula */ "_xlfn.IFS(clc_build!L$40 > 0.77,\n\", sondern müsste etwas größer sein.\",\nAND(clc_build!L$40 > 0.65, clc_build!L$40 <= 0.77),\n\", sondern müsste ein Drittel größer sein.\",\nAND(clc_build!L$40 > 0.5, clc_build!L$40 <= 0.65),\n\", sondern müsste 50 Prozent größer sein.\",\nclc_build!L$40 <= 0.5,\n\", sondern müsste mindestens doppelt so groß sein.\")",
  "N9":  /* formula */ "_xlfn.IFS(clc_build!M$40 > 0.77,\n\", sondern müsste etwas größer sein.\",\nAND(clc_build!M$40 > 0.65, clc_build!M$40 <= 0.77),\n\", sondern müsste ein Drittel größer sein.\",\nAND(clc_build!M$40 > 0.5, clc_build!M$40 <= 0.65),\n\", sondern müsste 50 Prozent größer sein.\",\nclc_build!M$40 <= 0.5,\n\", sondern müsste mindestens doppelt so groß sein.\")",
  "O9":  /* formula */ "_xlfn.IFS(clc_build!N$40 > 0.77,\n\", sondern müsste etwas größer sein.\",\nAND(clc_build!N$40 > 0.65, clc_build!N$40 <= 0.77),\n\", sondern müsste ein Drittel größer sein.\",\nAND(clc_build!N$40 > 0.5, clc_build!N$40 <= 0.65),\n\", sondern müsste 50 Prozent größer sein.\",\nclc_build!N$40 <= 0.5,\n\", sondern müsste mindestens doppelt so groß sein.\")",
  "P9":  /* formula */ "_xlfn.IFS(clc_build!O$40 > 0.77,\n\", sondern müsste etwas größer sein.\",\nAND(clc_build!O$40 > 0.65, clc_build!O$40 <= 0.77),\n\", sondern müsste ein Drittel größer sein.\",\nAND(clc_build!O$40 > 0.5, clc_build!O$40 <= 0.65),\n\", sondern müsste 50 Prozent größer sein.\",\nclc_build!O$40 <= 0.5,\n\", sondern müsste mindestens doppelt so groß sein.\")",
  "Q9":  /* formula */ "_xlfn.IFS(clc_build!P$40 > 0.77,\n\", sondern müsste etwas größer sein.\",\nAND(clc_build!P$40 > 0.65, clc_build!P$40 <= 0.77),\n\", sondern müsste ein Drittel größer sein.\",\nAND(clc_build!P$40 > 0.5, clc_build!P$40 <= 0.65),\n\", sondern müsste 50 Prozent größer sein.\",\nclc_build!P$40 <= 0.5,\n\", sondern müsste mindestens doppelt so groß sein.\")",
  "R9":  /* formula */ "_xlfn.IFS(clc_build!Q$40 > 0.77,\n\", sondern müsste etwas größer sein.\",\nAND(clc_build!Q$40 > 0.65, clc_build!Q$40 <= 0.77),\n\", sondern müsste ein Drittel größer sein.\",\nAND(clc_build!Q$40 > 0.5, clc_build!Q$40 <= 0.65),\n\", sondern müsste 50 Prozent größer sein.\",\nclc_build!Q$40 <= 0.5,\n\", sondern müsste mindestens doppelt so groß sein.\")",
  "S9":  /* formula */ "_xlfn.IFS(clc_build!R$40 > 0.77,\n\", sondern müsste etwas größer sein.\",\nAND(clc_build!R$40 > 0.65, clc_build!R$40 <= 0.77),\n\", sondern müsste ein Drittel größer sein.\",\nAND(clc_build!R$40 > 0.5, clc_build!R$40 <= 0.65),\n\", sondern müsste 50 Prozent größer sein.\",\nclc_build!R$40 <= 0.5,\n\", sondern müsste mindestens doppelt so groß sein.\")",
  "T9":  /* formula */ "_xlfn.IFS(clc_build!S$40 > 0.77,\n\", sondern müsste etwas größer sein.\",\nAND(clc_build!S$40 > 0.65, clc_build!S$40 <= 0.77),\n\", sondern müsste ein Drittel größer sein.\",\nAND(clc_build!S$40 > 0.5, clc_build!S$40 <= 0.65),\n\", sondern müsste 50 Prozent größer sein.\",\nclc_build!S$40 <= 0.5,\n\", sondern müsste mindestens doppelt so groß sein.\")",
  "U9":  /* formula */ "_xlfn.IFS(clc_build!T$40 > 0.77,\n\", sondern müsste etwas größer sein.\",\nAND(clc_build!T$40 > 0.65, clc_build!T$40 <= 0.77),\n\", sondern müsste ein Drittel größer sein.\",\nAND(clc_build!T$40 > 0.5, clc_build!T$40 <= 0.65),\n\", sondern müsste 50 Prozent größer sein.\",\nclc_build!T$40 <= 0.5,\n\", sondern müsste mindestens doppelt so groß sein.\")",
  "V9":  /* formula */ "_xlfn.IFS(clc_build!U$40 > 0.77,\n\", sondern müsste etwas größer sein.\",\nAND(clc_build!U$40 > 0.65, clc_build!U$40 <= 0.77),\n\", sondern müsste ein Drittel größer sein.\",\nAND(clc_build!U$40 > 0.5, clc_build!U$40 <= 0.65),\n\", sondern müsste 50 Prozent größer sein.\",\nclc_build!U$40 <= 0.5,\n\", sondern müsste mindestens doppelt so groß sein.\")",
  "A10":  /* unknown */ "Ausgabe Heizkörpertausch Raumebene",
  "B10":  /* unknown */ "room",
  "D10":  /* unknown */ "TXT_room__R3_Qdot",
  "G10":  /* unknown */ "R3",
  "H10":  /* formula */ "_xlfn.IFS(\nclc_build!G$39 > 1,\nTXT_rooms!$E$19,\nclc_build!G$40<0.5,\nTXT_rooms!$E$13 & H7 & TXT_rooms!$E$14,\nclc_build!G$40 < 1,\nTXT_rooms!$E$15&H$8&TXT_rooms!$E$16 & H$9,\nAND(clc_build!G$40 > 1,clc_build!G$39 < 1),TXT_rooms!$E$17&H$8&TXT_rooms!$E$18\n)",
  "I10":  /* formula */ "_xlfn.IFS(\nclc_build!H$39 > 1,\nTXT_rooms!$E$19,\nclc_build!H$40<0.5,\nTXT_rooms!$E$13 & I7 & TXT_rooms!$E$14,\nclc_build!H$40 < 1,\nTXT_rooms!$E$15&I$8&TXT_rooms!$E$16 & I$9,\nAND(clc_build!H$40 > 1,clc_build!H$39 < 1),TXT_rooms!$E$17&I$8&TXT_rooms!$E$18\n)",
  "J10":  /* formula */ "_xlfn.IFS(\nclc_build!I$39 > 1,\nTXT_rooms!$E$19,\nclc_build!I$40<0.5,\nTXT_rooms!$E$13 & J7 & TXT_rooms!$E$14,\nclc_build!I$40 < 1,\nTXT_rooms!$E$15&J$8&TXT_rooms!$E$16 & J$9,\nAND(clc_build!I$40 > 1,clc_build!I$39 < 1),TXT_rooms!$E$17&J$8&TXT_rooms!$E$18\n)",
  "K10":  /* formula */ "_xlfn.IFS(\nclc_build!J$39 > 1,\nTXT_rooms!$E$19,\nclc_build!J$40<0.5,\nTXT_rooms!$E$13 & K7 & TXT_rooms!$E$14,\nclc_build!J$40 < 1,\nTXT_rooms!$E$15&K$8&TXT_rooms!$E$16 & K$9,\nAND(clc_build!J$40 > 1,clc_build!J$39 < 1),TXT_rooms!$E$17&K$8&TXT_rooms!$E$18\n)",
  "L10":  /* formula */ "_xlfn.IFS(\nclc_build!K$39 > 1,\nTXT_rooms!$E$19,\nclc_build!K$40<0.5,\nTXT_rooms!$E$13 & L7 & TXT_rooms!$E$14,\nclc_build!K$40 < 1,\nTXT_rooms!$E$15&L$8&TXT_rooms!$E$16 & L$9,\nAND(clc_build!K$40 > 1,clc_build!K$39 < 1),TXT_rooms!$E$17&L$8&TXT_rooms!$E$18\n)",
  "M10":  /* formula */ "_xlfn.IFS(\nclc_build!L$39 > 1,\nTXT_rooms!$E$19,\nclc_build!L$40<0.5,\nTXT_rooms!$E$13 & M7 & TXT_rooms!$E$14,\nclc_build!L$40 < 1,\nTXT_rooms!$E$15&M$8&TXT_rooms!$E$16 & M$9,\nAND(clc_build!L$40 > 1,clc_build!L$39 < 1),TXT_rooms!$E$17&M$8&TXT_rooms!$E$18\n)",
  "N10":  /* formula */ "_xlfn.IFS(\nclc_build!M$39 > 1,\nTXT_rooms!$E$19,\nclc_build!M$40<0.5,\nTXT_rooms!$E$13 & N7 & TXT_rooms!$E$14,\nclc_build!M$40 < 1,\nTXT_rooms!$E$15&N$8&TXT_rooms!$E$16 & N$9,\nAND(clc_build!M$40 > 1,clc_build!M$39 < 1),TXT_rooms!$E$17&N$8&TXT_rooms!$E$18\n)",
  "O10":  /* formula */ "_xlfn.IFS(\nclc_build!N$39 > 1,\nTXT_rooms!$E$19,\nclc_build!N$40<0.5,\nTXT_rooms!$E$13 & O7 & TXT_rooms!$E$14,\nclc_build!N$40 < 1,\nTXT_rooms!$E$15&O$8&TXT_rooms!$E$16 & O$9,\nAND(clc_build!N$40 > 1,clc_build!N$39 < 1),TXT_rooms!$E$17&O$8&TXT_rooms!$E$18\n)",
  "P10":  /* formula */ "_xlfn.IFS(\nclc_build!O$39 > 1,\nTXT_rooms!$E$19,\nclc_build!O$40<0.5,\nTXT_rooms!$E$13 & P7 & TXT_rooms!$E$14,\nclc_build!O$40 < 1,\nTXT_rooms!$E$15&P$8&TXT_rooms!$E$16 & P$9,\nAND(clc_build!O$40 > 1,clc_build!O$39 < 1),TXT_rooms!$E$17&P$8&TXT_rooms!$E$18\n)",
  "Q10":  /* formula */ "_xlfn.IFS(\nclc_build!P$39 > 1,\nTXT_rooms!$E$19,\nclc_build!P$40<0.5,\nTXT_rooms!$E$13 & Q7 & TXT_rooms!$E$14,\nclc_build!P$40 < 1,\nTXT_rooms!$E$15&Q$8&TXT_rooms!$E$16 & Q$9,\nAND(clc_build!P$40 > 1,clc_build!P$39 < 1),TXT_rooms!$E$17&Q$8&TXT_rooms!$E$18\n)",
  "R10":  /* formula */ "_xlfn.IFS(\nclc_build!Q$39 > 1,\nTXT_rooms!$E$19,\nclc_build!Q$40<0.5,\nTXT_rooms!$E$13 & R7 & TXT_rooms!$E$14,\nclc_build!Q$40 < 1,\nTXT_rooms!$E$15&R$8&TXT_rooms!$E$16 & R$9,\nAND(clc_build!Q$40 > 1,clc_build!Q$39 < 1),TXT_rooms!$E$17&R$8&TXT_rooms!$E$18\n)",
  "S10":  /* formula */ "_xlfn.IFS(\nclc_build!R$39 > 1,\nTXT_rooms!$E$19,\nclc_build!R$40<0.5,\nTXT_rooms!$E$13 & S7 & TXT_rooms!$E$14,\nclc_build!R$40 < 1,\nTXT_rooms!$E$15&S$8&TXT_rooms!$E$16 & S$9,\nAND(clc_build!R$40 > 1,clc_build!R$39 < 1),TXT_rooms!$E$17&S$8&TXT_rooms!$E$18\n)",
  "T10":  /* formula */ "_xlfn.IFS(\nclc_build!S$39 > 1,\nTXT_rooms!$E$19,\nclc_build!S$40<0.5,\nTXT_rooms!$E$13 & T7 & TXT_rooms!$E$14,\nclc_build!S$40 < 1,\nTXT_rooms!$E$15&T$8&TXT_rooms!$E$16 & T$9,\nAND(clc_build!S$40 > 1,clc_build!S$39 < 1),TXT_rooms!$E$17&T$8&TXT_rooms!$E$18\n)",
  "U10":  /* formula */ "_xlfn.IFS(\nclc_build!T$39 > 1,\nTXT_rooms!$E$19,\nclc_build!T$40<0.5,\nTXT_rooms!$E$13 & U7 & TXT_rooms!$E$14,\nclc_build!T$40 < 1,\nTXT_rooms!$E$15&U$8&TXT_rooms!$E$16 & U$9,\nAND(clc_build!T$40 > 1,clc_build!T$39 < 1),TXT_rooms!$E$17&U$8&TXT_rooms!$E$18\n)",
  "V10":  /* formula */ "_xlfn.IFS(\nclc_build!U$39 > 1,\nTXT_rooms!$E$19,\nclc_build!U$40<0.5,\nTXT_rooms!$E$13 & V7 & TXT_rooms!$E$14,\nclc_build!U$40 < 1,\nTXT_rooms!$E$15&V$8&TXT_rooms!$E$16 & V$9,\nAND(clc_build!U$40 > 1,clc_build!U$39 < 1),TXT_rooms!$E$17&V$8&TXT_rooms!$E$18\n)",
  "A11":  /* unknown */ "\"Kalkulierte Raumheizlast\" - Wert 1",
  "B11":  /* unknown */ "room",
  "D11":  /* unknown */ "Qdot_room_cor",
  "H11":  /* formula */ "clc_build!G7",
  "I11":  /* formula */ "clc_build!H7",
  "J11":  /* formula */ "clc_build!I7",
  "K11":  /* formula */ "clc_build!J7",
  "L11":  /* formula */ "clc_build!K7",
  "M11":  /* formula */ "clc_build!L7",
  "N11":  /* formula */ "clc_build!M7",
  "O11":  /* formula */ "clc_build!N7",
  "P11":  /* formula */ "clc_build!O7",
  "Q11":  /* formula */ "clc_build!P7",
  "R11":  /* formula */ "clc_build!Q7",
  "S11":  /* formula */ "clc_build!R7",
  "T11":  /* formula */ "clc_build!S7",
  "U11":  /* formula */ "clc_build!T7",
  "V11":  /* formula */ "clc_build!U7",
  "A12":  /* unknown */ "\"Kalkulierte Raumheizlast\" - Wert 2",
  "D12":  /* unknown */ "qdot_room_cor",
  "H12":  /* formula */ "clc_build!G8",
  "I12":  /* formula */ "clc_build!H8",
  "J12":  /* formula */ "clc_build!I8",
  "K12":  /* formula */ "clc_build!J8",
  "L12":  /* formula */ "clc_build!K8",
  "M12":  /* formula */ "clc_build!L8",
  "N12":  /* formula */ "clc_build!M8",
  "O12":  /* formula */ "clc_build!N8",
  "P12":  /* formula */ "clc_build!O8",
  "Q12":  /* formula */ "clc_build!P8",
  "R12":  /* formula */ "clc_build!Q8",
  "S12":  /* formula */ "clc_build!R8",
  "T12":  /* formula */ "clc_build!S8",
  "U12":  /* formula */ "clc_build!T8",
  "V12":  /* formula */ "clc_build!U8",
  "A13":  /* unknown */ "Ausgabewert \"Kalkulierte Raumheizlast\" als String",
  "D13":  /* unknown */ "TXT_qdot_room",
  "H13":  /* formula */ "TEXT(H11,\"0\")&\" Watt | \" & TEXT(H12,\"0\") & \" W/m²\"",
  "I13":  /* formula */ "TEXT(I11,\"0\")&\" Watt | \" & TEXT(I12,\"0\") & \" W/m²\"",
  "J13":  /* formula */ "TEXT(J11,\"0\")&\" Watt | \" & TEXT(J12,\"0\") & \" W/m²\"",
  "K13":  /* formula */ "TEXT(K11,\"0\")&\" Watt | \" & TEXT(K12,\"0\") & \" W/m²\"",
  "L13":  /* formula */ "TEXT(L11,\"0\")&\" Watt | \" & TEXT(L12,\"0\") & \" W/m²\"",
  "M13":  /* formula */ "TEXT(M11,\"0\")&\" Watt | \" & TEXT(M12,\"0\") & \" W/m²\"",
  "N13":  /* formula */ "TEXT(N11,\"0\")&\" Watt | \" & TEXT(N12,\"0\") & \" W/m²\"",
  "O13":  /* formula */ "TEXT(O11,\"0\")&\" Watt | \" & TEXT(O12,\"0\") & \" W/m²\"",
  "P13":  /* formula */ "TEXT(P11,\"0\")&\" Watt | \" & TEXT(P12,\"0\") & \" W/m²\"",
  "Q13":  /* formula */ "TEXT(Q11,\"0\")&\" Watt | \" & TEXT(Q12,\"0\") & \" W/m²\"",
  "R13":  /* formula */ "TEXT(R11,\"0\")&\" Watt | \" & TEXT(R12,\"0\") & \" W/m²\"",
  "S13":  /* formula */ "TEXT(S11,\"0\")&\" Watt | \" & TEXT(S12,\"0\") & \" W/m²\"",
  "T13":  /* formula */ "TEXT(T11,\"0\")&\" Watt | \" & TEXT(T12,\"0\") & \" W/m²\"",
  "U13":  /* formula */ "TEXT(U11,\"0\")&\" Watt | \" & TEXT(U12,\"0\") & \" W/m²\"",
  "V13":  /* formula */ "TEXT(V11,\"0\")&\" Watt | \" & TEXT(V12,\"0\") & \" W/m²\"",
  "A14":  /* unknown */ "\"Wie gut sind die Heizkörper geeignet?\" - Leistung Aktueller Heizkörper",
  "D14":  /* unknown */ "TXT_Qdot_rad_act",
  "H14":  /* formula */ "TEXT(clc_build!G37,\"0\") & \" Watt\"",
  "I14":  /* formula */ "TEXT(clc_build!H37,\"0\") & \" Watt\"",
  "J14":  /* formula */ "TEXT(clc_build!I37,\"0\") & \" Watt\"",
  "K14":  /* formula */ "TEXT(clc_build!J37,\"0\") & \" Watt\"",
  "L14":  /* formula */ "TEXT(clc_build!K37,\"0\") & \" Watt\"",
  "M14":  /* formula */ "TEXT(clc_build!L37,\"0\") & \" Watt\"",
  "N14":  /* formula */ "TEXT(clc_build!M37,\"0\") & \" Watt\"",
  "O14":  /* formula */ "TEXT(clc_build!N37,\"0\") & \" Watt\"",
  "P14":  /* formula */ "TEXT(clc_build!O37,\"0\") & \" Watt\"",
  "Q14":  /* formula */ "TEXT(clc_build!P37,\"0\") & \" Watt\"",
  "R14":  /* formula */ "TEXT(clc_build!Q37,\"0\") & \" Watt\"",
  "S14":  /* formula */ "TEXT(clc_build!R37,\"0\") & \" Watt\"",
  "T14":  /* formula */ "TEXT(clc_build!S37,\"0\") & \" Watt\"",
  "U14":  /* formula */ "TEXT(clc_build!T37,\"0\") & \" Watt\"",
  "V14":  /* formula */ "TEXT(clc_build!U37,\"0\") & \" Watt\"",
  "A15":  /* unknown */ "\"Wie gut sind die Heizkörper geeignet?\" - Leistung Besserer heizkörper (Typ 33)",
  "D15":  /* unknown */ "TXT_Qdot_rad_typ33",
  "H15":  /* formula */ "TEXT(clc_build!G38,\"0\") & \" Watt\"",
  "I15":  /* formula */ "TEXT(clc_build!H38,\"0\") & \" Watt\"",
  "J15":  /* formula */ "TEXT(clc_build!I38,\"0\") & \" Watt\"",
  "K15":  /* formula */ "TEXT(clc_build!J38,\"0\") & \" Watt\"",
  "L15":  /* formula */ "TEXT(clc_build!K38,\"0\") & \" Watt\"",
  "M15":  /* formula */ "TEXT(clc_build!L38,\"0\") & \" Watt\"",
  "N15":  /* formula */ "TEXT(clc_build!M38,\"0\") & \" Watt\"",
  "O15":  /* formula */ "TEXT(clc_build!N38,\"0\") & \" Watt\"",
  "P15":  /* formula */ "TEXT(clc_build!O38,\"0\") & \" Watt\"",
  "Q15":  /* formula */ "TEXT(clc_build!P38,\"0\") & \" Watt\"",
  "R15":  /* formula */ "TEXT(clc_build!Q38,\"0\") & \" Watt\"",
  "S15":  /* formula */ "TEXT(clc_build!R38,\"0\") & \" Watt\"",
  "T15":  /* formula */ "TEXT(clc_build!S38,\"0\") & \" Watt\"",
  "U15":  /* formula */ "TEXT(clc_build!T38,\"0\") & \" Watt\"",
  "V15":  /* formula */ "TEXT(clc_build!U38,\"0\") & \" Watt\"",
  "A16":  /* unknown */ "\"Wie gut sind die Heizkörper geeignet?\" - Deckung Aktueller Heizkörper",
  "D16":  /* unknown */ "TXT_r_rad_act",
  "H16":  /* formula */ "TEXT(clc_build!G39*100,\"0\") & \" % Deckung\"",
  "I16":  /* formula */ "TEXT(clc_build!H39*100,\"0\") & \" % Deckung\"",
  "J16":  /* formula */ "TEXT(clc_build!I39*100,\"0\") & \" % Deckung\"",
  "K16":  /* formula */ "TEXT(clc_build!J39*100,\"0\") & \" % Deckung\"",
  "L16":  /* formula */ "TEXT(clc_build!K39*100,\"0\") & \" % Deckung\"",
  "M16":  /* formula */ "TEXT(clc_build!L39*100,\"0\") & \" % Deckung\"",
  "N16":  /* formula */ "TEXT(clc_build!M39*100,\"0\") & \" % Deckung\"",
  "O16":  /* formula */ "TEXT(clc_build!N39*100,\"0\") & \" % Deckung\"",
  "P16":  /* formula */ "TEXT(clc_build!O39*100,\"0\") & \" % Deckung\"",
  "Q16":  /* formula */ "TEXT(clc_build!P39*100,\"0\") & \" % Deckung\"",
  "R16":  /* formula */ "TEXT(clc_build!Q39*100,\"0\") & \" % Deckung\"",
  "S16":  /* formula */ "TEXT(clc_build!R39*100,\"0\") & \" % Deckung\"",
  "T16":  /* formula */ "TEXT(clc_build!S39*100,\"0\") & \" % Deckung\"",
  "U16":  /* formula */ "TEXT(clc_build!T39*100,\"0\") & \" % Deckung\"",
  "V16":  /* formula */ "TEXT(clc_build!U39*100,\"0\") & \" % Deckung\"",
  "A17":  /* unknown */ "\"Wie gut sind die Heizkörper geeignet?\" - Deckung Besserer heizkörper (Typ 33)",
  "D17":  /* unknown */ "TXT_r_rad_typ33",
  "H17":  /* formula */ "TEXT(clc_build!G40*100,\"0\") & \" % Deckung\"",
  "I17":  /* formula */ "TEXT(clc_build!H40*100,\"0\") & \" % Deckung\"",
  "J17":  /* formula */ "TEXT(clc_build!I40*100,\"0\") & \" % Deckung\"",
  "K17":  /* formula */ "TEXT(clc_build!J40*100,\"0\") & \" % Deckung\"",
  "L17":  /* formula */ "TEXT(clc_build!K40*100,\"0\") & \" % Deckung\"",
  "M17":  /* formula */ "TEXT(clc_build!L40*100,\"0\") & \" % Deckung\"",
  "N17":  /* formula */ "TEXT(clc_build!M40*100,\"0\") & \" % Deckung\"",
  "O17":  /* formula */ "TEXT(clc_build!N40*100,\"0\") & \" % Deckung\"",
  "P17":  /* formula */ "TEXT(clc_build!O40*100,\"0\") & \" % Deckung\"",
  "Q17":  /* formula */ "TEXT(clc_build!P40*100,\"0\") & \" % Deckung\"",
  "R17":  /* formula */ "TEXT(clc_build!Q40*100,\"0\") & \" % Deckung\"",
  "S17":  /* formula */ "TEXT(clc_build!R40*100,\"0\") & \" % Deckung\"",
  "T17":  /* formula */ "TEXT(clc_build!S40*100,\"0\") & \" % Deckung\"",
  "U17":  /* formula */ "TEXT(clc_build!T40*100,\"0\") & \" % Deckung\"",
  "V17":  /* formula */ "TEXT(clc_build!U40*100,\"0\") & \" % Deckung\"",
  "A20":  /* unknown */ "Warnhinweis Raumebene",
  "B20":  /* unknown */ "room",
  "D20":  /* unknown */ "TXT_room_RW",
  "G20":  /* unknown */ "RW",
  "I20":  /* formula */ "IF(clc_load!J$5=\"Bad*\",\nIF(clc_load!J$10>24,TXT_rooms!$E$20,\"\"),\nIF(clc_load!J$10>20,TXT_rooms!$E$20,\"\")\n)",
  "J20":  /* formula */ "IF(clc_load!K$5=\"Bad*\",\nIF(clc_load!K$10>24,TXT_rooms!$E$20,\"\"),\nIF(clc_load!K$10>20,TXT_rooms!$E$20,\"\")\n)",
  "K20":  /* formula */ "IF(clc_load!L$5=\"Bad*\",\nIF(clc_load!L$10>24,TXT_rooms!$E$20,\"\"),\nIF(clc_load!L$10>20,TXT_rooms!$E$20,\"\")\n)",
  "L20":  /* formula */ "IF(clc_load!M$5=\"Bad*\",\nIF(clc_load!M$10>24,TXT_rooms!$E$20,\"\"),\nIF(clc_load!M$10>20,TXT_rooms!$E$20,\"\")\n)",
  "M20":  /* formula */ "IF(clc_load!N$5=\"Bad*\",\nIF(clc_load!N$10>24,TXT_rooms!$E$20,\"\"),\nIF(clc_load!N$10>20,TXT_rooms!$E$20,\"\")\n)",
  "A24":  /* unknown */ "Input Warnungen >> @Till: keine Priorität, wird nach OUT_build umgesetzt",
  "A25":  /* unknown */ "AW-Länge > Kantenlänge Quadrat mit Raumfläche ",
  "A26":  /* unknown */ "A_win > A_wall ",
  "A27":  /* unknown */ "A_roof_win > A_roof ",
  "A28":  /* unknown */ "kein Heizkörper angelegt ",
  "A29":  /* unknown */ "L_roof_jamb_hei > L_wall_hei",
  "A30":  /* unknown */ "Geometrie Dachfläche (Hypotenuse <Ankatete)",
} as const;
