// Sheet: res_col
export const data = {
  "B2":  /* formula */ "clc_load!#REF!",
  "B3":  /* unknown */ "Heizlast",
  "C3":  /* formula */ "clc_load!$I$72/1000",
  "D3":  /* unknown */ "[kW]",
  "B4":  /* unknown */ "Norm-Heizleistung aller Heizkörper",
  "C4":  /* formula */ "(clc_col!C11+clc_col!C31)/1000",
  "D4":  /* unknown */ "[kW]",
  "B5":  /* unknown */ "Deckungsgrad total bei Normbedingungen",
  "C5":  /* formula */ "$C$4/$C$3",
  "D5":  /* unknown */ "[-]",
  "B6":  /* unknown */ "Heizleistung aller Heizkörper bei NT-ready Vorlauftemperatur",
  "C6":  /* formula */ "(clc_col!C16+clc_col!C36)/1000",
  "D6":  /* unknown */ "[kW]",
  "B7":  /* unknown */ "Deckungsgrad total bei NT-ready",
  "C7":  /* formula */ "$C$6/$C$3",
  "D7":  /* unknown */ "[-]",
  "B8":  /* unknown */ "Empfehlungen",
  "B14":  /* unknown */ "Raum 2",
  "D14":  /* unknown */ "[kW]",
  "B15":  /* formula */ "B3",
  "D15":  /* unknown */ "[kW]",
  "B16":  /* formula */ "B4",
  "D16":  /* unknown */ "[-]",
  "B17":  /* formula */ "B5",
  "D17":  /* unknown */ "[-]",
  "B18":  /* formula */ "B7",
  "B20":  /* unknown */ "Raum 3",
  "D20":  /* unknown */ "[kW]",
  "B21":  /* formula */ "B15",
  "D21":  /* unknown */ "[kW]",
  "B22":  /* formula */ "B16",
  "D22":  /* unknown */ "[-]",
  "B23":  /* formula */ "B17",
  "D23":  /* unknown */ "[-]",
  "B24":  /* formula */ "B18",
  "B26":  /* unknown */ "Raum 4",
  "D26":  /* unknown */ "[kW]",
  "B27":  /* formula */ "B21",
  "D27":  /* unknown */ "[kW]",
  "B28":  /* formula */ "B22",
  "D28":  /* unknown */ "[-]",
  "B29":  /* formula */ "B23",
  "D29":  /* unknown */ "[-]",
  "B30":  /* formula */ "B24",
  "B32":  /* unknown */ "Raum 5",
  "D32":  /* unknown */ "[kW]",
  "B33":  /* formula */ "B27",
  "D33":  /* unknown */ "[kW]",
  "B34":  /* formula */ "B28",
  "D34":  /* unknown */ "[-]",
  "B35":  /* formula */ "B29",
  "D35":  /* unknown */ "[-]",
  "B36":  /* formula */ "B30",
} as const;
