// Sheet: res_flat
export const data = {
  "B2":  /* formula */ "clc_load!#REF!",
  "B3":  /* unknown */ "Heizlast",
  "C3":  /* formula */ "clc_load!$I$72/1000",
  "D3":  /* unknown */ "[kW]",
  "B4":  /* unknown */ "Norm-Heizleistung aller Heizkörper",
  "C4":  /* formula */ "(clc_flat!$C$14)/1000",
  "D4":  /* unknown */ "[kW]",
  "B5":  /* unknown */ "Deckungsgrad total bei Normbedingungen",
  "C5":  /* formula */ "$C$4/$C$3",
  "B6":  /* unknown */ "Heizleistung aller Heizkörper bei NT-ready Vorlauftemperatur",
  "C6":  /* formula */ "(clc_flat!$C$16)/1000",
  "D6":  /* unknown */ "[kW]",
  "B7":  /* unknown */ "Deckungsgrad total bei NT-ready",
  "C7":  /* formula */ "$C$6/$C$3",
  "B8":  /* unknown */ "Deckungsgrad bei Austausch durch Typ 33",
  "C8":  /* formula */ "clc_flat!C17/1000/$C$3",
  "B9":  /* unknown */ "Empfehlungen",
  "B15":  /* unknown */ "Raum 2",
  "D15":  /* unknown */ "[kW]",
  "B16":  /* formula */ "B3",
  "D16":  /* unknown */ "[kW]",
  "B17":  /* formula */ "B4",
  "D17":  /* unknown */ "[-]",
  "B18":  /* formula */ "B5",
  "D18":  /* unknown */ "[-]",
  "B19":  /* formula */ "B7",
  "B21":  /* unknown */ "Raum 3",
  "D21":  /* unknown */ "[kW]",
  "B22":  /* formula */ "B16",
  "D22":  /* unknown */ "[kW]",
  "B23":  /* formula */ "B17",
  "D23":  /* unknown */ "[-]",
  "B24":  /* formula */ "B18",
  "D24":  /* unknown */ "[-]",
  "B25":  /* formula */ "B19",
  "B27":  /* unknown */ "Raum 4",
  "D27":  /* unknown */ "[kW]",
  "B28":  /* formula */ "B22",
  "D28":  /* unknown */ "[kW]",
  "B29":  /* formula */ "B23",
  "D29":  /* unknown */ "[-]",
  "B30":  /* formula */ "B24",
  "D30":  /* unknown */ "[-]",
  "B31":  /* formula */ "B25",
  "B33":  /* unknown */ "Raum 5",
  "D33":  /* unknown */ "[kW]",
  "B34":  /* formula */ "B28",
  "D34":  /* unknown */ "[kW]",
  "B35":  /* formula */ "B29",
  "D35":  /* unknown */ "[-]",
  "B36":  /* formula */ "B30",
  "D36":  /* unknown */ "[-]",
  "B37":  /* formula */ "B31",
} as const;
