// Sheet: Skala_Marker
export const data = {
  "A1":  /* unknown */ "Deckungsgrad Test",
  "B1":  /* unknown */ 0.6,
  "B3":  /* unknown */ "grün",
  "C3":  /* unknown */ "gelb",
  "D3":  /* unknown */ "orange",
  "E3":  /* unknown */ "rot ",
  "H3":  /* unknown */ "Alte Formel Zeile 35 OUT_rooms",
  "I3":  /* formula */ "_xlfn.LET(\n  _xlpm.deck_ist,clc_build!G$39,\n\n     _xlfn.IFS(\n      _xlpm.deck_ist>=1,0.125,\n      0.8>=_xlpm.deck_ist<1, _xlpm.deck_ist*0.245,\n       0.8<_xlpm.deck_ist>=0.6, _xlpm.deck_ist*0.495,\n        0.6<_xlpm.deck_ist, _xlpm.deck_ist*0.745))",
  "A4":  /* unknown */ "Deckungsgrad",
  "H4":  /* unknown */ "Alte Formel Zeile 36 OUT_rooms",
  "I4":  /* formula */ "_xlfn.LET(\n\n  _xlpm.deck_Typ33,clc_build!H$40,\n     _xlfn.IFS(\n      _xlpm.deck_Typ33>1,0.125,\n      0.8>=_xlpm.deck_Typ33<1, _xlpm.deck_Typ33*0.245,\n       0.8<_xlpm.deck_Typ33>=0.6, _xlpm.deck_Typ33*0.495,\n        0.6<_xlpm.deck_Typ33, _xlpm.deck_Typ33*0.745))",
  "A5":  /* unknown */ "von",
  "B5":  /* unknown */ 1.5,
  "C5":  /* unknown */ 1,
  "D5":  /* unknown */ 0.8,
  "E5":  /* unknown */ 0.6,
  "N5":  /* unknown */ "Test  AW Fläche ",
  "O5":  /* formula */ "IF(\n    OR(IN_rooms!R$28=\"Nein\",IN_rooms!R$31=0,IN_rooms!R$30 = 0,  IN_rooms!R$9 = 0,IN_build!$P$4 = \"Flach bzw. Flachdach\"),\n    IN_rooms!R$9 * IN_rooms!R$5 - (IN_rooms!R$13 * IN_rooms!R$14 +\n    IN_rooms!R$17 * IN_rooms!R$18 + IN_rooms!R$21 * IN_rooms!R$22),\n_xlfn.LET(\n  _xlpm.b_ceil, IN_rooms!R$32,\n  _xlpm.b_room, IF(IN_rooms!R$29=\"Nein\", IN_rooms!R$4 / IN_rooms!R$30, 2 * IN_rooms!R$4 / IN_rooms!R$30),\n  _xlpm.L_wall, IN_rooms!R$9,\n  _xlpm.L_giebel, IF(_xlpm.L_wall / 1.5 <= _xlpm.b_room, _xlpm.L_wall, _xlpm.L_wall / 2),\n  _xlpm.h_knee, IF(IN_rooms!R$37 > 0, IN_rooms!R$37, IN_rooms!R$39),\n  _xlpm.h_roof, IN_rooms!R$31,\n  _xlpm.is_jamb, IN_rooms!R$35=\"Ja\",\n  _xlpm.h_room, IN_rooms!R$5,\n  _xlpm.alpha, _xlfn.IFS(\n    IN_build!$P$4 = \"geneigt\", 25,\n    IN_build!$P$4 = \"steil\", 40,\n    IN_build!$P$4 = \"sehr steil\", 55),\n  _xlpm.A_win, (IN_rooms!R$13 * IN_rooms!R$14 + IN_rooms!R$17 * IN_rooms!R$18 + IN_rooms!R$21 * IN_rooms!R$22),\n  _xlpm.A_knee, IF(_xlpm.is_jamb, 0, _xlpm.h_knee *  IN_rooms!R$30),\n  _xlpm.A_no_slop, IN_rooms!R$9 * IN_rooms!R$5 - _xlpm.A_win,\n   _xlpm.A_big_rect, _xlpm.h_roof * _xlpm.b_ceil,\n  _xlpm.A_triangle, IF(_xlpm.h_roof < _xlpm.L_giebel - _xlpm.b_ceil,0, 1/2 * (_xlpm.L_giebel - _xlpm.b_ceil) * SQRT(_xlpm.h_roof^2 - (_xlpm.L_giebel - _xlpm.b_ceil)^2)),\n  _xlpm.A_small_rect, _xlpm.h_knee * _xlpm.h_roof * COS(_xlpm.alpha*PI()/180),\n  _xlpm.A_triangle_jamb, 1/2 * _xlpm.h_knee^2 * _xlfn.COT(_xlpm.alpha*PI()/180),\n  _xlpm.A_slop_tot, _xlpm.A_triangle + _xlpm.A_small_rect + IF(_xlpm.is_jamb, _xlpm.A_triangle_jamb,0),\n\n  _xlpm.giebel_1_slop_1, AND(IN_rooms!R$29 = \"Nein\", _xlpm.L_wall / 1.5 <= _xlpm.b_room),\n  _xlpm.giebel_2_slop_1, AND(IN_rooms!R$29 = \"Nein\", _xlpm.L_wall / 1.5 > _xlpm.b_room),\n  _xlpm.giebel_1_slop_2, AND(IN_rooms!R$29 = \"Ja\", _xlpm.L_wall / 1.5 <= _xlpm.b_room),\n  _xlpm.giebel_2_slop_2, AND(IN_rooms!R$29 = \"Ja\", _xlpm.L_wall / 1.5 > _xlpm.b_room),\n\n  MAX(MIN(_xlfn.IFS(\n    _xlpm.giebel_1_slop_1, _xlpm.A_big_rect + _xlpm.A_slop_tot - _xlpm.A_win,\n    _xlpm.giebel_2_slop_1, 2 * (_xlpm.A_big_rect + _xlpm.A_slop_tot) - _xlpm.A_win,\n    _xlpm.giebel_1_slop_2, _xlpm.A_big_rect + 2 * _xlpm.A_slop_tot - _xlpm.A_win,\n    _xlpm.giebel_2_slop_2, 2 * (_xlpm.A_big_rect + 2 * _xlpm.A_slop_tot) - _xlpm.A_win,\n    TRUE, _xlpm.A_no_slop),_xlpm.A_no_slop) + _xlpm.A_knee,0)\n))",
  "A6":  /* unknown */ "bis",
  "B6":  /* unknown */ 1,
  "C6":  /* unknown */ 0.8,
  "D6":  /* unknown */ 0.6,
  "E6":  /* unknown */ 0.4,
  "N6":  /* unknown */ "Test Dachlfäche",
  "O6":  /* formula */ "_xlfn.IFS(\n   IN_rooms!R$28<>\"Ja\",\n    0,\n    IN_build!$P$4 = \"Flach bzw. Flachdach\",\n      IN_rooms!R$4     - (IN_rooms!R$41 * IN_rooms!R$42)\n      - (IN_rooms!R$45 * IN_rooms!R$46),\n  IN_rooms!R$39>0,\n    IN_rooms!R$30 * IN_rooms!R$31\n      * IF(IN_rooms!R$29=\"Nein\",1,2)\n    + IN_rooms!R$39\n      / SIN(\n          _xlfn.IFS(\n            IN_build!$P$4=\"geneigt\",   25,\n            IN_build!$P$4=\"steil\",     40,\n            IN_build!$P$4=\"sehr steil\",55\n          )\n          * PI() / 180\n        )\n      * IN_rooms!R$30\n    - (IN_rooms!R$41 * IN_rooms!R$42)\n    - (IN_rooms!R$45 * IN_rooms!R$46),\n\n  OR(\n    IN_rooms!R$39=0,\n    IN_rooms!R$37>0\n  ),\n    IN_rooms!R$30 * IN_rooms!R$31\n    - (IN_rooms!R$41 * IN_rooms!R$42)\n    - (IN_rooms!R$45 * IN_rooms!R$46)\n)",
  "A7":  /* unknown */ "delta",
  "B7":  /* formula */ "B5-B6",
  "C7":  /* formula */ "C5-C6",
  "D7":  /* formula */ "D5-D6",
  "E7":  /* formula */ "E5-E6",
  "A9":  /* unknown */ "rel. Position Marker",
  "A10":  /* unknown */ "von",
  "B10":  /* unknown */ 0,
  "C10":  /* unknown */ 0.25,
  "D10":  /* unknown */ 0.5,
  "E10":  /* unknown */ 0.75,
  "A11":  /* unknown */ "bis",
  "B11":  /* unknown */ 0.25,
  "C11":  /* unknown */ 0.5,
  "D11":  /* unknown */ 0.75,
  "E11":  /* unknown */ 1,
  "A12":  /* unknown */ "delta",
  "A14":  /* unknown */ "Bedingung rel Position IST-Heizkörper",
  "B14":  /* unknown */ "rel_pos = MAX(0; MIN(,25; (1,5 - deck)*0,25/0,5))",
  "C14":  /* unknown */ "rel_pos = MAX(0,27; MIN(,5; 0,25 + (1 - deck)*0,25/0,2))",
  "D14":  /* unknown */ "rel_pos = MAX(0,52; MIN(,75; 0,5 + (0,8 - deck)*0,25/0,2))",
  "E14":  /* unknown */ "rel_pos = MAX(0,77; MIN(1; 0,75 + (0,6 - deck)*0,25/0,2))",
  "B15":  /* formula */ "MAX(0, MIN(0.25, (1.5 - B1)*0.25/0.5))",
  "C15":  /* formula */ "MAX(0.27, MIN(0.5, 0.25 + (1 - B1)*0.25/0.2))",
  "D15":  /* formula */ "MAX(0.52, MIN(0.75, 0.5 + (0.8 - B1)*0.25/0.2))",
  "E15":  /* formula */ "MAX(0.77, MIN(1, 0.75 + (0.6 - B1)*0.25/0.2))",
  "A17":  /* unknown */ "Bedingung rel Position Typ 33 (unabhängig von der NT-ready Bewertung des Raumes)",
  "B17":  /* unknown */ "rel_pos = MAX(0; MIN(,25; (1,5 - deck)*0,25/0,5))",
  "C17":  /* unknown */ "MAX(0,27; MIN(1; 0,25 + (1 - deck) *0,75/0,6))",
  "D17":  /* unknown */ "MAX(0,27; MIN(1; 0,25 + (1 - deck) *0,75/0,6))",
  "E17":  /* unknown */ "MAX(0,27; MIN(1; 0,25 + (1 - deck) *0,75/0,6))",
  "B18":  /* formula */ "MAX(0, MIN(0.25, (1.5 - B1)*0.25/0.5))",
  "C18":  /* formula */ "MAX(0.27, MIN(1, 0.25 + (1 - B1) *0.75/0.6))",
  "D18":  /* formula */ "MAX(0.27, MIN(1, 0.25 + (1 - B1) *0.75/0.6))",
  "E18":  /* formula */ "MAX(0.27, MIN(1, 0.25 + (1 - B1) *0.75/0.6))",
} as const;
