// Sheet: Syntax
export const data = {
  "A2":  /* richtext_as_string */ "Syntax Variablen: Größe | Medium | System | Subsystem | Spezifikation | Spezifikation 2",
  "A3":  /* unknown */ "Kursive Kategorien sind optional ",
  "B5":  /* unknown */ "Variable ",
  "C5":  /* unknown */ "Bezeichnung",
  "D5":  /* unknown */ "Einheit ",
  "A6":  /* unknown */ "(phys.) Größe ",
  "B6":  /* unknown */ "A",
  "C6":  /* unknown */ "Fläche",
  "D6":  /* unknown */ "m²",
  "B7":  /* unknown */ "B",
  "C7":  /* unknown */ "Zustandsgröße ",
  "B8":  /* unknown */ "EXIST",
  "C8":  /* unknown */ "Merkmal vorhanden",
  "B9":  /* unknown */ "freq",
  "C9":  /* unknown */ "Frequenz",
  "D9":  /* unknown */ "1/h",
  "B10":  /* unknown */ "ID",
  "C10":  /* unknown */ "Identifikationsnummer",
  "B11":  /* unknown */ "lambda",
  "C11":  /* unknown */ "Wärmeleitfähigkeit",
  "D11":  /* unknown */ "W/(mK)",
  "B12":  /* unknown */ "L",
  "C12":  /* unknown */ "Distanz",
  "D12":  /* unknown */ "m",
  "B13":  /* unknown */ "n",
  "C13":  /* unknown */ "Anzahl / Heizkörperexponent",
  "B14":  /* unknown */ "NO",
  "C14":  /* unknown */ "Nummer",
  "B15":  /* unknown */ "Q",
  "C15":  /* unknown */ "Wärmemenge",
  "D15":  /* unknown */ "Wh",
  "B16":  /* unknown */ "q",
  "C16":  /* unknown */ "spez. Wärmemenge",
  "B17":  /* unknown */ "Qdot",
  "C17":  /* unknown */ "Wärmestrom",
  "D17":  /* unknown */ "W",
  "B18":  /* unknown */ "qdot",
  "C18":  /* unknown */ "spez. Wärmeleistung",
  "B19":  /* unknown */ "R",
  "C19":  /* unknown */ "Wärmedurchgangswiderstand",
  "D19":  /* unknown */ "m²K/W",
  "B20":  /* unknown */ "r",
  "C20":  /* unknown */ "Anteil",
  "B21":  /* unknown */ "S",
  "C21":  /* unknown */ "Status",
  "B22":  /* unknown */ "T",
  "C22":  /* unknown */ "Temperatur",
  "D22":  /* unknown */ "°C",
  "B23":  /* unknown */ "Tdif",
  "C23":  /* unknown */ "Temperaturdifferenz ",
  "D23":  /* unknown */ "K ",
  "B24":  /* unknown */ "TXT",
  "C24":  /* unknown */ "Text",
  "B25":  /* unknown */ "TYP",
  "C25":  /* unknown */ "Art",
  "B26":  /* unknown */ "STYP",
  "C26":  /* unknown */ "Unterart",
  "B27":  /* unknown */ "U",
  "C27":  /* unknown */ "Wärmedurchgangskoeffizient",
  "D27":  /* unknown */ "W/(m²K)",
  "B28":  /* unknown */ "V",
  "C28":  /* unknown */ "Volumen ",
  "D28":  /* unknown */ "m³",
  "B29":  /* unknown */ "Vdot",
  "C29":  /* unknown */ "Volumenstrom",
  "D29":  /* unknown */ "m³/h",
  "B30":  /* unknown */ "YEAR",
  "C30":  /* unknown */ "Jahr",
  "D30":  /* unknown */ "-",
  "A36":  /* unknown */ "System/Subsystem",
  "B36":  /* unknown */ "build",
  "C36":  /* unknown */ "Gebäude",
  "B37":  /* unknown */ "room",
  "C37":  /* unknown */ "Raum ",
  "B38":  /* unknown */ "wall",
  "C38":  /* unknown */ "Außenwand",
  "B39":  /* unknown */ "heater",
  "C39":  /* unknown */ "Heizkörper",
  "B40":  /* unknown */ "inwall",
  "C40":  /* unknown */ "Innenwand",
  "B41":  /* unknown */ "heatp",
  "C41":  /* unknown */ "Wärmepumpe",
  "B42":  /* unknown */ "rad",
  "C42":  /* unknown */ "Radiator ",
  "B43":  /* unknown */ "win",
  "C43":  /* unknown */ "Fenster ",
  "B44":  /* unknown */ "roof",
  "C44":  /* unknown */ "Dach ",
  "B45":  /* unknown */ "topceil",
  "C45":  /* unknown */ "Decke ",
  "B46":  /* unknown */ "botceil",
  "C46":  /* unknown */ "Boden ",
  "B47":  /* unknown */ "ins",
  "C47":  /* unknown */ "Dämmung ",
  "B48":  /* unknown */ "conn",
  "C48":  /* unknown */ "Bauteilanschluss",
  "B49":  /* unknown */ "slop",
  "C49":  /* unknown */ "Schräge",
  "A50":  /* unknown */ "Spezifikation",
  "B50":  /* unknown */ "trans",
  "C50":  /* unknown */ "Transmission",
  "B51":  /* unknown */ "vent",
  "C51":  /* unknown */ "Ventilation ",
  "B52":  /* unknown */ "flat",
  "C52":  /* unknown */ "Flach",
  "B53":  /* unknown */ "col",
  "C53":  /* unknown */ "Gliederheizkörper (column radiator)",
  "B54":  /* unknown */ "conv",
  "C54":  /* unknown */ "Konvektor",
  "B55":  /* unknown */ "tube",
  "C55":  /* unknown */ "Rohrradiator ",
  "B56":  /* unknown */ "tubular",
  "C56":  /* unknown */ "Rohrheizkörper",
  "B57":  /* unknown */ "heated",
  "C57":  /* unknown */ "beheizt ",
  "B58":  /* unknown */ "unheated",
  "C58":  /* unknown */ "unbeheizt/Erdreich",
  "B59":  /* unknown */ "amb",
  "C59":  /* unknown */ "Außenluft/Umgebung ",
  "B60":  /* unknown */ "VL",
  "C60":  /* unknown */ "Vorlauf",
  "B61":  /* unknown */ "RL",
  "C61":  /* unknown */ "Rücklauf",
  "B62":  /* unknown */ "In",
  "C62":  /* unknown */ "Eintritt",
  "B63":  /* unknown */ "Out",
  "C63":  /* unknown */ "Austritt",
  "B64":  /* unknown */ "len",
  "C64":  /* unknown */ "Länge",
  "B65":  /* unknown */ "wid",
  "C65":  /* unknown */ "Breite",
  "B66":  /* unknown */ "hei",
  "C66":  /* unknown */ "Höhe ",
  "B67":  /* unknown */ "thick",
  "C67":  /* unknown */ "Dicke",
  "B68":  /* unknown */ "set",
  "C68":  /* unknown */ "sollwert",
  "B69":  /* unknown */ "act",
  "C69":  /* unknown */ "Istwert",
  "B70":  /* unknown */ "bj",
  "C70":  /* unknown */ "Baujahr",
  "B71":  /* unknown */ "above",
  "C71":  /* unknown */ "oberhalb",
  "B72":  /* unknown */ "below",
  "C72":  /* unknown */ "unterhalb",
  "B73":  /* unknown */ "denkmal",
  "C73":  /* unknown */ "denkmalschutz",
  "B74":  /* unknown */ "distr",
  "C74":  /* unknown */ "Verteilung ",
  "B75":  /* unknown */ "meas",
  "C75":  /* unknown */ "gemessen",
  "B76":  /* unknown */ "calc",
  "C76":  /* unknown */ "berechnet",
  "B77":  /* unknown */ "nom",
  "C77":  /* unknown */ "nominal / Auslegungspunkt",
  "B78":  /* unknown */ "san",
  "C78":  /* unknown */ "modernisierung",
  "B79":  /* unknown */ "nt",
  "C79":  /* unknown */ "Niedertemperatur",
  "B80":  /* unknown */ "const",
  "C80":  /* unknown */ "Konstante",
  "B81":  /* unknown */ "norm",
  "C81":  /* unknown */ "normativ",
  "B82":  /* unknown */ "warn",
  "C82":  /* unknown */ "Warnhinweis",
} as const;
