// Sheet: Todo
export const data = {
  "A1":  /* unknown */ "Datum",
  "B1":  /* unknown */ "Sheet",
  "C1":  /* unknown */ "Zeile",
  "D1":  /* unknown */ "Bug?",
  "E1":  /* unknown */ "Beschreibung ",
  "F1":  /* unknown */ "viel Aufwand Till",
  "G1":  /* unknown */ "Priorität",
  "H1":  /* unknown */ "Status",
  "I1":  /* unknown */ "Kommentar",
  "A2":  /* unknown */ new Date("2025-05-20T00:00:00.000Z"),
  "B2":  /* unknown */ "IN_build",
  "E2":  /* unknown */ "Initial-Wert \"Ich kann im heizungsraum die Vorlauftemperatur..\"\nNein und keine Preset-Values, bereits in Excel angepasst",
  "G2":  /* unknown */ 1,
  "H2":  /* unknown */ "abgeschlossen",
  "A3":  /* unknown */ new Date("2025-05-20T00:00:00.000Z"),
  "B3":  /* unknown */ "IN_rooms",
  "E3":  /* unknown */ "Initial-Wert Raumfläche löschen ",
  "G3":  /* unknown */ 1,
  "H3":  /* unknown */ "abgeschlossen",
  "A4":  /* unknown */ new Date("2025-05-20T00:00:00.000Z"),
  "B4":  /* unknown */ "IN_rooms",
  "E4":  /* unknown */ "Abmaße Fenster in m statt cm ",
  "G4":  /* unknown */ 1,
  "A5":  /* unknown */ new Date("2025-05-20T00:00:00.000Z"),
  "B5":  /* unknown */ "IN_rooms",
  "E5":  /* unknown */ "Option \"wie Gebäude\" 2x aufgeführt\nLiegt der Fehler in Excel oder Typescript?",
  "G5":  /* unknown */ 2,
  "H5":  /* unknown */ "abgeschlossen",
  "A6":  /* unknown */ new Date("2025-05-20T00:00:00.000Z"),
  "G6":  /* unknown */ 2,
  "H6":  /* unknown */ "abgeschlossen",
  "A7":  /* unknown */ new Date("2025-05-20T00:00:00.000Z"),
  "B7":  /* unknown */ "IN_rooms",
  "E7":  /* unknown */ "Heizkörperhöhe bei Typ Rohrradiator, Subtyp Handtuchradiator als Freifeld statt Dropdown",
  "G7":  /* unknown */ 2,
  "H7":  /* unknown */ "abgeschlossen",
  "A8":  /* unknown */ new Date("2025-05-20T00:00:00.000Z"),
  "B8":  /* unknown */ "IN_rooms",
  "E8":  /* unknown */ "Dropdown HK Abmaße falsche Einheit \nDerzeit Werte in Liste noch in mm, Einheit aber cm ",
  "G8":  /* unknown */ 1,
  "A9":  /* unknown */ new Date("2025-05-20T00:00:00.000Z"),
  "B9":  /* unknown */ "IN_rooms",
  "E9":  /* unknown */ "Hilfstext bei gewünschter Raumtemp wird doppelt gezeigt (Mouseover Fragezeichen und dauerhaft sichtbar unter dem Eingabfeld für die Temp",
  "G9":  /* unknown */ 2,
  "H9":  /* unknown */ "ungelöst",
  "I9":  /* unknown */ "FM 1.7.25",
  "A10":  /* unknown */ new Date("2025-05-20T00:00:00.000Z"),
  "B10":  /* unknown */ "clc_load",
  "D10":  /* unknown */ "X",
  "E10":  /* unknown */ "U-Wert Berechnung Dach, Decke, Fußboden, Fenstern wird nicht akzeptiert. In Typescript resultiert immer = 1",
  "A11":  /* unknown */ new Date("2025-05-20T00:00:00.000Z"),
  "B11":  /* unknown */ "clc_load",
  "D11":  /* unknown */ "X",
  "E11":  /* unknown */ "Abmaße Fenster intern z.T. noch in cm verarbeitet, z.T. bereits in m ",
  "A12":  /* unknown */ new Date("2025-05-20T00:00:00.000Z"),
  "B12":  /* unknown */ "clc_load",
  "D12":  /* unknown */ "X",
  "E12":  /* unknown */ "Abweichung Flächenberechnung Außenwand und Dachfläche Excel vs. Typescript\nUrsache liegt nicht bei Fenster-Abmaßen (Einfluss identisch), sondern  bei Berechnung anhand Dachneigung, Giebel, Drempel usw.",
  "H12":  /* unknown */ "Todo_ifeu",
  "I12":  /* unknown */ "Todo Jakob: Fälle durchspielen für Debugging Berechnung ",
  "A13":  /* unknown */ new Date("2025-05-21T00:00:00.000Z"),
  "B13":  /* unknown */ "clc_power",
  "D13":  /* unknown */ "X",
  "E13":  /* unknown */ "Felder Breite und Tiefe scheinen in UI vertauscht, zumindest für Gliederheizkörper >> daher findet die Look-Up Funktion keinen Wert für nominale Leistung G21 usw\n\nRückmeldung Fachbeirat: Für die fiktive installierte Heizfläche „Gussradiator“ (2000x580x70mm, 20 Glieder) in einem Raum wird eine Heizleistung von 0 Watt berechnet. \n>> in Excel klappt die Eingabe, daher vsl. gleiches Problem",
  "A14":  /* unknown */ new Date("2025-08-01T00:00:00.000Z"),
  "B14":  /* unknown */ "IN_build",
  "E14":  /* unknown */ "Raumliste überarbeiten. Einzelne Abfragen in fünf Freifeldern entfernen und in einem Freifeld bündeln (siehe miro). \n\nFragentext: \"Bitte Räume zur Erfassung eingeben\"\u000b\nDarunter einen grünen Kasten mit Anweisungen:\n\u000bKritische Räume erkennen: \u000b- Bleibt der Raum im Winter oft zu kalt?\n- Hat der Raum viel Kontakt zur Außenluft (über Außenwand, Dach, Fenster)?\n- Liegt der Raum über oder unter unbeheizten Räumen oder direkt an Außenluft?\n- Hat der Raum viel Fensterfläche?\n\nHinweis: Mehrere Räume können durch (+) hinzugefügt werden. Es sind nur beheizte Räume relevant.",
  "A15":  /* unknown */ new Date("2025-08-01T00:00:00.000Z"),
  "B15":  /* unknown */ "IN_rooms",
  "E15":  /* unknown */ "Heizkörper Subtypen als Grafiken unterhalb Haupttyp aufführen. Siehe reduzierte Anzahl Subtypen Flachheizkörper in Log",
  "G15":  /* unknown */ 2,
  "A16":  /* unknown */ new Date("2025-08-01T00:00:00.000Z"),
  "B16":  /* unknown */ "IN_rooms",
  "E16":  /* unknown */ "Außenwand ohne Fenster abbilden:\nVorschlag: könnte man sowohl bei Fenster in Außenwand als auch bei Dachfenstern per default gar keine Fenstereingabe darstellen und nur einen Button \"+ weiteren Fenstertyp erfassen\" darstellen? Nur, wenn es sich einfach umsetzen lässt, da die +-Funktion ohnehin implementiert ist. ",
  "G16":  /* unknown */ 2,
  "A17":  /* unknown */ new Date("2025-08-01T00:00:00.000Z"),
  "B17":  /* unknown */ "IN_build",
  "E17":  /* unknown */ "Wurde z.T. so interpretiert, dass man direkt in der Liste klicken kann. \nGgf. stattdessen Hinweis: \"Es kann nur der letzte Raum in der Liste entfernt werden.\"\n>> @Till: was meinst Du aus User-Perspektive?",
  "A18":  /* unknown */ new Date("2025-08-01T00:00:00.000Z"),
  "B18":  /* unknown */ "OUT_rooms",
  "E18":  /* unknown */ "Grafik Heizkörpertausch und Bildunterschrift sind noch nicht mit den Ergebnissen verknüpft, derzeit immer \"orange\", \"Heizkörper vergrößern\" ",
  "A19":  /* unknown */ new Date("2025-08-01T00:00:00.000Z"),
  "B19":  /* unknown */ "OUT_rooms",
  "E19":  /* unknown */ "Grafiken Bauteilbewertung sind noch nicht mit den U-Werten der Bauteile verknüpft, derzeit alle Bauteile \"grün\" ",
  "A20":  /* unknown */ new Date("2025-08-01T00:00:00.000Z"),
  "B20":  /* unknown */ "OUT_build",
  "E20":  /* unknown */ "Raumübersicht: Gebäudegrafik zur Darstellung des schlechtesten Bauteils bei \"Erforderliche Heizlast\" fehlt. Diese soll anhand der Bauteilbezeichnung in Zeile 25 in OUT_rooms ausgewählt werden. Farbe des Bauteils anhand Zeile 26 OUT_rooms. \n\nWenn die Heizlast okay ist, dann bitte als Symbolbild \"pic_G2_load_wall\" mit Farbe \"green\" darstellen.",
  "A21":  /* unknown */ new Date("2025-08-01T00:00:00.000Z"),
  "B21":  /* unknown */ "OUT_build",
  "E21":  /* unknown */ "Raumübersicht: Bildunterschrift \"green\" bei \"Leistung der Heizkörper\" entfernen",
  "A22":  /* unknown */ new Date("2025-08-01T00:00:00.000Z"),
  "B22":  /* unknown */ "OUT_build",
  "E22":  /* unknown */ "Gebäudehülle: Bauteil-Grafiken werden noch nicht zur Bewertung eingefärbt und die Bildunterschrift (Anteil an den Transmissionswärmeverlusten) wird noch nicht korrekt angezeigt. ",
  "A23":  /* unknown */ new Date("2025-08-01T00:00:00.000Z"),
  "E23":  /* unknown */ "Wenn in ein Feld geklickt wird sollte der Inhalt automatisch markiert werden, damit bei der Eingabe einer Zahl, die derzeit vorhandene gelöscht wird.",
  "G23":  /* unknown */ 2,
  "A24":  /* unknown */ new Date("2025-08-01T00:00:00.000Z"),
  "B24":  /* unknown */ "IN_rooms",
  "E24":  /* unknown */ "Zwischentext🔥 Warum die Heizkörperdaten wichtig sind: In Navigationsleiste bereits „Heizflächen“ einfärben, damit klar wird, wozu die Information gehört.",
  "G24":  /* unknown */ 2,
  "A25":  /* unknown */ new Date("2025-08-01T00:00:00.000Z"),
  "E25":  /* unknown */ "Wäre es mit wenig Aufwand möglich, dass die Zwischentexte nur beim ersten Raum gezeigt werden? Oder Wiederholung für Laien User sinnvoll? ",
  "G25":  /* unknown */ 4,
  "A26":  /* unknown */ new Date("2025-08-01T00:00:00.000Z"),
  "E26":  /* unknown */ "Bei Importieren eines Datensatzes: PopUp \"Datenimport erfolgreich\" oÄ ",
  "A27":  /* unknown */ new Date("2025-08-01T00:00:00.000Z"),
  "E27":  /* unknown */ "Wäre eine einfache Funktion zum Zurücksetzen des Tools möglich oder aufwändig? Button \"Werte zurücksetzen\" ",
  "G27":  /* unknown */ 3,
  "A28":  /* unknown */ new Date("2025-08-01T00:00:00.000Z"),
  "B28":  /* unknown */ "IN_build",
  "E28":  /* unknown */ "Dropdownlisten Modernisierung (IN_build und IN_rooms) jeweils auf das eingegebene BJ des Gebäudes limitieren. Ggf. auch einfacher in Excel umzusetzen? ",
  "G28":  /* unknown */ 3,
  "A29":  /* unknown */ new Date("2025-08-01T00:00:00.000Z"),
  "E29":  /* unknown */ "Glossar anlegen ",
  "A30":  /* unknown */ new Date("2025-08-01T00:00:00.000Z"),
  "E30":  /* unknown */ "Tooltips analog der Einträge Glossar in statischen Texten anlegen ",
} as const;
