// Sheet: Todo
export const data = {
  "A1":  /* unknown */ "Sheet",
  "B1":  /* unknown */ "Top ",
  "C1":  /* unknown */ "Beschreibung ",
  "D1":  /* unknown */ "Priorität",
  "E1":  /* unknown */ "Status",
  "F1":  /* unknown */ "Kommentar",
  "A2":  /* unknown */ "IN_build",
  "B2":  /* unknown */ "Initial-Wert \"Ich kann im heizungsraum die Vorlauftemperatur..\"",
  "C2":  /* unknown */ "Nein und keine Preset-Values, bereits in Excel angepasst",
  "D2":  /* unknown */ 1,
  "A3":  /* unknown */ "IN_rooms",
  "B3":  /* unknown */ "Initial-Wert Raumfläche löschen ",
  "D3":  /* unknown */ 1,
  "A4":  /* unknown */ "IN_rooms",
  "B4":  /* unknown */ "Abmaße Fenster in m statt cm ",
  "D4":  /* unknown */ 1,
  "A5":  /* unknown */ "IN_rooms",
  "B5":  /* unknown */ "Außenwand ohne Fenster abbilden",
  "C5":  /* unknown */ "Bspw. Giebelwand z.T. ohne Fenster, daher Abmaße Fenster 1 nicht als Pflichtfeld ",
  "D5":  /* unknown */ 2,
  "A6":  /* unknown */ "IN_rooms",
  "B6":  /* unknown */ "Option \"wie Gebäude\" 2x aufgeführt",
  "C6":  /* unknown */ "Liegt der Fehler in Excel oder Typescript?",
  "D6":  /* unknown */ 2,
  "B7":  /* unknown */ "In Chrome werden die Räume mit leeren Strings noch nicht ausgeblendet, sondern als \"\" dargestellt ",
  "D7":  /* unknown */ 2,
  "A8":  /* unknown */ "IN_rooms",
  "B8":  /* unknown */ "Dropdown HK Abmaße falsche Einheit ",
  "C8":  /* unknown */ "Derzeit Werte in Liste noch in mm, Einheit aber cm ",
  "D8":  /* unknown */ 1,
  "A9":  /* unknown */ "IN_rooms",
  "B9":  /* unknown */ "Dachfenster Abmaße derzeit Pflichtfeld",
  "C9":  /* unknown */ "Sollte kein Pflichtfeld sein (siehe In_rooms) ",
  "D9":  /* unknown */ 1,
  "B10":  /* unknown */ "Schlechtpunkträume Beispiele ",
  "C10":  /* unknown */ "\"Ergänzen Sie falls vorhanden Räume deren Decke oder Boden an Außenluft oder unbeheizte Räume grenzt.\" \n>>  \"z.B. Kellerraum\" passt hier nicht, stattdessen \"z.B. Wohnzimmer\" ",
  "D10":  /* unknown */ 3,
  "B11":  /* unknown */ "Heizkörper Subtyp als Radio Button mit Grafik oder Info-Button mit Grafik",
  "D11":  /* unknown */ 3,
} as const;
