// Sheet: TXT_build
export const data = {
  "A1":  /* unknown */ "Gruppe",
  "B1":  /* unknown */ "Variable ",
  "C1":  /* unknown */ "Kommentar",
  "D1":  /* unknown */ "INPUT_TXT_rooms",
  "A2":  /* unknown */ "G1 NT-ready",
  "B2":  /* unknown */ "TXT_build_G1_not",
  "D2":  /* unknown */ "Derzeit nicht niedertemperaturfähig – Maßnahmen erforderlich\nNoch nicht bereit für einen Wärmepumpenbetrieb.\nEin niedertemperaturfähiges Gebäude sollte auch an kalten Wintertagen in allen Räumen mit einer Vorlauftemperatur von unter 55°C auskommen. Im jetzigen Zustand des Gebäudes ist die erforderliche Vorlauftemperatur deutlich zu hoch.\nIn den meisten Räumen sind entweder die Heizkörper oder die Gebäudehülle noch nicht geeignet. Ohne gezielte Verbesserungen wäre eine Wärmepumpe nicht wirtschaftlich zu betreiben. Sollten Sie umfangreichere Verbesserungen an der Gebäudehülle erst in ein paar Jahren planen, kann vorerst eine Hybrid-Wärmepumpe eine effiziente Lösung für Sie darstellen.",
  "A3":  /* unknown */ "G1 NT-ready",
  "B3":  /* unknown */ "TXT_build_G1_notyet",
  "D3":  /* unknown */ "Teilweise niedertemperaturfähig – Maßnahmen erforderlich\nGute Basis – mit Potenzial\nEin niedertemperaturfähiges Gebäude sollte auch an kalten Wintertagen in allen Räumen mit einer Vorlauftemperatur von unter 55°C auskommen. Im jetzigen Zustand des Gebäudes ist die erforderliche Vorlauftemperatur zu hoch.\nManche Räume erfüllen bereits die Anforderungen für niedrigere Vorlauftemperaturen. Einige Räume brauchen jedoch eine höhere Vorlauftemperatur. Mit einfachen, gezielten Maßnahmen kann das gesamte Gebäude NT-ready (für den Betrieb mit Vorlauftemperaturen unter 55°C geeignet) werden.",
  "A4":  /* unknown */ "G1 NT-ready",
  "B4":  /* unknown */ "TXT_build_G1_almost",
  "D4":  /* unknown */ "Fast niedertemperaturfähig – Maßnahmen empfehlenswert\nGute Basis – mit Potenzial\nEin niedertemperaturfähiges Gebäude sollte auch an kalten Wintertagen in allen Räumen mit einer Vorlauftemperatur von unter 55°C auskommen. Im jetzigen Zustand des Gebäudes ist die erforderliche Vorlauftemperatur etwas zu hoch.\nEinige Räume erfüllen bereits die Anforderungen für niedrigere Vorlauftemperaturen. Ein Praxischeck im ersten Winter kann Klarheit bringen, ob in den anderen Räumen kleine, gezielte Maßnahmen erforderlich sind, damit das gesamte Gebäude NT-ready (für den Betrieb mit Vorlauftemperaturen unter 55°C geeignet)  wird.",
  "A5":  /* unknown */ "G1 NT-ready",
  "B5":  /* unknown */ "TXT_build_G1_NTr",
  "D5":  /* unknown */ "Niedertemperaturfähig – gute Voraussetzungen\nBereit für die Wärmepumpe!\nAlle erfassten Räume können schon heute mit ausreichend geringer Vorlauftemperatur von unter 55°C effizient beheizt werden – das Gebäude ist NT-ready.",
  "A6":  /* unknown */ "G2 Dashboard",
  "B6":  /* unknown */ "TXT_build_G2_load_1",
  "A7":  /* unknown */ "G2 Dashboard",
  "B7":  /* unknown */ "TXT_build_G2_load_2",
  "A8":  /* unknown */ "G2 Dashboard",
  "B8":  /* unknown */ "TXT_build_G2_power_1",
  "A9":  /* unknown */ "G2 Dashboard",
  "B9":  /* unknown */ "TXT_build_G2_power_2",
  "A10":  /* unknown */ "G3 Heizkörpertausch",
  "B10":  /* unknown */ "TXT_build_G3_notsuff_1",
  "A11":  /* unknown */ "G3 Heizkörpertausch",
  "B11":  /* unknown */ "TXT_build_G3_notsuff_2",
  "D11":  /* unknown */ "Viele Heizkörper sind nicht geeignet – Maßnahmen erforderlich\nHier ist ein Heizkörpertausch notwendig.\n[Alle / x von y Heizkörpern] der in Ihrem Gebäude erfassten Räume benötigen aktuell eine sehr hohe Vorlauftemperatur. Damit eine Wärmepumpe effizient arbeiten kann, sollten Sie diese Heizkörper durch größere oder leistungsstärkere Modelle ersetzen.\n💡 Hinweis: Sie können weitere Räume eingeben, um ein vollständigeres Bild zu erhalten. Wenn nicht, sollte die Heizkörperbewertung im Rahmen der konkreten Planung erfolgen.",
  "A12":  /* unknown */ "G3 Heizkörpertausch",
  "B12":  /* unknown */ "TXT_build_G3_suffchangeobl_1",
  "A13":  /* unknown */ "G3 Heizkörpertausch",
  "B13":  /* unknown */ "TXT_build_G3_suffchangeobl_2",
  "D13":  /* unknown */ "Einzelne Heizkörper sind nicht geeignet – Maßnahmen sinnvoll\nEin Tausch verbessert die Effizienz.\nEin Teil der Heizkörper benötigt relativ hohe Vorlauftemperaturen. Durch einen Austausch gegen effizientere Modelle können Sie die Voraussetzungen für eine Wärmepumpe verbessern und zukünftig den Stromverbrauch fürs Heizen senken.\n💡 Hinweis: Prüfen Sie zusätzliche Räume oder klären Sie Details in der weiteren Planung.",
  "A14":  /* unknown */ "G3 Heizkörpertausch",
  "B14":  /* unknown */ "TXT_build_G3_suffchange_1",
  "A15":  /* unknown */ "G3 Heizkörpertausch",
  "B15":  /* unknown */ "TXT_build_G3_suffchange_2",
  "D15":  /* unknown */ "Die meisten Heizkörper passen\nEin Praxischeck (nach Einbau der Wärmepumpe prüfen, ob die kritischen Räume Ihren Bedürfnissen entsprechend warm werden) kann zeigen, ob die Leistung in kritischen Räumen ausreicht. \nEinige Heizkörper benötigen eine etwas zu hohe Vorlauftemperatur. Je nach Heizverhalten und Nutzung der Räume, können diese jedoch für einen effizienten Wärmepumpenbetrieb ausreichen. Nach der ersten Heizperiode mit Wärmepumpe haben Sie Klarheit und können über einen Austausch entscheiden. \n💡 Hinweis: Wenn Sie weitere Räume hinzufügen, kann die Einschätzung noch präziser werden.",
  "A16":  /* unknown */ "G3 Heizkörpertausch",
  "B16":  /* unknown */ "TXT_build_G3_suff_1",
  "A17":  /* unknown */ "G3 Heizkörpertausch",
  "B17":  /* unknown */ "TXT_build_G3_suff_2",
  "D17":  /* unknown */ "Heizkörper sind gut geeignet – keine Maßnahmen erforderlich\nGute Voraussetzungen!\nDie Heizkörper in den eingegebenen Räumen können die Raumheizlast bereits mit ausreichend geringer Vorlauftemperatur decken. Ein effizienter Wärmepumpenbetrieb ist möglich – ein Austausch ist nicht erforderlich.\n💡 Hinweis: Wenn Sie weitere Räume hinzufügen, kann die Einschätzung noch präziser werden.",
  "A18":  /* unknown */ "G4 Gebäudehülle ",
  "B18":  /* unknown */ "TXT_build_G4_intro_notsuit",
  "A19":  /* unknown */ "G4 Gebäudehülle ",
  "B19":  /* unknown */ "TXT_build_G4_intro_almostsuit",
  "A20":  /* unknown */ "G4 Gebäudehülle ",
  "B20":  /* unknown */ "TXT_build_G4_intro_suit",
  "A21":  /* unknown */ "G4 Gebäudehülle ",
  "B21":  /* unknown */ "TXT_build_G4_intro_verysuit",
  "A22":  /* unknown */ "G4 Gebäudehülle ",
  "B22":  /* unknown */ "TXT_buid_G4_wall_notsuit",
  "D22":  /* unknown */ "Hohe Wärmeverluste über die Außenwand – Dämmung erforderlich \nDie Außenwand hat einen sehr hohen U-Wert. Deshalb entweicht hier ein Großteil der Wärme. Eine (zusätzliche) Dämmung senkt den Energieverbrauch und die Heizlast deutlich.",
  "A23":  /* unknown */ "G4 Gebäudehülle ",
  "B23":  /* unknown */ "TXT_buid_G4_wall_almostsuit",
  "D23":  /* unknown */ "Außenwand mit hohem Energieverlust – Verbesserung empfohlen\nDie Dämmung der Außenwand ist unzureichend. Wärmeverluste sind deutlich spürbar. Eine energetische Verbesserung ist zu empfehlen und verbessert die Wärmepumpen-Eignung des gesamten Gebäudes. ",
  "A24":  /* unknown */ "G4 Gebäudehülle ",
  "B24":  /* unknown */ "TXT_buid_G4_wall_suit",
  "D24":  /* unknown */ "Ausbaufähiger Wärmeschutz Außenwand – Maßnahmen vorteilhaft\nDie Außenwand zeigt bereits einen moderaten Wärmeschutz. Eine zusätzliche Dämmung kann die Heizlast weiter reduzieren und damit die Wärmepumpen-Eignung verbessern. ",
  "A25":  /* unknown */ "G4 Gebäudehülle ",
  "B25":  /* unknown */ "TXT_buid_G4_wall_verysuit",
  "D25":  /* unknown */ "Außenwand gut gedämmt – geringe Wärmeverluste\nDie Außenwand hat einen guten energetischen Standard und sorgt für geringe Wärmeverluste. Damit bietet sie gute Voraussetzungen für den effizienten Betrieb einer Wärmepumpe. ",
  "A26":  /* unknown */ "G4 Gebäudehülle ",
  "B26":  /* unknown */ "TXT_buid_G4_win_notsuit",
  "D26":  /* unknown */ "Veraltete Fenster – Maßnahmen erforderlich\nDie Fenster verlieren sehr viel Wärme.\nIn vielen Räumen sind die Fenster energetisch veraltet. Der hohe Wärmeverlust verschlechtert die Effizienz einer Wärmepumpe. Ein Austausch ist empfehlenswert – am besten im Zuge einer möglichen Fassadensanierung, um Kosten zu sparen und die Fenster in die Dämmebene zu versetzen.",
  "A27":  /* unknown */ "G4 Gebäudehülle ",
  "B27":  /* unknown */ "TXT_buid_G4_win_almostsuit",
  "D27":  /* unknown */ "Einige Fenster veraltet – Maßnahmen sinnvoll\nFenster verlieren viel Wärme.\nEinige Fenster sind energetisch ungünstig veraltet. Der Austausch – am besten im Zuge einer möglichen Fassadensanierung – verbessert die Wärmepumpen-Eignung und spart Energie.",
  "A28":  /* unknown */ "G4 Gebäudehülle ",
  "B28":  /* unknown */ "TXT_buid_G4_win_suit",
  "D28":  /* unknown */ "Einzelne Fenster als Schwachstelle – Maßnahmen vorteilhaft\nFenster verbessern – für mehr Effizienz.\nEinige Fenster sind energetisch ungünstig. Der Austausch verbessert die Wärmepumpen-Eignung und spart Energie.",
  "A29":  /* unknown */ "G4 Gebäudehülle ",
  "B29":  /* unknown */ "TXT_buid_G4_win_verysuit",
  "D29":  /* unknown */ "Fenster in gutem Zustand – kein Austausch nötig\nAlles im grünen Bereich.\nDie Fenster sind ausreichend wärmedämmend – für die Nutzung einer Wärmepumpe bestehen keine Einschränkungen.",
  "A30":  /* unknown */ "G4 Gebäudehülle ",
  "B30":  /* unknown */ "TXT_buid_G4_roof_notsuit",
  "D30":  /* unknown */ "Dach mit sehr hohen Wärmeverlusten – Dämmung erforderlich\nDas Dach besitzt aktuell wenig Wärmeschutz. Dadurch entstehen hohe Wärmeverluste, die die Heizlast deutlich erhöhen. Eine Dämmung kann hier wirksam Abhilfe schaffen – sie verbessert den Wohnkomfort und trägt zur Reduktion der Vorlauftemperatur bei.",
  "A31":  /* unknown */ "G4 Gebäudehülle ",
  "B31":  /* unknown */ "TXT_buid_G4_roof_almostsuit",
  "D31":  /* unknown */ "Höhere Energieverluste Dachflächen – Verbesserung empfohlen\nDer vorhandene Wärmeschutz des Dachs ist ausbaufähig. Eine nachträgliche oder stärkere Dämmung reduziert nicht nur die Heizkosten, sondern erleichtert auch den effizienten Betrieb einer Wärmepumpe.",
  "A32":  /* unknown */ "G4 Gebäudehülle ",
  "B32":  /* unknown */ "TXT_buid_G4_roof_suit",
  "D32":  /* unknown */ "Dach mit moderatem Wärmeschutz – Optimierungspotenzial\nDas Dach bietet bereits einen soliden Wärmeschutz, der jedoch weiter verbessert werden kann. Eine zusätzliche Dämmung hilft, die Heizlast weiter zu senken und ermöglicht niedrigere Vorlauftemperaturen – ein Pluspunkt für den Wärmepumpenbetrieb.",
  "A33":  /* unknown */ "G4 Gebäudehülle ",
  "B33":  /* unknown */ "TXT_buid_G4_roof_verysuit",
  "D33":  /* unknown */ "Dach gut isoliert – sehr gute Voraussetzung\nDas Dach hat einen niedrigen U-Wert. Damit verliert es wenig Wärme und leistet bereits einen wichtigen Beitrag zum Wärmeschutz des Gebäudes. Das ist ideal für den wirtschaftlichen und effizienten Betrieb einer Wärmepumpe.",
  "A34":  /* unknown */ "G4 Gebäudehülle ",
  "B34":  /* unknown */ "TXT_buid_G4_botceil_notsuit",
  "A35":  /* unknown */ "G4 Gebäudehülle ",
  "B35":  /* unknown */ "TXT_buid_G4_botceil_almostsuit",
  "A36":  /* unknown */ "G4 Gebäudehülle ",
  "B36":  /* unknown */ "TXT_buid_G4_botceil_suit",
  "A37":  /* unknown */ "G4 Gebäudehülle ",
  "B37":  /* unknown */ "TXT_buid_G4_botceil_verysuit",
  "A38":  /* unknown */ "G4 Gebäudehülle ",
  "B38":  /* unknown */ "TXT_buid_G4_topceil_notsuit",
  "A39":  /* unknown */ "G4 Gebäudehülle ",
  "B39":  /* unknown */ "TXT_buid_G4_topceil_almostsuit",
  "A40":  /* unknown */ "G4 Gebäudehülle ",
  "B40":  /* unknown */ "TXT_buid_G4_topceil_suit",
  "A41":  /* unknown */ "G4 Gebäudehülle ",
  "B41":  /* unknown */ "TXT_buid_G4_topceil_verysuit",
  "D42":  /* unknown */ "Wärmeschutzniveau unzureichend – Maßnahmen erforderlich\nDie Gebäudehülle verliert zu viel Wärme. Im aktuellen Zustand begrenzt der unzureichende Wärmeschutz die Effizienz einer Wärmepumpe.\nMehrere Bauteile weisen einen sehr hohen Wärmedurchgang (genannt: U-Wert) auf. Ein Großteil der Wärme entweicht über [die Außenwände und …] – eine (zusätzliche) Dämmung senkt den Energieverbrauch und die Heizlast deutlich und schafft die nötigen Voraussetzungen für den effizienten Wärmepumpenbetrieb.\n💡 Hinweis: Ergänzen Sie weitere Räume, um ein vollständigeres Bild der Hüllqualität zu erhalten – oder klären Sie die erforderliche Ertüchtigung der Bauteile in der Planungsphase.",
  "D43":  /* unknown */ "Wärmeschutz ausbaufähig – Maßnahmen empfehlenswert\nEinige Bauteile bieten Verbesserungspotenzial.\nDas Wärmeschutzniveau ist teilweise gut, aber es bestehen noch zu hohe Wärmeverluste. Vor allem über [die Außenwände]  bestehen spürbar hohe Wärmeverluste.\nDurch gezielte Dämmmaßnahmen lassen sich Effizienz und Wirtschaftlichkeit einer Wärmepumpe deutlich verbessern.\n💡 Hinweis: Für eine genauere Bewertung können weitere Räume ergänzt oder im Planungsprozess detailliert betrachtet werden.",
  "D44":  /* unknown */ "Wärmeschutz ausbaufähig – Maßnahmen vorteilhaft\nEinige Bauteile bieten Verbesserungspotenzial.\nDas Wärmeschutzniveau ist teilweise gut, aber es bestehen noch zu hohe Wärmeverluste. Vor allem über [die Außenwände]  bestehen spürbar hohe Wärmeverluste.\nDurch gezielte Dämmmaßnahmen lassen sich Effizienz und Wirtschaftlichkeit einer Wärmepumpe deutlich verbessern.\n💡 Hinweis: Für eine genauere Bewertung können weitere Räume ergänzt oder im Planungsprozess detailliert betrachtet werden.",
  "D45":  /* unknown */ "Sehr gute Voraussetzungen!\nDie eingegebenen Räume zeigen gut gedämmte Außenbauteile – die Wärmeverluste sind gering. Einer effizienten Beheizung mit einer Wärmepumpe steht nichts im Weg.\n💡 Hinweis: Zusätzliche Räume können helfen, das Bild weiter zu schärfen.",
} as const;
