// Sheet: TXT_rooms
export const data = {
  "A1":  /* unknown */ "Gruppe",
  "B1":  /* unknown */ "Variable ",
  "D1":  /* unknown */ "Kommentar",
  "E1":  /* unknown */ "INPUT_TXT_rooms",
  "A2":  /* unknown */ "R1",
  "B2":  /* unknown */ "TXT_room_R1_not",
  "E2":  /* unknown */ "## <i class=\"bi bi-circle-fill rating-red\"></i> Nicht niedertemperaturfähig (NT-ready)\n\n### Noch nicht geeignet, sehr hohe Vorlauftemperatur nötig.\n\nIn diesem Zustand kann der Raum nur sehr ineffizient mit einer Wärmepumpe beheizt werden – der Stromverbrauch wäre deutlich zu hoch.  \nNachfolgend finden Sie Hinweise, wie sich die Eignung Ihres Gebäudes verbessern lässt.",
  "A3":  /* unknown */ "R1",
  "B3":  /* unknown */ "TXT_room_R1_notyet",
  "E3":  /* unknown */ "## <i class=\"bi bi-circle-fill rating-orange\"></i> Noch nicht niedertemperaturfähig (NT-ready)\n\n### Es fehlt noch ein Stück, deutlich erhöhte Vorlauftemperatur.\n\nDie Wärmepumpe müsste mit einer zu hohen Vorlauftemperatur arbeiten – dadurch wäre der Stromverbrauch zu hoch.  \nNachfolgend finden Sie Hinweise, wie sich die Eignung Ihres Gebäudes verbessern lässt.",
  "A4":  /* unknown */ "R1",
  "B4":  /* unknown */ "TXT_room_R1_almost",
  "E4":  /* unknown */ "## <i class=\"bi bi-circle-fill rating-yellow\"></i> Fast niedertemperaturfähig (NT-ready)\n\n### Leicht erhöhte Vorlauftemperatur, fast geschafft!\n\nDieser Raum ist beinahe bereit für den effizienten Betrieb mit einer Wärmepumpe – die Vorlauftemperatur ist nur leicht erhöht.  \nJe nach Komfortansprüchen und Nutzung ist es möglich, dass Sie diesen Raum bereits gut mit einer Wärmepumpe beheizen können.  \nDenken Sie über eine geringfügig niedrigere Raumtemperatur nach, schon ein Grad Celsius kann ausreichen, um in diesem Raum eine Wärmepumpeneignung herbeizuführen. Nach dem ersten Winter wissen Sie endgültig , ob der Heizkörper in diesem Raum Ihre Ansprüche bedient.  \nDann können Sie über den empfohlenen Heizkörpertausch entscheiden.",
  "A5":  /* unknown */ "R1",
  "B5":  /* unknown */ "TXT_room_R1_NTr",
  "E5":  /* unknown */ "## <i class=\"bi bi-circle-fill rating-green\"></i> Niedertemperaturfähig (NT-ready)\n\n### Gute Voraussetzungen, eine Wärmepumpe ist möglich!\n\nDieser Raum ist bereit für eine effiziente Beheizung mit einer Wärmepumpe – die gewünschte Raumtemperatur wird bereits mit ausreichend geringer Vorlauftemperatur erreicht.",
  "A6":  /* unknown */ "R2",
  "B6":  /* unknown */ "TXT_room_R2_verysuit",
  "E6":  /* unknown */ "## <i class=\"bi bi-circle-fill rating-green\"></i> Sehr gut geeignet.\n\n### Stark gemacht!\n\nDie Heizlast in diesem Raum ist bereits sehr niedrig – eine Wärmepumpe kann den Raum effizient beheizen. Zusätzliche Maßnahmen wie Dämmung oder neue Fenster bringen nur noch geringe Verbesserungen.",
  "A7":  /* unknown */ "R2",
  "B7":  /* unknown */ "TXT_room_R2_suit_1",
  "E7":  /* unknown */ "## <i class=\"bi bi-circle-fill rating-yellow\"></i> Gut geeignet, mit Potenzial.\n\n### Gute Basis – noch optimierbar.\n\nDie Heizlast ist durchschnittlich. Eine Dämmung oder Erneuerung der",
  "A8":  /* unknown */ "R2",
  "B8":  /* unknown */ "TXT_room_R2_suit_2",
  "E8":  /* unknown */ "bietet hier das größte Potenzial, um den Wärmepumpenbetrieb effizienter zu gestalten und Energie zu sparen.",
  "A9":  /* unknown */ "R2",
  "B9":  /* unknown */ "TXT_room_R2_almostsuit_1",
  "E9":  /* unknown */ "## <i class=\"bi bi-circle-fill rating-orange\"></i> Verbesserungsbedarf.\n\n### Da geht noch was.\n\nDie Heizlast ist überdurchschnittlich.  \nVor allem über die",
  "A10":  /* unknown */ "R2",
  "B10":  /* unknown */ "TXT_room_R2_almostsuit_2",
  "E10":  /* unknown */ "geht viel Wärme verloren – durch Verbesserung des Wärmeschutzes kann die Effizienz der Wärmepumpe deutlich gesteigert werden.",
  "A11":  /* unknown */ "R2",
  "B11":  /* unknown */ "TXT_room_R2_notsuit_1",
  "E11":  /* unknown */ "## <i class=\"bi bi-circle-fill rating-red\"></i> Noch nicht geeignet ohne Maßnahmen.  \n\n### Jetzt ist Optimierung gefragt.  \n\nDie Heizlast ist sehr hoch. Für den sinnvollen Einsatz einer Wärmepumpe ist eine energetische Verbesserung der Gebäudehülle voraussichtlich notwendig.  \nDie meiste Wärme geht über die",
  "A12":  /* unknown */ "R2",
  "B12":  /* unknown */ "TXT_room_R2_notsuit_2",
  "E12":  /* unknown */ "verloren.",
  "A13":  /* unknown */ "R3",
  "B13":  /* unknown */ "TXT_room_R3_notsuff_1",
  "E13":  /* unknown */ "## <i class=\"bi bi-circle-fill rating-red\"></i> Sehr niedrige Heizkörperleistung.  \n\n### Hier reicht der Heizkörper nicht aus.    \n\nDamit eine Wärmepumpe den Raum effizient beheizen kann, wäre ein",
  "A14":  /* unknown */ "R3",
  "B14":  /* unknown */ "TXT_room_R3_notsuff_2",
  "E14":  /* unknown */ "Heizkörper oder ein zusätzlicher Heizkörper notwendig. Auch ein besserer Heizkörper (Typ 33) müsste mindestens doppelt so groß sein.  \nEin höherer Wärmeschutz der Bauteile kann helfen, den Wärmebedarf zu senken. Dann muss die Heizkörperfläche nicht so viel größer werden.\n\n<i class=\"bi bi-lightbulb-fill\"></i> Hinweis: Eine <abbr title=\"Die durch die Gebläse verstärkte Luftbewegung erhöht die Leistung des Heizkörpers, siehe Wärmepumpen-Heizkörper\"> Gebläseunterstützung </abbr> könnte dabei helfen, dass der Heizkörper nicht so groß sein muss.  \nFür diese Heizkörper-Modelle ist ein zusätzlicher Stromanschluss für die Gebläse erforderlich. ",
  "A15":  /* unknown */ "R3",
  "B15":  /* unknown */ "TXT_room_R3_suffchangeobl_1",
  "E15":  /* unknown */ "## <i class=\"bi bi-circle-fill rating-orange\"></i> Deutlich zu geringe Leistung\n\n### Ein Tausch bringt viel.\n\nEin neuer Heizkörper mit",
  "A16":  /* unknown */ "R3",
  "B16":  /* unknown */ "TXT_room_R3_suffchangeobl_2",
  "E16":  /* unknown */ "Leistung kann die Effizienz einer Wärmepumpe in diesem Raum erheblich verbessern. \n\nDer neue Heizkörper müsste größer dimensioniert sein, um die Raumheizlast zu decken.  \nAuch ein besserer Heizkörper (Typ 33) gleicher Größe ist wahrscheinlich nicht ausreichend",
  "A17":  /* unknown */ "R3",
  "B17":  /* unknown */ "TXT_room_R3_suffchange_1",
  "E17":  /* unknown */ "## <i class=\"bi bi-circle-fill rating-yellow\"></i> Etwas zu geringe Leistung.\n\n### Mit dem richtigen Typ klappt’s.\n\nEin Heizkörpertausch kann hier viel bewirken – ein Modell mit",
  "A18":  /* unknown */ "R3",
  "B18":  /* unknown */ "TXT_room_R3_suffchange_2",
  "E18":  /* unknown */ "mehr Leistung reicht aus.  \nVoraussichtlich genügt es, bei gleicher Größe auf einen leistungsstärkeren Typ umzusteigen.",
  "A19":  /* unknown */ "R3",
  "B19":  /* unknown */ "TXT_room_R3_suff",
  "E19":  /* unknown */ "## <i class=\"bi bi-circle-fill rating-green\"></i> Ausreichend Heizkörperleistung.\n\n### Gut ausgestattet!\n\nDer Heizkörper hat genügend Leistung, um den Raum mit einer Wärmepumpe effizient zu beheizen. Ein Tausch ist hier nicht erforderlich.",
  "A20":  /* unknown */ "room",
  "B20":  /* unknown */ "TXT_room_RW",
  "E20":  /* unknown */ "## <i class=\"bi bi-exclamation-triangle-fill-yellow\"></i> Achtung! Hohe Raumtemperatur gewählt.\n\n### Die angegebene Raumtemperatur ist vergleichsweise hoch.\n\nTypischerweise werden 20 °C in Wohnräumen und 24 °C in Bädern angesetzt.  \nHandelt es sich um ein Badezimmer? Testen Sie die Eignung bei 20 °C Raumtemperatur.  \nSollte die Heizfläche dann ausreichen, genügt es zumeist, dass an sehr kalten Tagen mit einem Infrarotstrahler oder einem Heizlüfter unterstützt wird.",
} as const;
