// Sheet: TXT_rooms
export const data = {
  "A1":  /* unknown */ "Gruppe",
  "B1":  /* unknown */ "Variable ",
  "C1":  /* unknown */ "Einheit",
  "D1":  /* unknown */ "Kommentar",
  "E1":  /* unknown */ "INPUT_TXT_rooms",
  "A2":  /* unknown */ "R1",
  "B2":  /* unknown */ "TXT_room_R1_not",
  "E2":  /* unknown */ "Nicht niedertemperaturfähig (NT-ready):\nNoch nicht geeignet, sehr hohe Vorlauftemperatur nötig.\nIn diesem Zustand kann der Raum nur sehr ineffizient mit einer Wärmepumpe beheizt werden – der Stromverbrauch wäre deutlich zu hoch. Nachfolgend finden Sie Hinweise, wie sich die Eignung Ihres Gebäudes verbessern lässt.",
  "A3":  /* unknown */ "R1",
  "B3":  /* unknown */ "TXT_room_R1_notyet",
  "E3":  /* unknown */ "Noch nicht niedertemperaturfähig (NT-ready):\nEs fehlt noch ein Stück, deutlich erhöhte Vorlauftemperatur.\nDie Wärmepumpe müsste mit einer zu hohen Vorlauftemperatur arbeiten – dadurch wäre der Stromverbrauch zu hoch. Nachfolgend finden Sie Hinweise, wie sich die Eignung Ihres Gebäudes verbessern lässt.",
  "A4":  /* unknown */ "R1",
  "B4":  /* unknown */ "TXT_room_R1_almost",
  "E4":  /* unknown */ "Fast niedertemperaturfähig (NT-ready):\nLeicht erhöhte Vorlauftemperatur, fast geschafft!\nDieser Raum ist beinahe bereit für den effizienten Betrieb mit einer Wärmepumpe – die Vorlauftemperatur ist nur leicht erhöht. Je nach Komfortansprüchen und Nutzung ist es möglich, dass Sie diesen Raum bereits gut mit einer Wärmepumpe beheizen können. Denken Sie über eine geringfügig niedrigere Raumtemperatur nach, schon ein Grad Celsius kann ausreichen, um in diesem Raum eine Wärmepumpeneignung herbeizuführen. Nach dem ersten Winter wissen Sie endgültig , ob der Heizkörper in diesem Raum Ihre Ansprüche bedient. Dann können Sie über den empfohlenen Heizkörpertausch entscheiden.",
  "A5":  /* unknown */ "R1",
  "B5":  /* unknown */ "TXT_room_R1_NTr",
  "E5":  /* unknown */ "Niedertemperaturfähig (NT-ready):\nGute Voraussetzungen, eine Wärmepumpe ist möglich!\nDieser Raum ist bereit für eine effiziente Beheizung mit einer Wärmepumpe – die gewünschte Raumtemperatur wird bereits mit ausreichend geringer Vorlauftemperatur erreicht.",
  "A6":  /* unknown */ "R2",
  "B6":  /* unknown */ "TXT_room_R2_verysuit",
  "E6":  /* unknown */ "Sehr gut geeignet.\nStark gemacht!\nDie Heizlast in diesem Raum ist bereits sehr niedrig – eine Wärmepumpe kann den Raum effizient beheizen. Zusätzliche Maßnahmen wie Dämmung oder neue Fenster bringen nur noch geringe Verbesserungen.",
  "A7":  /* unknown */ "R2",
  "B7":  /* unknown */ "TXT_room_R2_suit_1",
  "E7":  /* unknown */ "Gut geeignet, mit Potenzial.\nGute Basis – noch optimierbar.\nDie Heizlast ist durchschnittlich. Eine Dämmung der",
  "A8":  /* unknown */ "R2",
  "B8":  /* unknown */ "TXT_room_R2_suit_2",
  "E8":  /* unknown */ "bietet hier das größte Potenzial, um den Wärmepumpenbetrieb effizienter zu gestalten und Energie zu sparen.",
  "A9":  /* unknown */ "R2",
  "B9":  /* unknown */ "TXT_room_R2_almostsuit_1",
  "E9":  /* unknown */ "Verbesserungsbedarf.\nDa geht noch was.\nDie Heizlast ist überdurchschnittlich. Vor allem über die",
  "A10":  /* unknown */ "R2",
  "B10":  /* unknown */ "TXT_room_R2_almostsuit_2",
  "E10":  /* unknown */ "geht viel Wärme verloren – durch Verbesserung des Wärmeschutzes kann die Effizienz der Wärmepumpe deutlich gesteigert werden.",
  "A11":  /* unknown */ "R2",
  "B11":  /* unknown */ "TXT_room_R2_notsuit_1",
  "E11":  /* unknown */ "Noch nicht geeignet ohne Maßnahmen.\nJetzt ist Optimierung gefragt.\nDie Heizlast ist sehr hoch. Für den sinnvollen Einsatz einer Wärmepumpe ist eine energetische Verbesserung der Gebäudehülle voraussichtlich notwendig. Die meiste Wärme geht über die",
  "A12":  /* unknown */ "R2",
  "B12":  /* unknown */ "TXT_room_R2_notsuit_2",
  "E12":  /* unknown */ "verloren.",
  "A13":  /* unknown */ "R3",
  "B13":  /* unknown */ "TXT_room_R3_notsuff_1",
  "E13":  /* unknown */ "Sehr niedrige Heizkörperleistung\nHier reicht der Heizkörper nicht aus.  \nDamit eine Wärmepumpe den Raum effizient beheizen kann, wäre ein",
  "A14":  /* unknown */ "R3",
  "B14":  /* unknown */ "TXT_room_R3_notsuff_2",
  "E14":  /* unknown */ "Heizkörper gleicher Bauart oder ein zusätzlicher Heizkörper notwendig. Auch ein Heizkörper der effektivsten Bauart könnte bei gleichen Abmessungen den Raum nicht ausreichend beheizen. Eine bessere Dämmung der Bauteile kann helfen, den Wärmebedarf zu senken. Dann muss die Heizkörperfläche nicht so viel größer werden.",
  "A15":  /* unknown */ "R3",
  "B15":  /* unknown */ "TXT_room_R3_suffchangeobl_1",
  "E15":  /* unknown */ "Deutlich zu geringe Leistung\nEin Tausch bringt viel.\nEin neuer Heizkörper mit",
  "A16":  /* unknown */ "R3",
  "B16":  /* unknown */ "TXT_room_R3_suffchangeobl_2",
  "E16":  /* unknown */ "Leistung kann die Effizienz einer Wärmepumpe in diesem Raum erheblich verbessern. Der neue Heizkörper müsste größer dimensioniert sein, um die Raumheizlast zu decken. Ein besserer Heizkörper (Typ 33) gleicher Größe ist wahrscheinlich nicht ausreichend",
  "A17":  /* unknown */ "R3",
  "B17":  /* unknown */ "TXT_room_R3_suffchange_1",
  "E17":  /* unknown */ "Etwas zu geringe Leistung.\nMit dem richtigen Typ klappt’s.\nEin Heizkörpertausch kann hier viel bewirken – ein Modell mit",
  "A18":  /* unknown */ "R3",
  "B18":  /* unknown */ "TXT_room_R3_suffchange_2",
  "E18":  /* unknown */ "mehr Leistung reicht aus. Voraussichtlich genügt es, bei gleicher Größe auf einen leistungsstärkeren Typ umzusteigen.",
  "A19":  /* unknown */ "R3",
  "B19":  /* unknown */ "TXT_room_R3_suff",
  "E19":  /* unknown */ "Ausreichend Heizkörperleistung.\nGut ausgestattet!\nDer Heizkörper hat genügend Leistung, um den Raum mit einer Wärmepumpe effizient zu beheizen. Ein Tausch ist hier nicht erforderlich.",
  "A20":  /* unknown */ "room",
  "B20":  /* unknown */ "TXT_room_RW",
  "E20":  /* unknown */ "Achtung! Hohe Raumtemperatur gewählt.\nDie angegebene Raumtemperatur ist vergleichsweise hoch.\nTypischerweise werden 20 °C in Wohnräumen und 24 °C in Bädern angesetzt.\nHandelt es sich um ein Badezimmer? Testen Sie die Eignung bei 20 °C Raumtemperatur. Sollte die Heizfläche dann ausreichen, genügt es zumeist, dass an sehr kalten Tagen mit einem Infrarotstrahler oder einem Heizlüfter unterstützt wird.",
} as const;
