// Sheet: U_GEG_A.7
// Generated on: 2025-05-10T13:08:38.977Z

export const data: Record<string, any> = {
  "C8":  /* unknown */ "WG & NWG >19°C",
  "D8":  /* unknown */ "NWG",
  "C9":  /* unknown */ "Umax [W/(m²K)]",
  "D9":  /* unknown */ "Umax [W/(m²K)]",
  "A10":  /* unknown */ "Außenwände",
  "B10":  /* unknown */ "AW",
  "C10":  /* unknown */ 0.24,
  "D10":  /* unknown */ 0.35,
  "A11":  /* unknown */ "Gegen Außenluft abgrenzende Fenster und Fenstertüren",
  "B11":  /* unknown */ "FE",
  "C11":  /* unknown */ 1.3,
  "D11":  /* unknown */ 1.9,
  "A12":  /* unknown */ "Gegen Außenluft abgrenzende Dachflächenfenster",
  "B12":  /* unknown */ "DFF",
  "C12":  /* unknown */ 1.4,
  "D12":  /* unknown */ 1.9,
  "A13":  /* unknown */ "Gegen Außenluft abgrenzende Fenster, Fenstertüren und Dachflächenfenster bei Ersatz der Verglasung oder des Rahmens",
  "B13":  /* unknown */ "FEDFF_tausch",
  "C13":  /* unknown */ 1.1,
  "D13":  /* unknown */ "Keine Anforderung",
  "A14":  /* unknown */ "Vorhangfassaden in Pfosten-Riegel-Konstruktion, deren Bauart DIN EN ISO 12631: 2018-01 entspricht",
  "B14":  /* unknown */ "PRK",
  "C14":  /* unknown */ 1.5,
  "D14":  /* unknown */ 1.9,
  "A15":  /* unknown */ "Gegen Außenluft abgrenzende Glasdächer",
  "B15":  /* unknown */ "GD",
  "C15":  /* unknown */ 2,
  "D15":  /* unknown */ 2.7,
  "A16":  /* unknown */ "Gegen Außenluft abgrenzende Fenstertüren mit Klapp-, Falt-, Schiebe- oder Hebemechanismus",
  "B16":  /* unknown */ "FT",
  "C16":  /* unknown */ 1.6,
  "D16":  /* unknown */ 1.9,
  "A17":  /* unknown */ "Gegen Außenluft abgrenzende Fenster, Fenstertüren und Dachflächenfenster mit Sonderverglasung",
  "B17":  /* unknown */ "FE_sonder",
  "C17":  /* unknown */ 2,
  "D17":  /* unknown */ 2.8,
  "A18":  /* unknown */ "Gegen Außenluft abgrenzende Fenster, Fenstertüren und Dachflächenfenster mit Sonderverglasung bei Ersatz der Verglasung oder des Rahmens",
  "B18":  /* unknown */ "FEDFF_sondertausch",
  "C18":  /* unknown */ 1.6,
  "D18":  /* unknown */ "-",
  "A19":  /* unknown */ "Vorhangfassaden in Pfosten-Riegel-Konstruktion, deren Bauart DIN EN ISO 12631: 2018-01 entspricht, mit Sonderverglasung",
  "B19":  /* unknown */ "PRK_sonder",
  "C19":  /* unknown */ 2.3,
  "D19":  /* unknown */ 3,
  "A20":  /* unknown */ "Einbau neuer Außentüren (ohne rahmenlose Türanlagen aus Glas, Karusselltüren und kraftbetätigte Türen)",
  "B20":  /* unknown */ "AT",
  "C20":  /* unknown */ 1.8,
  "D20":  /* unknown */ 1.8,
  "A21":  /* unknown */ "Gegen Außenluft abgrenzende Dachflächen einschließlich Dachgauben sowie gegen unbeheizte Dachräume abgrenzende Decken (oberste Geschossdecken) und Wände (einschließlich Abseitenwände)",
  "B21":  /* unknown */ "DA",
  "C21":  /* unknown */ 0.24,
  "D21":  /* unknown */ 0.35,
  "A22":  /* unknown */ "Gegen Außenluft abgrenzende Dachflächen mit Abdichtung",
  "B22":  /* unknown */ "DA_dicht",
  "C22":  /* unknown */ 0.2,
  "D22":  /* unknown */ 0.35,
  "A23":  /* unknown */ "Wände, die an Erdreich oder an unbeheizte Räume (mit Ausnahme von Dachräumen) grenzen, und Decken, die beheizte Räume nach unten zum Erdreich oder zu unbeheizten Räumen abgrenzen",
  "B23":  /* unknown */ "AWDE_kalt",
  "C23":  /* unknown */ 0.3,
  "D23":  /* unknown */ "-",
  "A24":  /* unknown */ "Decken, die beheizte Räume nach unten zum Erdreich, zur Außenluft oder zu unbeheizten Räumen abgrenzen",
  "B24":  /* unknown */ "DE_kalt",
  "C24":  /* unknown */ 0.5,
  "D24":  /* unknown */ "-",
  "A25":  /* unknown */ "Decken, die beheizte Räume nach unten zur Außenluft abgrenzen",
  "B25":  /* unknown */ "DE_unten",
  "C25":  /* unknown */ 0.24,
  "D25":  /* unknown */ 0.35,
};
